import PhysicsSM.Draft.NullEdge.LorentzAtlasStructureGroup

/-!
# Cone-nerve gauge trivialization

This module isolates a global-topology control for finite atlas experiments.
If one chart is a cone point of the occupied nerve, so every occupied edge
`i-j` extends to the occupied triple `i-j-r`, the exact Cech cocycle makes the
whole transition field pure gauge on occupied edges.  The root-chart gauge is
simply `h(i) = T(i,r)`.

Consequently, a carrier atlas with a global common intersection can test local
overlap compatibility and matrix reconstruction, but it cannot realize a
nontrivial bundle class.  In particular its Lorentz, determinant-orientation,
and time-orientation transition data are all gauge-trivial.  Connection
holonomy remains a separate object and is not constrained by this theorem.

Claim grade: `M [orig/comp]`, finite group and Cech algebra only.
-/

namespace PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization

open PhysicsSM.Draft.NullEdge.AtlasComponentCharacter
open PhysicsSM.Draft.NullEdge.AtlasTransitionHolonomy
open PhysicsSM.Draft.NullEdge.CarrierProbeRestrictedLorentzTransition
open PhysicsSM.Draft.NullEdge.LorentzAtlasStructureGroup

/-- A transition field is gauge-trivial on every occupied pair overlap. -/
def IsGaugeTrivialOn {I G : Type*} [Group G]
    (pairOverlap : I -> I -> Prop) (T : TransitionField I G) : Prop :=
  Exists fun h : ChartGauge I G =>
    forall i j, pairOverlap i j -> gaugeTransition h T i j = 1

/-- A chart is a cone point when every occupied edge extends to an occupied
triple with that chart. -/
def IsConeChart {I : Type*}
    (pairOverlap : I -> I -> Prop)
    (tripleOverlap : I -> I -> I -> Prop) (r : I) : Prop :=
  forall i j, pairOverlap i j -> tripleOverlap i j r

/-- Gauge every chart relative to one root chart. -/
def rootGauge {I G : Type*} [Group G]
    (T : TransitionField I G) (r : I) : ChartGauge I G :=
  fun i => T i r

/-- On a triple containing the root chart, the Cech cocycle makes the
root-gauged transition exactly the identity. -/
theorem gaugeTransition_rootGauge_eq_one {I G : Type*} [Group G]
    {pairOverlap : I -> I -> Prop}
    {tripleOverlap : I -> I -> I -> Prop}
    {T : TransitionField I G}
    (S : IsCechTransition pairOverlap tripleOverlap T)
    {i j r : I} (hijr : tripleOverlap i j r) :
    gaugeTransition (rootGauge T r) T i j = 1 := by
  calc
    gaugeTransition (rootGauge T r) T i j =
        (T i r)⁻¹ * (T i j * T j r) := by
      rw [gaugeTransition, rootGauge]
      exact mul_assoc _ _ _
    _ = (T i r)⁻¹ * T i r := by
      rw [S.cocycle i j r hijr]
    _ = 1 := inv_mul_cancel _

/-- Every Cech transition field on a cone-shaped occupied nerve is
gauge-trivial on all occupied edges. -/
theorem cech_gaugeTrivialOn_of_cone {I G : Type*} [Group G]
    {pairOverlap : I -> I -> Prop}
    {tripleOverlap : I -> I -> I -> Prop}
    {T : TransitionField I G}
    (S : IsCechTransition pairOverlap tripleOverlap T)
    {r : I} (hcone : IsConeChart pairOverlap tripleOverlap r) :
    IsGaugeTrivialOn pairOverlap T := by
  refine ⟨rootGauge T r, ?_⟩
  intro i j hij
  exact gaugeTransition_rootGauge_eq_one S (hcone i j hij)

/-- Applying any component character preserves the cone trivialization. -/
theorem component_gaugeTrivialOn_of_cone {I G : Type*} [Group G]
    {pairOverlap : I -> I -> Prop}
    {tripleOverlap : I -> I -> I -> Prop}
    {T : TransitionField I G}
    (S : IsCechTransition pairOverlap tripleOverlap T)
    (character : MonoidHom G ComponentGroup)
    {r : I} (hcone : IsConeChart pairOverlap tripleOverlap r) :
    IsGaugeTrivialOn pairOverlap (componentTransition character T) := by
  exact cech_gaugeTrivialOn_of_cone
    (componentTransition_isCech S character) hcone

/-- On a cone-shaped eta-Lorentz atlas, one Lorentz-valued chart gauge makes
every occupied transition the identity and hence restricted Lorentz. -/
theorem lorentz_cone_gauges_into_restricted {I : Type*}
    {pairOverlap : I -> I -> Prop}
    {tripleOverlap : I -> I -> I -> Prop}
    {T : TransitionField I EtaLorentzGroup}
    (S : IsCechTransition pairOverlap tripleOverlap T)
    {r : I} (hcone : IsConeChart pairOverlap tripleOverlap r) :
    Exists fun h : ChartGauge I EtaLorentzGroup =>
      forall i j, pairOverlap i j ->
        IsRestrictedLorentz (toMatrix (gaugeTransition h T i j)) := by
  refine ⟨rootGauge T r, ?_⟩
  intro i j hij
  rw [gaugeTransition_rootGauge_eq_one S (hcone i j hij)]
  simp [IsRestrictedLorentz, IsEtaLorentz, IsProperLorentz,
    IsOrthochronousLorentz]

/-- A transition field generated by chart representatives is exact Cech data
on the complete nerve. -/
def pureGaugeTransition {I G : Type*} [Group G]
    (h : ChartGauge I G) : TransitionField I G :=
  gaugeTransition h (fun _ _ => 1)

/-- Pure-gauge data give a nonvacuous model of the exact Cech hypotheses. -/
theorem pureGaugeTransition_isCech {I G : Type*} [Group G]
    (h : ChartGauge I G) :
    IsCechTransition (fun _ _ => True) (fun _ _ _ => True)
      (pureGaugeTransition h) := by
  refine {
    normalized := ?_
    inverse := ?_
    cocycle := ?_ }
  · intro i _
    simp [pureGaugeTransition, gaugeTransition]
  · intro i j _
    simp [pureGaugeTransition, gaugeTransition, mul_assoc]
  · intro i j k _
    simp [pureGaugeTransition, gaugeTransition, mul_assoc]

/-- A two-chart sign gauge with genuinely nonidentity raw transition. -/
def signWitnessGauge : ChartGauge (Fin 2) ComponentGroup :=
  fun i => if i = 0 then 1 else Multiplicative.ofAdd 1

/-- Nonidentity transition entries do not themselves imply a bundle
obstruction: this one is exact Cech data on a cone and is gauge-trivial. -/
theorem nonidentity_cone_transition_is_gauge_trivial :
    pureGaugeTransition signWitnessGauge 0 1 != 1 /\
      IsGaugeTrivialOn (fun _ _ : Fin 2 => True)
        (pureGaugeTransition signWitnessGauge) := by
  constructor
  · decide
  · apply cech_gaugeTrivialOn_of_cone
      (r := 0) (pureGaugeTransition_isCech signWitnessGauge)
    intro _ _ _
    trivial

end PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization

/-! ## Axiom audit -/

/-- info: 'PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.cech_gaugeTrivialOn_of_cone' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.cech_gaugeTrivialOn_of_cone

/-- info: 'PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.lorentz_cone_gauges_into_restricted' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.lorentz_cone_gauges_into_restricted

/-- info: 'PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.nonidentity_cone_transition_is_gauge_trivial' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.AtlasConeGaugeTrivialization.nonidentity_cone_transition_is_gauge_trivial
