import Mathlib

/-!
# Cayley Hamiltonian generator and exact turn witness

DRAFT (kernel-clean). This module strengthens the finite dynamics layer with a
generator-to-update theorem. For a finite complex matrix `H`, the Cayley step

`(1 + i dt H / 2)^{-1} (1 - i dt H / 2)`

solves the cleared-denominator Crank-Nicolson equation. For Hermitian `H` with
the displayed two-sided inverse identities, the step is unitary. The exact two-level
witness `H = sigma_x`, `dt = 2` gives the nontrivial turn `-i sigma_x`, taking
the first basis state to the second with phase `-i`.

This is a finite generator/update theorem, not a derivation selecting the
physical Hamiltonian of the null-edge carrier and not a continuum-limit result.

Provenance: clean-room finite matrix formalization, organized after the
Crank-Nicolson/Cayley patterns used in numerical quantum dynamics. Aristotle job
`e8a43f64-23aa-4c84-b201-803a9afea9e4` supplied the generic proof; the exact
two-level witness was completed and checked locally under the pinned toolchain.
-/

open Matrix Complex

namespace PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- Left-hand Crank-Nicolson matrix `1 + i dt H / 2`. -/
noncomputable def cayleyA (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  1 + ((((dt / 2 : ℝ) : ℂ) * I) • H)

/-- Right-hand Crank-Nicolson matrix `1 - i dt H / 2`. -/
noncomputable def cayleyB (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  1 - ((((dt / 2 : ℝ) : ℂ) * I) • H)

/-- Cayley transfer step generated by `H`. -/
noncomputable def cayleyStep (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  (cayleyA H dt)⁻¹ * cayleyB H dt

/-- The Cayley step solves the cleared-denominator linear update. -/
theorem cayleyStep_iff_linear_update (H : Matrix n n ℂ) (dt : ℝ)
    (hleft : cayleyA H dt * (cayleyA H dt)⁻¹ = 1)
    (hright : (cayleyA H dt)⁻¹ * cayleyA H dt = 1)
    (psi psi' : n → ℂ) :
    psi' = (cayleyStep H dt).mulVec psi ↔
      (cayleyA H dt).mulVec psi' = (cayleyB H dt).mulVec psi := by
  constructor
  · simp_all +decide [cayleyStep, ← Matrix.mulVec_mulVec]
    simp +decide [← Matrix.mul_assoc, hleft]
  · intro h
    convert congrArg (fun x => (cayleyA H dt)⁻¹.mulVec x) h using 1 <;>
      simp +decide [hright, cayleyStep]

/-- The cleared-denominator linear update is exactly the finite
Crank-Nicolson equation. -/
theorem linear_update_iff_crankNicolson (H : Matrix n n ℂ) (dt : ℝ)
    (psi psi' : n → ℂ) :
    (cayleyA H dt).mulVec psi' = (cayleyB H dt).mulVec psi ↔
      I • (psi' - psi) =
        ((dt / 2 : ℝ) : ℂ) • H.mulVec (psi' + psi) := by
  unfold cayleyA cayleyB
  simp +decide [funext_iff, Matrix.mulVec, dotProduct]
  simp +decide [Matrix.one_apply, mul_add, add_mul, sub_mul, mul_sub,
    Finset.mul_sum _ _ _, Finset.sum_add_distrib, mul_assoc, mul_left_comm]
  simp +decide only [← Finset.mul_sum _ _ _]
  grind +suggestions

/-- A Hermitian generator with the displayed two-sided inverse identities has a unitary
Cayley step. -/
theorem cayleyStep_unitary (H : Matrix n n ℂ) (dt : ℝ)
    (hH : H.IsHermitian)
    (hAleft : cayleyA H dt * (cayleyA H dt)⁻¹ = 1)
    (hAright : (cayleyA H dt)⁻¹ * cayleyA H dt = 1)
    (hBleft : cayleyB H dt * (cayleyB H dt)⁻¹ = 1)
    (hBright : (cayleyB H dt)⁻¹ * cayleyB H dt = 1) :
    cayleyStep H dt ∈ Matrix.unitaryGroup n ℂ := by
  have h_comm : cayleyA H dt * cayleyB H dt = cayleyB H dt * cayleyA H dt := by
    unfold cayleyA cayleyB
    simp +decide [mul_add, add_mul, sub_mul, mul_sub]
    ext i j
    norm_num
    ring
  have h_comm_inv :
      (cayleyA H dt)⁻¹ * (cayleyB H dt)⁻¹ =
        (cayleyB H dt)⁻¹ * (cayleyA H dt)⁻¹ := by
    rw [← Matrix.mul_inv_rev, ← Matrix.mul_inv_rev, h_comm]
  have h_conj :
      Matrix.conjTranspose (cayleyA H dt) = cayleyB H dt ∧
        Matrix.conjTranspose (cayleyB H dt) = cayleyA H dt := by
    unfold cayleyA cayleyB
    simp +decide [Matrix.conjTranspose_smul]
    simp +decide [sub_eq_add_neg, hH.eq]
  simp_all +decide [cayleyStep, Matrix.mem_unitaryGroup_iff']
  simp_all +decide [← mul_assoc, star]
  simp_all +decide [Matrix.conjTranspose_nonsing_inv]
  grind

/-! ## Exact two-level turn witness -/

/-- Pauli `sigma_x`, the two-level turn generator. -/
noncomputable def sigmaX : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]

/-- First standard basis state. -/
noncomputable def e0 : Fin 2 → ℂ := ![1, 0]

/-- Second standard basis state. -/
noncomputable def e1 : Fin 2 → ℂ := ![0, 1]

/-- The turn generator squares to the identity. -/
theorem sigmaX_sq : sigmaX * sigmaX = 1 := by
  unfold sigmaX
  ext i j
  fin_cases i <;> fin_cases j <;> norm_num [Matrix.mul_apply]

/-- The turn generator is Hermitian. -/
theorem sigmaX_hermitian : sigmaX.IsHermitian := by
  ext i j
  fin_cases i <;> fin_cases j <;> norm_num [sigmaX]

/-- Exact inverse at `dt = 2`: `(1 + i sigma_x)^{-1} = (1 - i sigma_x)/2`. -/
theorem sigmaX_cayley_inverse :
    (cayleyA sigmaX 2)⁻¹ = (1 / 2 : ℂ) • cayleyB sigmaX 2 := by
  have h_inv : (cayleyA sigmaX 2) * ((1 / 2 : ℂ) • cayleyB sigmaX 2) = 1 := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      norm_num [Matrix.mul_apply, cayleyA, cayleyB]
    · unfold sigmaX
      norm_num [Complex.ext_iff]
    · norm_num [sigmaX]
      ring
    · unfold sigmaX
      norm_num [Complex.ext_iff]
    · norm_num [Complex.ext_iff, sigmaX]
  rw [Matrix.inv_eq_right_inv h_inv]

/-- The exact Cayley step at `dt = 2` is the nontrivial turn `-i sigma_x`. -/
theorem sigmaX_cayley_step : cayleyStep sigmaX 2 = (-I) • sigmaX := by
  rw [cayleyStep, sigmaX_cayley_inverse]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [cayleyB, sigmaX, Matrix.mul_apply, Complex.ext_iff]

/-- The generated step turns the first basis state into the second with phase
`-i`, so its transition amplitude is exactly nonzero. -/
theorem sigmaX_cayley_turns_basis :
    (cayleyStep sigmaX 2).mulVec e0 = (-I) • e1 ∧
      (cayleyStep sigmaX 2).mulVec e0 1 = -I ∧
      (cayleyStep sigmaX 2).mulVec e0 1 ≠ 0 := by
  rw [sigmaX_cayley_step]
  constructor
  · ext i
    fin_cases i <;>
      norm_num [sigmaX, e0, e1, Matrix.mulVec, dotProduct, Complex.ext_iff]
  · constructor <;>
      norm_num [sigmaX, e0, Matrix.mulVec, dotProduct, Complex.ext_iff]

/-- The exact two-level Cayley turn is unitary. -/
theorem sigmaX_cayley_unitary :
    cayleyStep sigmaX 2 ∈ Matrix.unitaryGroup (Fin 2) ℂ := by
  rw [sigmaX_cayley_step, Matrix.mem_unitaryGroup_iff']
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [sigmaX, Matrix.mul_apply, Complex.ext_iff]

/-- The finite generator/update verdict with an explicit phase-carrying turn. -/
theorem cayley_hamiltonian_generator_verdict :
    cayleyStep sigmaX 2 = (-I) • sigmaX ∧
      (cayleyStep sigmaX 2).mulVec e0 = (-I) • e1 ∧
      (cayleyStep sigmaX 2).mulVec e0 1 ≠ 0 ∧
      cayleyStep sigmaX 2 ∈ Matrix.unitaryGroup (Fin 2) ℂ :=
  ⟨sigmaX_cayley_step, sigmaX_cayley_turns_basis.1,
    sigmaX_cayley_turns_basis.2.2, sigmaX_cayley_unitary⟩

/-! ## Axiom-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.cayleyStep_iff_linear_update' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms cayleyStep_iff_linear_update

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.linear_update_iff_crankNicolson' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms linear_update_iff_crankNicolson

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.cayleyStep_unitary' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms cayleyStep_unitary

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.sigmaX_cayley_inverse' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms sigmaX_cayley_inverse

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.sigmaX_cayley_turns_basis' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms sigmaX_cayley_turns_basis

/-- info: 'PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator.cayley_hamiltonian_generator_verdict' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms cayley_hamiltonian_generator_verdict

end PhysicsSM.Draft.NullEdge.CayleyHamiltonianGenerator
