import PhysicsSM.Draft.NullEdge.ChannelDecompositionModuliCapstone

/-!
# Target: a rational stabilizer orbit obstructs invariant selection

The exact six-coordinate even Krein-self-adjoint normal form has two negative
coordinates, `b` and `f`, with equal coefficient in the Gram form.  Swapping
those coordinates is therefore a rational involutive isometry.  It fixes the
three named even channels, whose two negative coordinates vanish, but exchanges
the positive complement rays at `(3/5,0)` and `(0,3/5)`.

Prove all six statements without weakening the hypotheses.  The capstone must
exhibit the two distinct positive represented sectors and show that every
selector invariant under this explicitly declared normal-form symmetry gives
their complement witnesses the same value.

Scope: this is a stabilizer inside the rational six-coordinate quadratic model.
It is not asserted to be a carrier-algebra automorphism, gauge transformation,
edge relabeling, dynamical symmetry, or physical equivalence.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace PhysicsSM.Draft.NullEdge.ChannelStabilizerSelectorSuccessor

open CarrierRigidity.Concrete
open ChannelKreinMetricNoGo
open ChannelKreinSectorSignature
open ChannelPositiveComplementDisk

/-- Swap the equally weighted negative coordinates after reading the exact
normal-form entries of a represented matrix.  Claims about this map below are
restricted to the even Krein-self-adjoint normal-form sector. -/
def swapNegativeNormal (X : N) : N :=
  normalForm (X 0 0) (X 1 1) (X 2 2) (X 3 3) (X 2 3) (X 0 1)

/-- Reflection of the rational positive-complement disk across its diagonal. -/
def swapDisk (p : ℚ × ℚ) : ℚ × ℚ := (p.2, p.1)

/-- Orbit relation for the genuine order-two action generated by `swapDisk`. -/
def SameSwapOrbit (p q : ℚ × ℚ) : Prop :=
  q = p ∨ q = swapDisk p

/-- On exact normal forms, the map exchanges only the two negative
coordinates. -/
theorem swapNegativeNormal_normalForm (a d e g b f : ℚ) :
    swapNegativeNormal (normalForm a d e g b f) =
      normalForm a d e g f b := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [swapNegativeNormal, normalForm]

/-- The coordinate swap is an involution on the full even
Krein-self-adjoint normal-form sector. -/
theorem swapNegativeNormal_involutive
    (X : N) (hself : kadj X = X) (heven : Gam * X = X * Gam) :
    swapNegativeNormal (swapNegativeNormal X) = X := by
  obtain ⟨a, d, e, g, b, f, rfl⟩ :=
    ChannelKreinSectorSignature.even_selfadjoint_exists_normalForm X hself heven
  rw [swapNegativeNormal_normalForm, swapNegativeNormal_normalForm]

/-- The coordinate swap preserves the exact Gram pairing on every pair of
normal-form vectors, not only their self-pairings. -/
theorem swapNegativeNormal_gram
    (a d e g b f a' d' e' g' b' f' : ℚ) :
    kreinGram (swapNegativeNormal (normalForm a d e g b f))
        (swapNegativeNormal (normalForm a' d' e' g' b' f')) =
      kreinGram (normalForm a d e g b f)
        (normalForm a' d' e' g' b' f') := by
  rw [swapNegativeNormal_normalForm, swapNegativeNormal_normalForm,
    ChannelPositiveComplementDisk.normalForm_gram_bilinear,
    ChannelPositiveComplementDisk.normalForm_gram_bilinear]
  ring

/-- The residual rational isometry fixes each of the three named even
channels pointwise. -/
theorem swapNegativeNormal_fixes_named_channels :
    swapNegativeNormal apertureC = apertureC ∧
      swapNegativeNormal closureC = closureC ∧
      swapNegativeNormal turnC = turnC := by
  refine ⟨?_, ?_, ?_⟩
  · rw [ChannelPositiveComplementDisk.apertureC_normalForm,
      swapNegativeNormal_normalForm]
  · rw [ChannelPositiveComplementDisk.closureC_normalForm,
      swapNegativeNormal_normalForm]
  · rw [ChannelPositiveComplementDisk.turnC_normalForm,
      swapNegativeNormal_normalForm]

/-- On classified positive-complement representatives, the residual isometry
acts by reflection across the diagonal of the rational open disk. -/
theorem swapNegativeNormal_diskVector (u v : ℚ) :
    swapNegativeNormal (diskVector u v) = diskVector v u := by
  rw [diskVector, diskVector, swapNegativeNormal_normalForm]

/-- **Stabilizer-orbit selector obstruction.** The rational points `(3/5,0)`
and `(0,3/5)` give distinct, strictly positive represented sectors, while
their normalized complement witnesses lie in one orbit of a Gram isometry
fixing all three named channels.  Consequently a selector invariant under this
single declared residual symmetry cannot separate those witnesses.

This does not assert that the orbit is a physical equivalence class. -/
theorem rational_swap_orbit_obstructs_invariant_selector
    {A : Type*} (selector : N → A)
    (hinv : ∀ X : N, kadj X = X → Gam * X = X * Gam →
      selector (swapNegativeNormal X) = selector X) :
    let X := diskVector (3 / 5) 0
    let Y := diskVector 0 (3 / 5)
    X ≠ Y ∧
      SameSwapOrbit ((3 / 5, 0) : ℚ × ℚ) (0, 3 / 5) ∧
      swapNegativeNormal X = Y ∧
      InTiltedSector (3 / 5) 0 X ∧
      ¬ InTiltedSector 0 (3 / 5) X ∧
      InTiltedSector 0 (3 / 5) Y ∧
      ¬ InTiltedSector (3 / 5) 0 Y ∧
      kreinGram X X = 32 / 25 ∧
      kreinGram Y Y = 32 / 25 ∧
      selector X = selector Y := by
  intro X Y
  have hX : X = normalForm 1 (-1) 0 0 (3 / 5) 0 := rfl
  have hY : Y = normalForm 1 (-1) 0 0 0 (3 / 5) := rfl
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · rw [hX, hY]
    intro h
    obtain ⟨_, _, _, _, hb, _⟩ :=
      ChannelKreinSectorSignature.normalForm_coordinates_unique h
    norm_num at hb
  · exact Or.inr rfl
  · rw [hX, hY, swapNegativeNormal_normalForm]
  · rw [hX]
    exact ⟨0, 1, 0, 0, by
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [tiltedPositive, normalForm]⟩
  · rw [hX]
    rintro ⟨m, x, e, g, h⟩
    simp only [tiltedPositive] at h
    obtain ⟨_, _, _, _, hb, _⟩ :=
      ChannelKreinSectorSignature.normalForm_coordinates_unique h
    norm_num at hb
  · rw [hY]
    exact ⟨0, 1, 0, 0, by
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [tiltedPositive, normalForm]⟩
  · rw [hY]
    rintro ⟨m, x, e, g, h⟩
    simp only [tiltedPositive] at h
    obtain ⟨_, _, _, _, _, hf⟩ :=
      ChannelKreinSectorSignature.normalForm_coordinates_unique h
    norm_num at hf
  · rw [hX, ChannelPositiveComplementDisk.normalForm_gram_bilinear]
    norm_num
  · rw [hY, ChannelPositiveComplementDisk.normalForm_gram_bilinear]
    norm_num
  · have hself : kadj X = X := by
      rw [hX]; exact ChannelKreinSectorSignature.normalForm_selfadjoint _ _ _ _ _ _
    have heven : Gam * X = X * Gam := by
      rw [hX]; exact ChannelKreinSectorSignature.normalForm_even _ _ _ _ _ _
    have hsel := hinv X hself heven
    rw [show swapNegativeNormal X = Y from by
      rw [hX, hY, swapNegativeNormal_normalForm]] at hsel
    exact hsel.symm

end PhysicsSM.Draft.NullEdge.ChannelStabilizerSelectorSuccessor
