import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Mathlib.LinearAlgebra.Matrix.Charpoly.Coeff
import PhysicsSM.Draft.NullEdge.FiniteEinsteinHilbertActionResponse

/-!
# Coframe volume and inverse-metric variation

The affine interval action has no nontrivial stationary point because its
gradient is constant. This module supplies the first genuinely nonlinear
geometric response needed by an Einstein-Hilbert successor: the variation of
oriented coframe volume.

For a real square coframe `e` and generator `X`, use the multiplicative path

```text
e(t) = e (1 + t X).
```

Determinant multiplicativity and the polynomial identity

```text
d/dt det(1 + t X) |_(t=0) = trace X
```

give `delta det(e) = det(e) trace(X)`. The corresponding inverse-metric
variation is

```text
h = -(X gInv + gInv X^T).
```

When `gInv` is the two-sided inverse of the symmetric covariant metric `g`,
the exact trace identity is

```text
<g, h> = -2 trace(X),
```

so `delta det(e) = -(det(e)/2) <g,h>`. This is the finite counterpart of the
standard inverse-metric volume-density variation. The generator map reaches
every symmetric inverse-metric variation when `g` and `gInv` are symmetric
two-sided inverses.

No graph-derived coframe, orientation, or nondegeneracy theorem is claimed.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.CoframeVolumeMetricVariation

open Matrix
open EinsteinEquationVariation
open StressEnergyPhysicalControls
open RelaxedCausalMetricVariationBridge

variable {I : Type*} [Fintype I] [DecidableEq I]

/-- A real square coframe used for differentiable finite geometry. -/
abbrev RealCoframe := Matrix I I Real

/-- Oriented coframe volume. Positive-orientation hypotheses are needed before
identifying it with the unsigned Lorentzian volume density. -/
def coframeVolume (e : RealCoframe (I := I)) : Real := e.det

/-- Covariant metric induced by a coframe and an internal bilinear form. -/
def inducedCovariantMetric
    (eta e : RealCoframe (I := I)) : Tensor (I := I) :=
  e.transpose * eta * e

/-- First covariant-metric response generated by `e -> e (1 + t X)`. -/
def covariantMetricVariation
    (metric X : Tensor (I := I)) : Tensor (I := I) :=
  X.transpose * metric + metric * X

/-- First inverse-metric response corresponding to the same coframe path. -/
def inverseMetricVariation
    (inverseMetric X : Tensor (I := I)) : Tensor (I := I) :=
  -(X * inverseMetric + inverseMetric * X.transpose)

/-- The determinant derivative at the identity is the matrix trace. This is
proved from Mathlib's polynomial determinant identity, not inserted as a
calculus assumption. -/
theorem hasDerivAt_det_one_add_smul (X : RealCoframe (I := I)) :
    HasDerivAt (fun t : Real => (1 + t • X).det) X.trace 0 := by
  let p : Polynomial Real :=
    Matrix.det
      (1 + (Polynomial.X : Polynomial Real) • X.map Polynomial.C)
  have hp : HasDerivAt (fun t : Real => p.eval t)
      (p.derivative.eval 0) 0 :=
    p.hasDerivAt 0
  have hDerivative : p.derivative.eval 0 = X.trace := by
    dsimp [p]
    exact Matrix.derivative_det_one_add_X_smul X
  rw [hDerivative] at hp
  convert hp using 1
  funext t
  dsimp [p]
  simp [eval_det, ← smul_eq_mul_diagonal]

/-- Exact coframe-volume derivative along a multiplicative frame path. -/
theorem hasDerivAt_coframeVolume_mulPath
    (e X : RealCoframe (I := I)) :
    HasDerivAt
      (fun t : Real => coframeVolume (e * (1 + t • X)))
      (coframeVolume e * X.trace) 0 := by
  simpa [coframeVolume, Matrix.det_mul] using
    (hasDerivAt_det_one_add_smul X).const_mul e.det

/-- The same volume derivative written as an affine tangent path through the
coframe, with tangent `e X`. -/
theorem hasDerivAt_coframeVolume_affinePath
    (e X : RealCoframe (I := I)) :
    HasDerivAt
      (fun t : Real => coframeVolume (e + t • (e * X)))
      (coframeVolume e * X.trace) 0 := by
  convert hasDerivAt_coframeVolume_mulPath e X using 1
  funext t
  congr 1
  simp [Matrix.mul_add]

omit [DecidableEq I] in
/-- A symmetric internal form induces a symmetric covariant metric. -/
theorem inducedCovariantMetric_isSymm
    (eta e : RealCoframe (I := I)) (hEta : eta.IsSymm) :
    (inducedCovariantMetric eta e).IsSymm := by
  unfold inducedCovariantMetric Matrix.IsSymm
  rw [Matrix.transpose_mul, Matrix.transpose_mul, Matrix.transpose_transpose,
    hEta.eq, Matrix.mul_assoc]

omit [DecidableEq I] in
/-- Every coframe generator produces a symmetric inverse-metric response when
the inverse metric is symmetric. -/
theorem inverseMetricVariation_isSymm
    (inverseMetric X : Tensor (I := I))
    (hInverseMetric : inverseMetric.IsSymm) :
    (inverseMetricVariation inverseMetric X).IsSymm := by
  unfold inverseMetricVariation Matrix.IsSymm
  simp only [Matrix.transpose_neg, Matrix.transpose_add,
    Matrix.transpose_mul, Matrix.transpose_transpose, hInverseMetric.eq]
  rw [add_comm]

/-- The inverse-metric response is linear in the coframe generator. -/
def inverseMetricVariationLinear
    (inverseMetric : Tensor (I := I)) :
    Tensor (I := I) →ₗ[Real] Tensor (I := I) where
  toFun := inverseMetricVariation inverseMetric
  map_add' X Y := by
    unfold inverseMetricVariation
    simp only [add_mul, Matrix.transpose_add, mul_add]
    abel
  map_smul' scalar X := by
    unfold inverseMetricVariation
    simp only [Matrix.smul_mul, Matrix.transpose_smul, Matrix.mul_smul,
      RingHom.id_apply]
    module

/-- Pairing the covariant metric with its coframe-generated inverse variation
gives minus twice the generator trace. -/
theorem metricVariationPairing_inverseMetricVariation
    (metric inverseMetric X : Tensor (I := I))
    (hMetric : metric.IsSymm)
    (hLeft : inverseMetric * metric = 1)
    (hRight : metric * inverseMetric = 1) :
    metricVariationPairing metric
        (inverseMetricVariation inverseMetric X) =
      -2 * X.trace := by
  have hFirst :
      Matrix.trace (metric * (X * inverseMetric)) = X.trace := by
    calc
      Matrix.trace (metric * (X * inverseMetric)) =
          Matrix.trace (inverseMetric * (metric * X)) :=
        Matrix.trace_mul_cycle' metric X inverseMetric
      _ = Matrix.trace ((inverseMetric * metric) * X) := by
        rw [Matrix.mul_assoc]
      _ = X.trace := by rw [hLeft, Matrix.one_mul]
  have hSecond :
      Matrix.trace (metric * (inverseMetric * X.transpose)) = X.trace := by
    calc
      Matrix.trace (metric * (inverseMetric * X.transpose)) =
          Matrix.trace (X.transpose * (metric * inverseMetric)) :=
        Matrix.trace_mul_cycle' metric inverseMetric X.transpose
      _ = Matrix.trace X.transpose := by rw [hRight, Matrix.mul_one]
      _ = X.trace := Matrix.trace_transpose X
  unfold metricVariationPairing inverseMetricVariation
  rw [hMetric.eq, Matrix.mul_neg, Matrix.trace_neg, Matrix.mul_add,
    Matrix.trace_add, hFirst, hSecond]
  ring

/-- **Coframe volume response in inverse-metric form.** The determinant
response is exactly the standard negative one-half metric trace. -/
theorem coframeVolumeResponse_eq_inverseMetricPairing
    (e : RealCoframe (I := I))
    (metric inverseMetric X : Tensor (I := I))
    (hMetric : metric.IsSymm)
    (hLeft : inverseMetric * metric = 1)
    (hRight : metric * inverseMetric = 1) :
    coframeVolume e * X.trace =
      -(coframeVolume e / 2) *
        metricVariationPairing metric
          (inverseMetricVariation inverseMetric X) := by
  rw [metricVariationPairing_inverseMetricVariation metric inverseMetric X
    hMetric hLeft hRight]
  ring

/-- The coframe determinant derivative, now expressed entirely through the
generated inverse-metric variation. -/
theorem hasDerivAt_coframeVolume_eq_inverseMetricPairing
    (e : RealCoframe (I := I))
    (metric inverseMetric X : Tensor (I := I))
    (hMetric : metric.IsSymm)
    (hLeft : inverseMetric * metric = 1)
    (hRight : metric * inverseMetric = 1) :
    HasDerivAt
      (fun t : Real => coframeVolume (e + t • (e * X)))
      (-(coframeVolume e / 2) *
        metricVariationPairing metric
          (inverseMetricVariation inverseMetric X)) 0 := by
  have hDerivative := hasDerivAt_coframeVolume_affinePath e X
  rw [coframeVolumeResponse_eq_inverseMetricPairing e metric inverseMetric X
    hMetric hLeft hRight] at hDerivative
  exact hDerivative

/-- **Full inverse-metric reach from coframe generators.** For a symmetric
nondegenerate metric, every symmetric inverse-metric variation is generated by
some matrix `X`. -/
theorem inverseMetricVariationLinear_isFull
    (metric inverseMetric : Tensor (I := I))
    (hMetric : metric.IsSymm) (hInverseMetric : inverseMetric.IsSymm)
    (hLeft : inverseMetric * metric = 1)
    (hRight : metric * inverseMetric = 1) :
    IsFullSymmetricMetricDerivative
      (inverseMetricVariationLinear inverseMetric) := by
  constructor
  · intro X
    exact inverseMetricVariation_isSymm inverseMetric X hInverseMetric
  · intro variation hVariation
    let X : Tensor (I := I) := (-1 / 2 : Real) • (variation * metric)
    refine ⟨X, ?_⟩
    change inverseMetricVariation inverseMetric X = variation
    unfold inverseMetricVariation X
    rw [Matrix.smul_mul, Matrix.mul_assoc, hRight, Matrix.mul_one,
      Matrix.transpose_smul, Matrix.transpose_mul, hVariation.eq, hMetric.eq,
      Matrix.mul_smul, ← Matrix.mul_assoc, hLeft, Matrix.one_mul]
    module

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.CoframeVolumeMetricVariation.hasDerivAt_coframeVolume_eq_inverseMetricPairing' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms hasDerivAt_coframeVolume_eq_inverseMetricPairing

/-- info: 'PhysicsSM.Draft.NullEdge.CoframeVolumeMetricVariation.inverseMetricVariationLinear_isFull' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms inverseMetricVariationLinear_isFull

end PhysicsSM.Draft.NullEdge.CoframeVolumeMetricVariation
