import PhysicsSM.Draft.NullEdge.DixonDiracGamma

/-!
# P2: classification test for quaternionic bar operators

This file exhausts the sixteen unsigned operators `u|v`, where each entry is
one of `1, i₁, i₂, i₃`.  The proposed uniqueness of Lorentz signature is
**false** for this class: besides Lorentzian quadruples, the class contains
mutually anticommuting quadruples of signature `(2,2)`.  A kernel-checked
counterexample is exhibited below.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.DixonSignatureClassification

set_option maxHeartbeats 16000000
set_option maxRecDepth 16000

open PhysicsSM.Algebra.Octonion.ComplexOctonion
open PhysicsSM.Draft.NullEdge.DixonAlgebra
open PhysicsSM.Draft.NullEdge.DixonAlgebra.Dixon
open PhysicsSM.Draft.NullEdge.DixonWeakLadders
open PhysicsSM.Draft.NullEdge.DixonDiracGamma

/-- The four unsigned quaternion basis units. -/
inductive HUnit where
  | one | i1 | i2 | i3
  deriving DecidableEq, Repr

/-- An unsigned quaternionic bar-operator label. -/
structure HPair where
  left : HUnit
  right : HUnit
  deriving DecidableEq, Repr

/-- Interpretation of an unsigned unit in the Dixon algebra. -/
def HUnit.val : HUnit → Dixon
  | .one => 1
  | .i1 => Dixon.i1
  | .i2 => Dixon.i2
  | .i3 => Dixon.i3

/-- The bar operator represented by a pair. -/
def B (p : HPair) (z : Dixon) : Dixon := bar p.left.val p.right.val z

/-- Whether a basis unit is imaginary. -/
def HUnit.imaginary : HUnit → Bool
  | .one => false
  | _ => true

/-- The square sign of an unsigned pair.  It is negative exactly when one,
but not both, entries is imaginary. -/
def negativeSquare (p : HPair) : Bool := p.left.imaginary != p.right.imaginary

/-- Apply the square sign belonging to `p`. -/
def squareSigned (p : HPair) (z : Dixon) : Dixon :=
  if negativeSquare p then -z else z

/-- Shared coordinatewise kernel closer.  `simp_all` also disposes of the
finite Boolean side conditions generated by case splits. -/
macro "bar_kernel" : tactic =>
  `(tactic|
    (refine Dixon.ext ?_ ?_ ?_ ?_ <;>
      ext <;>
        simp [B, HUnit.val, squareSigned, negativeSquare, HUnit.imaginary,
          bar, Idix, ofColour, mul, Dixon.i1, Dixon.i2, Dixon.i3, I,
          ComplexOctonion.mul_re, ComplexOctonion.mul_im] <;>
        ring))

/-! ## 1. Complete square table -/

/-- Square-table entry `one|one`. -/
theorem sq_one_one (z : Dixon) : B ⟨.one, .one⟩ (B ⟨.one, .one⟩ z) = z := by
  bar_kernel

/-- Square-table entry `one|i1`. -/
theorem sq_one_i1 (z : Dixon) : B ⟨.one, .i1⟩ (B ⟨.one, .i1⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `one|i2`. -/
theorem sq_one_i2 (z : Dixon) : B ⟨.one, .i2⟩ (B ⟨.one, .i2⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `one|i3`. -/
theorem sq_one_i3 (z : Dixon) : B ⟨.one, .i3⟩ (B ⟨.one, .i3⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `i1|one`. -/
theorem sq_i1_one (z : Dixon) : B ⟨.i1, .one⟩ (B ⟨.i1, .one⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `i1|i1`. -/
theorem sq_i1_i1 (z : Dixon) : B ⟨.i1, .i1⟩ (B ⟨.i1, .i1⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i1|i2`. -/
theorem sq_i1_i2 (z : Dixon) : B ⟨.i1, .i2⟩ (B ⟨.i1, .i2⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i1|i3`. -/
theorem sq_i1_i3 (z : Dixon) : B ⟨.i1, .i3⟩ (B ⟨.i1, .i3⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i2|one`. -/
theorem sq_i2_one (z : Dixon) : B ⟨.i2, .one⟩ (B ⟨.i2, .one⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `i2|i1`. -/
theorem sq_i2_i1 (z : Dixon) : B ⟨.i2, .i1⟩ (B ⟨.i2, .i1⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i2|i2`. -/
theorem sq_i2_i2 (z : Dixon) : B ⟨.i2, .i2⟩ (B ⟨.i2, .i2⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i2|i3`. -/
theorem sq_i2_i3 (z : Dixon) : B ⟨.i2, .i3⟩ (B ⟨.i2, .i3⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i3|one`. -/
theorem sq_i3_one (z : Dixon) : B ⟨.i3, .one⟩ (B ⟨.i3, .one⟩ z) = -z := by
  bar_kernel

/-- Square-table entry `i3|i1`. -/
theorem sq_i3_i1 (z : Dixon) : B ⟨.i3, .i1⟩ (B ⟨.i3, .i1⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i3|i2`. -/
theorem sq_i3_i2 (z : Dixon) : B ⟨.i3, .i2⟩ (B ⟨.i3, .i2⟩ z) = z := by
  bar_kernel

/-- Square-table entry `i3|i3`. -/
theorem sq_i3_i3 (z : Dixon) : B ⟨.i3, .i3⟩ (B ⟨.i3, .i3⟩ z) = z := by
  bar_kernel

/-- The square law for all sixteen unsigned pairs. -/
theorem square_law (p : HPair) (z : Dixon) : B p (B p z) = squareSigned p z := by
  rcases p with ⟨u, v⟩
  cases u <;> cases v <;> simp [squareSigned, negativeSquare, HUnit.imaginary]
  all_goals first | exact sq_one_one z | exact sq_one_i1 z | exact sq_one_i2 z | exact sq_one_i3 z | exact sq_i1_one z | exact sq_i1_i1 z | exact sq_i1_i2 z | exact sq_i1_i3 z | exact sq_i2_one z | exact sq_i2_i1 z | exact sq_i2_i2 z | exact sq_i2_i3 z | exact sq_i3_one z | exact sq_i3_i1 z | exact sq_i3_i2 z | exact sq_i3_i3 z

/-! ## 2. Anticommutation checks used by the counterexample -/

/-- Pointwise anticommutation of two bar operators. -/
def Anticomm (p q : HPair) : Prop :=
  ∀ z, B p (B q z) + B q (B p z) = 0

/-- Anticommutation check for `one_i1` and `one_i2`. -/
theorem ac_one_i1_one_i2 (z : Dixon) :
    B ⟨.one, .i1⟩ (B ⟨.one, .i2⟩ z) + B ⟨.one, .i2⟩ (B ⟨.one, .i1⟩ z) = 0 := by
  bar_kernel

/-- Anticommutation check for `one_i1` and `i1_i3`. -/
theorem ac_one_i1_i1_i3 (z : Dixon) :
    B ⟨.one, .i1⟩ (B ⟨.i1, .i3⟩ z) + B ⟨.i1, .i3⟩ (B ⟨.one, .i1⟩ z) = 0 := by
  bar_kernel

/-- Anticommutation check for `one_i1` and `i2_i3`. -/
theorem ac_one_i1_i2_i3 (z : Dixon) :
    B ⟨.one, .i1⟩ (B ⟨.i2, .i3⟩ z) + B ⟨.i2, .i3⟩ (B ⟨.one, .i1⟩ z) = 0 := by
  bar_kernel

/-- Anticommutation check for `one_i2` and `i1_i3`. -/
theorem ac_one_i2_i1_i3 (z : Dixon) :
    B ⟨.one, .i2⟩ (B ⟨.i1, .i3⟩ z) + B ⟨.i1, .i3⟩ (B ⟨.one, .i2⟩ z) = 0 := by
  bar_kernel

/-- Anticommutation check for `one_i2` and `i2_i3`. -/
theorem ac_one_i2_i2_i3 (z : Dixon) :
    B ⟨.one, .i2⟩ (B ⟨.i2, .i3⟩ z) + B ⟨.i2, .i3⟩ (B ⟨.one, .i2⟩ z) = 0 := by
  bar_kernel

/-- Anticommutation check for `i1_i3` and `i2_i3`. -/
theorem ac_i1_i3_i2_i3 (z : Dixon) :
    B ⟨.i1, .i3⟩ (B ⟨.i2, .i3⟩ z) + B ⟨.i2, .i3⟩ (B ⟨.i1, .i3⟩ z) = 0 := by
  bar_kernel

/-- The six pairwise checks for the split-signature counterexample. -/
theorem split_signature_pair_table :
    Anticomm ⟨.one, .i1⟩ ⟨.one, .i2⟩ ∧
    Anticomm ⟨.one, .i1⟩ ⟨.i1, .i3⟩ ∧
    Anticomm ⟨.one, .i1⟩ ⟨.i2, .i3⟩ ∧
    Anticomm ⟨.one, .i2⟩ ⟨.i1, .i3⟩ ∧
    Anticomm ⟨.one, .i2⟩ ⟨.i2, .i3⟩ ∧
    Anticomm ⟨.i1, .i3⟩ ⟨.i2, .i3⟩ := by
  constructor
  · exact ac_one_i1_one_i2
  constructor
  · exact ac_one_i1_i1_i3
  constructor
  · exact ac_one_i1_i2_i3
  constructor
  · exact ac_one_i2_i1_i3
  constructor
  · exact ac_one_i2_i2_i3
  · exact ac_i1_i3_i2_i3

/-! ## 3–4. The proposed classification fails -/

/-- Six pairwise anticommutation conditions for a quadruple. -/
def MutuallyAnticommuting4 (a b c d : HPair) : Prop :=
  Anticomm a b ∧ Anticomm a c ∧ Anticomm a d ∧
  Anticomm b c ∧ Anticomm b d ∧ Anticomm c d

/-- The claimed Lorentzian sign condition: exactly one square is negative. -/
def LorentzianSigns4 (a b c d : HPair) : Prop :=
  (negativeSquare a = true ∧ negativeSquare b = false ∧
    negativeSquare c = false ∧ negativeSquare d = false) ∨
  (negativeSquare a = false ∧ negativeSquare b = true ∧
    negativeSquare c = false ∧ negativeSquare d = false) ∨
  (negativeSquare a = false ∧ negativeSquare b = false ∧
    negativeSquare c = true ∧ negativeSquare d = false) ∨
  (negativeSquare a = false ∧ negativeSquare b = false ∧
    negativeSquare c = false ∧ negativeSquare d = true)

/-- **Prominent `(2,2)` counterexample.**  The operators
`1|i₁, 1|i₂, i₁|i₃, i₂|i₃` mutually anticommute. -/
theorem split_signature_counterexample_anticomm :
    MutuallyAnticommuting4 ⟨.one, .i1⟩ ⟨.one, .i2⟩
      ⟨.i1, .i3⟩ ⟨.i2, .i3⟩ := by
  exact split_signature_pair_table

/-- The same counterexample has square signs `(-,-,+,+)`. -/
theorem split_signature_counterexample_squares (z : Dixon) :
    B ⟨.one, .i1⟩ (B ⟨.one, .i1⟩ z) = -z ∧
    B ⟨.one, .i2⟩ (B ⟨.one, .i2⟩ z) = -z ∧
    B ⟨.i1, .i3⟩ (B ⟨.i1, .i3⟩ z) = z ∧
    B ⟨.i2, .i3⟩ (B ⟨.i2, .i3⟩ z) = z := by
  exact ⟨sq_one_i1 z, sq_one_i2 z, sq_i1_i3 z, sq_i2_i3 z⟩

/-- The requested universal classification theorem is false over the full
sixteen-member class.  This statement quantifies over that full class and
refutes precisely the proposed implication. -/
theorem lorentz_signature_not_forced :
    ¬ (∀ a b c d : HPair,
      MutuallyAnticommuting4 a b c d → LorentzianSigns4 a b c d) := by
  intro h
  have hc := h ⟨.one, .i1⟩ ⟨.one, .i2⟩ ⟨.i1, .i3⟩ ⟨.i2, .i3⟩
    split_signature_counterexample_anticomm
  simp [LorentzianSigns4, negativeSquare, HUnit.imaginary] at hc

end PhysicsSM.Draft.NullEdge.DixonSignatureClassification
