import Mathlib

/-!
# Finite diagonal-plus-causal massive resolvent

This module generalizes the strictly off-diagonal retarded series to a
massless kernel with a diagonal term,

```text
G0 = b * I + N,
```

where `N` is nilpotent. This is the finite algebraic shape relevant to a
truncated link exponential, whose constant identity term is a local contact
convention rather than a positive-length propagation step. The massive
scattering response is `G0 * (I + c * G0)^{-1}`.

The proof bodies were recovered from the in-progress snapshot of Aristotle
project `18ad01bc-dd21-4cbe-9424-81ff8451d03f` and replayed under the pinned
project toolchain without changing the public statements.

No continuum limit, kernel normalization, or identification with a physical
Green function is claimed. Matrix rows are targets and columns are sources.
Claim grade: `M [comp]`.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Finite geometric candidate for the inverse of `a * I + N`. -/
def nilpotentInverse
    (a : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (a⁻¹) • ∑ k ∈ Finset.range H, (-a⁻¹) ^ k • N ^ k

/-- A scalar plus an `H`-nilpotent matrix times the finite inverse is exactly
the identity. -/
theorem scalar_add_nilpotent_mul_inverse
    (a : Real) (N : Matrix V V Real) (H : Nat)
    (ha : a ≠ 0) (hNil : N ^ H = 0) :
    (a • (1 : Matrix V V Real) + N) * nilpotentInverse a N H = 1 := by
  unfold nilpotentInverse
  simp +decide [add_mul, ha]
  convert (Finset.sum_range_sub' (fun k => (-a⁻¹) ^ k • N ^ k) H) using 1
  simp_all +decide [pow_succ', Finset.mul_sum _ _ _]
  ring_nf
  · simp +decide [mul_assoc, Finset.smul_sum, Finset.sum_add_distrib,
      smul_smul]
  · aesop

/-- The same finite inverse is also a right inverse. -/
theorem inverse_mul_scalar_add_nilpotent
    (a : Real) (N : Matrix V V Real) (H : Nat)
    (ha : a ≠ 0) (hNil : N ^ H = 0) :
    nilpotentInverse a N H * (a • (1 : Matrix V V Real) + N) = 1 := by
  have hLeft := scalar_add_nilpotent_mul_inverse a N H ha hNil
  exact mul_eq_one_comm.mp hLeft

/-- Massive scattering response generated by `G0 = b * I + N`. -/
def massiveScatteringResponse
    (b c : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (b • (1 : Matrix V V Real) + N) *
    nilpotentInverse (1 + c * b) (c • N) H

/-- Exact left resolvent for a diagonal-plus-nilpotent massless kernel. -/
theorem one_add_massless_mul_massiveScatteringResponse
    (b c : Real) (N : Matrix V V Real) (H : Nat)
    (hDen : 1 + c * b ≠ 0) (hNil : N ^ H = 0) :
    (1 + c • (b • (1 : Matrix V V Real) + N)) *
        massiveScatteringResponse b c N H =
      b • (1 : Matrix V V Real) + N := by
  convert congr_arg
    (fun x : Matrix V V Real => (b • 1 + N) * x)
    (scalar_add_nilpotent_mul_inverse
      (1 + c * b) (c • N) H hDen (by simp [hNil, smul_pow])) using 1
  · simp +decide [massiveScatteringResponse, mul_add, add_mul, mul_assoc,
      smul_smul]
    module
  · rw [mul_one]

/-- Exact right resolvent for the same response. -/
theorem massiveScatteringResponse_mul_one_add_massless
    (b c : Real) (N : Matrix V V Real) (H : Nat)
    (hDen : 1 + c * b ≠ 0) (hNil : N ^ H = 0) :
    massiveScatteringResponse b c N H *
        (1 + c • (b • (1 : Matrix V V Real) + N)) =
      b • (1 : Matrix V V Real) + N := by
  convert congr_arg
    (fun x : Matrix V V Real => (b • 1 + N) * x)
    (inverse_mul_scalar_add_nilpotent
      (1 + c * b) (c • N) H hDen (by simp [hNil, smul_pow])) using 1
  · simp +decide [massiveScatteringResponse, nilpotentInverse, mul_add,
      add_mul, mul_assoc, smul_smul, mul_left_comm, mul_comm]
    module
  · rw [mul_one]

/-- Primitive link kernel on the chain `0 -> 1 -> 2`. -/
def threeLinkKernel : Matrix (Fin 3) (Fin 3) Real :=
  !![0, 0, 0; 1, 0, 0; 0, 1, 0]

/-- Off-diagonal part of the exact finite exponential of the cube-zero link
kernel: `exp(L) = I + L + (1/2)L^2`. -/
def threeExpOffDiagonal : Matrix (Fin 3) (Fin 3) Real :=
  threeLinkKernel + (1 / 2 : Real) • threeLinkKernel ^ 2

/-- Nonvacuous diagonal-kernel control. The primitive link has no endpoint
entry, the truncated exponential has endpoint entry `1/2`, and at scattering
coefficient `c = 2` the massive response has endpoint entry `-1/54`. -/
theorem threeLink_exponential_massive_witness :
    threeLinkKernel 2 0 = 0 ∧
      (1 + threeExpOffDiagonal) 2 0 = 1 / 2 ∧
      threeExpOffDiagonal ^ 3 = 0 ∧
      massiveScatteringResponse 1 2 threeExpOffDiagonal 3 2 0 = -1 / 54 := by
  unfold massiveScatteringResponse nilpotentInverse
  norm_num [Finset.sum_range_succ, pow_succ]
  unfold threeLinkKernel threeExpOffDiagonal
  norm_num [Matrix.mul_apply, Fin.sum_univ_succ]
  norm_num [threeLinkKernel, pow_two]
  simp +decide [Matrix.one_apply] at *
  exact ⟨by ext i j; fin_cases i <;> fin_cases j <;> rfl, by norm_num⟩

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent.scalar_add_nilpotent_mul_inverse' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms scalar_add_nilpotent_mul_inverse

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent.one_add_massless_mul_massiveScatteringResponse' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms one_add_massless_mul_massiveScatteringResponse

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent.massiveScatteringResponse_mul_one_add_massless' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms massiveScatteringResponse_mul_one_add_massless

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent.threeLink_exponential_massive_witness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms threeLink_exponential_massive_witness

end PhysicsSM.Draft.NullEdge.FiniteDiagonalCausalResolvent

end
