import Mathlib

/-!
# A finite local even fermionic pair interaction

This module is an interacting control for the null-edge `3+1` program.  It uses
five ordered occupation modes: four modes form one interaction cell and the
fifth is an explicit outside mode.  The displayed quartic CAR word equals an
exact pair-transfer Hamiltonian.  A closed pair update is unitary when its
complex phase has unit norm, preserves number and parity, fixes vacuum and the
one-particle sector, and acts nontrivially on a two-particle state.

Locality is proved operator-theoretically.  The update and inverse commute with
the outside creation and annihilation operators, conjugation fixes both outside
CAR generators, and the simultaneous commutant defining the cell algebra is
closed under conjugation.  The full two-particle sector is invariant, while an
explicit one-dimensional pair sector is mixed.

This finite model does not prove positivity of energy, a free-plus-interacting
QCA light cone, an interacting continuum limit, scattering, or QFT.  In
particular, fermion parity is not interpreted as a positive-energy selector.

Provenance: proof generated by Aristotle project
`b24cac42-5b01-4b43-b2e4-9c3317a7d019`, locally rechecked under the pinned
toolchain.  Claim grade `M`, `[comp]`.
-/

open scoped ComplexConjugate
open Classical

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace FermionInteraction

abbrev Mode := Fin 5
abbrev Config := Finset Mode
abbrev Fock := Config → ℂ
abbrev Op := Fock → Fock

instance : AddCommGroup Fock := Pi.addCommGroup
instance : Module ℂ Fock := Pi.module _ _ _

/-- Ordered Jordan--Wigner sign: the number of occupied modes preceding `i`. -/
def jwSign (C : Config) (i : Mode) : ℂ :=
  if Even ((C.filter (fun j => j < i)).card) then 1 else -1

/-- Creation operator in the exact occupation basis. -/
def create (i : Mode) : Op := fun ψ C =>
  if i ∈ C then jwSign (C.erase i) i * ψ (C.erase i) else 0

/-- Annihilation operator in the exact occupation basis. -/
def annihilate (i : Mode) : Op := fun ψ C =>
  if i ∈ C then 0 else jwSign C i * ψ (insert i C)

/-- Composition of operators, written in the order used in the displayed Hamiltonian. -/
def mul (A B : Op) : Op := fun ψ => A (B ψ)

infixr:80 " ∘ₒ " => mul

/-- The occupation ket. -/
def ket (C : Config) : Fock := fun D => if D = C then 1 else 0

/-- The four-mode interaction cell.  Mode `4` is an explicit outside mode. -/
def cell : Finset Mode := {0, 1, 2, 3}

def pair01 : Config := {0, 1}
def pair23 : Config := {2, 3}

/-- Whether the outside mode is occupied. -/
def outsideBit (C : Config) : Bool := decide ((4 : Mode) ∈ C)

/-- Remove the explicit outside mode. -/
def core (C : Config) : Config := C.erase 4

/-- Exact pair transfer, with a possible occupation of mode 4 carried unchanged. -/
def pairForward : Op := fun ψ C =>
  if core C = pair23 then ψ ((pair01 ∪ (C ∩ {4} : Config))) else 0

def pairBackward : Op := fun ψ C =>
  if core C = pair01 then ψ ((pair23 ∪ (C ∩ {4} : Config))) else 0

/-- The quartic Hamiltonian, first given literally in ordered CAR form. -/
def quarticHamiltonian (z : ℂ) : Op :=
  fun ψ => z • ((create 2 ∘ₒ create 3 ∘ₒ annihilate 1 ∘ₒ annihilate 0) ψ) +
    conj z • ((create 0 ∘ₒ create 1 ∘ₒ annihilate 3 ∘ₒ annihilate 2) ψ)

/-- Closed occupation-basis form of the same Hamiltonian. -/
def H (z : ℂ) : Op := fun ψ C =>
  z * pairForward ψ C + conj z * pairBackward ψ C

/-
All Jordan--Wigner ordering signs in the displayed quartic evaluate to `+1`.
-/
theorem quarticHamiltonian_eq_H (z : ℂ) : quarticHamiltonian z = H z := by
  apply funext;
  intro ψ; ext C; simp +decide [ quarticHamiltonian, H, pairForward, pairBackward ] ;
  unfold mul create annihilate; simp +decide [ Finset.filter_eq', Finset.filter_ne' ] ;
  fin_cases C <;> simp +decide [ jwSign ];
  · exact Or.inl rfl;
  · exact Or.inl rfl;
  · exact Or.inl ( congr_arg _ ( by decide ) );
  · exact Or.inl ( congr_arg _ ( by decide ) )

/-- Matrix-entry formulation of the adjoint relation. -/
def IsAdjoint (A B : Op) : Prop :=
  ∀ C D, conj (A (ket D) C) = B (ket C) D

def IsHermitian (A : Op) : Prop := IsAdjoint A A

/-
`H z` is Hermitian.
-/
theorem H_hermitian (z : ℂ) : IsHermitian (H z) := by
  intro C D; simp +decide [ H ];
  unfold pairForward pairBackward ket; simp +decide [ Finset.ext_iff ] ;
  split_ifs <;> simp_all +decide [ Finset.ext_iff ];
  all_goals simp_all +decide [ Fin.forall_fin_succ, Fin.exists_fin_succ, core, pair01, pair23 ]

/-- Number-sector preservation, stated as vanishing of matrix entries between
unequal occupation numbers. -/
def PreservesNumber (A : Op) : Prop :=
  ∀ C D, C.card ≠ D.card → A (ket D) C = 0

/-- Parity preservation, independently stated (not called positive energy). -/
def PreservesParity (A : Op) : Prop :=
  ∀ C D, C.card % 2 ≠ D.card % 2 → A (ket D) C = 0

theorem H_preserves_number (z : ℂ) : PreservesNumber (H z) := by
  intros C D h_neq; simp_all +decide [ H, IsAdjoint, PreservesNumber ] ;
  by_cases h2 : core C = pair23 <;> simp_all +decide [ pairForward, pairBackward, ket ];
  · rintro rfl; fin_cases C <;> trivial;
  · rintro h3 rfl; fin_cases C <;> trivial;

theorem number_implies_parity (A : Op) (h : PreservesNumber A) : PreservesParity A := by
  intro C D hD; specialize h C D; aesop;

theorem H_preserves_parity (z : ℂ) : PreservesParity (H z) :=
  number_implies_parity _ (H_preserves_number z)

theorem H_vacuum (z : ℂ) : H z (ket ∅) = 0 := by
  funext C; simp +decide [ H, pairForward, pairBackward, core, pair01, pair23 ] ;
  unfold ket; aesop;

theorem H_one_particle (z : ℂ) (i : Mode) : H z (ket {i}) = 0 := by
  funext C;
  unfold H;
  fin_cases i <;> simp +decide [ pairForward, pairBackward ];
  · unfold ket; simp +decide [ Finset.ext_iff ] ;
    split_ifs <;> simp_all +decide [ Fin.forall_fin_succ ];
  · fin_cases C <;> simp +decide [ ket ];
  · fin_cases C <;> simp +decide [ ket ];
  · fin_cases C <;> simp +decide [ core, pair01, pair23, ket ];
  · fin_cases C <;> simp +decide [ ket ]

/-
The explicit pair state is transferred with coefficient `z`.
-/
theorem H_pair01_at_pair23 (z : ℂ) : H z (ket pair01) pair23 = z := by
  unfold H; simp +decide [ pairForward, pairBackward, ket ] ;

theorem H_nontrivial {z : ℂ} (hz : z ≠ 0) : H z (ket pair01) ≠ 0 := by
  exact fun h => hz <| by simpa [ H_pair01_at_pair23 ] using congr_fun h pair23;

/-- A closed-form interaction update.  On each `01/23` pair block it is the
matrix `[[0, -conj z], [z, 0]]`; elsewhere it is the identity. -/
def U (z : ℂ) : Op := fun ψ C =>
  if core C = pair23 then z * ψ (pair01 ∪ (C ∩ {4} : Config))
  else if core C = pair01 then -(conj z) * ψ (pair23 ∪ (C ∩ {4} : Config))
  else ψ C

/-- Its explicit inverse (and adjoint when `normSq z = 1`). -/
def Uinv (z : ℂ) : Op := fun ψ C =>
  if core C = pair23 then -(z) * ψ (pair01 ∪ (C ∩ {4} : Config))
  else if core C = pair01 then conj z * ψ (pair23 ∪ (C ∩ {4} : Config))
  else ψ C

/-- Exact unitary condition for the phase parameter. -/
def IsUnitary (V W : Op) : Prop :=
  (∀ ψ, V (W ψ) = ψ) ∧ (∀ ψ, W (V ψ) = ψ) ∧ IsAdjoint V W

theorem U_unitary {z : ℂ} (hz : Complex.normSq z = 1) : IsUnitary (U z) (Uinv z) := by
  refine' ⟨ _, _, _ ⟩;
  · intro ψ; ext C; simp +decide [ U, Uinv ] ;
    fin_cases C <;> simp +decide [ core ] at hz ⊢;
    · simp_all +decide [ Complex.ext_iff, Complex.normSq_apply ];
      constructor <;> ring_nf; all_goals rw [ show z.re ^ 2 = 1 - z.im ^ 2 by linarith ] ; ring!;
    · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
      cases hz <;> simp_all +decide [ Complex.ext_iff, sq ];
      · exact ⟨ rfl, rfl ⟩;
      · linarith [ norm_nonneg z ];
    · simp_all +decide [ Complex.ext_iff, Complex.normSq_apply ];
      constructor <;> ring_nf;
      · rw [ show ( insert 4 pair01 : Finset Mode ) = { 0, 1, 4 } by decide ] ; rw [ show z.re ^ 2 = 1 - z.im ^ 2 by linarith ] ; ring!;
      · rw [ show ( insert 4 pair01 : Config ) = { 0, 1, 4 } by decide ] ; rw [ show z.re ^ 2 = 1 - z.im ^ 2 by linarith ] ; ring!;
    · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
      cases hz <;> simp_all +decide [ sq ];
      · congr;
        decide +revert;
      · linarith [ norm_nonneg z ];
  · intro ψ;
    ext C;
    unfold U Uinv;
    split_ifs <;> simp_all +decide [ Complex.normSq_eq_norm_sq, mul_assoc, mul_left_comm ];
    · fin_cases C <;> simp +decide [ core ] at *;
      · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
        cases hz <;> simp_all +decide [ Complex.ext_iff, sq ];
        · exact ⟨ rfl, rfl ⟩;
        · linarith [ norm_nonneg z ];
      · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
        cases hz <;> simp_all +decide [ Complex.normSq_eq_norm_sq ];
        · congr;
          decide +revert;
        · linarith [ norm_nonneg z ];
    · fin_cases C <;> simp +decide [ core ] at *;
      · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
        cases hz <;> simp_all +decide [ Complex.normSq_eq_norm_sq ];
        · congr;
        · linarith [ norm_nonneg z ];
      · simp_all +decide [ ← mul_assoc, Complex.mul_conj, Complex.normSq_eq_norm_sq ];
        cases hz <;> simp_all +decide [ Complex.normSq_eq_norm_sq ];
        · congr;
          decide +revert;
        · linarith [ norm_nonneg z ];
  · intro C D; by_cases hC : core C = pair23 <;> by_cases hD : core D = pair23 <;> simp_all +decide [ U, Uinv ] ;
    · unfold ket; simp_all +decide [ Finset.ext_iff ] ;
      unfold core pair23 pair01 at *; simp_all +decide [ Fin.forall_fin_succ ] ;
    · unfold ket; split_ifs <;> simp_all +decide [ Finset.ext_iff ] ;
      · simp_all +decide [ core, pair01, pair23 ];
        grind;
      · simp_all +decide [ core, pair01, pair23 ];
        simp_all +decide [ Fin.forall_fin_succ, Fin.exists_fin_succ ];
      · simp_all +decide [ core, pair01, pair23 ];
        grind;
    · unfold ket; split_ifs <;> simp_all +decide [ Finset.ext_iff ] ;
      · simp_all +decide [ Fin.forall_fin_succ, Fin.exists_fin_succ, core, pair01, pair23 ];
      · simp_all +decide [ core, pair01, pair23 ];
        grind;
      · unfold core pair01 pair23 at *; simp_all +decide [ Finset.ext_iff ] ;
        grind;
    · grind +locals

theorem U_preserves_number (z : ℂ) : PreservesNumber (U z) := by
  intro C D h; unfold U; simp +decide [ h, PreservesNumber ] ;
  split_ifs <;> simp_all +decide [ ket ];
  · rintro rfl; simp_all +decide [ core, pair01, pair23 ] ;
    fin_cases C <;> simp_all +decide;
  · intro hD; have := congr_arg Finset.card hD; simp_all +decide ;
    subst hD; fin_cases C <;> simp_all +decide ;
  · aesop

theorem U_preserves_parity (z : ℂ) : PreservesParity (U z) :=
  number_implies_parity _ (U_preserves_number z)

theorem U_vacuum (z : ℂ) : U z (ket ∅) = ket ∅ := by
  ext C; unfold U ket; fin_cases C <;> simp +decide [ core, pair01, pair23 ] ;

theorem U_one_particle (z : ℂ) (i : Mode) : U z (ket {i}) = ket {i} := by
  ext C; fin_cases i <;> fin_cases C <;> simp +decide [ U, ket ] ;

theorem U_pair01_at_pair23 (z : ℂ) : U z (ket pair01) pair23 = z := by
  unfold U ket; simp +decide ;

theorem U_nonidentity {z : ℂ} (hz : z ≠ 0) : U z ≠ id := by
  intro h; have := congrFun ( congrFun h ( ket pair01 ) ) pair23; simp_all +decide [ U ] ;
  simp_all +decide [ ket ]

/-- A more direct kernel support predicate used for the algebra closure theorem. -/
def KernelSupportedInCell (A : Op) : Prop := ∀ C D,
  A (ket D) C = 0 ∨
    ((4 : Mode) ∈ C ↔ (4 : Mode) ∈ D) ∧ (core C).card = (core D).card

theorem H_kernel_supported (z : ℂ) : KernelSupportedInCell (H z) := by
  unfold H;
  intro C D; by_cases h : core C = pair23 <;> by_cases h' : core C = pair01 <;> simp_all +decide [ pairForward, pairBackward ] ;
  · by_cases h'' : D = pair01 ∪ C ∩ { 4 } <;> simp_all +decide [ ket ];
    · fin_cases C <;> simp +decide [ core ] at h ⊢;
    · tauto;
  · by_cases h'' : D = pair23 ∪ C ∩ { 4 } <;> simp_all +decide [ ket ];
    · fin_cases C <;> simp +decide [ core ] at h' ⊢;
    · tauto

theorem U_kernel_supported (z : ℂ) : KernelSupportedInCell (U z) := by
  intro C D; by_cases h : core C = pair23 <;> by_cases h' : core C = pair01 <;> simp_all +decide [ U ] ;
  · by_cases h'' : D = pair01 ∪ C ∩ { 4 } <;> simp_all +decide [ ket ];
    · fin_cases C <;> simp +decide [ core ] at h ⊢;
    · exact Or.inl <| Or.inr <| Ne.symm h'';
  · by_cases h'' : D = pair23 ∪ C ∩ { 4 } <;> simp_all +decide [ ket ];
    · fin_cases C <;> simp +decide [ core ] at h' ⊢;
    · exact Or.inl <| Or.inr <| Ne.symm h'';
  · by_cases hD : D = C <;> simp_all +decide [ ket ];
    tauto

/-- In this five-mode tensor factorization, the cell operator algebra is
characterized operator-theoretically as the simultaneous commutant of the
outside creation and annihilation generators.  This is a genuine algebraic
support condition. -/
def InCellCAR (A : Op) : Prop :=
  A ∘ₒ create 4 = create 4 ∘ₒ A ∧
  A ∘ₒ annihilate 4 = annihilate 4 ∘ₒ A

/-
The support condition is closed under operator composition.
-/
theorem InCellCAR.comp {A B : Op} (hA : InCellCAR A) (hB : InCellCAR B) :
    InCellCAR (A ∘ₒ B) := by
  constructor;
  · simp_all +decide [ funext_iff, InCellCAR ];
    simp_all +decide [ mul ];
    exact fun x y => by rw [ show B ( create 4 x ) = create 4 ( B x ) from funext fun z => hB.1 x z ] ; exact hA.1 _ _;
  · ext ψ C; simp +decide [ mul ] ;
    convert congrFun ( congrFun hA.2 ( B ψ ) ) C using 1;
    exact congr_arg ( fun f => A f C ) ( funext fun D => congr_fun ( congr_fun hB.2 ψ ) D )

/-
Both the update and its inverse are operators in the cell algebra.
-/
theorem U_inCellCAR (z : ℂ) : InCellCAR (U z) := by
  constructor;
  · ext ψ C; simp +decide [ mul ] ;
    unfold U create; split_ifs <;> simp_all +decide [ Finset.card_erase_of_mem ] ;
    · fin_cases C <;> simp_all +decide [ core ];
      simp +decide [ jwSign, pair01 ];
    · fin_cases C <;> simp_all +decide [ Finset.ext_iff ];
      unfold jwSign; simp +decide [ pair23 ] ;
    · unfold core at *; aesop;
  · funext ψ C;
    unfold mul annihilate U; simp +decide ;
    fin_cases C <;> simp +decide [ core ];
    · unfold jwSign; simp +decide [ pair23 ] ;
    · unfold jwSign; simp +decide [ pair01 ] ;

theorem Uinv_inCellCAR (z : ℂ) : InCellCAR (Uinv z) := by
  constructor;
  · ext ψ C; simp +decide [ mul ] ;
    unfold Uinv create;
    split_ifs <;> simp_all +decide [ core ];
    · simp_all +decide [ jwSign, pair01, pair23 ];
    · unfold jwSign; simp +decide [ pair01, pair23 ] ;
  · ext ψ C; simp +decide [ mul ] ;
    unfold Uinv annihilate;
    by_cases h4 : 4 ∈ C <;> simp +decide [ h4, core ];
    split_ifs <;> simp_all +decide [ jwSign ]

/-- Conjugation by the interaction update. -/
def conjugateByU (z : ℂ) (A : Op) : Op := U z ∘ₒ A ∘ₒ Uinv z

/-
Explicit outside-mode locality: conjugation fixes both outside CAR generators.
-/
theorem conjugate_outside_create {z : ℂ} (hz : Complex.normSq z = 1) :
    conjugateByU z (create 4) = create 4 := by
  have h_comm : ∀ ψ : Fock, U z (create 4 (Uinv z ψ)) = create 4 (U z (Uinv z ψ)) := by
    intro ψ; ext C; simp +decide [ U, create ] ;
    split_ifs <;> simp_all +decide [ core ]; all_goals simp +decide [ jwSign, pair01, pair23 ];
  have := U_unitary hz;
  exact funext fun ψ => by simpa [ this.1 ] using h_comm ψ;

theorem conjugate_outside_annihilate {z : ℂ} (hz : Complex.normSq z = 1) :
    conjugateByU z (annihilate 4) = annihilate 4 := by
  convert Uinv_inCellCAR z |> fun h => h.2 |> fun h' => ?_ using 1;
  have h'' : ∀ ψ : Fock, U z (Uinv z ψ) = ψ := by
    exact U_unitary hz |>.1;
  convert congr_arg ( fun f => fun ψ => U z ( f ψ ) ) h' using 1;
  · unfold conjugateByU; aesop;
  · exact funext fun ψ => by rw [ ← h', mul ] ; exact h'' _ ▸ rfl;

/-
Operator/algebra locality on the supported CAR algebra.
-/
theorem conjugate_maps_cell_CAR {z : ℂ}
    {A : Op} (hA : InCellCAR A) : InCellCAR (conjugateByU z A) := by
  convert InCellCAR.comp ( U_inCellCAR z ) ( InCellCAR.comp hA ( Uinv_inCellCAR z ) ) using 1

/-- Projector onto configurations satisfying a predicate. -/
def sectorProjector (p : Config → Prop) [DecidablePred p] : Op := fun ψ C =>
  if p C then ψ C else 0

/-
Exact pointwise commutator criterion for a selected sector projector.
It is stated for arbitrary operators, without silently assuming linearity from
basis matrix entries.
-/
theorem projector_commutes_iff (A : Op) (p : Config → Prop) [DecidablePred p] :
    (A ∘ₒ sectorProjector p = sectorProjector p ∘ₒ A) ↔
      ∀ ψ C, A (fun D => if p D then ψ D else 0) C =
        if p C then A ψ C else 0 := by
  exact ⟨ fun h ψ C => congr_fun ( congr_fun h ψ ) C, fun h => funext fun ψ => funext fun C => h ψ C ⟩

/-
The nontrivial two-particle selected sector is preserved.
-/
theorem two_particle_sector_preserved (z : ℂ) :
    U z ∘ₒ sectorProjector (fun C => C.card = 2) =
      sectorProjector (fun C => C.card = 2) ∘ₒ U z := by
  convert projector_commutes_iff _ _ |>.2 _ using 1;
  intro ψ C;
  unfold U;
  fin_cases C <;> simp +decide [ core ]

/-
The wrong one-dimensional sector selecting `01` is mixed into `23`.
-/
theorem pair01_sector_mixed {z : ℂ} (hz : z ≠ 0) :
    U z ∘ₒ sectorProjector (fun C => C = pair01) ≠
      sectorProjector (fun C => C = pair01) ∘ₒ U z := by
  intro h_eq;
  have := congr_fun ( congr_fun h_eq ( fun C => if C = pair01 then 1 else 0 ) ) pair23; simp_all +decide [ mul ] ;
  simp_all +decide [ U, sectorProjector ]

end FermionInteraction
