import Mathlib

/-!
# Finite self-adjoint transfer reflection and pole bridge

This module replaces primitive diagonal spectral weights by an actual finite
self-adjoint transfer matrix `T` and an observable vector `v`.  Self-adjointness
turns the reflected correlation kernel into an orbit Gram matrix, hence gives
an exact finite reflection-nonnegativity theorem.  A visible transfer
eigenvector also gives an exact exponential correlation and a simple resolvent
pole whose residue is its positive norm square.

The general orbit-Gram theorem needs self-adjointness, not positivity of `T`.
Interpreting `-log lambda` as a positive transfer energy additionally requires
an eigenvalue `lambda` in `(0, 1)`, as supplied by the explicit two-level
control.  The result is finite: it does not establish action-level reflection
positivity, infinite-volume reconstruction, changing-lattice atom persistence,
LSZ, or a physical QCD/Higgs pole.

Provenance: clean-room formalization returned by Aristotle project
`51983ddf-7ca0-4881-8127-9fa112822814`, task
`80e574fc-7737-421a-95a7-1f00df02f8ad`, informed by the finite-transfer
architecture of Luscher, Osterwalder-Seiler, and Usui (arXiv:1201.3415).
-/

open scoped BigOperators
open Filter Matrix Set

set_option autoImplicit false
set_option maxHeartbeats 8000000

namespace PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole

noncomputable section

abbrev Mat (d : Nat) := Matrix (Fin d) (Fin d) Real
abbrev Vec (d : Nat) := Fin d -> Real

/-- Two-point transfer correlation of one finite observable vector. -/
def correlation {d : Nat} (T : Mat d) (v : Vec d) (n : Nat) : Real :=
  dotProduct v (T ^ n *ᵥ v)

/-- Finite positive-time orbit combination generated by the transfer matrix. -/
def orbitCombination {d n : Nat} (T : Mat d) (v : Vec d)
    (c : Fin n -> Real) : Vec d :=
  ∑ t, c t • (T ^ t.val *ᵥ v)

/-- Self-adjoint transfer powers turn a reflected correlation into an orbit
Gram pairing. -/
theorem correlation_add_eq_orbit_dot {d : Nat} (T : Mat d) (v : Vec d)
    (hT : T.IsHermitian) (t s : Nat) :
    correlation T v (t + s) =
      dotProduct (T ^ t *ᵥ v) (T ^ s *ᵥ v) := by
  unfold correlation
  simp +decide [pow_add, Matrix.dotProduct_mulVec, Matrix.vecMul_mulVec]
  convert rfl

/-- The reflected quadratic form of an actual self-adjoint transfer operator
is exactly the squared norm of one finite orbit combination. -/
theorem reflectedQuadratic_eq_orbit_sq {d n : Nat} (T : Mat d) (v : Vec d)
    (hT : T.IsHermitian) (c : Fin n -> Real) :
    (∑ t, ∑ s, c t * correlation T v (t.val + s.val) * c s) =
      dotProduct (orbitCombination T v c) (orbitCombination T v c) := by
  simp +decide [correlation_add_eq_orbit_dot T v hT, orbitCombination]
  simp +decide [dotProduct, Finset.mul_sum _ _ _, mul_assoc, mul_comm,
    mul_left_comm]
  exact Finset.sum_comm_cycle

/-- Finite reflected-kernel nonnegativity derived from a self-adjoint transfer
operator rather than assumed spectral weights. -/
theorem reflectedQuadratic_nonneg {d n : Nat} (T : Mat d) (v : Vec d)
    (hT : T.IsHermitian) (c : Fin n -> Real) :
    0 <= ∑ t, ∑ s, c t * correlation T v (t.val + s.val) * c s := by
  rw [reflectedQuadratic_eq_orbit_sq]
  · exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
  · exact hT

/-- A transfer eigenvector has an exact one-exponential correlation law. -/
theorem correlation_eigenmode {d : Nat} (T : Mat d) (v : Vec d)
    (lambda : Real) (hEig : T *ᵥ v = lambda • v) (n : Nat) :
    correlation T v n = lambda ^ n * dotProduct v v := by
  have h_ind : ∀ n : Nat, T ^ n *ᵥ v = lambda ^ n • v := by
    intro n
    induction n <;> simp_all +decide [pow_succ']
    simp_all +decide [← Matrix.mulVec_mulVec]
    rw [Matrix.mulVec_smul, hEig, smul_smul, mul_comm]
  unfold correlation
  simp +decide [h_ind, dotProduct_smul]

/-- Energy resolvent of one visible transfer eigenmode. -/
def eigenResolvent {d : Nat} (lambda : Real) (v : Vec d)
    (z : Complex) : Complex :=
  ((dotProduct v v : Real) : Complex) /
    (z - (-Real.log lambda : Complex))

/-- A nonzero eigenvector produces a positive simple residue at reconstructed
energy `-log lambda`.  Positivity of that energy is a separate condition on
`lambda`. -/
theorem eigenResolvent_has_positive_residue {d : Nat} (lambda : Real)
    (v : Vec d) (hv : v ≠ 0) :
    0 < dotProduct v v ∧
      Tendsto
        (fun z : Complex =>
          (z - (-Real.log lambda : Complex)) * eigenResolvent lambda v z)
        (nhdsWithin (-Real.log lambda : Complex)
          ({(-Real.log lambda : Complex)} : Set Complex)ᶜ)
        (nhds ((dotProduct v v : Real) : Complex)) := by
  refine And.intro ?_ (tendsto_const_nhds.congr' ?_)
  · exact lt_of_le_of_ne
      (Finset.sum_nonneg fun _ _ => mul_self_nonneg _)
      (Ne.symm <| by simpa [funext_iff] using hv)
  · filter_upwards [self_mem_nhdsWithin] with z hz using by
      rw [eigenResolvent, mul_div_cancel₀ _ (sub_ne_zero_of_ne hz)]

/-- Exact nondegenerate two-level control.  The transfer operator has
eigenvalues `1` and `1/2`; the observable sees the second channel, whose
reconstructed energy is the positive value `log 2`, whose reflected kernel is
nonnegative, and whose pole residue is one. -/
theorem two_level_operator_gap_pole_control :
    let T : Mat 2 := !![1, 0; 0, (1 / 2 : Real)]
    let v : Vec 2 := ![0, 1]
    T.IsHermitian ∧
      (T *ᵥ v = (1 / 2 : Real) • v) ∧
      (∀ n, correlation T v n = (1 / 2 : Real) ^ n) ∧
      (∀ (n : Nat) (c : Fin n -> Real),
        0 <= ∑ t, ∑ s, c t * correlation T v (t.val + s.val) * c s) ∧
      Tendsto
        (fun z : Complex =>
          (z - (Real.log 2 : Complex)) * eigenResolvent (1 / 2) v z)
        (nhdsWithin (Real.log 2 : Complex)
          ({(Real.log 2 : Complex)} : Set Complex)ᶜ)
        (nhds (1 : Complex)) := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · ext i j
    fin_cases i <;> fin_cases j <;> rfl
  · ext i
    fin_cases i <;> norm_num [Matrix.mulVec]
  · intro n
    convert correlation_eigenmode
      !![1, 0; 0, 1 / 2] ![0, 1] (1 / 2) ?_ n using 1
    · norm_num [dotProduct]
    · ext i
      fin_cases i <;> norm_num [Matrix.mulVec]
  · intro n c
    refine reflectedQuadratic_nonneg _ _ ?_ _
    ext i j
    fin_cases i <;> fin_cases j <;> norm_num
  · convert eigenResolvent_has_positive_residue (1 / 2) ![0, 1] ?_ |>.2 using 2 <;>
      norm_num [eigenResolvent]
    · norm_num [Real.log_div, Complex.ofReal_log]
      ring_nf
      norm_num
    · norm_num [Complex.ext_iff, Complex.log_re, Complex.log_im, Real.log_div]
    · norm_num [Complex.ext_iff, Complex.log_re, Complex.log_im, Real.log_div]

end

end PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole.reflectedQuadratic_nonneg' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole.reflectedQuadratic_nonneg

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole.two_level_operator_gap_pole_control' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteSelfAdjointTransferReflectionPole.two_level_operator_gap_pole_control
