import Mathlib

/-!
# Finite Hamiltonian to transfer decay and pole

This draft module gives a finite-dimensional quadratic bridge from a positive
Hermitian Hamiltonian to a transfer operator, visible exponential decay, and a
simple transfer-variable pole. It proves contraction, finite orbit-Gram
positivity, exact mode decay and energy reconstruction, and a nondegenerate
two-level witness.

The Gram statement is ordinary finite Gram positivity, not full
Osterwalder-Schrader reflection positivity. The positive pole weight is the
coefficient recovered after multiplication by `1 - z*q`; the analytic residue
in the local coordinate `z - q^-1` has a different sign and scale.

Scope: finite-dimensional quadratic dynamics only. This module does not prove
interacting reconstruction, infinite-volume persistence, or LSZ.

Provenance: Aristotle project `7b77c837-737e-4469-869c-760cf7e36ed2`,
clean-room Mathlib proof, semantically reviewed and integrated 2026-07-21.
-/

open scoped BigOperators ComplexConjugate Matrix.Norms.L2Operator

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 200000
set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace PhysicsSM.Draft.NullEdge.FiniteHamiltonianTransferPole

open Matrix
open NormedSpace

variable {d : Type*} [Fintype d] [DecidableEq d] [Nonempty d]

/-- The finite-dimensional transfer matrix generated by a Hamiltonian at spacing `a`. -/
noncomputable def transfer (a : ℝ) (H : Matrix d d ℂ) : Matrix d d ℂ :=
  exp ((-(a : ℂ)) • H)

/-- A Hamiltonian whose quadratic form is nonnegative. -/
def HamiltonianPSD (H : Matrix d d ℂ) : Prop :=
  (Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) H).IsPositive

/-- Matrix-action formulation of contraction in the matrix L2 operator norm. -/
def IsContraction (T : Matrix d d ℂ) : Prop := ‖T‖ ≤ 1

/-- Exponentiation preserves an eigenmode, stated directly for matrix action. -/
theorem exp_mulVec_of_mulVec_eq_smul (A : Matrix d d ℂ) (v : d → ℂ) (μ : ℂ)
    (hv : A *ᵥ v = μ • v) :
    exp A *ᵥ v = Complex.exp μ • v := by
  have h_ind : ∀ n : ℕ, (A ^ n) *ᵥ v = μ ^ n • v := by
    intro n
    induction' n with n ih
    · simp +decide
    · simp +decide [pow_succ', ← Matrix.mulVec_mulVec, hv, ih, smul_smul]
      rw [Matrix.mulVec_smul, hv, smul_smul, mul_comm]
  simp +decide [Complex.exp_eq_exp_ℂ, NormedSpace.exp_eq_tsum_div, h_ind]
  have h_fubini : ∀ N : ℕ,
      (∑ n ∈ Finset.range N, (1 / Nat.factorial n : ℂ) • (A ^ n)) *ᵥ v =
        ∑ n ∈ Finset.range N, (μ ^ n / Nat.factorial n : ℂ) • v := by
    intro N
    have h_fubini :
        (∑ n ∈ Finset.range N, (1 / Nat.factorial n : ℂ) • (A ^ n)) *ᵥ v =
          ∑ n ∈ Finset.range N, ((1 / Nat.factorial n : ℂ) • (A ^ n)) *ᵥ v := by
      induction' (Finset.range N) using Finset.induction <;>
        simp_all +decide [Finset.sum_range_succ, Matrix.mulVec_add, Matrix.mulVec_smul]
      simp +decide [*, Matrix.add_mulVec]
    simp_all +decide [div_eq_inv_mul, Matrix.mulVec_smul]
    simp +decide [Matrix.mulVec, funext_iff] at h_ind ⊢
    simp +decide [mul_assoc, dotProduct, Finset.mul_sum _ _ _, h_ind]
    simp +decide [← h_ind, Finset.mul_sum _ _ _, dotProduct]
  have h_cont : Filter.Tendsto
      (fun N => (∑ n ∈ Finset.range N, (1 / Nat.factorial n : ℂ) • (A ^ n)) *ᵥ v)
      Filter.atTop
      (nhds ((∑' n, (1 / Nat.factorial n : ℂ) • (A ^ n)) *ᵥ v)) := by
    have h_cont : Summable (fun n : ℕ => (1 / Nat.factorial n : ℂ) • (A ^ n)) := by
      refine' Pi.summable.mpr _
      intro i
      have h_summable : Summable (fun n : ℕ => (1 / (Nat.factorial n) : ℂ) • (A ^ n) i) := by
        have h_bound : ∀ n : ℕ, ‖(A ^ n) i‖ ≤ (∑ i, ∑ j, ‖A i j‖) ^ n := by
          intro n
          have h_bound : ∀ i j, ‖(A ^ n) i j‖ ≤ (∑ i, ∑ j, ‖A i j‖) ^ n := by
            induction' n with n ih <;> simp_all +decide [pow_succ, Matrix.mul_apply]
            · intro i j
              by_cases hij : i = j <;> aesop
            · intro i j
              have h_bound : ∀ j_1,
                  ‖(A ^ n) i j_1 * A j_1 j‖ ≤
                    (∑ i, ∑ j, ‖A i j‖) ^ n * ‖A j_1 j‖ := by
                exact fun j_1 => by
                  rw [norm_mul]
                  exact mul_le_mul_of_nonneg_right (ih i j_1) (norm_nonneg _)
              refine' le_trans (norm_sum_le _ _)
                (le_trans (Finset.sum_le_sum fun _ _ => h_bound _) _)
              rw [Finset.mul_sum _ _ _]
              exact Finset.sum_le_sum fun i _ =>
                mul_le_mul_of_nonneg_left
                  (Finset.single_le_sum (fun j _ => norm_nonneg (A i j))
                    (Finset.mem_univ j))
                  (pow_nonneg
                    (Finset.sum_nonneg fun i _ =>
                      Finset.sum_nonneg fun j _ => norm_nonneg (A i j)) _)
          exact pi_norm_le_iff_of_nonneg (by positivity) |>.2 fun j => h_bound i j
        refine' .of_norm <| _
        simp_all +decide [norm_smul]
        exact Summable.of_nonneg_of_le
          (fun n => mul_nonneg (inv_nonneg.2 (Nat.cast_nonneg _)) (norm_nonneg _))
          (fun n => mul_le_mul_of_nonneg_left (h_bound n)
            (inv_nonneg.2 (Nat.cast_nonneg _)))
          (by simpa [inv_mul_eq_div] using Real.summable_pow_div_factorial _)
      exact h_summable
    convert Filter.Tendsto.comp
      (Continuous.tendsto
        (show Continuous fun m : Matrix d d ℂ => m *ᵥ v from
          continuous_id.matrix_mulVec continuous_const) _)
      (h_cont.hasSum.tendsto_sum_nat) using 1
  convert tendsto_nhds_unique h_cont _
  · simp +decide [NormedSpace.exp_eq_tsum]
    grind +suggestions
  · convert Summable.hasSum _ |> HasSum.tendsto_sum_nat |>
      Filter.Tendsto.smul_const <| v using 1
    · simp_all +decide [div_eq_inv_mul, Finset.sum_smul]
    · infer_instance
    · exact Summable.of_norm <| by
        simpa using Real.summable_pow_div_factorial (Complex.normSq μ |> Real.sqrt)

/-- A Hamiltonian eigenmode has the expected transfer eigenvalue. -/
theorem transfer_mulVec_eigenmode (a E : ℝ) (H : Matrix d d ℂ) (v : d → ℂ)
    (hv : H *ᵥ v = (E : ℂ) • v) :
    transfer a H *ᵥ v = (Real.exp (-a * E) : ℂ) • v := by
  convert exp_mulVec_of_mulVec_eq_smul (-(a : ℂ) • H) v (-(a : ℂ) * E) _ using 1
  · norm_num [Complex.exp_ofReal_re]
  · rw [Matrix.smul_mulVec, hv, smul_smul]

/-- Hermiticity of the transfer matrix follows from Hermiticity of the Hamiltonian. -/
theorem transfer_isHermitian (a : ℝ) (H : Matrix d d ℂ) (hH : H.IsHermitian) :
    (transfer a H).IsHermitian := by
  have h_scalar : ((-(a : ℂ)) • H).IsHermitian := by
    simp_all +decide [Matrix.IsHermitian, Matrix.conjTranspose_smul]
  convert h_scalar.exp using 1

/-- The exponential of a Hermitian finite matrix is positive definite. -/
theorem transfer_posDef (a : ℝ) (H : Matrix d d ℂ) (hH : H.IsHermitian) :
    IsStrictlyPositive (Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) (transfer a H)) := by
  let +nondep : NormedAlgebra ℚ (Matrix d d ℂ) := .restrictScalars ℚ ℂ _
  let +nondep : NormedAlgebra ℚ
      (EuclideanSpace ℂ d →L[ℂ] EuclideanSpace ℂ d) := .restrictScalars ℚ ℂ _
  let f := Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ)
  have hf : Continuous f := by
    exact LinearMap.continuous_of_finiteDimensional
      f.toAlgEquiv.toLinearEquiv.toLinearMap
  have hmap : f (exp ((-(a : ℂ)) • H)) = exp (f ((-(a : ℂ)) • H)) := by
    exact NormedSpace.map_exp f hf _
  rw [show transfer a H = exp ((-(a : ℂ)) • H) from rfl, hmap]
  apply IsStrictlyPositive.iff_of_unital.mpr
  constructor
  · apply IsSelfAdjoint.exp_nonneg
    have hs : IsSelfAdjoint ((-(a : ℂ)) • H) := by
      rw [IsSelfAdjoint]
      simpa [Matrix.IsHermitian] using congrArg (fun X => (-(a : ℂ)) • X) hH
    rw [IsSelfAdjoint] at hs ⊢
    rw [← map_star f]
    exact congrArg f hs
  · exact NormedSpace.isUnit_exp _

/-- The exponential of a nonpositive scalar multiple of a positive operator is contractive. -/
theorem exp_neg_positive_contraction
    (A : EuclideanSpace ℂ d →L[ℂ] EuclideanSpace ℂ d) (a : ℝ)
    (ha : 0 ≤ a) (hA : A.IsPositive) :
    ‖exp ((-(a : ℂ)) • A)‖ ≤ 1 := by
  have haApos : ((a : ℂ) • A).IsPositive :=
    hA.smul_of_nonneg (by exact_mod_cast ha)
  have haAle : (0 : EuclideanSpace ℂ d →L[ℂ] EuclideanSpace ℂ d) ≤ (a : ℂ) • A :=
    (ContinuousLinearMap.nonneg_iff_isPositive _).mpr haApos
  have hB : (-(a : ℂ)) • A ≤ 0 := by
    calc
      (-(a : ℂ)) • A = -((a : ℂ) • A) := neg_smul (a : ℂ) A
      _ ≤ 0 := neg_nonpos.mpr haAle
  have hsA : IsSelfAdjoint A := hA.isSelfAdjoint
  have hsB : IsSelfAdjoint ((-(a : ℂ)) • A) := by
    rw [IsSelfAdjoint]
    simpa using congrArg (fun X => (-(a : ℂ)) • X) hsA
  rw [← CFC.real_exp_eq_normedSpace_exp hsB]
  apply norm_cfc_le zero_le_one
  intro x hx
  rw [Real.norm_eq_abs, abs_of_pos (Real.exp_pos x), Real.exp_le_one_iff]
  have hs : ∀ y ∈ spectrum ℝ ((-(a : ℂ)) • A), y ≤ 0 :=
    (le_algebraMap_iff_spectrum_le
      (R := ℝ) (a := (-(a : ℂ)) • A) (r := 0)).mp (by simpa using hB)
  exact hs x hx

/-- A positive-semidefinite Hamiltonian generates a contraction for nonnegative time. -/
theorem transfer_isContraction (a : ℝ) (H : Matrix d d ℂ)
    (ha : 0 ≤ a) (hH : HamiltonianPSD H) :
    IsContraction (transfer a H) := by
  have h_exp :
      ‖exp ((-(a : ℂ)) • Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) H)‖ ≤ 1 := by
    convert exp_neg_positive_contraction
      (Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) H) a ha hH using 1
  have h_transfer :
      Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) (transfer a H) =
        exp ((-(a : ℂ)) • Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) H) := by
    convert NormedSpace.map_exp _ _ _ using 1
    any_goals try infer_instance
    · congr! 1
      ext
      simp +decide [Matrix.toEuclideanCLM]
      simp +decide [Matrix.toLin_apply, Matrix.mulVec, dotProduct]
      simp +decide [mul_assoc, Finset.mul_sum _ _ _, Finset.sum_mul]
    · refine' { .. }
      intro r x
      convert norm_smul_le (r : ℂ) x using 1
      norm_num [Norm.norm]
      exact Or.inl (by rw [Real.sqrt_mul_self_eq_abs])
    · exact LinearMap.continuous_of_finiteDimensional
        (Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ)).toAlgEquiv.toLinearEquiv.toLinearMap
  unfold IsContraction
  calc
    ‖transfer a H‖ =
        ‖Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) (transfer a H)‖ :=
      (Matrix.l2_opNorm_toEuclideanCLM (transfer a H)).symm
    _ = ‖exp ((-(a : ℂ)) • Matrix.toEuclideanCLM (n := d) (𝕜 := ℂ) H)‖ :=
      congrArg norm h_transfer
    _ ≤ 1 := h_exp

/-- The kernel associated to a finite transfer orbit. -/
noncomputable def orbitKernel (T : Matrix d d ℂ) (v : d → ℂ) (t s : ℕ) : ℂ :=
  ∑ i, conj (((T ^ t) *ᵥ v) i) * ((T ^ s) *ᵥ v) i

/-- Positivity of a complex kernel means nonnegativity of every finite quadratic form. -/
def GramPositive {ι : Type*} [Fintype ι] (K : ι → ι → ℂ) : Prop :=
  ∀ c : ι → ℂ, 0 ≤ Complex.re (∑ i, ∑ j, conj (c i) * K i j * c j)

/-- Every finite orbit-kernel matrix is literally a Gram kernel and hence positive. -/
theorem orbitKernel_gramPositive (T : Matrix d d ℂ) (v : d → ℂ)
    {ι : Type*} [Fintype ι] (time : ι → ℕ) :
    GramPositive (fun i j => orbitKernel T v (time i) (time j)) := by
  intro c
  have h_expand :
      ∑ i, ∑ j, (starRingEnd ℂ) (c i) *
          (∑ k, (starRingEnd ℂ) (((T ^ (time i)) *ᵥ v) k) *
            ((T ^ (time j)) *ᵥ v) k) * c j =
        ∑ k, (∑ i, (starRingEnd ℂ) (c i) *
          (starRingEnd ℂ) (((T ^ (time i)) *ᵥ v) k)) *
          (∑ j, c j * ((T ^ (time j)) *ᵥ v) k) := by
    simp +decide only [mul_comm, Finset.mul_sum _ _ _, mul_left_comm, Finset.sum_mul]
    exact Eq.symm (Finset.sum_comm.trans
      (Finset.sum_congr rfl fun _ _ => Finset.sum_comm.trans
        (Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring)))
  simp_all +decide [orbitKernel]
  refine' Finset.sum_le_sum fun k _ => _
  norm_num [Finset.sum_add_distrib, Finset.mul_sum _ _ _]
  linarith [
    sq_nonneg
      (∑ x, (c x |> Complex.re) * ((T ^ time x *ᵥ v) k |> Complex.re) -
        ∑ x, (c x |> Complex.im) * ((T ^ time x *ᵥ v) k |> Complex.im)),
    sq_nonneg
      (∑ x, (c x |> Complex.re) * ((T ^ time x *ᵥ v) k |> Complex.im) +
        ∑ x, (c x |> Complex.im) * ((T ^ time x *ᵥ v) k |> Complex.re))]

/-- Iterating one visible transfer eigenmode gives exact exponential decay. -/
theorem transfer_pow_mulVec_eigenmode (a E : ℝ) (H : Matrix d d ℂ) (v : d → ℂ)
    (hv : H *ᵥ v = (E : ℂ) • v) (n : ℕ) :
    (transfer a H ^ n) *ᵥ v = (Real.exp (-a * E * n) : ℂ) • v := by
  induction' n with n ih
  · simp +decide [Matrix.one_mulVec]
  · convert congr_arg (fun x => transfer a H *ᵥ x) ih using 1
    · rw [pow_succ', Matrix.mulVec_mulVec]
    · have := transfer_mulVec_eigenmode a E H v hv
      simp_all +decide [mul_add, add_mul, Real.exp_add, Matrix.mulVec_smul]
      module

/-- The energy is reconstructed exactly from its transfer eigenvalue. -/
theorem reconstructed_energy (a E : ℝ) (ha : 0 < a) :
    -(Real.log (Real.exp (-a * E))) / a = E := by
  rw [Real.log_exp, div_eq_iff] <;> linarith

/-- Scalar resolvent amplitude of a visible one-dimensional transfer mode. -/
noncomputable def modeResolvent (q weight z : ℝ) : ℝ := weight / (1 - z * q)

/-- Multiplication by the simple-pole denominator recovers the weight exactly. -/
theorem modeResolvent_weight (q weight z : ℝ) (hz : z ≠ q⁻¹) (hq : q ≠ 0) :
    (1 - z * q) * modeResolvent q weight z = weight := by
  unfold modeResolvent
  grind

/-- The denominator of the mode resolvent vanishes at exactly one point. -/
theorem modeResolvent_unique_pole (q z : ℝ) (hq : q ≠ 0) :
    1 - z * q = 0 ↔ z = q⁻¹ := by
  grind

/-- Squared Hilbert norm, used as the visible mode's transfer-denominator weight. -/
def vecNormSq (v : d → ℂ) : ℝ := ∑ i, Complex.normSq (v i)

/-- A nonzero visible vector has strictly positive transfer-denominator weight. -/
theorem visible_weight_pos (v : d → ℂ) (hv : v ≠ 0) : 0 < vecNormSq v := by
  obtain ⟨i, hi⟩ := Function.ne_iff.mp hv
  exact lt_of_lt_of_le (Complex.normSq_pos.mpr (by simpa using hi))
    (Finset.single_le_sum (fun i _ => Complex.normSq_nonneg (v i)) (Finset.mem_univ i))

/-- Complete downstream chain for one positive-energy visible eigenmode. -/
theorem visible_mode_chain (a E : ℝ) (H : Matrix d d ℂ) (v : d → ℂ)
    (ha : 0 < a) (hE : 0 < E) (hv0 : v ≠ 0)
    (hv : H *ᵥ v = (E : ℂ) • v) :
    (∀ n : ℕ, (transfer a H ^ n) *ᵥ v =
        (Real.exp (-a * E * n) : ℂ) • v) ∧
      -(Real.log (Real.exp (-a * E))) / a = E ∧
      0 < Real.exp (-a * E) ∧ Real.exp (-a * E) < 1 ∧
      0 < vecNormSq v ∧
      (∀ z : ℝ, z ≠ (Real.exp (-a * E))⁻¹ →
        (1 - z * Real.exp (-a * E)) *
          modeResolvent (Real.exp (-a * E)) (vecNormSq v) z = vecNormSq v) := by
  refine' ⟨_, _, Real.exp_pos _, ?_, _, _⟩
  · convert transfer_pow_mulVec_eigenmode a E H v hv using 1
  · rw [Real.log_exp, neg_mul, neg_neg, mul_div_cancel_left₀ _ ha.ne']
  · rw [Real.exp_lt_one_iff]
    nlinarith
  · exact visible_weight_pos v hv0
  · exact fun z hz => modeResolvent_weight _ _ _ hz (by positivity)

section TwoLevel

abbrev Two := Fin 2

/-- Exact two-level Hamiltonian: ground energy `0`, excited energy `log 2`. -/
noncomputable def twoLevelH : Matrix Two Two ℂ :=
  diagonal ![(0 : ℂ), (Real.log 2 : ℂ)]

/-- The unit visible excited vector. -/
def excited : Two → ℂ := ![(0 : ℂ), 1]

/-- Exact two-level transfer matrix at spacing one. -/
noncomputable def twoLevelT : Matrix Two Two ℂ := transfer 1 twoLevelH

/-- The two energies are distinct, so the fixture is nondegenerate. -/
theorem twoLevel_nondegenerate : (0 : ℝ) ≠ Real.log 2 := by
  positivity

/-- The fixture Hamiltonian is Hermitian and positive semidefinite. -/
theorem twoLevel_hamiltonian_psd :
    twoLevelH.IsHermitian ∧ HamiltonianPSD twoLevelH := by
  constructor
  · ext i j
    fin_cases i <;> fin_cases j <;> norm_num [twoLevelH]
    norm_num [Complex.ext_iff, Complex.log_re, Complex.log_im]
  · constructor
    · intro x y
      simp +decide [toEuclideanCLM]
      simp +decide [twoLevelH, toLin_apply]
      simp +decide [Matrix.mulVec, dotProduct, inner]
      norm_num [Complex.ext_iff, Complex.log_re, Complex.log_im]
      ring
      grind
    · unfold twoLevelH
      simp +decide [EuclideanSpace.norm_eq, toEuclideanCLM,
        ContinuousLinearMap.reApplyInnerSelf]
      simp +decide [EuclideanSpace.norm_eq, inner]
      intro x
      erw [toLin_apply]
      norm_num [Matrix.mulVec]
      ring_nf
      norm_num [Complex.log_re]
      positivity

/-- The ground and excited vectors have the advertised exact energies. -/
theorem twoLevel_energy_actions :
    twoLevelH *ᵥ ![(1 : ℂ), 0] = (0 : ℂ) • ![(1 : ℂ), 0] ∧
    twoLevelH *ᵥ excited = (Real.log 2 : ℂ) • excited := by
  constructor <;> ext i <;> fin_cases i <;> norm_num [*, twoLevelH, excited]
  all_goals norm_num [Matrix.mulVec]

/-- At spacing one the visible excited transfer eigenvalue is exactly `1/2`. -/
theorem twoLevel_transfer_excited :
    twoLevelT *ᵥ excited = (1 / 2 : ℂ) • excited := by
  convert transfer_mulVec_eigenmode 1 (Real.log 2) twoLevelH excited ?_ using 1
  · norm_num [Real.exp_neg, Real.exp_log]
  · convert twoLevel_energy_actions.2 using 1

/-- The visible excited vector has unit transfer-denominator weight. -/
theorem twoLevel_unit_weight : vecNormSq excited = 1 := by
  unfold vecNormSq excited
  norm_num [Fin.sum_univ_succ]

/-- The exact two-level fixture packages nondegeneracy, decay, and unit weight. -/
theorem twoLevel_fixture :
    (0 : ℝ) ≠ Real.log 2 ∧
    twoLevelT *ᵥ excited = (1 / 2 : ℂ) • excited ∧
    (∀ n : ℕ, (twoLevelT ^ n) *ᵥ excited = ((1 / 2 : ℂ) ^ n) • excited) ∧
    vecNormSq excited = 1 := by
  refine' ⟨_, _, _, _⟩
  · positivity
  · convert twoLevel_transfer_excited
  · intro n
    induction n <;> simp_all +decide [pow_succ, Matrix.mulVec_smul]
    simp_all +decide [← Matrix.mulVec_mulVec, twoLevel_transfer_excited]
    rw [Matrix.mulVec_smul, ‹twoLevelT ^ _ *ᵥ excited = _›, smul_smul, mul_comm]
  · convert twoLevel_unit_weight

end TwoLevel

end PhysicsSM.Draft.NullEdge.FiniteHamiltonianTransferPole
