import PhysicsSM.Draft.NullEdge.FinitePalatiniBoundaryCancellation

/-!
# Explicit finite Palatini coframe-chart action

The preceding modules derive the determinant volume response and show how a
Ricci-plus-divergence curvature response yields the Einstein tensor. This
module supplies an actual nonlinear finite action witnessing that architecture
at a fixed geometric base point.

The variables are local coframe generators `X(x)`. At each site,

```text
volume_X = det(e (1 + X)),
gInv_X   = gInv + delta_gInv(X),
R_X      = <Ric, gInv_X>.
```

The Ricci tensor is held fixed, as in the metric variation of a first-order
Palatini action with independent connection. The total chart action is

```text
(1 / (2 kappa)) sum_x volume_X (R_X - 2 Lambda)
  - (1 / 2) sum_x volume_0 <T, delta_gInv(X)>.
```

Its derivative is computed from the displayed action. The determinant theorem
supplies the volume channel, fixed-connection contraction supplies the Ricci
channel, and the coframe generator map reaches every symmetric inverse-metric
variation. Hence stationarity at the chart origin is equivalent to the
pointwise finite Einstein equation.

This is a nonvacuous finite action control, not the completed null-edge gravity
theory. Coframes, orientation, Ricci curvature, stress, and their common graph
origin are supplied, and the inverse-metric chart is a first-order local chart
rather than a global metric parametrization.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.FinitePalatiniCoframeChartAction

open scoped BigOperators
open EinsteinEquationVariation
open StressEnergyPhysicalControls
open LocalEinsteinEquationVariation
open RelaxedCausalMetricVariationBridge
open LayerWeightMetricRankNoGo
open FiniteEinsteinHilbertActionResponse
open CoframeVolumeMetricVariation
open FinitePalatiniEinsteinHilbertVariation

variable {Site : Type*} [Fintype Site]

/-- Sitewise inverse-metric variation generated by local coframe matrices. -/
def localInverseMetricVariation
    (inverseMetric generator : LocalTensor (Site := Site)) :
    LocalTensor (Site := Site) :=
  fun site => inverseMetricVariation (inverseMetric site) (generator site)

/-- The local coframe-generator to inverse-metric-variation map is linear. -/
def localInverseMetricVariationLinear
    (inverseMetric : LocalTensor (Site := Site)) :
    LocalTensor (Site := Site) →ₗ[Real] LocalTensor (Site := Site) where
  toFun := localInverseMetricVariation inverseMetric
  map_add' X Y := by
    funext site
    change (inverseMetricVariationLinear (inverseMetric site))
        (X site + Y site) = _
    rw [map_add]
    rfl
  map_smul' scalar X := by
    funext site
    change (inverseMetricVariationLinear (inverseMetric site))
        (scalar • X site) = _
    rw [map_smul]
    rfl

omit [Fintype Site] in
/-- Pointwise full coframe reach composes to full local symmetric metric reach.
-/
theorem localInverseMetricVariationLinear_isFull
    (metric inverseMetric : LocalTensor (Site := Site))
    (hMetric : LocalSymmetric metric)
    (hInverseMetric : LocalSymmetric inverseMetric)
    (hLeft : forall site, inverseMetric site * metric site = 1)
    (hRight : forall site, metric site * inverseMetric site = 1) :
    IsFullLocalSymmetricMetricDerivative
      (localInverseMetricVariationLinear inverseMetric) := by
  constructor
  · intro generator site
    exact inverseMetricVariation_isSymm (inverseMetric site) (generator site)
      (hInverseMetric site)
  · intro variation hVariation
    choose generator hGenerator using fun site =>
      (inverseMetricVariationLinear_isFull (metric site) (inverseMetric site)
        (hMetric site) (hInverseMetric site) (hLeft site) (hRight site)).2
        (variation site) (hVariation site)
    refine ⟨generator, ?_⟩
    funext site
    exact hGenerator site

/-- Base oriented volume field of the coframe chart. -/
def chartBaseVolume
    (coframe : Site -> RealCoframe (I := Fin 4)) : Site -> Real :=
  fun site => coframeVolume (coframe site)

/-- Nonlinear coframe volume at chart parameter `generator`. -/
def chartVolume
    (coframe : Site -> RealCoframe (I := Fin 4))
    (generator : LocalTensor (Site := Site)) : Site -> Real :=
  fun site => coframeVolume (coframe site * (1 + generator site))

/-- Affine inverse-metric chart with the exact coframe-generated tangent. -/
def chartInverseMetric
    (inverseMetric generator : LocalTensor (Site := Site)) :
    LocalTensor (Site := Site) :=
  inverseMetric + localInverseMetricVariation inverseMetric generator

/-- Scalar curvature in the fixed-connection Palatini chart. -/
def chartScalarCurvature
    (ricci inverseMetric generator : LocalTensor (Site := Site)) :
    Site -> Real :=
  fun site => metricVariationPairing (ricci site)
    (chartInverseMetric inverseMetric generator site)

/-- Scalar curvature at the chart origin. -/
def chartBaseScalarCurvature
    (ricci inverseMetric : LocalTensor (Site := Site)) : Site -> Real :=
  fun site => metricVariationPairing (ricci site) (inverseMetric site)

/-- Volume response in a local generator direction. -/
def chartVolumeResponse
    (coframe : Site -> RealCoframe (I := Fin 4))
    (direction : LocalTensor (Site := Site)) : Site -> Real :=
  fun site => coframeVolume (coframe site) * (direction site).trace

/-- Fixed-connection scalar-curvature response in a local generator
direction. -/
def chartCurvatureResponse
    (ricci inverseMetric direction : LocalTensor (Site := Site)) :
    Site -> Real :=
  fun site => metricVariationPairing (ricci site)
    (inverseMetricVariation (inverseMetric site) (direction site))

/-- Einstein-Hilbert part of the finite coframe-chart action. -/
def chartGravityAction
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci inverseMetric : LocalTensor (Site := Site))
    (cosmologicalConstant : Real)
    (generator : LocalTensor (Site := Site)) : Real :=
  (1 / (2 * kappa)) *
    finiteEinsteinHilbertBulk (chartVolume coframe generator)
      (chartScalarCurvature ricci inverseMetric generator)
      cosmologicalConstant

/-- Linearized matter part in the same inverse-metric chart. -/
def chartMatterAction
    (coframe : Site -> RealCoframe (I := Fin 4))
    (inverseMetric stress : LocalTensor (Site := Site))
    (generator : LocalTensor (Site := Site)) : Real :=
  -(1 / 2) * weightedLocalMetricPairing (chartBaseVolume coframe) stress
    (localInverseMetricVariation inverseMetric generator)

/-- Total finite Palatini coframe-chart action. -/
def chartTotalAction
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci inverseMetric stress : LocalTensor (Site := Site))
    (cosmologicalConstant : Real)
    (generator : LocalTensor (Site := Site)) : Real :=
  chartGravityAction kappa coframe ricci inverseMetric cosmologicalConstant
      generator +
    chartMatterAction coframe inverseMetric stress generator

/-! ## Directional derivatives of the displayed action -/

/-- The metric-variation pairing is additive in its variation argument. -/
theorem metricVariationPairing_add_right
    (coefficient variation variation' : Tensor (I := Fin 4)) :
    metricVariationPairing coefficient (variation + variation') =
      metricVariationPairing coefficient variation +
        metricVariationPairing coefficient variation' := by
  unfold metricVariationPairing
  rw [Matrix.mul_add, Matrix.trace_add]

/-- The metric-variation pairing is homogeneous in its variation argument. -/
theorem metricVariationPairing_smul_right
    (coefficient variation : Tensor (I := Fin 4)) (scalar : Real) :
    metricVariationPairing coefficient (scalar • variation) =
      scalar * metricVariationPairing coefficient variation := by
  unfold metricVariationPairing
  rw [Matrix.mul_smul, Matrix.trace_smul]
  rfl

omit [Fintype Site] in
/-- The fixed-connection scalar-curvature chart is affine in every generator
direction. -/
theorem chartScalarCurvature_smul
    (ricci inverseMetric direction : LocalTensor (Site := Site))
    (t : Real) (site : Site) :
    chartScalarCurvature ricci inverseMetric (t • direction) site =
      chartBaseScalarCurvature ricci inverseMetric site +
        t * chartCurvatureResponse ricci inverseMetric direction site := by
  unfold chartScalarCurvature chartBaseScalarCurvature chartCurvatureResponse
    chartInverseMetric
  change metricVariationPairing (ricci site)
      (inverseMetric site +
        (localInverseMetricVariationLinear inverseMetric)
          (t • direction) site) = _
  rw [map_smul]
  change metricVariationPairing (ricci site)
      (inverseMetric site + t •
        localInverseMetricVariation inverseMetric direction site) = _
  rw [metricVariationPairing_add_right,
    metricVariationPairing_smul_right]
  rfl

omit [Fintype Site] in
/-- The sitewise scalar-curvature chart derivative is its Ricci pairing. -/
theorem hasDerivAt_chartScalarCurvature
    (ricci inverseMetric direction : LocalTensor (Site := Site))
    (site : Site) :
    HasDerivAt
      (fun t : Real =>
        chartScalarCurvature ricci inverseMetric (t • direction) site)
      (chartCurvatureResponse ricci inverseMetric direction site) 0 := by
  rw [show (fun t : Real =>
      chartScalarCurvature ricci inverseMetric (t • direction) site) =
      (fun t : Real => chartBaseScalarCurvature ricci inverseMetric site +
        t * chartCurvatureResponse ricci inverseMetric direction site) by
    funext t
    exact chartScalarCurvature_smul ricci inverseMetric direction t site]
  simpa using
    ((hasDerivAt_id (𝕜 := Real) 0).mul_const
      (chartCurvatureResponse ricci inverseMetric direction site)).const_add
        (chartBaseScalarCurvature ricci inverseMetric site)

omit [Fintype Site] in
/-- The sitewise nonlinear determinant chart has the derived volume response.
-/
theorem hasDerivAt_chartVolume
    (coframe : Site -> RealCoframe (I := Fin 4))
    (direction : LocalTensor (Site := Site)) (site : Site) :
    HasDerivAt
      (fun t : Real => chartVolume coframe (t • direction) site)
      (chartVolumeResponse coframe direction site) 0 := by
  simpa [chartVolume, chartVolumeResponse] using
    hasDerivAt_coframeVolume_mulPath (coframe site) (direction site)

/-- Derivative of the displayed nonlinear gravity action. -/
theorem chartGravityAction_directionalDerivative
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci inverseMetric direction : LocalTensor (Site := Site))
    (cosmologicalConstant : Real) :
    HasDerivAt
      (fun t : Real => chartGravityAction kappa coframe ricci inverseMetric
        cosmologicalConstant (t • direction))
      ((1 / (2 * kappa)) *
        finiteEinsteinHilbertBulkResponse (chartBaseVolume coframe)
          (chartVolumeResponse coframe direction)
          (chartBaseScalarCurvature ricci inverseMetric)
          (chartCurvatureResponse ricci inverseMetric direction)
          cosmologicalConstant) 0 := by
  unfold chartGravityAction finiteEinsteinHilbertBulk
  apply HasDerivAt.const_mul
  apply HasDerivAt.fun_sum
  intro site _
  have hVolume := hasDerivAt_chartVolume coframe direction site
  have hCurvature :=
    (hasDerivAt_chartScalarCurvature ricci inverseMetric direction site).sub_const
      (2 * cosmologicalConstant)
  convert hVolume.mul hCurvature using 1
  all_goals simp [chartVolume, chartBaseVolume, chartScalarCurvature,
    chartBaseScalarCurvature,
    chartInverseMetric, localInverseMetricVariation, inverseMetricVariation]

/-- Weighted local pairing is linear in its variation argument. -/
theorem weightedLocalMetricPairing_smul_right
    (volume : Site -> Real)
    (coefficient variation : LocalTensor (Site := Site))
    (scalar : Real) :
    weightedLocalMetricPairing volume coefficient (scalar • variation) =
      scalar * weightedLocalMetricPairing volume coefficient variation := by
  classical
  unfold weightedLocalMetricPairing metricVariationPairing
  simp only [Pi.smul_apply, Matrix.mul_smul, Matrix.trace_smul, smul_eq_mul]
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro site _
  ring

/-- Derivative of the displayed linearized matter action. -/
theorem chartMatterAction_directionalDerivative
    (coframe : Site -> RealCoframe (I := Fin 4))
    (inverseMetric stress direction : LocalTensor (Site := Site)) :
    HasDerivAt
      (fun t : Real => chartMatterAction coframe inverseMetric stress
        (t • direction))
      (-(1 / 2) * weightedLocalMetricPairing (chartBaseVolume coframe) stress
        (localInverseMetricVariation inverseMetric direction)) 0 := by
  have hPath : (fun t : Real => chartMatterAction coframe inverseMetric stress
      (t • direction)) =
      (fun t : Real => t *
        (-(1 / 2) * weightedLocalMetricPairing (chartBaseVolume coframe) stress
          (localInverseMetricVariation inverseMetric direction))) := by
    funext t
    unfold chartMatterAction
    change -(1 / 2) * weightedLocalMetricPairing (chartBaseVolume coframe)
      stress ((localInverseMetricVariationLinear inverseMetric)
        (t • direction)) = _
    rw [map_smul, weightedLocalMetricPairing_smul_right]
    change -(1 / 2) *
      (t * weightedLocalMetricPairing (chartBaseVolume coframe) stress
        (localInverseMetricVariation inverseMetric direction)) = _
    ring
  rw [hPath]
  simpa using (hasDerivAt_id (𝕜 := Real) 0).mul_const
    (-(1 / 2) * weightedLocalMetricPairing (chartBaseVolume coframe) stress
      (localInverseMetricVariation inverseMetric direction))

/-- **Exact derivative of the nonlinear chart action.** -/
theorem chartTotalAction_directionalDerivative
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci inverseMetric stress direction : LocalTensor (Site := Site))
    (cosmologicalConstant : Real) :
    HasDerivAt
      (fun t : Real => chartTotalAction kappa coframe ricci inverseMetric stress
        cosmologicalConstant (t • direction))
      (normalizedEinsteinHilbertMatterResponse kappa
        (finiteEinsteinHilbertBulkResponse (chartBaseVolume coframe)
          (chartVolumeResponse coframe direction)
          (chartBaseScalarCurvature ricci inverseMetric)
          (chartCurvatureResponse ricci inverseMetric direction)
          cosmologicalConstant)
        (chartBaseVolume coframe) stress
        (localInverseMetricVariation inverseMetric direction)) 0 := by
  unfold chartTotalAction normalizedEinsteinHilbertMatterResponse
  convert (chartGravityAction_directionalDerivative kappa coframe ricci
    inverseMetric direction cosmologicalConstant).add
      (chartMatterAction_directionalDerivative coframe inverseMetric stress
        direction) using 1; ring

/-! ## Stationarity gives the finite Einstein equation -/

/-- The displayed chart action has the weighted Einstein-matter first
variation after pullback through the coframe-generated inverse metric. -/
theorem chartTotalAction_hasPulledBackWeightedEinsteinFirstVariation
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci metric inverseMetric stress : LocalTensor (Site := Site))
    (cosmologicalConstant : Real)
    (hKappa : Not (kappa = 0))
    (hMetric : LocalSymmetric metric)
    (hLeft : forall site, inverseMetric site * metric site = 1)
    (hRight : forall site, metric site * inverseMetric site = 1) :
    HasPulledBackWeightedEinsteinFirstVariation
      (chartTotalAction kappa coframe ricci inverseMetric stress
        cosmologicalConstant)
      0 (localInverseMetricVariationLinear inverseMetric) kappa
      (chartBaseVolume coframe)
      (fun site => finiteEinsteinLHS (ricci site)
        (chartBaseScalarCurvature ricci inverseMetric site) (metric site)
        cosmologicalConstant)
      stress := by
  intro direction
  have hVolume : HasInverseMetricVolumeResponse
      (chartBaseVolume coframe) (chartVolumeResponse coframe direction)
      metric (localInverseMetricVariation inverseMetric direction) := by
    exact coframe_hasInverseMetricVolumeResponse coframe metric inverseMetric
      direction hMetric hLeft hRight
  have hPalatini : HasFinitePalatiniCurvatureResponse
      (chartBaseVolume coframe) ricci
      (localInverseMetricVariation inverseMetric direction)
      (chartCurvatureResponse ricci inverseMetric direction) 0 := by
    unfold HasFinitePalatiniCurvatureResponse weightedLocalMetricPairing
      chartCurvatureResponse localInverseMetricVariation
    simp
  have hDerivative := chartTotalAction_directionalDerivative kappa coframe
    ricci inverseMetric stress direction cosmologicalConstant
  rw [normalizedResponse_eq_weightedLocalTotalMetricFirstVariation kappa
    (chartBaseVolume coframe) (chartVolumeResponse coframe direction)
    (chartBaseScalarCurvature ricci inverseMetric)
    (chartCurvatureResponse ricci inverseMetric direction) ricci metric stress
    (localInverseMetricVariation inverseMetric direction)
    cosmologicalConstant hKappa hVolume hPalatini] at hDerivative
  simpa using hDerivative

/-- **Explicit nonlinear Palatini action control.** Under symmetric
nondegenerate supplied geometry and nonzero oriented local volumes,
stationarity of the displayed coframe-chart action at the origin is equivalent
to the pointwise finite Einstein equation. -/
theorem chartTotalAction_stationary_iff_localFiniteEinsteinEquation
    (kappa : Real)
    (coframe : Site -> RealCoframe (I := Fin 4))
    (ricci metric inverseMetric stress : LocalTensor (Site := Site))
    (cosmologicalConstant : Real)
    (hVolume : forall site, chartBaseVolume coframe site ≠ 0)
    (hRicci : LocalSymmetric ricci) (hMetric : LocalSymmetric metric)
    (hInverseMetric : LocalSymmetric inverseMetric)
    (hStress : LocalSymmetric stress)
    (hLeft : forall site, inverseMetric site * metric site = 1)
    (hRight : forall site, metric site * inverseMetric site = 1)
    (hKappa : Not (kappa = 0)) :
    ParameterStationary
        (chartTotalAction kappa coframe ricci inverseMetric stress
          cosmologicalConstant)
        0 <->
      LocalFiniteEinsteinEquation kappa ricci
        (chartBaseScalarCurvature ricci inverseMetric) metric
        cosmologicalConstant stress := by
  apply parameterStationary_iff_weightedLocalFiniteEinsteinEquation
    (chartTotalAction kappa coframe ricci inverseMetric stress
      cosmologicalConstant)
    0 (localInverseMetricVariationLinear inverseMetric) kappa
    (chartBaseVolume coframe) (chartBaseScalarCurvature ricci inverseMetric)
    ricci metric stress cosmologicalConstant
  · exact chartTotalAction_hasPulledBackWeightedEinsteinFirstVariation kappa
      coframe ricci metric inverseMetric stress cosmologicalConstant hKappa
      hMetric hLeft hRight
  · exact localInverseMetricVariationLinear_isFull metric inverseMetric hMetric
      hInverseMetric hLeft hRight
  · exact hVolume
  · exact hRicci
  · exact hMetric
  · exact hStress
  · exact hKappa

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.FinitePalatiniCoframeChartAction.chartTotalAction_directionalDerivative' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms chartTotalAction_directionalDerivative

/-- info: 'PhysicsSM.Draft.NullEdge.FinitePalatiniCoframeChartAction.chartTotalAction_stationary_iff_localFiniteEinsteinEquation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms chartTotalAction_stationary_iff_localFiniteEinsteinEquation

end PhysicsSM.Draft.NullEdge.FinitePalatiniCoframeChartAction
