import Mathlib.LinearAlgebra.CliffordAlgebra.Contraction
import Mathlib.LinearAlgebra.ExteriorPower.Basis
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.Analysis.Complex.Exponential

open scoped BigOperators

noncomputable section

namespace PhysicsSM.Draft.NullEdge.FiniteFermionicLocality

/-!
# Finite fermionic locality from sparse one-particle transport

This module gives an exterior-algebra realization of finite fermionic Fock
space. It proves that determinant-minor second quantization conjugates creation
and annihilation operators by the one-particle matrix, and that a declared
column-support relation therefore sends each local CAR algebra into the
corresponding neighborhood algebra. Matrix support composes over a finite
schedule, yielding a finite-depth CAR light cone once an inverse pair for the
schedule product is supplied.

The result is a free finite many-body locality theorem. It does not prove
locality of an interacting update, preservation of a positive-energy sector,
or a continuum quantum-field-theory limit.

Provenance: theorem design and initial proof generated by Aristotle project
`78221f1e-595b-4029-ac5a-f98d48ef9174`, then reviewed and integrated into
PhysicsSM on 2026-07-21. The construction uses Mathlib's exterior algebra and
Clifford contraction APIs; it is independent of the occupation-function model
in `FiniteCARFockBasic` and `FiniteCARSecondQuantization`.

## Conventions
# Conventions

* `ι` is a finite linearly ordered mode type.
* A one-particle vector is a column `x : ι → ℂ`; a matrix acts by
  `(U x) j = ∑ i, U j i * x i` (row = output, column = input).
* Fock space is the full exterior algebra `ExteriorAlgebra ℂ (ι → ℂ)`.  Products are written
  from left to right in increasing occupation order.  Creation is left exterior multiplication.
* The annihilator at `i` is left contraction by the coordinate functional `x ↦ x i`.  Thus
  `a i (e i * ψ) = ψ - e i * a i ψ`; this fixes all fermionic ordering signs.
* `secondQuantization U` is the exterior-algebra map induced by the one-particle map.  On an
  increasing `n`-particle basis it is the usual determinant-minor matrix (proved below).
* `Near i j` means that output mode `j` is allowed to depend on input mode `i`.  Consequently
  locality is the column-support condition `¬ Near i j → U j i = 0`.
* For a unitary, `V` below is its conjugate transpose: `V i j = conj (U j i)`.  We retain both
  inverse equations explicitly, so no locality is inferred from unitarity.
-/

variable {ι : Type*} [Fintype ι] [DecidableEq ι] [LinearOrder ι]

abbrev OneParticle (ι : Type*) := ι → ℂ
abbrev Fock (ι : Type*) := ExteriorAlgebra ℂ (OneParticle ι)
abbrev FockEnd (ι : Type*) := Module.End ℂ (Fock ι)

/-- The standard one-particle basis vector. -/
def basisVec (i : ι) : OneParticle ι := Pi.single i 1

/-- Coordinate covector. -/
def coord (i : ι) : Module.Dual ℂ (OneParticle ι) :=
  LinearMap.proj i

/-- Matrix action, with output (row) as the first matrix index. -/
def oneParticleMap (U : Matrix ι ι ℂ) : OneParticle ι →ₗ[ℂ] OneParticle ι :=
  (Matrix.toLin' : Matrix ι ι ℂ ≃ₗ[ℂ] (OneParticle ι →ₗ[ℂ] OneParticle ι)) U

/-- Determinant-minor second quantization, presented functorially on the exterior algebra. -/
def secondQuantization (U : Matrix ι ι ℂ) : Fock ι →ₐ[ℂ] Fock ι :=
  ExteriorAlgebra.map (oneParticleMap U)

/-- Creation is left exterior multiplication by the corresponding standard basis vector. -/
def create (i : ι) : FockEnd ι :=
  LinearMap.mulLeft ℂ (ExteriorAlgebra.ι ℂ (basisVec i))

/-- Annihilation is left contraction by the corresponding coordinate covector. -/
def annihilate (i : ι) : FockEnd ι :=
  CliffordAlgebra.contractLeft (Q := (0 : QuadraticForm ℂ (OneParticle ι))) (coord i)

/-- Algebraic conjugation.  When `V = Uᴴ`, this is `Γ(U) T Γ(U)⁎`. -/
def conjugate (U V : Matrix ι ι ℂ) (T : FockEnd ι) : FockEnd ι :=
  (secondQuantization U).toLinearMap ∘ₗ T ∘ₗ (secondQuantization V).toLinearMap

/-- Explicit inverse/unitary data used by every conjugation theorem. -/
structure UnitaryPair (U V : Matrix ι ι ℂ) : Prop where
  left_inv : U * V = 1
  right_inv : V * U = 1
  adjoint_entries : ∀ i j, V i j = starRingEnd ℂ (U j i)

lemma oneParticleMap_basis (U : Matrix ι ι ℂ) (i : ι) :
    oneParticleMap U (basisVec i) = ∑ j, U j i • basisVec j := by
  ext j;
  simp +decide [ oneParticleMap, basisVec, Pi.single_apply ]

lemma oneParticleMap_mul (U V : Matrix ι ι ℂ) :
    oneParticleMap (U * V) = (oneParticleMap U) ∘ₗ (oneParticleMap V) := by
  ext; simp [oneParticleMap]

lemma secondQuantization_mul (U V : Matrix ι ι ℂ) :
    (secondQuantization U).comp (secondQuantization V) = secondQuantization (U * V) := by
  simp +decide [ secondQuantization, oneParticleMap_mul ]

lemma secondQuantization_one :
    secondQuantization (1 : Matrix ι ι ℂ) = AlgHom.id ℂ (Fock ι) := by
  unfold secondQuantization;
  unfold oneParticleMap;
  ext; simp [Matrix.toLin'_one]

lemma exteriorPower_map_basis_minor
    (U : Matrix ι ι ℂ) (n : ℕ) (s : Set.powersetCard ι n) :
    exteriorPower.map n (oneParticleMap U) ((Pi.basisFun ℂ ι).exteriorPower n s) =
      ∑ t : Set.powersetCard ι n,
        Matrix.det (U.submatrix
          (Set.powersetCard.ofFinEmbEquiv.symm t)
          (Set.powersetCard.ofFinEmbEquiv.symm s)) •
          (Pi.basisFun ℂ ι).exteriorPower n t := by
  have h_det : ∀ (t : Set.powersetCard ι n), (Module.Basis.exteriorPower n (Pi.basisFun ℂ ι)).repr (exteriorPower.map n (oneParticleMap U) (Module.Basis.exteriorPower n (Pi.basisFun ℂ ι) s)) t = (U.submatrix (Set.powersetCard.ofFinEmbEquiv.symm t) (Set.powersetCard.ofFinEmbEquiv.symm s)).det := by
    intro t;
    have := @exteriorPower.ιMultiDual_apply_ιMulti;
    convert this ℂ n ( Pi.basisFun ℂ ι ) t ( fun i => oneParticleMap U ( Pi.basisFun ℂ ι ( Set.powersetCard.ofFinEmbEquiv.symm s i ) ) ) using 1;
    · simp +decide [ exteriorPower.map_apply_ιMulti ];
      convert this ℂ n ( Pi.basisFun ℂ ι ) t ( fun i => oneParticleMap U ( Pi.basisFun ℂ ι ( Set.powersetCard.ofFinEmbEquiv.symm s i ) ) ) using 1;
      · exact
          exteriorPower.basis_repr_apply ℂ n (Pi.basisFun ℂ ι)
            (exteriorPower.ιMulti_family ℂ n (⇑(oneParticleMap U) ∘ ⇑(Pi.basisFun ℂ ι)) s) t;
      · simp +decide [ Pi.single_apply, oneParticleMap ];
    · simp +decide [ oneParticleMap, Matrix.mulVec, dotProduct ];
      exact Matrix.det_transpose _;
  rw [ ← ( Module.Basis.exteriorPower n ( Pi.basisFun ℂ ι ) ).sum_repr ( exteriorPower.map n ( oneParticleMap U ) ( ( Module.Basis.exteriorPower n ( Pi.basisFun ℂ ι ) ) s ) ) ];
  exact Finset.sum_congr rfl fun _ _ => h_det _ ▸ rfl

/-
The exterior-map definition is exactly determinant-minor second quantization.
-/
theorem secondQuantization_on_occupation
    (U : Matrix ι ι ℂ) (n : ℕ) (s : Set.powersetCard ι n) :
    secondQuantization U (exteriorPower.ιMulti_family ℂ n (Pi.basisFun ℂ ι) s) =
      ∑ t : Set.powersetCard ι n,
        Matrix.det (U.submatrix
          (Set.powersetCard.ofFinEmbEquiv.symm t)
          (Set.powersetCard.ofFinEmbEquiv.symm s)) •
          exteriorPower.ιMulti_family ℂ n (Pi.basisFun ℂ ι) t := by
  have := exteriorPower_map_basis_minor U n s;
  convert congr_arg Subtype.val this;
  · simp +decide [ secondQuantization, exteriorPower.ιMulti_family ];
  · exact Eq.symm (exteriorPower.coe_basis ℂ n (Pi.basisFun ℂ ι))

/-
The sign convention for annihilation on a newly created state.
-/
theorem annihilate_create_apply (i : ι) (x : OneParticle ι) (ψ : Fock ι) :
    annihilate i (ExteriorAlgebra.ι ℂ x * ψ) =
      x i • ψ - ExteriorAlgebra.ι ℂ x * annihilate i ψ := by
  convert CliffordAlgebra.contractLeft_ι_mul _ _ _ using 2

/-
Creation conjugation law.  `V` is the explicitly supplied inverse (and, for a unitary,
its adjoint), so the rightmost map is exactly `Γ(U)⁎`.
-/
theorem conjugate_create (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) (i : ι) :
    conjugate U V (create i) = ∑ j, U j i • create j := by
  ext ψ;
  simp +decide [ conjugate, create, oneParticleMap_basis ];
  convert congr_arg ( fun x => x * ( secondQuantization U ) ( ( secondQuantization V ) ( ExteriorAlgebra.ιMulti ℂ ψ ‹_› ) ) ) ( show ( secondQuantization U ) ( ExteriorAlgebra.ι ℂ ( basisVec i ) ) = ∑ j, U j i • ExteriorAlgebra.ι ℂ ( basisVec j ) from ?_ ) using 1;
  · rw [ Finset.sum_mul _ _ _ ];
    have h_secondQuantization : (secondQuantization U).comp (secondQuantization V) = AlgHom.id ℂ (Fock ι) := by
      rw [ secondQuantization_mul, h.left_inv, secondQuantization_one ];
    replace h_secondQuantization := congr_arg ( fun f => f ( ExteriorAlgebra.ιMulti ℂ ψ ‹_› ) ) h_secondQuantization ; aesop;
  · unfold secondQuantization;
    simp +decide [ oneParticleMap_basis ]

/-
Annihilation conjugation law, with the conjugated coefficient forced by the stated
adjoint-entry convention.
-/
theorem conjugate_annihilate (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) (i : ι) :
    conjugate U V (annihilate i) =
      ∑ j, starRingEnd ℂ (U j i) • annihilate j := by
  -- By definition of annihilate, we have:
  have h_annihilate : ∀ x : Fock ι, (secondQuantization U).toLinearMap (annihilate i ((secondQuantization V).toLinearMap x)) = ∑ j, (starRingEnd ℂ (U j i)) • (annihilate j x) := by
    intro x
    have h_annihilate : (annihilate i) ((secondQuantization V).toLinearMap x) = (secondQuantization V).toLinearMap ((CliffordAlgebra.contractLeft (Q := (0 : QuadraticForm ℂ (OneParticle ι))) (coord i ∘ₗ oneParticleMap V)) x) := by
      unfold annihilate secondQuantization;
      induction x using CliffordAlgebra.left_induction <;> simp_all +decide [ CliffordAlgebra.contractLeft_ι_mul ];
    -- By definition of $V$, we know that $coord i ∘ₗ oneParticleMap V = \sum_j V i j • coord j$.
    have h_coord_V : coord i ∘ₗ oneParticleMap V = ∑ j, V i j • coord j := by
      ext x;
      simp +decide [ coord, oneParticleMap ];
      simp +decide [ Pi.single_apply ];
    simp_all +decide [ annihilate ];
    have h_secondQuantization_V : ∀ j, (secondQuantization U) ((secondQuantization V) ((CliffordAlgebra.contractLeft (coord j)) x)) = (CliffordAlgebra.contractLeft (coord j)) x := by
      intro j
      have h_secondQuantization_V : (secondQuantization U) ((secondQuantization V) ((CliffordAlgebra.contractLeft (coord j)) x)) = (secondQuantization (U * V)) ((CliffordAlgebra.contractLeft (coord j)) x) := by
        exact congr_arg ( fun f => f ( CliffordAlgebra.contractLeft ( coord j ) x ) ) ( secondQuantization_mul U V );
      rw [ h_secondQuantization_V, h.left_inv, secondQuantization_one ] ; aesop;
    exact Finset.sum_congr rfl fun j _ => by rw [ h_secondQuantization_V j, h.adjoint_entries ] ;
  exact LinearMap.ext fun x => by simpa using h_annihilate x;

/-- The algebra generated by creators and annihilators in a set of modes. -/
def modeAlgebra (S : Set ι) : Subalgebra ℂ (FockEnd ι) :=
  Algebra.adjoin ℂ ({T | ∃ i ∈ S, T = create i} ∪ {T | ∃ i ∈ S, T = annihilate i})

/-- The strictly local CAR algebra at one mode. -/
def localCAR (i : ι) : Subalgebra ℂ (FockEnd ι) := modeAlgebra {i}

/-- Neighborhood algebra for the declared (input, output) relation. -/
def neighborhoodCAR (Near : ι → ι → Prop) (i : ι) : Subalgebra ℂ (FockEnd ι) :=
  modeAlgebra {j | Near i j}

lemma conjugate_one (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) :
    conjugate U V (1 : FockEnd ι) = 1 := by
  ext x;
  convert congr_arg ( fun f => f ( List.ofFn fun i => ( ExteriorAlgebra.ι ℂ ) ( ‹Fin x → OneParticle ι› i ) ).prod ) ( secondQuantization_mul U V ) using 1;
  rw [ h.left_inv, secondQuantization_one ] ; aesop

lemma conjugate_mul (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) (A B : FockEnd ι) :
    conjugate U V (A * B) = conjugate U V A * conjugate U V B := by
  ext x
  simp [conjugate];
  have h_inv : (secondQuantization V).comp (secondQuantization U) = AlgHom.id ℂ (Fock ι) := by
    convert secondQuantization_mul V U using 1;
    rw [ h.right_inv, secondQuantization_one ];
  replace h_inv := congr_arg ( fun f => f ( B ( ( secondQuantization V ) ( ExteriorAlgebra.ιMulti ℂ x ‹_› ) ) ) ) h_inv ; aesop

lemma conjugate_zero (U V : Matrix ι ι ℂ) : conjugate U V (0 : FockEnd ι) = 0 := by
  unfold conjugate; aesop;

lemma conjugate_add (U V : Matrix ι ι ℂ) (A B : FockEnd ι) :
    conjugate U V (A + B) = conjugate U V A + conjugate U V B := by
  unfold conjugate; aesop;

lemma conjugate_algebraMap (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) (z : ℂ) :
    conjugate U V (algebraMap ℂ (FockEnd ι) z) = algebraMap ℂ (FockEnd ι) z := by
  convert congr_arg ( fun x : FockEnd ι => z • x ) ( conjugate_one U V h ) using 1;
  unfold conjugate; aesop;

/-- Algebra homomorphism induced by conjugation with an explicitly inverse pair. -/
def conjugationAlgHom (U V : Matrix ι ι ℂ) (h : UnitaryPair U V) :
    FockEnd ι →ₐ[ℂ] FockEnd ι where
  toFun := conjugate U V
  map_one' := conjugate_one U V h
  map_mul' := conjugate_mul U V h
  map_zero' := conjugate_zero U V
  map_add' := conjugate_add U V
  commutes' := conjugate_algebraMap U V h

/-- Locality is a genuine matrix-column support hypothesis. -/
def LocalFor (Near : ι → ι → Prop) (U : Matrix ι ι ℂ) : Prop :=
  ∀ i j, ¬ Near i j → U j i = 0

lemma weighted_create_mem_modeAlgebra (S : Set ι) (c : ι → ℂ)
    (hc : ∀ j, j ∉ S → c j = 0) (i : ι) :
    (∑ j, c j • create j) ∈ modeAlgebra S := by
  have h_sum_mem : ∀ j, j ∈ S → create j ∈ modeAlgebra S := by
    exact fun j hj => Algebra.subset_adjoin <| Set.mem_union_left _ ⟨ j, hj, rfl ⟩;
  exact Subalgebra.sum_mem _ fun j hj => by by_cases hjS : j ∈ S <;> aesop;

lemma weighted_annihilate_mem_modeAlgebra (S : Set ι) (c : ι → ℂ)
    (hc : ∀ j, j ∉ S → c j = 0) (i : ι) :
    (∑ j, c j • annihilate j) ∈ modeAlgebra S := by
  convert Subalgebra.sum_mem _ fun j _ => ?_;
  by_cases hjS : j ∈ S <;> simp_all +decide [ Algebra.smul_def ];
  exact Subalgebra.mul_mem _ ( Subalgebra.algebraMap_mem _ _ ) ( Algebra.subset_adjoin <| Set.mem_union_right _ ⟨ j, hjS, rfl ⟩ )

/-
The image of the local CAR algebra is contained in the declared neighborhood algebra.
-/
theorem localCAR_image_le_neighborhood
    (Near : ι → ι → Prop) (U V : Matrix ι ι ℂ) (hunit : UnitaryPair U V)
    (hloc : LocalFor Near U) (i : ι) :
    (localCAR i).map (conjugationAlgHom U V hunit) ≤ neighborhoodCAR Near i := by
  intro x hx;
  obtain ⟨ y, hy, rfl ⟩ := hx;
  refine' Algebra.adjoin_induction _ _ _ _ hy;
  · rintro x ( ⟨ j, rfl, rfl ⟩ | ⟨ j, rfl, rfl ⟩ ) <;> simp +decide [ conjugate_create, conjugate_annihilate, hloc ];
    · convert weighted_create_mem_modeAlgebra { j_1 | Near j j_1 } ( fun k => U k j ) ( fun k hk => hloc j k hk ) j using 1;
      convert conjugate_create U V hunit j using 1;
    · convert weighted_annihilate_mem_modeAlgebra { k | Near j k } ( fun k => starRingEnd ℂ ( U k j ) ) _ j using 1;
      · convert conjugate_annihilate U V hunit j using 1;
      · aesop;
  · intro r
    simp [conjugationAlgHom];
    convert Subalgebra.algebraMap_mem _ r;
    exact conjugate_algebraMap U V hunit r;
  · simp +contextual [ conjugationAlgHom ];
    exact fun x y hx hy hx' hy' => by rw [ conjugate_add ] ; exact Subalgebra.add_mem _ hx' hy';
  · intro x y hx hy hx' hy';
    convert Subalgebra.mul_mem _ hx' hy' using 1;
    exact conjugate_mul U V hunit x y

/-- Relational composition, in input-to-output orientation. -/
def RelComp (R S : ι → ι → Prop) (i k : ι) : Prop := ∃ j, R i j ∧ S j k

/-
Matrix multiplication enlarges one-particle support only by relational composition.
-/
theorem localFor_mul
    (R S : ι → ι → Prop) (U V : Matrix ι ι ℂ)
    (hU : LocalFor R U) (hV : LocalFor S V) :
    LocalFor (RelComp R S) (V * U) := by
  intro i k; by_cases hk : ∃ j, R i j ∧ S j k <;> simp_all +decide [ RelComp ] ;
  exact Finset.sum_eq_zero fun j _ => by by_cases hj : R i j <;> aesop;

/-
Exact two-layer conjugation composition.
-/
theorem conjugate_compose
    (U Ui V Vi : Matrix ι ι ℂ) (hU : UnitaryPair U Ui) (hV : UnitaryPair V Vi)
    (T : FockEnd ι) :
    conjugate V Vi (conjugate U Ui T) = conjugate (V * U) (Ui * Vi) T := by
  unfold conjugate;
  ext; simp +decide [ secondQuantization_mul ] ;
  simp +decide [ ← secondQuantization_mul ]

/-- `n`-fold relational light cone. -/
def RelPower (R : ι → ι → Prop) : ℕ → ι → ι → Prop
  | 0 => Eq
  | n + 1 => RelComp (RelPower R n) R

/-
A finite-depth sequence of sparse matrices has support in the corresponding recursively
composed light cone.
-/
theorem finite_depth_light_cone
    (R : ι → ι → Prop) (Us : List (Matrix ι ι ℂ))
    (hUs : ∀ U ∈ Us, LocalFor R U) :
    LocalFor (RelPower R Us.length) (Us.reverse.foldl (· * ·) 1) := by
  revert hUs;
  induction Us using List.reverseRecOn <;> simp_all +decide [ LocalFor ];
  · exact fun i j hij => if_neg ( Ne.symm hij );
  · rename_i k hk;
    have h_mul : ∀ (A B : Matrix ι ι ℂ), (∀ i j, ¬RelPower R (List.length ‹List (Matrix ι ι ℂ)›) i j → A j i = 0) → (∀ i j, ¬R i j → B j i = 0) → (∀ i j, ¬RelPower R (List.length ‹List (Matrix ι ι ℂ)› + 1) i j → (B * A) j i = 0) := by
      intro A B hA hB i j hij;
      rw [ Matrix.mul_apply, Finset.sum_eq_zero ] ; intros ; simp_all +decide [ RelPower ];
      exact Classical.or_iff_not_imp_left.2 fun h => hA _ _ fun h' => hij ⟨ _, h', by contrapose! h; aesop ⟩;
    intro h;
    convert h_mul _ _ ( hk fun U hU => h U ( Or.inl hU ) ) ( h k ( Or.inr rfl ) ) using 1;
    congr! 3;
    have h_foldr : ∀ (l : List (Matrix ι ι ℂ)) (k : Matrix ι ι ℂ), List.foldr (fun x y => y * x) k l = k * List.foldr (fun x y => y * x) 1 l := by
      intro l k; induction l <;> simp +decide [ *, mul_assoc ] ;
    exact h_foldr _ _ ▸ rfl

/-
The finite-depth support theorem lifts to the algebra generated by creation and
annihilation operators. The inverse matrix is explicit input: sparsity of the
forward schedule alone does not manufacture unitarity.
-/
theorem finite_depth_localCAR_image_le
    (R : ι → ι → Prop) (Us : List (Matrix ι ι ℂ))
    (hUs : ∀ U ∈ Us, LocalFor R U)
    (W : Matrix ι ι ℂ)
    (hunit : UnitaryPair (Us.reverse.foldl (· * ·) 1) W)
    (i : ι) :
    (localCAR i).map
        (conjugationAlgHom (Us.reverse.foldl (· * ·) 1) W hunit) ≤
      neighborhoodCAR (RelPower R Us.length) i :=
  localCAR_image_le_neighborhood
    (RelPower R Us.length) (Us.reverse.foldl (· * ·) 1) W hunit
    (finite_depth_light_cone R Us hUs) i

section Controls

/-- A nonidentity sparse unitary: the swap on two modes. -/
def swap2 : Matrix (Fin 2) (Fin 2) ℂ := fun i j => if i = 1 - j then 1 else 0

/-- Its exact declared support relation. -/
def SwapNear (i j : Fin 2) : Prop := j = 1 - i

theorem swap2_unitary_pair : UnitaryPair swap2 swap2 := by
  constructor <;> norm_num [ swap2 ];
  · ext i j; fin_cases i <;> fin_cases j <;> simp +decide [ Matrix.mul_apply, swap2 ] ;
  · ext i j; fin_cases i <;> fin_cases j <;> simp +decide [ swap2, Matrix.mul_apply ] ;

theorem swap2_local : LocalFor SwapNear swap2 := by
  unfold LocalFor;
  simp +decide [ SwapNear, swap2 ]

theorem swap2_nonidentity : swap2 ≠ (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  exact ne_of_apply_ne ( fun m => m 1 0 ) ( by simp +decide [ swap2 ] )

/-
The wrong empty neighborhood fails for the same unitary.  This is the requested
load-bearing-hypothesis counterexample.
-/
theorem swap2_not_local_for_empty : ¬ LocalFor (fun _ _ : Fin 2 => False) swap2 := by
  unfold LocalFor; simp +decide [ swap2 ] ;

/-
Correspondingly, the creation operator really moves to the other mode.
-/
theorem swap2_moves_creation :
    conjugate swap2 swap2 (create (0 : Fin 2)) = create (1 : Fin 2) := by
  convert conjugate_create swap2 swap2 swap2_unitary_pair 0 using 1;
  unfold swap2; simp +decide [ Fin.sum_univ_succ ] ;

end Controls

end PhysicsSM.Draft.NullEdge.FiniteFermionicLocality

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.secondQuantization_on_occupation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.secondQuantization_on_occupation

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.localCAR_image_le_neighborhood' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.localCAR_image_le_neighborhood

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.finite_depth_localCAR_image_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.finite_depth_localCAR_image_le

/-- info: 'PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.swap2_moves_creation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.FiniteFermionicLocality.swap2_moves_creation
