import Mathlib

/-!
# Controlled transverse-sector Floquet composition

This standalone target combines a finite transverse rank-one selector with two
independent unitary spin-sector updates.  It is deliberately abstract in the
spin updates: a later project will instantiate the selected update with the
exact HNU endpoint and the complement update with the compensating pi-gap or
bulk dynamics.

Provenance: generated by Aristotle task `9c89efe3-5325-494d-9169-72fb8d214718`, independently replayed and semantically approved by interactive Claude/Opus in `AutonomousLab/reviews/CLAUDE_REVIEW_NullDilation_NoGo_ControlledSector_2026-07-13.md`.\n\nThe target is finite linear algebra only.  It does not claim real-space
locality, primitive-null support, a Weyl winding, anomaly inflow, a bulk-edge
theorem, or a physical domain wall.  Introducing the complement update `V` as a
free parameter does **not** by itself construct any compensating dynamics; it
merely records a slot for it.
-/

namespace PhysicsSM.Draft.NullEdge.FloquetTransverseComposite

open Matrix

noncomputable section

abbrev TSite := Fin 3
abbrev Spin := Fin 2

def IsUnitary {n : Type} [Fintype n] [DecidableEq n]
    (U : Matrix n n Complex) : Prop :=
  U.conjTranspose * U = 1 ∧ U * U.conjTranspose = 1

def w : TSite -> Complex := ![2, 0, -1]

def selector : Matrix TSite TSite Complex :=
  (1 / 5 : Complex) • vecMulVec w w

def controlled (U V : Matrix Spin Spin Complex) :
    Matrix (TSite × Spin) (TSite × Spin) Complex :=
  kroneckerMap (fun a b => a * b) selector U +
    kroneckerMap (fun a b => a * b)
      ((1 : Matrix TSite TSite Complex) - selector) V

def embed (e : Spin -> Complex) : TSite × Spin -> Complex :=
  fun p => w p.1 * e p.2

/-! ## Basic normalisation and projector algebra -/

/-- The transverse profile `w` has squared norm `5`. -/
theorem w_dotProduct_self : w ⬝ᵥ w = 5 := by
  norm_num [w]

/-- Acting the rank-one selector on a vector projects onto the `w` line. -/
theorem selector_mulVec (x : TSite -> Complex) :
    selector *ᵥ x = ((1 / 5 : Complex) * (w ⬝ᵥ x)) • w := by
  ext i
  unfold selector
  norm_num [Matrix.mulVec, dotProduct]
  ring_nf
  simp +decide [vecMulVec, mul_comm, mul_left_comm, Finset.mul_sum _ _ _]

/-- The rank-one selector is an exact Hermitian projector. -/
theorem selector_isHermitian : selector.IsHermitian := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp +decide [selector, w]

/-- The rank-one selector is idempotent. -/
theorem selector_idempotent : selector * selector = selector := by
  ext i j
  simp +decide [selector, Matrix.mul_apply, vecMulVec]
  ring_nf
  fin_cases i <;> fin_cases j <;> norm_num [Fin.sum_univ_succ, w]

/-- The selector fixes the transverse profile `w`. -/
theorem selector_mulVec_w : selector *ᵥ w = w := by
  convert selector_mulVec w using 1
  norm_num [w_dotProduct_self]

/-- The complement projector annihilates the transverse profile `w`. -/
theorem complement_mulVec_w :
    ((1 : Matrix TSite TSite Complex) - selector) *ᵥ w = 0 := by
  rw [Matrix.sub_mulVec, Matrix.one_mulVec, selector_mulVec_w, sub_self]

/-- The complement projector `1 - selector` is Hermitian. -/
theorem complement_isHermitian :
    ((1 : Matrix TSite TSite Complex) - selector).IsHermitian :=
  Matrix.isHermitian_one.sub selector_isHermitian

/-- The complement projector is idempotent. -/
theorem complement_idempotent :
    ((1 : Matrix TSite TSite Complex) - selector) *
      ((1 : Matrix TSite TSite Complex) - selector)
      = (1 : Matrix TSite TSite Complex) - selector := by
  rw [sub_mul, mul_sub]
  simp +decide [mul_sub]
  rw [sub_eq_zero, selector_idempotent]

/-- Block orthogonality: the selector followed by its complement is zero. -/
theorem selector_mul_complement :
    selector * ((1 : Matrix TSite TSite Complex) - selector) = 0 := by
  rw [Matrix.mul_sub, mul_one, sub_eq_zero, selector_idempotent]

/-- Block orthogonality: the complement followed by the selector is zero. -/
theorem complement_mul_selector :
    ((1 : Matrix TSite TSite Complex) - selector) * selector = 0 := by
  rw [sub_mul, one_mul, sub_eq_zero, selector_idempotent]

/-! ## Kronecker action on product vectors -/

/-- A Kronecker product acts factorwise on a product vector. -/
theorem kronecker_mulVec_prod
    {l m n p : Type*} [Fintype m] [Fintype p]
    (A : Matrix l m Complex) (B : Matrix n p Complex)
    (u : m -> Complex) (v : p -> Complex) :
    (kroneckerMap (fun a b => a * b) A B) *ᵥ (fun q => u q.1 * v q.2)
      = fun q => (A *ᵥ u) q.1 * (B *ᵥ v) q.2 := by
  ext ⟨i, j⟩
  simp +decide [Matrix.mulVec, dotProduct, Fintype.sum_prod_type]
  simp +decide only [mul_left_comm, mul_comm, Finset.mul_sum _ _ _]
  rw [Finset.sum_comm]

/-! ## Unitarity of the controlled composition -/

/-- Independent unitary updates on the two orthogonal transverse sectors give
an exactly unitary combined update.  This is the full operator statement, not a
componentwise or selected-sector weakening. -/
theorem controlled_isUnitary {U V : Matrix Spin Spin Complex}
    (hU : IsUnitary U) (hV : IsUnitary V) :
    IsUnitary (controlled U V) := by
  have h_unitary : (kroneckerMap (fun a b => a * b) selector U +
      kroneckerMap (fun a b => a * b) (1 - selector) V) *
      (kroneckerMap (fun a b => a * b) selector U +
        kroneckerMap (fun a b => a * b) (1 - selector) V).conjTranspose = 1 := by
    simp_all +decide [Matrix.mul_add, Matrix.add_mul, Matrix.conjTranspose_add]
    simp_all +decide [IsUnitary, Matrix.conjTranspose_kronecker]
    simp_all +decide [← Matrix.mul_kronecker_mul]
    simp_all +decide [selector_isHermitian.eq, selector_idempotent]
    simp_all +decide [Matrix.mul_sub, sub_mul, selector_idempotent]
    ext i j
    simp +decide [Matrix.one_apply, kroneckerMap]
    grind
  exact ⟨mul_eq_one_comm.mp h_unitary, h_unitary⟩

/-! ## Exact sector restriction -/

/-- The selected transverse sector carries `U` exactly, independently of the
complement update `V`. -/
theorem controlled_restriction (U V : Matrix Spin Spin Complex)
    (e : Spin -> Complex) :
    controlled U V *ᵥ embed e = embed (U *ᵥ e) := by
  ext ⟨i, j⟩
  convert congr_arg (fun x : TSite × Spin → ℂ => x (i, j))
    (kronecker_mulVec_prod selector U w e) using 1
  · unfold embed
    simp +decide [controlled, Matrix.add_mulVec]
    convert congr_arg (fun x : TSite × Spin → ℂ => x (i, j))
      (kronecker_mulVec_prod (1 - selector) V w e) using 1
    simp +decide [complement_mulVec_w]
  · rw [selector_mulVec_w]; aesop

/-- Dual restriction: on a transverse profile `f` killed by the selector, the
controlled update carries the complement `V` exactly, independently of `U`.
This is the slot a pi-gap compensator would occupy. -/
theorem controlled_complement_restriction (U V : Matrix Spin Spin Complex)
    (f : TSite -> Complex) (e : Spin -> Complex) (hf : selector *ᵥ f = 0) :
    controlled U V *ᵥ (fun q => f q.1 * e q.2)
      = fun q => f q.1 * (V *ᵥ e) q.2 := by
  ext q
  convert congr_arg (fun x : TSite × Spin → ℂ => x q)
    (kronecker_mulVec_prod ((1 : Matrix TSite TSite ℂ) - selector) V f e) using 1
  · unfold controlled
    simp +decide [Matrix.add_mulVec]
    rw [kronecker_mulVec_prod]; aesop
  · simp_all +decide [Matrix.sub_mulVec]

/-- A nonzero spinor remains nonzero after embedding, so the restriction is
nonvacuous. -/
theorem embed_ne_zero {e : Spin -> Complex} (he : e != 0) : embed e != 0 := by
  obtain ⟨i, hi⟩ := Function.ne_iff.mp (by simpa using he)
  unfold embed
  fin_cases i <;> simp_all +decide [funext_iff, Fin.forall_fin_succ]
  · unfold w; norm_num
  · unfold w; aesop

/-- The stationary-complement choice is explicit rather than hidden.  This is a
control specialization (`V = 1`): it leaves the complement sector inert and
therefore does *not* realize the stronger all-moving primitive-null ontology,
which would require nontrivial complement dynamics. -/
theorem stationary_complement_restriction (U : Matrix Spin Spin Complex)
    (e : Spin -> Complex) :
    controlled U 1 *ᵥ embed e = embed (U *ᵥ e) :=
  controlled_restriction U 1 e

/-! ## Standard-axiom guards

Build-enforced checks that the projector, unitarity, and restriction theorems
depend only on the standard Lean/Mathlib axioms. -/

/-- info: 'PhysicsSM.Draft.NullEdge.FloquetTransverseComposite.selector_isHermitian' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms selector_isHermitian

/-- info: 'PhysicsSM.Draft.NullEdge.FloquetTransverseComposite.selector_idempotent' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms selector_idempotent

/-- info: 'PhysicsSM.Draft.NullEdge.FloquetTransverseComposite.controlled_isUnitary' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms controlled_isUnitary

/-- info: 'PhysicsSM.Draft.NullEdge.FloquetTransverseComposite.controlled_restriction' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms controlled_restriction

end

end PhysicsSM.Draft.NullEdge.FloquetTransverseComposite
