import Mathlib

/-!
# Frame-blindness forbids selective suppression (Opus, verified b222f690)

GENERALIZES the program's permutation-invariant Lambda no-go to an ARBITRARY finite
group action, so the obstruction is about INVARIANCE AS SUCH, not about permutations.
This is the flagship outward-facing result identified in
`AutonomousLab/work/NE-DYNAMICS/OPUS_CROSS_LANE_SYNTHESIS_2026-07-21.md`.

Proved: invariant kernels are constant on diagonal-action orbits of `X x X`; the
orbit-coefficient representation, with orbit-algebra dimension equal to the number
of pair-orbits; invariant matrices commute with the induced permutation
representation; for TRANSITIVE actions row sums are constant and the all-ones vector
is an eigenvector; the zero-sum sector is stable under symmetric invariant
covariances; invariant quadratic variance is CONSTANT ALONG EVERY GROUP ORBIT; PSD
zero variance implies membership in the operator kernel; and therefore SUPPRESSION
EXTENDS to every translate and to the full linear span of the mode's orbit.

THE SHARP WITNESS PAIR: an explicit `S3` action on `Fin 3` with an invariant PSD
covariance suppressing the ENTIRE zero-sum block, versus an explicit NON-invariant
rank-one PSD covariance that suppresses EXACTLY ONE LINE in that block while failing
to suppress a translated mode. So selective suppression is possible precisely when
invariance is given up.

PRECISION (the prover sharpened the requested statement - keep this wording): the
general theorem holds at the level of the SUBREPRESENTATION GENERATED BY THE ORBIT,
NOT the whole isotypic component. An arbitrary commutant operator need not
annihilate an entire isotypic component when that component has MULTIPLICITY. In the
`S3` witness the zero-sum representation is the relevant irreducible block, so there
suppression does propagate through the whole block. Do NOT state this as an
isotypic-wide theorem.

PHYSICS READING (and its limit): everpresent-Lambda derives its magnitude from
POISSON number fluctuations (arXiv:2304.03819); the natural escape is to make the
process HYPERUNIFORM, suppressing long-wavelength fluctuations below Poisson. This
theorem says a frame-blind covariance cannot suppress a regional mode selectively -
suppression propagates along the orbit. It is the finite, machine-checked shadow of
the causal-set zero-one laws (arXiv:1909.06070: sprinklings cannot prefer a timelike
direction; no Poincare-invariant sprinkling other than Poisson is known). It is NOT
a derivation of the value or sign of Lambda, NOT a continuum or Lorentzian statement,
and the group here is FINITE - the Lorentz-flavoured version remains open.

Namespace kept as the prover's FrameBlindness. Provenance: verified at pin from task
6cbbd6db. Standard three. Claim grade M, [orig]. -/

open scoped BigOperators
open scoped Classical

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace FrameBlindness

variable {G X : Type*} [Group G] [Fintype G] [Fintype X]
  [DecidableEq X] [MulAction G X]

/-- Simultaneous invariance of a kernel under a group action. -/
def KernelInvariant (C : Matrix X X ℝ) : Prop :=
  ∀ (g : G) (x y : X), C (g • x) (g • y) = C x y

/-- The finite set of orbits on ordered pairs under the diagonal action. -/
abbrev PairOrbit := Quotient (MulAction.orbitRel G (X × X))

/-- The abstract orbit algebra: one real coefficient for each orbit on pairs. -/
abbrev OrbitAlgebra := PairOrbit (G := G) (X := X) → ℝ

/-- Realize orbit coefficients as a matrix, constant on every pair orbit. -/
def orbitMatrix (a : OrbitAlgebra (G := G) (X := X)) : Matrix X X ℝ :=
  fun x y => a (Quotient.mk (MulAction.orbitRel G (X × X)) (x, y))

/-- Invariance says exactly that the kernel is constant on every orbit on pairs. -/
theorem invariant_constant_on_pair_orbits (C : Matrix X X ℝ)
    (hC : KernelInvariant (G := G) C) (g : G) (x y : X) :
    C (g • x) (g • y) = C x y := by
  exact hC g x y

/-
Every invariant matrix is the realization of orbit coefficients.
-/
theorem invariant_eq_orbitMatrix (C : Matrix X X ℝ) (hC : KernelInvariant (G := G) C) :
    ∃ a : OrbitAlgebra (G := G) (X := X), orbitMatrix a = C := by
  refine ⟨ ?_, funext fun x => funext fun y => ?_ ⟩;
  refine' fun o => Quotient.liftOn' o ( fun p => C p.1 p.2 ) fun p q h => _;
  obtain ⟨ g, rfl ⟩ := h
  exact invariant_constant_on_pair_orbits C hC g q.1 q.2;
  unfold orbitMatrix; aesop;

/-
The orbit algebra has dimension equal to the number of orbits on `X × X`.
-/
theorem orbitAlgebra_finrank :
    Module.finrank ℝ (OrbitAlgebra (G := G) (X := X)) =
      Fintype.card (PairOrbit (G := G) (X := X)) := by
  convert ( Module.finrank_eq_card_basis ( Pi.basisFun ℝ ( PairOrbit ( G := G ) ( X := X ) ) ) ) using 1

/-- The action on column vectors, by precomposition with the inverse permutation. -/
def actVec (g : G) (f : X → ℝ) : X → ℝ := fun x => f (g⁻¹ • x)

/-
An invariant matrix commutes with the permutation representation.
-/
theorem mulVec_actVec (C : Matrix X X ℝ) (hC : KernelInvariant (G := G) C)
    (g : G) (f : X → ℝ) :
    C.mulVec (actVec (G := G) g f) = actVec (G := G) g (C.mulVec f) := by
  ext x;
  simp +decide only [Matrix.mulVec, dotProduct, actVec];
  conv_rhs => rw [ ← Equiv.sum_comp ( Equiv.ofBijective ( fun y => g⁻¹ • y ) ⟨ fun y => by aesop, fun y => ⟨ g • y, by aesop ⟩ ⟩ ) ] ; simp +decide [ hC g⁻¹ ] ;

/-- The quadratic variance associated to a covariance matrix. -/
def variance (C : Matrix X X ℝ) (f : X → ℝ) : ℝ :=
  dotProduct f (C.mulVec f)

/-
Invariance makes variance constant on the entire group orbit of a mode.
-/
theorem variance_actVec (C : Matrix X X ℝ) (hC : KernelInvariant (G := G) C)
    (g : G) (f : X → ℝ) :
    variance C (actVec (G := G) g f) = variance C f := by
  convert congr_arg ( fun x => dotProduct ( fun x => f ( g⁻¹ • x ) ) x ) ( mulVec_actVec C hC g f ) using 1;
  simp +decide [ variance, dotProduct, actVec ];
  rw [ ← Equiv.sum_comp ( Equiv.ofBijective ( fun x => g⁻¹ • x ) ⟨ fun x y hxy => by simpa using hxy, fun x => ⟨ g • x, by simp +decide ⟩ ⟩ ) ] ; simp +decide [ Matrix.mulVec, dotProduct ]

/-
On a transitive finite action, every invariant matrix has constant row sum.
-/
theorem rowSum_constant [MulAction.IsPretransitive G X]
    (C : Matrix X X ℝ) (hC : KernelInvariant (G := G) C) (x y : X) :
    ∑ z : X, C x z = ∑ z : X, C y z := by
  obtain ⟨ g, hg ⟩ := MulAction.exists_smul_eq G x y; simp +decide [ ← hg, hC g ] ;
  convert ( Equiv.sum_comp ( Equiv.ofBijective ( fun z => g • z ) ⟨ fun a b h => by simpa using h, fun a => ⟨ g⁻¹ • a, by simp +decide ⟩ ⟩ ) fun z => C x z ) using 1 ; simp +decide [ ← hg ];
  · conv_lhs => rw [ ← Equiv.sum_comp ( Equiv.ofBijective ( fun z => g • z ) ⟨ fun a b h => by simpa using h, fun a => ⟨ g⁻¹ • a, by simp +decide ⟩ ⟩ ) ] ; simp +decide [ ← hg ] ;
  · have h_sum : ∑ z, C (g • x) (g • z) = ∑ z, C x z := by
      exact Finset.sum_congr rfl fun _ _ => hC g _ _;
    rw [ ← h_sum, ← Equiv.sum_comp ( Equiv.ofBijective ( fun z => g • z ) ⟨ fun a b h => by simpa using h, fun a => ⟨ g⁻¹ • a, by simp +decide ⟩ ⟩ ) ] ; simp +decide [ hg ]

/-
Thus the all-ones (grand-total) mode is an eigenvector.
-/
theorem one_eigenvector [MulAction.IsPretransitive G X]
    (C : Matrix X X ℝ) (hC : KernelInvariant (G := G) C) (x₀ : X) :
    C.mulVec (fun _ => (1 : ℝ)) =
      (∑ z : X, C x₀ z) • (fun _ => (1 : ℝ)) := by
  ext x;
  convert rowSum_constant C hC x x₀ using 1;
  · simp +decide [ Matrix.mulVec, dotProduct ];
  · simp +decide

/-- The zero-sum space, i.e. the complement of the invariant grand-total mode. -/
def ZeroSum : Submodule ℝ (X → ℝ) where
  carrier := {f | ∑ x : X, f x = 0}
  zero_mem' := by simp
  add_mem' := by
    intro a b ha hb
    change (∑ x, (a x + b x)) = 0
    rw [Finset.sum_add_distrib, ha, hb, add_zero]
  smul_mem' := by
    intro c f hf
    change (∑ x, c * f x) = 0
    rw [← Finset.mul_sum, hf, mul_zero]

/-
Symmetry converts constant row sums into constant column sums.
-/
theorem columnSum_constant [MulAction.IsPretransitive G X]
    (C : Matrix X X ℝ) (hInv : KernelInvariant (G := G) C)
    (hSymm : C.IsSymm) (x y : X) :
    ∑ z : X, C z x = ∑ z : X, C z y := by
  convert rowSum_constant C hInv x y using 1;
  · exact Finset.sum_congr rfl fun _ _ => hSymm.apply _ _;
  · exact Finset.sum_congr rfl fun _ _ => hSymm.apply _ _ ▸ rfl

/-
For a symmetric invariant covariance on a transitive action, the zero-sum
(nontrivial) sector is preserved. Thus variance of a zero-sum mode is controlled by
the restriction of `C` to this sector.
-/
theorem mulVec_mem_zeroSum [MulAction.IsPretransitive G X]
    (C : Matrix X X ℝ) (hInv : KernelInvariant (G := G) C)
    (hSymm : C.IsSymm) {f : X → ℝ} (hf : f ∈ ZeroSum (X := X)) :
    C.mulVec f ∈ ZeroSum (X := X) := by
  by_cases hX : Nonempty X;
  · obtain ⟨x₀⟩ : ∃ x₀ : X, True := by
      exact ⟨ hX.some, trivial ⟩;
    -- By definition of `ZeroSum`, we need to show that $\sum_{x \in X} (C.mulVec f)(x) = 0$.
    have h_sum : ∑ x, (C.mulVec f) x = ∑ x, f x * ∑ y, C y x := by
      simp +decide only [Matrix.mulVec, dotProduct, Finset.mul_sum _ _ _];
      rw [ Finset.sum_comm ] ; congr ; ext ; congr ; ext ; rw [ hSymm.apply ] ; ring;
    -- By definition of `ZeroSum`, we need to show that $\sum_{x \in X} (C.mulVec f)(x) = 0$. Using the fact that $C$ is symmetric and invariant, we can simplify the expression.
    have h_simplified : ∑ x, f x * ∑ y, C y x = ∑ x, f x * ∑ y, C y x₀ := by
      exact Finset.sum_congr rfl fun x _ => by rw [ columnSum_constant C hInv hSymm x x₀ ] ;
    simp_all +decide [ ← Finset.sum_mul _ _ _, ZeroSum ];
  · simp_all +decide [ funext_iff, ZeroSum ]

/-
A group translate of a zero-sum mode is again zero-sum.
-/
theorem actVec_mem_zeroSum (g : G) {f : X → ℝ} (hf : f ∈ ZeroSum (X := X)) :
    actVec (G := G) g f ∈ ZeroSum (X := X) := by
  -- By definition of `actVec`, we know that `actVec g f` is in the zero-sum subspace.
  have h_actVec_zero_sum : ∑ x : X, (actVec g f) x = ∑ x : X, f x := by
    exact Equiv.sum_comp ( Equiv.ofBijective ( fun x => g⁻¹ • x ) ⟨ fun x y hxy => by simpa using hxy, fun x => ⟨ g • x, by simp +decide ⟩ ⟩ ) f;
  exact h_actVec_zero_sum.trans hf

/-
For a PSD matrix, zero quadratic variance puts the vector in the kernel.
-/
theorem mulVec_eq_zero_of_psd (C : Matrix X X ℝ) (hC : C.PosSemidef)
    (f : X → ℝ) (hf : variance C f = 0) :
    C.mulVec f = 0 := by
  exact (Matrix.PosSemidef.dotProduct_mulVec_zero_iff hC f).mp hf

/-
Suppression of one mode propagates to every translate, both as variance and as
an operator-kernel statement.  Hence it propagates to the group subrepresentation
spanned by that orbit (the precise general replacement for an irreducible/isotypic
block claim).
-/
theorem suppression_on_orbit (C : Matrix X X ℝ) (hInv : KernelInvariant (G := G) C)
    (hPSD : C.PosSemidef) (f : X → ℝ) (hf : variance C f = 0) (g : G) :
    variance C (actVec (G := G) g f) = 0 ∧ C.mulVec (actVec (G := G) g f) = 0 := by
  refine' ⟨ _, _ ⟩;
  · rw [ ← hf, variance_actVec C hInv g f ];
  · convert mulVec_eq_zero_of_psd C hPSD ( actVec g f ) _;
    rw [ variance_actVec C hInv g f, hf ]

/-
Every vector in the linear span of the orbit of a suppressed mode is killed.
-/
theorem suppression_on_orbit_span (C : Matrix X X ℝ) (hInv : KernelInvariant (G := G) C)
    (hPSD : C.PosSemidef) (f v : X → ℝ) (hf : variance C f = 0)
    (hv : v ∈ Submodule.span ℝ (Set.range (fun g : G => actVec (G := G) g f))) :
    C.mulVec v = 0 := by
  refine' Submodule.span_induction _ _ _ _ hv;
  · rintro _ ⟨ g, rfl ⟩ ; exact mulVec_eq_zero_of_psd C hPSD _ ( by rw [ variance_actVec C hInv g f, hf ] ) ;
  · simp +decide;
  · simp +contextual [ Matrix.mulVec_add ];
  · simp +contextual [ Matrix.mulVec_smul ]

section Witness

abbrev W := Fin 3
abbrev WG := Equiv.Perm W

/-- The all-ones covariance. -/
def invariantWitness : Matrix W W ℝ := fun _ _ => 1

/-- A regional zero-sum mode. -/
def regional : W → ℝ := ![1, -1, 0]

/-- Another translate of the regional mode. -/
def regional' : W → ℝ := ![1, 0, -1]

/-- A rank-one, deliberately frame-selective covariance. -/
def selectiveWitness : Matrix W W ℝ :=
  fun i j => (![1, 1, -2] : W → ℝ) i * (![1, 1, -2] : W → ℝ) j

/-
The invariant witness is PSD, suppresses the whole zero-sum block, and is
invariant under the full permutation action.
-/
theorem invariantWitness_properties :
    KernelInvariant (G := WG) invariantWitness ∧ invariantWitness.PosSemidef ∧
      (∀ f : W → ℝ, f ∈ ZeroSum (X := W) → invariantWitness.mulVec f = 0) := by
  constructor;
  · exact fun _ _ _ => rfl;
  · constructor;
    · constructor;
      · ext i j; simp +decide [ invariantWitness ] ;
      · norm_num [ Finsupp.sum_fintype, invariantWitness ];
        intro x; simp +decide only [← Finset.mul_sum _ _ _, ← Finset.sum_mul] ; exact mul_self_nonneg _;
    · unfold invariantWitness ZeroSum;
      simp +decide [ funext_iff, Matrix.mulVec, dotProduct ]

/-
The selective rank-one witness is PSD and suppresses exactly the line generated
by `regional` inside the two-dimensional zero-sum space.
-/
theorem selectiveWitness_kernel_on_zeroSum (f : W → ℝ)
    (hf : f ∈ ZeroSum (X := W)) :
    selectiveWitness.mulVec f = 0 ↔ ∃ a : ℝ, f = a • regional := by
  unfold ZeroSum at hf;
  simp_all +decide [ funext_iff, Fin.forall_fin_succ, Matrix.mulVec, dotProduct ];
  simp_all +decide [ Fin.sum_univ_three, selectiveWitness, regional ];
  constructor <;> intro h <;> constructor <;> linarith

/-
Selective suppression occurs, but a permutation translate is not suppressed;
therefore this covariance is not invariant.
-/
theorem selectiveWitness_sharp :
    selectiveWitness.PosSemidef ∧
    variance selectiveWitness regional = 0 ∧
    variance selectiveWitness regional' ≠ 0 ∧
    ¬ KernelInvariant (G := WG) selectiveWitness := by
  refine' ⟨ _, _, _, _ ⟩ <;> norm_num [ selectiveWitness, regional, regional', variance ];
  · constructor;
    · ext i j; simp +decide [ selectiveWitness ] ; ring;
    · intro x
      simp [selectiveWitness];
      simp +decide [ Finsupp.sum_fintype, Fin.sum_univ_three ];
      nlinarith [ sq_nonneg ( x 0 + x 1 - 2 * x 2 ) ];
  · unfold selectiveWitness; norm_num [ Matrix.vecHead, Matrix.vecTail, Matrix.mulVec ] ;
  · norm_num [ Matrix.vecHead, Matrix.vecTail, Matrix.mulVec, selectiveWitness ];
    erw [ Matrix.cons_val_succ' ] ; norm_num;
  · unfold KernelInvariant; norm_num [ selectiveWitness ] ;
    refine' ⟨ Equiv.swap 0 2, 0, 0, _ ⟩ ; norm_num;
    erw [ Matrix.cons_val_succ' ] ; norm_num

end Witness

end FrameBlindness
