import Mathlib

open scoped BigOperators
open scoped Classical

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000

/-!
# Goal III / Suite B — the full 4-channel RG: is soldering `E` an RG coordinate?

This file completes `Goal3ChannelRG` by adding the **fourth channel**, *soldering* `E`
(the geometric / E-slot coupling), to the exact rational decimation of the null-edge
chain.

## Model (all rational, concrete `2×2` blocks, no `Complex`)

We work in the real matrix algebra generated by

* `I` (identity),
* `J = !![0,-1;1,0]` with `J² = -I` (chiral turn), and
* `S = !![1,0;0,-1]` (the soldering / grading matrix, `S² = I`).

The **on-site block** is `A = lam·I + E·S` and the **coupling block** is
`B = kap·I + tau·J` (with conjugate `B̄ = kap·I - tau·J`).  A two-site Schur
complement decimates a middle site of on-site `H = lam·I + E·S`, whose inverse is
`H⁻¹ = (1/d)·(lam·I - E·S)` with `d = lam² - E²`.

The decimation rules are

* new on-site  `A' = A - (1/d)·(B·(lam I - E S)·B̄ + B̄·(lam I - E S)·B)`,
* new coupling `B' = -(1/d)·(B·(lam I - E S)·B)`.

The two ring identities `onsite_numerator` and `coupling_numerator` below are proved on
concrete rational `2×2` matrices.  Reading off the `I`/`S` components of `A'` and the
`I`/`J` components of `B'` gives the closed rational four-coupling map `R4`.  (The on-site
block closes exactly in `span{I,S}`; the coupling block acquires a small soldering
admixture `-E(kap²+tau²)/d · S` which vanishes on the invariant subspace `E = 0` and is
not retained among the four physical couplings.)

## Results

* `R4_closed_form` — the closed rational map and its reduction `R4(·,·,·,0) = (R3, 0)`.
* `critical_jacobian` — the exact `4×4` Jacobian `DR4` at the critical point
  `(1,1,0,0)` on the period-2 invariant line, every entry proved as the
  corresponding partial derivative via `HasDerivAt`.
* `rg_charpoly` / `rg_eigenvalues` — the characteristic quartic
  `(x-2)(x+1)(x+2)(x-3)` and its four roots `{2, -1, -2, 3}`.
* `soldering_verdict` — the soldering eigendirection has eigenvalue `r = 3`, hence
  `|r| > 1`: soldering is **RELEVANT**.  All four channels are RG coordinates.
-/

namespace Goal3ChannelRG4

/-! ## Concrete rational blocks and the Schur-complement grounding identities -/

/-- Soldering / grading matrix `S = diag(1,-1)`. -/
def Sm : Matrix (Fin 2) (Fin 2) ℝ := !![1, 0; 0, -1]

/-- Chiral-turn matrix `J`, with `J² = -I`. -/
def Jm : Matrix (Fin 2) (Fin 2) ℝ := !![0, -1; 1, 0]

/-- Coupling block `B = kap·I + tau·J`. -/
def Bm (kap tau : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  kap • (1 : Matrix (Fin 2) (Fin 2) ℝ) + tau • Jm

/-- Conjugate coupling block `B̄ = kap·I - tau·J`. -/
def Bbarm (kap tau : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  kap • (1 : Matrix (Fin 2) (Fin 2) ℝ) - tau • Jm

/-- Numerator of `H⁻¹`, i.e. `d·H⁻¹ = lam·I - E·S` with `d = lam² - E²`. -/
def Hinvnum (lam E : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  lam • (1 : Matrix (Fin 2) (Fin 2) ℝ) - E • Sm

/-- `J² = -I`. -/
lemma Jm_sq : Jm * Jm = - (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [Jm, Matrix.mul_apply, Fin.sum_univ_two]

/-- `S² = I`. -/
lemma Sm_sq : Sm * Sm = (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [Sm, Matrix.mul_apply, Fin.sum_univ_two]

/-
**Coupling numerator.**  `B·(lam I - E S)·B = lam(kap²-tau²)·I + 2 lam kap tau·J
    - E(kap²+tau²)·S`.  The `I`- and `J`-components define `kap'` and `tau'`; the
    `S`-component is the (truncated) soldering admixture of the coupling.
-/
lemma coupling_numerator (lam kap tau E : ℝ) :
    Bm kap tau * Hinvnum lam E * Bm kap tau
      = (lam * (kap ^ 2 - tau ^ 2)) • (1 : Matrix (Fin 2) (Fin 2) ℝ)
        + (2 * lam * kap * tau) • Jm
        - (E * (kap ^ 2 + tau ^ 2)) • Sm := by
  ext i j;
  fin_cases i <;> fin_cases j <;> simp +decide [ Bm, Hinvnum, Jm, Sm, Matrix.mul_apply ] <;> ring

/-
**On-site numerator.**  `B·(lam I - E S)·B̄ + B̄·(lam I - E S)·B
    = 2 lam(kap²+tau²)·I - 2 E(kap²-tau²)·S`.  Its `I`/`S`-components define `lam'`/`E'`;
    the on-site block closes exactly in `span{I,S}`.
-/
lemma onsite_numerator (lam kap tau E : ℝ) :
    Bm kap tau * Hinvnum lam E * Bbarm kap tau
        + Bbarm kap tau * Hinvnum lam E * Bm kap tau
      = (2 * lam * (kap ^ 2 + tau ^ 2)) • (1 : Matrix (Fin 2) (Fin 2) ℝ)
        - (2 * E * (kap ^ 2 - tau ^ 2)) • Sm := by
  unfold Bm Bbarm Hinvnum Sm Jm;
  ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.add_apply, Matrix.sub_apply, Matrix.smul_apply ] <;> ring

/-! ## The three- and four-channel decimation maps -/

/-- The landed three-coupling decimation (aperture `lam`, closure `kap`, chiral turn
    `tau`): the free-Dirac chiral square `z' = -z²/lam` for `z = kap + i·tau`. -/
noncomputable def R3 (lam kap tau : ℝ) : ℝ × ℝ × ℝ :=
  (lam - 2 * (kap ^ 2 + tau ^ 2) / lam,
   -(kap ^ 2 - tau ^ 2) / lam,
   -2 * kap * tau / lam)

/-- The exact rational **four-coupling** decimation obtained from the two-site Schur
    complement above, with `d = lam² - E²`.  The soldering channel `E` enters through the
    on-site inverse. -/
noncomputable def R4 (lam kap tau E : ℝ) : ℝ × ℝ × ℝ × ℝ :=
  (lam - 2 * lam * (kap ^ 2 + tau ^ 2) / (lam ^ 2 - E ^ 2),
   -lam * (kap ^ 2 - tau ^ 2) / (lam ^ 2 - E ^ 2),
   -2 * lam * kap * tau / (lam ^ 2 - E ^ 2),
   E + 2 * E * (kap ^ 2 - tau ^ 2) / (lam ^ 2 - E ^ 2))

/-! ## Target 1 — closed form and the soldering-free invariant subspace -/

/-
**`R4_closed_form`.**  On the soldering-free subspace `E = 0` the four-coupling map
    reduces to `R3` with `E' = 0`: the subspace `E = 0` is invariant.
-/
theorem R4_closed_form (lam kap tau : ℝ) (hlam : lam ≠ 0) :
    R4 lam kap tau 0
      = ((R3 lam kap tau).1, (R3 lam kap tau).2.1, (R3 lam kap tau).2.2, 0) := by
  unfold R4 R3;
  grind

/-! ## Target 2 — the exact `4×4` critical Jacobian, entry by entry -/

/-- The exact `4×4` Jacobian `DR4` of `R4` at the critical point `(1,1,0,0)`
on the period-2 invariant line. Rows/columns are ordered `(lam, kap, tau, E)`. -/
def DR4 : Matrix (Fin 4) (Fin 4) ℝ :=
  !![3, -4, 0, 0;
     1, -2, 0, 0;
     0,  0, -2, 0;
     0,  0, 0, 3]

/-
**`critical_jacobian`.**  Every entry of `DR4` is the corresponding partial derivative
    of `R4` at `(1,1,0,0)`, proved column by column via `HasDerivAt`.
-/
theorem critical_jacobian :
    -- column `lam`
    (HasDerivAt (fun l => (R4 l 1 0 0).1) 3 1) ∧
    (HasDerivAt (fun l => (R4 l 1 0 0).2.1) 1 1) ∧
    (HasDerivAt (fun l => (R4 l 1 0 0).2.2.1) 0 1) ∧
    (HasDerivAt (fun l => (R4 l 1 0 0).2.2.2) 0 1) ∧
    -- column `kap`
    (HasDerivAt (fun k => (R4 1 k 0 0).1) (-4) 1) ∧
    (HasDerivAt (fun k => (R4 1 k 0 0).2.1) (-2) 1) ∧
    (HasDerivAt (fun k => (R4 1 k 0 0).2.2.1) 0 1) ∧
    (HasDerivAt (fun k => (R4 1 k 0 0).2.2.2) 0 1) ∧
    -- column `tau`
    (HasDerivAt (fun t => (R4 1 1 t 0).1) 0 0) ∧
    (HasDerivAt (fun t => (R4 1 1 t 0).2.1) 0 0) ∧
    (HasDerivAt (fun t => (R4 1 1 t 0).2.2.1) (-2) 0) ∧
    (HasDerivAt (fun t => (R4 1 1 t 0).2.2.2) 0 0) ∧
    -- column `E`
    (HasDerivAt (fun e => (R4 1 1 0 e).1) 0 0) ∧
    (HasDerivAt (fun e => (R4 1 1 0 e).2.1) 0 0) ∧
    (HasDerivAt (fun e => (R4 1 1 0 e).2.2.1) 0 0) ∧
    (HasDerivAt (fun e => (R4 1 1 0 e).2.2.2) 3 0) := by
  refine' ⟨ _, _, _, _, _ ⟩;
  · convert HasDerivAt.sub ( hasDerivAt_id ( 1 : ℝ ) ) ( HasDerivAt.div ( HasDerivAt.mul ( HasDerivAt.const_mul 2 ( hasDerivAt_id ( 1 : ℝ ) ) ) ( hasDerivAt_const _ _ ) ) ( HasDerivAt.sub ( hasDerivAt_pow 2 ( 1 : ℝ ) ) ( hasDerivAt_const _ _ ) ) _ ) using 1 <;> norm_num;
  · unfold R4; norm_num;
    convert HasDerivAt.div ( hasDerivAt_neg ( 1 : ℝ ) ) ( hasDerivAt_pow 2 ( 1 : ℝ ) ) _ using 1 <;> norm_num;
  · unfold R4; norm_num [ hasDerivAt_const ] ;
  · unfold R4; norm_num [ hasDerivAt_const ] ;
  · unfold R4; norm_num;
    refine' ⟨ _, _, _, _, _, _ ⟩;
    convert HasDerivAt.const_sub _ ( HasDerivAt.const_mul _ ( hasDerivAt_pow 2 ( 1 : ℝ ) ) ) using 1 ; norm_num;
    · convert HasDerivAt.neg ( hasDerivAt_pow 2 ( 1 : ℝ ) ) using 1 ; norm_num;
    · exact hasDerivAt_const _ _;
    · convert HasDerivAt.sub ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( HasDerivAt.add ( hasDerivAt_const _ _ ) ( hasDerivAt_pow 2 ( 0 : ℝ ) ) ) ) using 1 ; norm_num;
    · simpa using hasDerivAt_pow 2 ( 0 : ℝ );
    · refine' ⟨ _, _, _, _, _ ⟩;
      · convert HasDerivAt.neg ( HasDerivAt.const_mul 2 ( hasDerivAt_id ( 0 : ℝ ) ) ) using 1 ; norm_num;
      · exact hasDerivAt_const _ _;
      · convert HasDerivAt.const_sub _ ( HasDerivAt.const_mul _ ( HasDerivAt.inv ( HasDerivAt.const_sub _ ( hasDerivAt_pow 2 ( 0 : ℝ ) ) ) _ ) ) using 1 <;> norm_num;
      · convert HasDerivAt.div ( hasDerivAt_const _ _ ) ( HasDerivAt.sub ( hasDerivAt_const _ _ ) ( hasDerivAt_pow 2 ( 0 : ℝ ) ) ) _ using 1 <;> norm_num;
      · exact ⟨ hasDerivAt_const _ _, by convert HasDerivAt.add ( hasDerivAt_id ( 0 : ℝ ) ) ( HasDerivAt.div ( HasDerivAt.const_mul 2 ( hasDerivAt_id ( 0 : ℝ ) ) ) ( HasDerivAt.const_sub 1 ( hasDerivAt_pow 2 ( 0 : ℝ ) ) ) _ ) using 1 <;> norm_num ⟩

/-! ## Target 3 — the characteristic quartic and its roots -/

/-- **`rg_charpoly`.**  The characteristic polynomial of `DR4` factors as the rational
    quartic `(x-2)(x+1)(x+2)(x-3)`. -/
theorem rg_charpoly (x : ℝ) :
    (x • (1 : Matrix (Fin 4) (Fin 4) ℝ) - DR4).det
      = (x - 2) * (x + 1) * (x + 2) * (x - 3) := by
  norm_num [DR4, Matrix.det_succ_row_zero]
  simp +decide [Fin.sum_univ_succ, Fin.succAbove, Matrix.one_apply]
  ring

/-- **`rg_eigenvalues`.**  The roots of the characteristic quartic are exactly
    `{2, -1, -2, 3}`.  The first three reproduce the three-channel spectrum `{2, -1, -2}`;
    the fourth, `r = 3`, is the soldering eigenvalue. -/
theorem rg_eigenvalues (x : ℝ) :
    (x - 2) * (x + 1) * (x + 2) * (x - 3) = 0
      ↔ x = 2 ∨ x = -1 ∨ x = -2 ∨ x = 3 := by
  grind

/-! ## Target 4 — the soldering verdict -/

/-- RG classification of an eigendirection by the modulus of its eigenvalue. -/
inductive RGClass
  | relevant
  | marginal
  | irrelevant
  deriving DecidableEq

/-- Classify an eigenvalue: `|r|>1` relevant, `|r|=1` marginal, `|r|<1` irrelevant. -/
noncomputable def classify (r : ℝ) : RGClass :=
  if 1 < |r| then RGClass.relevant
  else if |r| = 1 then RGClass.marginal
  else RGClass.irrelevant

/-- The soldering eigenvalue. -/
def solderingEigenvalue : ℝ := 3

/-- **`soldering_verdict`.**  The soldering eigenvalue is `r = 3`, so `|r| > 1`: the
    soldering channel is a **RELEVANT** RG coordinate.  Hence all four channels
    (aperture, closure, chiral turn, soldering) are genuine RG coordinates. -/
theorem soldering_verdict :
    classify solderingEigenvalue = RGClass.relevant ∧ 1 < |solderingEigenvalue| := by
  norm_num [ classify, solderingEigenvalue ]

/-! ## Kernel-checked axiom footprint of every headline theorem -/

/-- info: 'Goal3ChannelRG4.R4_closed_form' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms R4_closed_form

/-- info: 'Goal3ChannelRG4.critical_jacobian' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms critical_jacobian

/-- info: 'Goal3ChannelRG4.rg_charpoly' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rg_charpoly

/-- info: 'Goal3ChannelRG4.rg_eigenvalues' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rg_eigenvalues

/-- info: 'Goal3ChannelRG4.soldering_verdict' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms soldering_verdict

end Goal3ChannelRG4
