import PhysicsSM.Draft.NullEdge.Carrier.WeitzenbockQC_Torus
import PhysicsSM.Draft.NullEdge.CurvatureConvergenceInterface
import PhysicsSM.Draft.NullEdge.NonabelianHistoryClosureHolonomy

/-!
# Constructed graph-plaquette curvature limit

This draft module supplies a concrete finite-lattice witness for the G4
connection/curvature rung of the null-edge reconstruction program.

There are two related constructions:

* For arbitrary real `2 x 2` generators `A` and `B`, the difference between
  the two ordered near-identity transports across a plaquette is exactly
  `h^2 [A,B]`.  This coefficient is realized in the existing decorated
  `ZMod 2 x ZMod 2` torus connection API and in its covariant-difference
  commutator.
* For explicit upper and lower nilpotent generators, the affine links have
  exact matrix inverses.  Transport around the genuine closed square
  `0 -> 1 -> 2 -> 3 -> 0` is therefore group-valued.  Its exact expansion is
  identity plus plaquette area times a nonzero, orientation-selected
  commutator and a residual that converges componentwise to zero.

The additive path difference is normalized about zero.  The genuine loop
holonomy is normalized about the identity.  Both use the componentwise norm
topology inherited from the nested finite function space.

## Scope boundary

This is a fixed, decorated finite torus with a chosen refinement parameter and
chosen matrix generators.  It does not derive transports, plaquette areas, or
refinement maps from a bare graph.  It also does not identify arbitrary matrix
coefficients with a continuum Riemann tensor, establish derivative
convergence, recover the Riemann symmetries, or derive Einstein dynamics.

Provenance: clean-room finite lattice algebra, reusing the project torus
connection and history-holonomy APIs.  Claim grade: `M [orig]`.
-/

open Filter Topology Matrix

noncomputable section

namespace PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit

open PhysicsSM.Draft.NullEdge.Carrier
open PhysicsSM.Draft.NullEdge.CurvatureConvergenceInterface
open PhysicsSM.Draft.NullEdge.NonabelianHistoryClosureHolonomy

abbrev Vec2 := Fin 2 -> Real
abbrev Mat2 := Matrix (Fin 2) (Fin 2) Real
abbrev End2 := Vec2 →ₗ[Real] Vec2

local instance : NormedAddCommGroup Mat2 :=
  inferInstanceAs (NormedAddCommGroup (Fin 2 -> Fin 2 -> Real))

local instance : NormedSpace Real Mat2 :=
  inferInstanceAs (NormedSpace Real (Fin 2 -> Fin 2 -> Real))

/-! ## Exact matrix plaquette coefficient -/

/-- Matrix commutator used as the plaquette curvature coefficient. -/
def matrixCommutator (A B : Mat2) : Mat2 := A * B - B * A

/-- Constant near-identity link generated by `A` at mesh scale `h`. -/
def affineLink (h : Real) (A : Mat2) : Mat2 := 1 + h • A

/-- Difference of the two ordered two-edge transports across one plaquette. -/
def matrixPlaquettePathDifference (h : Real) (A B : Mat2) : Mat2 :=
  affineLink h A * affineLink h B - affineLink h B * affineLink h A

/-- The order-zero and order-one terms cancel, leaving exactly `h^2 [A,B]`. -/
theorem matrixPlaquettePathDifference_exact (h : Real) (A B : Mat2) :
    matrixPlaquettePathDifference h A B = h ^ 2 • matrixCommutator A B := by
  ext i j
  fin_cases i <;> fin_cases j
  all_goals
    simp [matrixPlaquettePathDifference, affineLink, matrixCommutator,
      Matrix.mul_apply, Fin.sum_univ_two, pow_two]
  all_goals ring

/-! ## Realization in the existing gauge-torus API -/

/-- Constant direction-dependent links on the finite gauge torus. -/
def torusAffineTransport (h : Real) (A B : Mat2) :
    Fin 2 -> Torus.Site -> End2 :=
  fun a _ =>
    if a = 0 then Matrix.toLin' (affineLink h A)
    else Matrix.toLin' (affineLink h B)

/-- The torus plaquette curvature is the linear-map realization of the matrix
path difference. -/
theorem torusPlaquetteCurvature_eq_toLin
    (h : Real) (A B : Mat2) (x : Torus.Site) :
    Torus.plaquetteCurvature (torusAffineTransport h A B) 0 1 x =
      Matrix.toLin' (matrixPlaquettePathDifference h A B) := by
  simp only [Torus.plaquetteCurvature, torusAffineTransport, if_pos,
    one_ne_zero, if_false]
  rw [← Matrix.toLin'_mul, ← Matrix.toLin'_mul, ← map_sub]
  rfl

/-- The concrete torus plaquette has coefficient `h^2 [A,B]` at every site. -/
theorem torusPlaquetteCurvature_exact
    (h : Real) (A B : Mat2) (x : Torus.Site) :
    Torus.plaquetteCurvature (torusAffineTransport h A B) 0 1 x =
      Matrix.toLin' (h ^ 2 • matrixCommutator A B) := by
  rw [torusPlaquetteCurvature_eq_toLin, matrixPlaquettePathDifference_exact]

/-- The covariant-difference commutator contains the same explicit scaled
matrix commutator as its plaquette coefficient. -/
theorem torusNablaCommutator_exact (h : Real) (A B : Mat2) :
    (Torus.nabla (torusAffineTransport h A B) 0).comp
          (Torus.nabla (torusAffineTransport h A B) 1) -
        (Torus.nabla (torusAffineTransport h A B) 1).comp
          (Torus.nabla (torusAffineTransport h A B) 0) =
      (Torus.gaugeLM
          (fun _ => Matrix.toLin' (h ^ 2 • matrixCommutator A B))).comp
        ((Torus.shiftLM 0).comp (Torus.shiftLM 1)) := by
  rw [Torus.nabla_commutator_path_difference]
  have hcurv :
      Torus.plaquetteCurvature (torusAffineTransport h A B) 0 1 =
        fun _ => Matrix.toLin' (h ^ 2 • matrixCommutator A B) := by
    funext x
    exact torusPlaquetteCurvature_exact h A B x
  rw [hcurv]

/-! ## A shrinking refinement family with zero residual -/

/-- Positive mesh spacing `1 / (n + 1)`. -/
def mesh (n : Nat) : Real := 1 / ((n : Real) + 1)

/-- Plaquette area associated with the mesh. -/
def plaquetteArea (n : Nat) : Real := mesh n ^ 2

/-- Matrix plaquette path difference at refinement level `n`. -/
def matrixPlaquetteSequence (A B : Mat2) (n : Nat) : Mat2 :=
  matrixPlaquettePathDifference (mesh n) A B

/-- Mesh spacing tends to zero. -/
theorem mesh_tendsto_zero : Tendsto mesh atTop (nhds 0) := by
  change Tendsto (fun n : Nat => (1 : Real) / ((n : Real) + 1))
    atTop (nhds 0)
  exact tendsto_one_div_add_atTop_nhds_zero_nat

/-- The positive plaquette areas shrink to zero. -/
theorem plaquetteArea_tendsto_zero : Tendsto plaquetteArea atTop (nhds 0) := by
  simpa [plaquetteArea] using mesh_tendsto_zero.pow 2

/-- Every plaquette area in the refinement family is strictly positive. -/
theorem plaquetteArea_pos (n : Nat) : 0 < plaquetteArea n := by
  unfold plaquetteArea mesh
  positivity

/-- The refinement sequence has an exact area-times-curvature expansion. -/
theorem matrixPlaquetteSequence_exact (A B : Mat2) (n : Nat) :
    matrixPlaquetteSequence A B n =
      plaquetteArea n • matrixCommutator A B := by
  unfold matrixPlaquetteSequence plaquetteArea
  exact matrixPlaquettePathDifference_exact (mesh n) A B

/-- The constructed matrix plaquette family satisfies the abstract first-order
interface with identically zero residual. The base is zero because this is a
difference of two path transports, not a group-valued loop holonomy. -/
def matrixPlaquetteFirstOrderLimit (A B : Mat2) :
    FirstOrderHolonomyLimit plaquetteArea
      (matrixPlaquetteSequence A B) 0 (matrixCommutator A B) := by
  refine ⟨fun _ => 0, ?_, plaquetteArea_tendsto_zero, ?_, tendsto_const_nhds⟩
  · exact Filter.Eventually.of_forall fun n => (plaquetteArea_pos n).ne'
  · exact Filter.Eventually.of_forall fun n => by
      rw [matrixPlaquetteSequence_exact]
      simp

/-- Area normalization recovers the commutator exactly before taking a limit. -/
theorem normalizedMatrixPlaquette_eq (A B : Mat2) (n : Nat) :
    normalizedHolonomyCurvature plaquetteArea
        (matrixPlaquetteSequence A B) 0 n =
      matrixCommutator A B := by
  unfold normalizedHolonomyCurvature
  rw [matrixPlaquetteSequence_exact]
  simp [(plaquetteArea_pos n).ne', smul_smul]

/-- The graph plaquette areas shrink and normalized path differences converge
to the constructed matrix commutator. -/
theorem normalizedMatrixPlaquette_tendsto (A B : Mat2) :
    Tendsto plaquetteArea atTop (nhds 0) ∧
      Tendsto
        (normalizedHolonomyCurvature plaquetteArea
          (matrixPlaquetteSequence A B) 0)
        atTop (nhds (matrixCommutator A B)) :=
  firstOrderHolonomyLimit_converges plaquetteArea
    (matrixPlaquetteSequence A B) 0 (matrixCommutator A B)
    (matrixPlaquetteFirstOrderLimit A B)

/-- The exact torus coefficient at every refinement level is the matrix
coefficient used by the normalized convergence theorem. -/
theorem torusPlaquetteRefinement_exact
    (A B : Mat2) (n : Nat) (x : Torus.Site) :
    Torus.plaquetteCurvature (torusAffineTransport (mesh n) A B) 0 1 x =
      Matrix.toLin' (plaquetteArea n • matrixCommutator A B) := by
  simpa [plaquetteArea] using torusPlaquetteCurvature_exact (mesh n) A B x

/-! ## Noncommuting nonzero witness -/

/-- Upper nilpotent generator. -/
def generatorA : Mat2 := !![0, 1; 0, 0]

/-- Lower nilpotent generator. -/
def generatorB : Mat2 := !![0, 0; 1, 0]

/-- Their commutator is the nonzero diagonal matrix `diag(1,-1)`. -/
theorem generator_commutator_value :
    matrixCommutator generatorA generatorB = !![1, 0; 0, -1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [matrixCommutator, generatorA, generatorB, Matrix.mul_apply,
      Fin.sum_univ_two]

/-- The target curvature coefficient is genuinely nonzero. -/
theorem generator_commutator_ne_zero :
    matrixCommutator generatorA generatorB ≠ 0 := by
  rw [generator_commutator_value]
  intro h
  have h00 := congrFun (congrFun h 0) 0
  norm_num at h00

/-! ## Genuine closed-loop group holonomy for the witness -/

/-- The upper-generator affine link, packaged with its exact reverse link. -/
def affineGeneratorAUnit (h : Real) : Mat2ˣ where
  val := affineLink h generatorA
  inv := affineLink (-h) generatorA
  val_inv := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [affineLink, generatorA, Matrix.mul_apply, Fin.sum_univ_two]
  inv_val := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [affineLink, generatorA, Matrix.mul_apply, Fin.sum_univ_two]

/-- The lower-generator affine link, packaged with its exact reverse link. -/
def affineGeneratorBUnit (h : Real) : Mat2ˣ where
  val := affineLink h generatorB
  inv := affineLink (-h) generatorB
  val_inv := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [affineLink, generatorB, Matrix.mul_apply, Fin.sum_univ_two]
  inv_val := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [affineLink, generatorB, Matrix.mul_apply, Fin.sum_univ_two]

/-- A square edge field with forward links generated by `A,B` and reverse
links given by their exact unit inverses. -/
def groupSquareEdgeField (h : Real) : EdgeField (Fin 4) Mat2ˣ :=
  fun x y =>
    if x = 0 ∧ y = 1 then affineGeneratorAUnit h
    else if x = 1 ∧ y = 2 then affineGeneratorBUnit h
    else if x = 2 ∧ y = 3 then (affineGeneratorAUnit h)⁻¹
    else if x = 3 ∧ y = 0 then (affineGeneratorBUnit h)⁻¹
    else 1

/-- Matrix value of transport around the oriented square `0,1,2,3,0`. -/
def groupSquareHolonomy (h : Real) : Mat2 :=
  ↑(transportFrom (groupSquareEdgeField h) (0 : Fin 4) [1, 2, 3, 0])

/-- Exact polynomial value of the closed square holonomy. -/
theorem groupSquareHolonomy_value (h : Real) :
    groupSquareHolonomy h =
      !![1 - h ^ 2, -h ^ 3; h ^ 3, 1 + h ^ 2 + h ^ 4] := by
  unfold groupSquareHolonomy
  simp only [transportFrom, groupSquareEdgeField, Units.val_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [affineGeneratorAUnit, affineGeneratorBUnit, Units.inv_mk,
      affineLink, generatorA, generatorB, Matrix.mul_apply,
      Fin.sum_univ_two] <;> ring

/-- Curvature coefficient selected by the closed-loop orientation. -/
def groupCurvatureTarget : Mat2 := -matrixCommutator generatorA generatorB

/-- Exact normalized residual in the group-valued holonomy expansion. -/
def groupHolonomyResidual (h : Real) : Mat2 := !![0, -h; h, h ^ 2]

/-- The genuine loop holonomy has an exact identity-plus-area expansion with
the displayed residual. -/
theorem groupSquareHolonomy_expansion (h : Real) :
    groupSquareHolonomy h =
      1 + h ^ 2 • (groupCurvatureTarget + groupHolonomyResidual h) := by
  rw [groupSquareHolonomy_value, groupCurvatureTarget,
    generator_commutator_value]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [groupHolonomyResidual] <;> ring

/-- Closed-loop holonomy at refinement level `n`. -/
def groupSquareHolonomySequence (n : Nat) : Mat2 := groupSquareHolonomy (mesh n)

/-- Normalized residual at refinement level `n`. -/
def groupHolonomyResidualSequence (n : Nat) : Mat2 :=
  groupHolonomyResidual (mesh n)

/-- Every component of the explicit group-holonomy residual tends to zero. -/
theorem groupHolonomyResidual_tendsto_zero :
    Tendsto groupHolonomyResidualSequence atTop (nhds 0) := by
  apply tendsto_pi_nhds.mpr
  intro i
  apply tendsto_pi_nhds.mpr
  intro j
  fin_cases i <;> fin_cases j
  · simp [groupHolonomyResidualSequence, groupHolonomyResidual]
  · simpa [groupHolonomyResidualSequence, groupHolonomyResidual] using
      mesh_tendsto_zero.neg
  · simpa [groupHolonomyResidualSequence, groupHolonomyResidual] using
      mesh_tendsto_zero
  · simpa [groupHolonomyResidualSequence, groupHolonomyResidual] using
      mesh_tendsto_zero.pow 2

/-- The actual closed-history holonomy satisfies the first-order interface at
base identity with the computed residual. -/
def groupSquareFirstOrderLimit :
    FirstOrderHolonomyLimit plaquetteArea groupSquareHolonomySequence 1
      groupCurvatureTarget := by
  refine ⟨groupHolonomyResidualSequence, ?_, plaquetteArea_tendsto_zero,
    ?_, groupHolonomyResidual_tendsto_zero⟩
  · exact Filter.Eventually.of_forall fun n => (plaquetteArea_pos n).ne'
  · exact Filter.Eventually.of_forall fun n => by
      simpa [groupSquareHolonomySequence, groupHolonomyResidualSequence,
        plaquetteArea] using groupSquareHolonomy_expansion (mesh n)

/-- **Genuine closed-loop curvature limit.** Area-normalized displacement of
the group-valued square holonomy from the identity converges to the nonzero
orientation-selected commutator coefficient. -/
theorem normalizedGroupSquareHolonomy_tendsto :
    Tendsto plaquetteArea atTop (nhds 0) ∧
      Tendsto
        (normalizedHolonomyCurvature plaquetteArea
          groupSquareHolonomySequence (1 : Mat2))
        atTop (nhds groupCurvatureTarget) :=
  firstOrderHolonomyLimit_converges plaquetteArea
    groupSquareHolonomySequence 1 groupCurvatureTarget
    groupSquareFirstOrderLimit

/-- The displayed history closes, its limiting curvature target is nonzero, and
its area-normalized group holonomy converges to that target. -/
theorem nonzero_group_holonomy_curvature_limit :
    finishFrom (0 : Fin 4) [1, 2, 3, 0] = 0 ∧
      groupCurvatureTarget ≠ 0 ∧
      Tendsto plaquetteArea atTop (nhds 0) ∧
      Tendsto
        (normalizedHolonomyCurvature plaquetteArea
          groupSquareHolonomySequence (1 : Mat2))
        atTop (nhds groupCurvatureTarget) := by
  refine ⟨rfl, ?_, normalizedGroupSquareHolonomy_tendsto⟩
  exact neg_ne_zero.mpr generator_commutator_ne_zero

/-- Nonvacuous decorated-torus connection-to-plaquette packet: a nonzero
coefficient, its exact appearance in every torus plaquette, shrinking positive
area, and normalized matrix convergence. -/
theorem nonzero_graph_plaquette_curvature_limit :
    matrixCommutator generatorA generatorB ≠ 0 ∧
      (∀ n x,
        Torus.plaquetteCurvature
            (torusAffineTransport (mesh n) generatorA generatorB) 0 1 x =
          Matrix.toLin'
            (plaquetteArea n • matrixCommutator generatorA generatorB)) ∧
      Tendsto plaquetteArea atTop (nhds 0) ∧
      Tendsto
        (normalizedHolonomyCurvature plaquetteArea
          (matrixPlaquetteSequence generatorA generatorB) 0)
        atTop (nhds (matrixCommutator generatorA generatorB)) := by
  refine ⟨generator_commutator_ne_zero, torusPlaquetteRefinement_exact _ _, ?_⟩
  exact normalizedMatrixPlaquette_tendsto generatorA generatorB

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.torusNablaCommutator_exact' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.torusNablaCommutator_exact

/-- info: 'PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.normalizedMatrixPlaquette_tendsto' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.normalizedMatrixPlaquette_tendsto

/-- info: 'PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.normalizedGroupSquareHolonomy_tendsto' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.normalizedGroupSquareHolonomy_tendsto

/-- info: 'PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.nonzero_group_holonomy_curvature_limit' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.nonzero_group_holonomy_curvature_limit

/-- info: 'PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.nonzero_graph_plaquette_curvature_limit' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit.nonzero_graph_plaquette_curvature_limit

end PhysicsSM.Draft.NullEdge.GraphPlaquetteCurvatureLimit
