import Mathlib

/-!
# Finite Higgs mass versus curvature-coupling identifiability

For the scalar equation convention

```text
(Box - bareMassSq - xi * R) h = source,
```

the local insertion profile is `bareMassSq + xi * R(x)`. This module proves
an exact finite identifiability boundary:

* on constant curvature, an affine shift of `bareMassSq` can be compensated by
  a shift of `xi`, leaving the local insertion matrix and every finite retarded
  series unchanged;
* equality of the effective profile at two distinct curvature values forces
  both parameters to agree.

Thus propagation on one constant-curvature control cannot separately identify
the radial mass and nonminimal curvature coupling. Curvature variation or an
independent parameter calibration is required.

This is finite algebra with supplied curvature, vertex measure, and retarded
kernel. It does not derive any of them, select `xi`, or prove a continuum
curved-space Higgs equation.

Provenance: project-internal identifiability algebra motivated by the curved-
space scalar equation and by Benincasa and Dowker, "The Scalar Curvature of a
Causal Set," arXiv:1001.2725. All six proof bodies were completed by Aristotle
task `d32bbee3-bcd2-4155-8937-8225b5d4602d` and replayed under the pinned
project toolchain without changing a public statement. Claim grade:
`M [orig/comp]`.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.HiggsCurvatureMassIdentifiability

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Effective local scalar mass-squared profile in the displayed sign
convention. -/
def effectiveLocalMassSq
    (bareMassSq xi : Real) (curvature : V -> Real) : V -> Real :=
  fun vertex => bareMassSq + xi * curvature vertex

/-- Vertex-measure-weighted diagonal effective mass insertion. -/
def effectiveMassMatrix
    (bareMassSq xi : Real) (curvature vertexMeasure : V -> Real) :
    Matrix V V Real :=
  Matrix.diagonal (fun vertex =>
    effectiveLocalMassSq bareMassSq xi curvature vertex *
      vertexMeasure vertex)

/-- Finite retarded series generated by a primitive kernel and local insertion
matrix. -/
def measuredMassRetardedSeries
    (K M : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  ∑ k ∈ Finset.range H, (-1 : Real) ^ k • ((K * M) ^ k * K)

omit [Fintype V] [DecidableEq V] in
/-- On constant curvature, the displayed affine parameter shift leaves the
effective local profile unchanged. -/
theorem constantCurvature_parameter_shift
    (bareMassSq xi curvatureValue delta : Real) :
    effectiveLocalMassSq (V := V)
        (bareMassSq + delta * curvatureValue) (xi - delta)
        (fun _ => curvatureValue) =
      effectiveLocalMassSq bareMassSq xi (fun _ => curvatureValue) := by
  ext
  unfold effectiveLocalMassSq
  ring

/-- Two distinct curvature values identify the bare mass and curvature
coupling separately. -/
theorem twoCurvatureValues_identify_parameters
    (bareMassSq xi bareMassSq' xi' curvatureX curvatureY : Real)
    (hX : bareMassSq + xi * curvatureX =
      bareMassSq' + xi' * curvatureX)
    (hY : bareMassSq + xi * curvatureY =
      bareMassSq' + xi' * curvatureY)
    (hCurvature : curvatureX ≠ curvatureY) :
    bareMassSq = bareMassSq' ∧ xi = xi' := by
  grind

omit [Fintype V] in
/-- Equal effective profiles give equal measured insertion matrices. -/
theorem effectiveMassMatrix_eq_of_profile_eq
    (bareMassSq xi bareMassSq' xi' : Real)
    (curvature vertexMeasure : V -> Real)
    (hProfile : effectiveLocalMassSq bareMassSq xi curvature =
      effectiveLocalMassSq bareMassSq' xi' curvature) :
    effectiveMassMatrix bareMassSq xi curvature vertexMeasure =
      effectiveMassMatrix bareMassSq' xi' curvature vertexMeasure := by
  exact Matrix.ext fun i j => by
    rw [effectiveMassMatrix, effectiveMassMatrix, Matrix.diagonal_apply,
      Matrix.diagonal_apply]
    aesop

/-- Equal effective profiles are indistinguishable by every finite measured
retarded series built from the same primitive kernel. -/
theorem measuredMassRetardedSeries_eq_of_profile_eq
    (K : Matrix V V Real) (H : Nat)
    (bareMassSq xi bareMassSq' xi' : Real)
    (curvature vertexMeasure : V -> Real)
    (hProfile : effectiveLocalMassSq bareMassSq xi curvature =
      effectiveLocalMassSq bareMassSq' xi' curvature) :
    measuredMassRetardedSeries K
        (effectiveMassMatrix bareMassSq xi curvature vertexMeasure) H =
      measuredMassRetardedSeries K
        (effectiveMassMatrix bareMassSq' xi' curvature vertexMeasure) H := by
  rw [effectiveMassMatrix_eq_of_profile_eq]
  simp_all +decide [funext_iff]

/-- Constant-curvature controls have a nontrivial affine parameter
degeneracy: for nonzero `delta`, the curvature coupling changes while the
insertion matrix and all finite retarded responses remain unchanged. -/
theorem constantCurvature_nontrivial_propagator_degeneracy
    (K : Matrix V V Real) (H : Nat)
    (bareMassSq xi curvatureValue delta : Real)
    (vertexMeasure : V -> Real) (hDelta : delta ≠ 0) :
    xi - delta ≠ xi ∧
      effectiveMassMatrix
          (bareMassSq + delta * curvatureValue) (xi - delta)
          (fun _ => curvatureValue) vertexMeasure =
        effectiveMassMatrix bareMassSq xi
          (fun _ => curvatureValue) vertexMeasure ∧
      measuredMassRetardedSeries K
          (effectiveMassMatrix
            (bareMassSq + delta * curvatureValue) (xi - delta)
            (fun _ => curvatureValue) vertexMeasure) H =
        measuredMassRetardedSeries K
          (effectiveMassMatrix bareMassSq xi
            (fun _ => curvatureValue) vertexMeasure) H := by
  grind +locals

omit [Fintype V] [DecidableEq V] in
/-- On one finite carrier, profile agreement at two vertices with distinct
curvature values forces equality of both parameters. -/
theorem twoVertices_identify_parameters
    (bareMassSq xi bareMassSq' xi' : Real)
    (curvature : V -> Real) (x y : V)
    (hProfileX : effectiveLocalMassSq bareMassSq xi curvature x =
      effectiveLocalMassSq bareMassSq' xi' curvature x)
    (hProfileY : effectiveLocalMassSq bareMassSq xi curvature y =
      effectiveLocalMassSq bareMassSq' xi' curvature y)
    (hCurvature : curvature x ≠ curvature y) :
    bareMassSq = bareMassSq' ∧ xi = xi' := by
  unfold effectiveLocalMassSq at *
  grind +qlia

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.HiggsCurvatureMassIdentifiability.constantCurvature_nontrivial_propagator_degeneracy' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms constantCurvature_nontrivial_propagator_degeneracy

/-- info: 'PhysicsSM.Draft.NullEdge.HiggsCurvatureMassIdentifiability.twoVertices_identify_parameters' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms twoVertices_identify_parameters

end PhysicsSM.Draft.NullEdge.HiggsCurvatureMassIdentifiability

end
