import PhysicsSM.Draft.NullEdge.FinitePeriodicLinkConnection
import PhysicsSM.Draft.NullEdge.LorentzBivectorLieAlgebraBridge

/-!
# Exact Lorentz plaquette tangent

This module supplies the nonlinear connection-variation bridge between the
group-valued periodic link substrate and the six-component Lorentz bivector
fiber. Links are invertible real `4 x 4` matrices. A six-component
right-trivialized variation is inserted by

`delta U = U hat(X)`,

where `hat` is the fixed mostly-minus Lorentz generator map. Applying the
formal product and inverse rules to an exact plaquette holonomy and translating
the result back to the identity gives a sum of four adjoint-transported link
generators. Eta-Lorentz links keep this tangent in the Lorentz Lie algebra. At
identity transport the result reduces exactly to the oriented additive
plaquette curl used by the linearized finite theory.

## Scope and provenance

These are exact finite matrix identities. The tangent is the algebraic
product/inverse response of the group-valued holonomy; this module does not
claim that the resulting right-logarithmic one-form has already been integrated
to a globally defined scalar action. Pairing this response with the corrected
complementary coframe face is the next Palatini step.

The plaquette architecture is inherited from
`FinitePeriodicLinkConnection`; the Lorentz generator convention is inherited
from `LorentzBivectorLieAlgebraBridge`. The four-corner tangent formula and its
Lean proof were prepared as a focused Aristotle task and reviewed against those
live definitions. Claim label: finite identity. Originality tag: `[comp]`.
-/

namespace PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent

open Matrix
open PhysicsSM.Draft.NullEdge.CarrierProbeRestrictedLorentzTransition
open PhysicsSM.Draft.NullEdge.FinitePeriodicCovariantLinkPalatiniVariation
open PhysicsSM.Draft.NullEdge.FinitePeriodicLinkConnection
open PhysicsSM.Draft.NullEdge.LorentzBivectorLieAlgebraBridge

/-- Invertible real `4 x 4` matrices used as Lorentz link transports. -/
abbrev GL4 := GL (Fin 4) Real

/-- A six-component right-trivialized variation on each directed link. -/
abbrev LinkVariation (Site : Type*) := Site -> Fin 4 -> Fiber 6

/-- Forget invertibility while retaining the underlying transport matrix. -/
def unitMatrix (unit : GL4) : Matrix (Fin 4) (Fin 4) Real := unit

@[simp]
theorem unitMatrix_one : unitMatrix (1 : GL4) = 1 := rfl

@[simp]
theorem unitMatrix_mul (left right : GL4) :
    unitMatrix (left * right) = unitMatrix left * unitMatrix right := rfl

/-- The typed generic two-step transport specialized to invertible matrices. -/
def twoStepUnit {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (site : Site) (a b : Fin 4) : GL4 :=
  twoStepTransport shift connection site a b

/-- The typed generic plaquette holonomy specialized to invertible matrices. -/
def plaquetteUnit {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (site : Site) (a b : Fin 4) : GL4 :=
  plaquetteHolonomy shift connection site a b

/-- Ambient matrix tangent generated by a right-trivialized six-component
link variation. -/
def linkMatrixVariation {Site : Type*}
    (connection : LinkConnection Site GL4) (variation : LinkVariation Site)
    (site : Site) (direction : Fin 4) : Matrix (Fin 4) (Fin 4) Real :=
  unitMatrix (connection site direction) *
    lorentzGenerator (variation site direction)

/-- Product-rule tangent of one ordered two-link path. -/
def twoStepMatrixVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  linkMatrixVariation connection variation site a *
      unitMatrix (connection (shift a site) b) +
    unitMatrix (connection site a) *
      linkMatrixVariation connection variation (shift a site) b

/-- Product/inverse-rule tangent of the exact group plaquette holonomy. -/
def plaquetteMatrixVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  let pathAB := twoStepUnit shift connection site a b
  let pathBA := twoStepUnit shift connection site b a
  let deltaAB := twoStepMatrixVariation shift connection variation site a b
  let deltaBA := twoStepMatrixVariation shift connection variation site b a
  deltaAB * unitMatrix pathBA⁻¹ -
    unitMatrix (pathAB * pathBA⁻¹) * deltaBA * unitMatrix pathBA⁻¹

/-- The plaquette tangent translated back to the Lie algebra at the identity.
-/
def rightTrivializedPlaquetteVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  plaquetteMatrixVariation shift connection variation site a b *
    unitMatrix (plaquetteUnit shift connection site a b)⁻¹

/-- Adjoint transport of one six-component Lorentz generator. -/
def lorentzAdjoint (transport : GL4) (bivector : Fiber 6) :
    Matrix (Fin 4) (Fin 4) Real :=
  unitMatrix transport * lorentzGenerator bivector * unitMatrix transport⁻¹

/-- Four-corner adjoint sum predicted by the right logarithmic derivative of
the plaquette. -/
def plaquetteAdjointSum {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site GL4)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  let pathAB := twoStepUnit shift connection site a b
  let holonomy := plaquetteUnit shift connection site a b
  lorentzAdjoint (connection site a) (variation site a) +
    lorentzAdjoint pathAB (variation (shift a site) b) -
    lorentzAdjoint (holonomy * connection site b) (variation site b) -
    lorentzAdjoint pathAB (variation (shift b site) a)

/-- The exact product/inverse tangent equals the four transported
Lie-algebra insertions. -/
theorem rightTrivializedPlaquetteVariation_eq_adjointSum
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (connection : LinkConnection Site GL4) (variation : LinkVariation Site)
    (site : Site) (a b : Fin 4) :
    rightTrivializedPlaquetteVariation shift connection variation site a b =
      plaquetteAdjointSum shift connection variation site a b := by
  simp +decide [rightTrivializedPlaquetteVariation, plaquetteAdjointSum,
    plaquetteMatrixVariation, twoStepMatrixVariation, linkMatrixVariation,
    lorentzAdjoint, plaquetteUnit, plaquetteHolonomy]
  unfold unitMatrix
  simp +decide [twoStepUnit, twoStepTransport, mul_assoc, add_mul, mul_add,
    sub_mul]
  abel1

/-- Conjugation by an eta-Lorentz unit preserves the Lorentz Lie algebra. -/
theorem lorentzAdjoint_mem
    (transport : GL4) (hTransport : IsEtaLorentz (unitMatrix transport))
    (bivector : Fiber 6) :
    IsLorentzLieAlgebra (lorentzAdjoint transport bivector) := by
  unfold IsLorentzLieAlgebra lorentzAdjoint
  convert congr_arg
    (fun x => (unitMatrix transport⁻¹).transpose * x * unitMatrix transport⁻¹)
    (lorentzGenerator_mem bivector) using 1
  · simp +decide [mul_add, add_mul, mul_assoc]
    simp_all +decide [<- mul_assoc, IsEtaLorentz]
    simp_all +decide [unitMatrix, mul_assoc]
    rw [<- Matrix.mul_assoc, <- hTransport]
    simp +decide [Matrix.mul_assoc, Matrix.transpose_nonsing_inv]
    simp_all +decide [<- mul_assoc]
  · norm_num

/-- With eta-Lorentz links, the exact right-trivialized plaquette tangent is a
Lorentz Lie-algebra element. -/
theorem rightTrivializedPlaquetteVariation_mem
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (connection : LinkConnection Site GL4)
    (hConnection : forall site direction,
      IsEtaLorentz (unitMatrix (connection site direction)))
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    IsLorentzLieAlgebra
      (rightTrivializedPlaquetteVariation shift connection variation site a b) := by
  have h_sum_terms : forall transport : GL4,
      IsEtaLorentz (unitMatrix transport) -> forall bivector : Fiber 6,
        IsLorentzLieAlgebra (lorentzAdjoint transport bivector) := by
    apply lorentzAdjoint_mem
  have h_pathAB :
      IsEtaLorentz (unitMatrix (twoStepUnit shift connection site a b)) := by
    simp_all +decide [IsEtaLorentz, twoStepUnit, twoStepTransport]
    grind +revert
  have h_holonomy : IsEtaLorentz
      (unitMatrix (plaquetteUnit shift connection site a b *
        connection site b)) := by
    have h_holonomy :
        IsEtaLorentz (unitMatrix (plaquetteUnit shift connection site a b)) := by
      have h_holonomy : forall transport : GL4,
          IsEtaLorentz (unitMatrix transport) ->
            IsEtaLorentz (unitMatrix transport⁻¹) := by
        intro transport hTransport
        simp [IsEtaLorentz] at hTransport ⊢
        convert congr_arg
          (fun x => (unitMatrix transport⁻¹)ᵀ * x * unitMatrix transport⁻¹)
          hTransport using 1 <;> simp +decide [Matrix.mul_assoc]
        · grind
        · convert congr_arg
            (fun x => (unitMatrix transport⁻¹)ᵀ * x * unitMatrix transport⁻¹)
            hTransport using 1 <;> simp +decide [Matrix.mul_assoc]
          simp +decide [<- Matrix.mul_assoc, unitMatrix]
          simp +decide [Matrix.transpose_nonsing_inv]
      have h_holonomy : forall transport1 transport2 : GL4,
          IsEtaLorentz (unitMatrix transport1) ->
          IsEtaLorentz (unitMatrix transport2) ->
            IsEtaLorentz (unitMatrix (transport1 * transport2)) := by
        simp +decide [IsEtaLorentz, unitMatrix]
        simp +contextual [<- mul_assoc]
        simp +contextual [mul_assoc, *]
      exact h_holonomy _ _ h_pathAB
        (‹forall transport : GL4, IsEtaLorentz (unitMatrix transport) ->
          IsEtaLorentz (unitMatrix transport⁻¹)› _
          (h_holonomy _ _ (hConnection _ _) (hConnection _ _)))
    simp_all +decide [IsEtaLorentz]
    grind
  rw [rightTrivializedPlaquetteVariation_eq_adjointSum]
  unfold plaquetteAdjointSum
  simp_all +decide [IsLorentzLieAlgebra]
  simp_all +decide [add_mul, mul_add, sub_mul, mul_sub]
  simp_all +decide [<- eq_sub_iff_add_eq']

/-- Identity transport on every link. -/
def identityConnection (Site : Type*) : LinkConnection Site GL4 :=
  fun _ _ => 1

/-- Oriented additive plaquette curl of a six-component link variation. -/
def additivePlaquetteCurl {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (variation : LinkVariation Site)
    (site : Site) (a b : Fin 4) : Fiber 6 :=
  fun component =>
    variation site a component + variation (shift a site) b component -
      variation site b component - variation (shift b site) a component

/-- At identity transport the nonlinear tangent reduces exactly to the
oriented additive plaquette curl. -/
theorem rightTrivializedPlaquetteVariation_identity
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    rightTrivializedPlaquetteVariation shift (identityConnection Site)
        variation site a b =
      lorentzGenerator (additivePlaquetteCurl shift variation site a b) := by
  convert rightTrivializedPlaquetteVariation_eq_adjointSum shift
    (identityConnection Site) variation site a b using 1
  unfold plaquetteAdjointSum additivePlaquetteCurl lorentzAdjoint
    lorentzGenerator bivectorMatrix MinkowskiConvention.eta
  simp +decide [unitMatrix, identityConnection, plaquetteUnit,
    plaquetteHolonomy, twoStepUnit, twoStepTransport]
  grind

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent.rightTrivializedPlaquetteVariation_eq_adjointSum' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rightTrivializedPlaquetteVariation_eq_adjointSum

/-- info: 'PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent.lorentzAdjoint_mem' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms lorentzAdjoint_mem

/-- info: 'PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent.rightTrivializedPlaquetteVariation_mem' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rightTrivializedPlaquetteVariation_mem

/-- info: 'PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent.rightTrivializedPlaquetteVariation_identity' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rightTrivializedPlaquetteVariation_identity

end PhysicsSM.Draft.NullEdge.LorentzPlaquetteTangent
