import Mathlib

/-!
# Finite massive retarded link series

This module studies the finite matrix series

```text
G_m(H) = sum_{k=0}^{H-1} (-massSq)^k K^(k+1)
```

generated by a supplied primitive retarded kernel `K`. It proves exact left
and right resolvent identities, termination for a nilpotent kernel, and a
three-event link-chain witness in which the primitive kernel has no direct
endpoint hop while the mass-deformed series has a nonzero two-hop term.

Provenance: clean-room finite algebra based on the matrix geometric-series
construction in Steven Johnston, "Particle propagators on discrete spacetime,"
arXiv:0806.3083, and the massive-from-massless causal-set Green-function
treatment in Nomaan X, Fay Dowker, and Sumati Surya, "Scalar Field Green
Functions on Causal Sets," arXiv:1701.07212. The proofs were completed by
Aristotle task `a5d949fc-a102-48bb-ac34-824874df32f7` and replayed in the
pinned project environment.

The result is finite matrix algebra. It does not identify `K` with a continuum
Green function, derive `massSq`, prove a continuum limit, or model an
interacting Higgs field.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.MassiveRetardedLinkSeries

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Truncated massive retarded series generated by one primitive kernel. -/
def massiveRetardedSeries
    (K : Matrix V V Real) (massSq : Real) (H : Nat) : Matrix V V Real :=
  ∑ k ∈ Finset.range H, (-massSq) ^ k • K ^ (k + 1)

/-- Exact left resolvent identity, including the finite terminal remainder. -/
theorem one_add_mass_kernel_mul_series
    (K : Matrix V V Real) (massSq : Real) (H : Nat) :
    (1 + massSq • K) * massiveRetardedSeries K massSq H =
      K - (-massSq) ^ H • K ^ (H + 1) := by
  induction H <;>
    simp_all +decide [pow_succ, add_mul, Matrix.mul_assoc]
  · unfold massiveRetardedSeries
    simp +decide
  · simp_all +decide [massiveRetardedSeries, pow_succ, mul_add,
      Finset.sum_range_succ]
    simp_all +decide [← mul_assoc, ← pow_succ']
    simp_all +decide [← add_assoc, ← eq_sub_iff_add_eq', pow_succ, mul_assoc,
      smul_smul]
    module

/-- Exact right resolvent identity. Powers of one primitive kernel commute
with that kernel, so the same terminal remainder appears. -/
theorem series_mul_one_add_mass_kernel
    (K : Matrix V V Real) (massSq : Real) (H : Nat) :
    massiveRetardedSeries K massSq H * (1 + massSq • K) =
      K - (-massSq) ^ H • K ^ (H + 1) := by
  induction H <;>
    simp_all +decide [pow_succ, Matrix.mul_assoc, massiveRetardedSeries]
  simp_all +decide [Finset.sum_range_succ, mul_add, add_mul, ← mul_assoc,
    smul_smul]
  rename_i n ih
  rw [← add_add_add_comm, ← add_assoc, ih]
  norm_num [mul_assoc, mul_comm, mul_left_comm, smul_smul]

/-- Nilpotence removes the left terminal remainder exactly. -/
theorem one_add_mass_kernel_mul_series_of_nilpotent
    (K : Matrix V V Real) (massSq : Real) (H : Nat)
    (hNil : K ^ (H + 1) = 0) :
    (1 + massSq • K) * massiveRetardedSeries K massSq H = K := by
  rw [one_add_mass_kernel_mul_series, hNil, smul_zero, sub_zero]

/-- Nilpotence removes the right terminal remainder exactly. -/
theorem series_mul_one_add_mass_kernel_of_nilpotent
    (K : Matrix V V Real) (massSq : Real) (H : Nat)
    (hNil : K ^ (H + 1) = 0) :
    massiveRetardedSeries K massSq H * (1 + massSq • K) = K := by
  rw [series_mul_one_add_mass_kernel, hNil, smul_zero, sub_zero]

/-- For positive truncation length, zero mass leaves only the primitive
retarded kernel. -/
theorem massiveRetardedSeries_zero_mass
    (K : Matrix V V Real) (H : Nat) (hH : 0 < H) :
    massiveRetardedSeries K 0 H = K := by
  induction hH <;>
    simp_all +decide [massiveRetardedSeries, pow_succ', Finset.sum_range_succ]
  grind

/-- Primitive link kernel on the three-event chain `0 -> 1 -> 2`. Matrix rows
are targets and columns are sources. -/
def threeLinkKernel : Matrix (Fin 3) (Fin 3) Real :=
  !![0, 0, 0; 1, 0, 0; 0, 1, 0]

/-- Nonvacuous multi-edge control. There is no primitive `0 -> 2` matrix
entry, but the square has unit `0 -> 1 -> 2` amplitude. The kernel is
cube-zero, and at `massSq = 1` the massive series has endpoint amplitude
`-1`, whereas its zero-mass value is zero. -/
theorem threeLink_massive_multiedge_witness :
    threeLinkKernel 2 0 = 0 ∧
      (threeLinkKernel ^ 2) 2 0 = 1 ∧
      threeLinkKernel ^ 3 = 0 ∧
      massiveRetardedSeries threeLinkKernel 1 3 2 0 = -1 ∧
      massiveRetardedSeries threeLinkKernel 0 3 2 0 = 0 := by
  unfold threeLinkKernel massiveRetardedSeries
  simp +decide [Finset.sum_range_succ, pow_succ']
  ext i j
  fin_cases i <;> fin_cases j <;> rfl

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.MassiveRetardedLinkSeries.one_add_mass_kernel_mul_series' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms one_add_mass_kernel_mul_series

/-- info: 'PhysicsSM.Draft.NullEdge.MassiveRetardedLinkSeries.threeLink_massive_multiedge_witness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms threeLink_massive_multiedge_witness

end PhysicsSM.Draft.NullEdge.MassiveRetardedLinkSeries

end
