import Mathlib

/-!
# All-moving null dilation of a projector-conditioned shift

A projector-conditioned lattice shift usually moves one internal sector and
holds its complement fixed. This file asks whether the hold can be resolved
into genuine microscopic motion after adding one compact auxiliary direction.

One fine tick moves the selected sector by tx and the complementary sector by
ts. The second fine tick again moves the selected sector by tx but moves the
complement by the inverse of ts. Under the exact projector relations, the
two-tick composition is the original coarse conditioned shift: the selected
sector has moved by two tx steps, while the auxiliary excursion cancels.

The intended physical reading requires an additional soldering declaration:
the physical and compact auxiliary edges must have equal null length per fine
tick. The algebra below proves the dilation, not that geometric declaration.

## Semantic boundary

Provenance: generated by Aristotle task `740737f1-fa4c-4d5b-ba96-5da5f2f1cdbc`, independently replayed and semantically approved by interactive Claude/Opus in `AutonomousLab/reviews/CLAUDE_REVIEW_NullDilation_NoGo_ControlledSector_2026-07-13.md`.\n\nThe results here are a purely algebraic two-fine-tick dilation on an enlarged
register obtained by adjoining one compact auxiliary direction. They do **not**
prove that the auxiliary direction is physical, that its edges are soldered
with the required null length, that the full depth-16 HNU schedule has winding
number one, or that a four-dimensional bulk decodes to observed 3+1 spacetime.
Only the finite-dimensional linear-algebra identities are established.
-/

namespace PhysicsSM.Draft.NullEdge.NullDilationConditionedShift

open Matrix

noncomputable section

abbrev Spin := Fin 2 -> Complex

def State (X S : Type) := X -> S -> Spin

/-- First all-moving fine tick: P moves physically and Q moves outward in the
compact auxiliary direction. -/
def microOut {X S : Type} (P Q : Matrix (Fin 2) (Fin 2) Complex)
    (tx : X ≃ X) (ts : S ≃ S) (psi : State X S) : State X S :=
  fun x s => P *ᵥ psi (tx.symm x) s + Q *ᵥ psi x (ts.symm s)

/-- Second all-moving fine tick: P moves physically again and Q returns in the
compact auxiliary direction. -/
def microBack {X S : Type} (P Q : Matrix (Fin 2) (Fin 2) Complex)
    (tx : X ≃ X) (ts : S ≃ S) (psi : State X S) : State X S :=
  fun x s => P *ᵥ psi (tx.symm x) s + Q *ᵥ psi x (ts s)

/-- Coarse update decoded after two fine ticks. -/
def coarse {X S : Type} (P Q : Matrix (Fin 2) (Fin 2) Complex)
    (tx : X ≃ X) (psi : State X S) : State X S :=
  fun x s => P *ᵥ psi (tx.symm (tx.symm x)) s + Q *ᵥ psi x s

/-- The auxiliary out-and-back motion exactly dilates the stationary sector:
after two fine ticks, P has translated twice and Q has returned to its original
auxiliary site. -/
theorem microBack_microOut {X S : Type} (P Q : Matrix (Fin 2) (Fin 2) Complex)
    (tx : X ≃ X) (ts : S ≃ S)
    (hPP : P * P = P) (hQQ : Q * Q = Q)
    (hPQ : P * Q = 0) (hQP : Q * P = 0)
    (psi : State X S) :
    microBack P Q tx ts (microOut P Q tx ts psi) = coarse P Q tx psi := by
  funext x s
  simp only [microBack, microOut, coarse, Matrix.mulVec_add, Matrix.mulVec_mulVec,
    Equiv.symm_apply_apply]
  rw [hPP, hQQ, hPQ, hQP]
  simp only [Matrix.zero_mulVec, add_zero, zero_add]

/-- Momentum-space control: opposite auxiliary phases cancel on Q, while the
selected physical phase is squared. -/
theorem symbol_dilation (P Q : Matrix (Fin 2) (Fin 2) Complex)
    (cx cs : Complex)
    (hPP : P * P = P) (hQQ : Q * Q = Q)
    (hPQ : P * Q = 0) (hQP : Q * P = 0)
    (hcs : cs != 0) :
    (cx • P + cs⁻¹ • Q) * (cx • P + cs • Q) =
      (cx * cx) • P + Q := by
  have hcs' : cs ≠ 0 := by simpa using hcs
  have hinv : cs⁻¹ * cs = 1 := inv_mul_cancel₀ hcs'
  rw [add_mul, mul_add, mul_add]
  rw [Matrix.smul_mul, Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.smul_mul, Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_smul]
  rw [hPP, hQQ, hPQ, hQP]
  simp only [smul_zero, add_zero, zero_add, smul_smul, hinv, one_smul]

/-
Each fine tick preserves the finite inner product under **complementary**
Hermitian projectors and bijective physical/auxiliary shifts.

Correction to the original statement: the informal claim invokes *complementary*
Hermitian projectors, which by definition satisfy the completeness relation
`P + Q = 1` in addition to being orthogonal idempotents (`P*Q = Q*P = 0`,
`P*P = P`, `Q*Q = Q`). The completeness hypothesis `hId : P + Q = 1` was absent
from the original signature, and without it the statement is false: taking
`P = Q = 0` satisfies every remaining hypothesis while the left-hand side
vanishes identically and the right-hand side does not. The completeness relation
is exactly the algebraic content of the word "complementary", so it is restored
here rather than weakening the conclusion. The original (false) signature is
preserved as a comment immediately below.
-/
theorem microOut_inner_preserving {X S : Type} [Fintype X] [Fintype S]
    (P Q : Matrix (Fin 2) (Fin 2) Complex) (tx : X ≃ X) (ts : S ≃ S)
    (hP : P.conjTranspose = P) (hQ : Q.conjTranspose = Q)
    (hPP : P * P = P) (hQQ : Q * Q = Q)
    (hPQ : P * Q = 0) (hQP : Q * P = 0)
    (hId : P + Q = 1)
    (psi phi : State X S) :
    (∑ x, ∑ s, ∑ a,
      starRingEnd Complex (microOut P Q tx ts psi x s a) *
        microOut P Q tx ts phi x s a) =
    ∑ x, ∑ s, ∑ a, starRingEnd Complex (psi x s a) * phi x s a := by
  have hdot : ∀ w1 w2 : Fin 2 → Complex,
      (∑ a, starRingEnd Complex (w1 a) * w2 a) = star w1 ⬝ᵥ w2 := by
    intro w1 w2; simp only [dotProduct, Pi.star_apply, starRingEnd_apply]
  have crossPQ : ∀ u v : Fin 2 → Complex, star (P *ᵥ u) ⬝ᵥ (Q *ᵥ v) = 0 := by
    intro u v
    rw [star_mulVec, dotProduct_mulVec, vecMul_vecMul, hP, hPQ, vecMul_zero, zero_dotProduct]
  have crossQP : ∀ u v : Fin 2 → Complex, star (Q *ᵥ u) ⬝ᵥ (P *ᵥ v) = 0 := by
    intro u v
    rw [star_mulVec, dotProduct_mulVec, vecMul_vecMul, hQ, hQP, vecMul_zero, zero_dotProduct]
  -- per-(x,s) evaluation: cross terms vanish, diagonal terms simplify by idempotence
  have hterm : ∀ x s,
      (∑ a, starRingEnd Complex (microOut P Q tx ts psi x s a) *
          microOut P Q tx ts phi x s a)
      = (star (psi (tx.symm x) s) ⬝ᵥ (P *ᵥ phi (tx.symm x) s))
        + (star (psi x (ts.symm s)) ⬝ᵥ (Q *ᵥ phi x (ts.symm s))) := by
    intro x s
    rw [hdot]
    simp only [microOut, star_add, add_dotProduct, dotProduct_add]
    rw [crossPQ, crossQP, add_zero, zero_add]
    rw [star_mulVec, star_mulVec, dotProduct_mulVec, dotProduct_mulVec,
        vecMul_vecMul, vecMul_vecMul, hP, hQ, hPP, hQQ, dotProduct_mulVec, dotProduct_mulVec]
  -- completeness P + Q = 1 splits the unshifted inner product into P and Q parts
  have hsplit : ∀ u v : Fin 2 → Complex,
      star u ⬝ᵥ v = star u ⬝ᵥ (P *ᵥ v) + star u ⬝ᵥ (Q *ᵥ v) := by
    intro u v
    rw [← dotProduct_add, ← add_mulVec, hId, one_mulVec]
  have hrhs : (∑ x, ∑ s, ∑ a, starRingEnd Complex (psi x s a) * phi x s a)
      = ∑ x, ∑ s, star (psi x s) ⬝ᵥ (phi x s) := by
    simp_rw [hdot]
  have hrhs2 : (∑ x, ∑ s, star (psi x s) ⬝ᵥ phi x s)
      = (∑ x, ∑ s, star (psi x s) ⬝ᵥ (P *ᵥ phi x s))
        + (∑ x, ∑ s, star (psi x s) ⬝ᵥ (Q *ᵥ phi x s)) := by
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl (fun x _ => ?_)
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl (fun s _ => hsplit (psi x s) (phi x s))
  rw [hrhs, hrhs2]
  simp_rw [hterm, Finset.sum_add_distrib]
  congr 1
  · -- physical branch: reindex the x-sum along the bijection tx
    exact Equiv.sum_comp tx.symm (fun x => ∑ s, star (psi x s) ⬝ᵥ (P *ᵥ phi x s))
  · -- auxiliary branch: reindex the s-sum along the bijection ts
    refine Finset.sum_congr rfl (fun x _ => ?_)
    exact Equiv.sum_comp ts.symm (fun s => star (psi x s) ⬝ᵥ (Q *ᵥ phi x s))

/-
-- Original (false as stated: missing the completeness relation `P + Q = 1`
-- that "complementary" denotes; `P = Q = 0` is a counterexample).
theorem microOut_inner_preserving {X S : Type} [Fintype X] [Fintype S]
    (P Q : Matrix (Fin 2) (Fin 2) Complex) (tx : X ≃ X) (ts : S ≃ S)
    (hP : P.conjTranspose = P) (hQ : Q.conjTranspose = Q)
    (hPP : P * P = P) (hQQ : Q * Q = Q)
    (hPQ : P * Q = 0) (hQP : Q * P = 0)
    (psi phi : State X S) :
    (∑ x, ∑ s, ∑ a,
      starRingEnd Complex (microOut P Q tx ts psi x s a) *
        microOut P Q tx ts phi x s a) =
    ∑ x, ∑ s, ∑ a, starRingEnd Complex (psi x s a) * phi x s a := by
  s o r r y

Analogous inner-product preservation for the return tick `microBack`, under
the same complementary Hermitian projectors and bijective shifts.
-/
theorem microBack_inner_preserving {X S : Type} [Fintype X] [Fintype S]
    (P Q : Matrix (Fin 2) (Fin 2) Complex) (tx : X ≃ X) (ts : S ≃ S)
    (hP : P.conjTranspose = P) (hQ : Q.conjTranspose = Q)
    (hPP : P * P = P) (hQQ : Q * Q = Q)
    (hPQ : P * Q = 0) (hQP : Q * P = 0)
    (hId : P + Q = 1)
    (psi phi : State X S) :
    (∑ x, ∑ s, ∑ a,
      starRingEnd Complex (microBack P Q tx ts psi x s a) *
        microBack P Q tx ts phi x s a) =
    ∑ x, ∑ s, ∑ a, starRingEnd Complex (psi x s a) * phi x s a := by
  convert microOut_inner_preserving P Q tx ts.symm hP hQ hPP hQQ hPQ hQP hId _ _ using 1

/-! ## Finite nontrivial cyclic witness

A concrete instantiation on cyclic physical and auxiliary registers `Fin 2`,
with a fixed-point-free cyclic shift on each, and the two diagonal rank-one
complementary Hermitian projectors. On every fine tick the P branch reads from
a strictly shifted physical site and the Q branch reads from a strictly shifted
auxiliary site, so both projector branches genuinely change a register
coordinate; both projectors are moreover nonzero. -/

/-- The two diagonal rank-one complementary projectors on `Fin 2`. -/
def projTop : Matrix (Fin 2) (Fin 2) Complex := !![1, 0; 0, 0]

/-- The complementary partner of `projTop`. -/
def projBot : Matrix (Fin 2) (Fin 2) Complex := !![0, 0; 0, 1]

/-- Fixed-point-free cyclic shift on `Fin 2`. -/
def cyc : Fin 2 ≃ Fin 2 := Equiv.addRight (1 : Fin 2)

/-
The cyclic witness: on `Fin 2 × Fin 2` registers with the cyclic shift `cyc`
in both the physical and auxiliary directions, the diagonal projectors are
nonzero complementary Hermitian projectors, and each fine tick strictly changes
the coordinate read by *both* branches (no fixed points), so neither branch is
stationary.
-/
theorem cyclic_witness :
    (projTop.conjTranspose = projTop) ∧ (projBot.conjTranspose = projBot) ∧
    (projTop * projTop = projTop) ∧ (projBot * projBot = projBot) ∧
    (projTop * projBot = 0) ∧ (projBot * projTop = 0) ∧
    (projTop + projBot = 1) ∧
    (projTop ≠ 0) ∧ (projBot ≠ 0) ∧
    (∀ x : Fin 2, cyc.symm x ≠ x) ∧ (∀ s : Fin 2, cyc.symm s ≠ s) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projTop, Matrix.conjTranspose_apply]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projBot, Matrix.conjTranspose_apply]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projTop, Matrix.mul_apply, Fin.sum_univ_two]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projBot, Matrix.mul_apply, Fin.sum_univ_two]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projTop, projBot, Matrix.mul_apply, Fin.sum_univ_two]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projTop, projBot, Matrix.mul_apply, Fin.sum_univ_two]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [projTop, projBot]
  · intro h; have := congrFun (congrFun h 0) 0; simp [projTop] at this
  · intro h; have := congrFun (congrFun h 1) 1; simp [projBot] at this
  · intro x; fin_cases x <;> decide
  · intro s; fin_cases s <;> decide

/-
Concrete motion of both branches: with a state supported at the single site
`(0,0)`, the first fine tick `microOut projTop projBot cyc cyc` moves the P
(physical) contribution to the shifted physical site `x = 0 + 1` and moves the Q
(auxiliary) contribution to the shifted auxiliary site `s = 0 + 1`, while the
original site `(0,0)` no longer carries the moved mass. This exhibits both
branches changing a register coordinate on the fine tick.
-/
theorem cyclic_witness_moves :
    let psi : State (Fin 2) (Fin 2) := fun x s => if x = 0 ∧ s = 0 then 1 else 0
    -- P branch has moved the physical coordinate: mass now sits at x = 1, s = 0.
    (microOut projTop projBot cyc cyc psi 1 0 ≠ 0) ∧
    -- Q branch has moved the auxiliary coordinate: mass now sits at x = 0, s = 1.
    (microOut projTop projBot cyc cyc psi 0 1 ≠ 0) ∧
    -- the P/Q-projected mass has left the original site (0,0).
    (microOut projTop projBot cyc cyc psi 0 0 = 0) := by
  unfold microOut
  simp +decide [projTop, projBot]
  norm_num [vecHead, vecTail]

end

/-! ## Standard-axiom guards

Every result above depends only on the standard Lean/Mathlib axioms
`propext`, `Classical.choice`, and `Quot.sound`. -/

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.microBack_microOut' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms microBack_microOut

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.symbol_dilation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms symbol_dilation

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.microOut_inner_preserving' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms microOut_inner_preserving

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.microBack_inner_preserving' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms microBack_inner_preserving

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.cyclic_witness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms cyclic_witness

/-- info: 'PhysicsSM.Draft.NullEdge.NullDilationConditionedShift.cyclic_witness_moves' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms cyclic_witness_moves

end PhysicsSM.Draft.NullEdge.NullDilationConditionedShift
