import PhysicsSM.Spinor.PluckerMassCovariance

/-!
# The Pluecker-derived finite Dirac mass operator

For two complex null spinors `psi, phi`, their complex Pluecker coordinate
`z = spinorWedge psi phi` defines the odd Hermitian matrix

```text
B(z) = !![0, z; conj z, 0].
```

This module proves that `B(z)^2 = |z|^2 I`, that `B(z)` anticommutes with the
diagonal velocity grading, and hence that the finite Dirac symbol
`H(k,z) = k sigma_z + B(z)` satisfies

```text
H(k,z)^2 = (k^2 + det(twoEdgeMomentum psi phi)) I.
```

The first-order rest gap is therefore `|z|`, while the determinant and every
quadratic cost are `|z|^2`. This removes the need to insert the determinant
itself as an independent first-order Dirac mass parameter.

Multiplying `z` by a unit complex phase conjugates `B(z)` by an explicit
unitary diagonal basis change. Thus the spectrum depends only on the momentum
matrix, although an oriented null decomposition retains a corner phase.

Provenance: clean-room formalization of the operator construction proposed in
the July 2026 manuscript review, built on the trusted Cauchy--Binet/Pluecker
identity in `PhysicsSM.Spinor.PluckerMass`. The construction is finite and
algebraic; no continuum or Standard Model identification is asserted.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.PluckerMassOperator

open Matrix Complex
open PhysicsSM.Spinor.PluckerMass
open PhysicsSM.Spinor.PluckerMassCovariance

/-- Complex `2 x 2` matrices used by the finite Dirac symbol. -/
abbrev Mat := Matrix (Fin 2) (Fin 2) ℂ

/-- The diagonal velocity grading. -/
def velocity : Mat := !![1, 0; 0, -1]

/-- The odd Hermitian mass operator generated by a complex Pluecker coordinate. -/
def massOperator (z : ℂ) : Mat :=
  !![0, z; (starRingEnd ℂ) z, 0]

/-- The finite one-dimensional Dirac symbol with Pluecker-derived rest term. -/
def diracSymbol (k : ℝ) (z : ℂ) : Mat :=
  (k : ℂ) • velocity + massOperator z

/-- A diagonal basis change implementing multiplication of `z` by a phase. -/
def phaseBasis (u : ℂ) : Mat := !![u, 0; 0, 1]

/-- The Pluecker mass operator is Hermitian. -/
theorem massOperator_isHermitian (z : ℂ) : (massOperator z).IsHermitian := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [massOperator]

/-- The mass operator is odd for the velocity grading. -/
theorem velocity_anticommutes_massOperator (z : ℂ) :
    velocity * massOperator z + massOperator z * velocity = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [velocity, massOperator]

/-- Squaring the odd mass operator forgets its phase and returns its squared
Pluecker area. -/
theorem massOperator_sq (z : ℂ) :
    massOperator z * massOperator z =
      complexAbsSq z • (1 : Mat) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [massOperator, complexAbsSq, Matrix.mul_apply]
  all_goals ring

/-- The finite Dirac symbol is Hermitian. -/
theorem diracSymbol_isHermitian (k : ℝ) (z : ℂ) :
    (diracSymbol k z).IsHermitian := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracSymbol, velocity, massOperator]

/-- Hero identity: the Pluecker-derived Dirac symbol has the exact relativistic
square, with no independent mass parameter. -/
theorem diracSymbol_sq (k : ℝ) (z : ℂ) :
    diracSymbol k z * diracSymbol k z =
      (((k ^ 2 : ℝ) : ℂ) + complexAbsSq z) • (1 : Mat) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracSymbol, velocity, massOperator, complexAbsSq,
      Matrix.mul_apply] <;> ring

/-- For a pair of null spinors, the squared mass operator is exactly the
determinant of their summed Hermitian momentum. -/
theorem massOperator_sq_eq_momentum_det (psi phi : CSpinor) :
    massOperator (spinorWedge psi phi) * massOperator (spinorWedge psi phi) =
      (twoEdgeMomentum psi phi).det • (1 : Mat) := by
  rw [massOperator_sq, two_edge_plucker_mass_identity]

/-- Pair-level synthesis: the same complex wedge determines the odd rest term,
while its squared norm is the momentum determinant in the Dirac square. -/
theorem pair_diracSymbol_sq (psi phi : CSpinor) (k : ℝ) :
    diracSymbol k (spinorWedge psi phi) *
        diracSymbol k (spinorWedge psi phi) =
      (((k ^ 2 : ℝ) : ℂ) + (twoEdgeMomentum psi phi).det) • (1 : Mat) := by
  rw [diracSymbol_sq, two_edge_plucker_mass_identity]

/-- The operator vanishes exactly on the zero-Pluecker locus. -/
theorem massOperator_eq_zero_iff (z : ℂ) :
    massOperator z = 0 ↔ z = 0 := by
  constructor
  · intro h
    have h01 := congrFun (congrFun h 0) 1
    simpa [massOperator] using h01
  · rintro rfl
    ext i j
    fin_cases i <;> fin_cases j <;> simp [massOperator]

/-- The rest operator vanishes exactly when the two spinor directions are
projectively collinear, provided the left spinor is nonzero. -/
theorem massOperator_eq_zero_iff_collinear (psi phi : CSpinor)
    (hpsi : psi 0 ≠ 0 ∨ psi 1 ≠ 0) :
    massOperator (spinorWedge psi phi) = 0 ↔
      ∃ c : ℂ, phi = c • psi := by
  rw [massOperator_eq_zero_iff]
  exact spinorWedge_eq_zero_iff_exists_smul_of_left_nonzero psi phi hpsi

/-- A phase change of the oriented Pluecker coordinate is an explicit diagonal
conjugacy of the mass operator. -/
theorem phase_covariance (u z : ℂ) :
    phaseBasis u * massOperator z * (phaseBasis u)ᴴ =
      massOperator (u * z) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseBasis, massOperator, Matrix.mul_apply, map_mul]
  all_goals ring

/-- When `u` has unit squared modulus, the phase basis is unitary. -/
theorem phaseBasis_unitary (u : ℂ) (hu : complexAbsSq u = 1) :
    phaseBasis u * (phaseBasis u)ᴴ = (1 : Mat) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseBasis, complexAbsSq, Matrix.mul_apply] at hu ⊢
  exact hu

/-- Classification of admissible rest operators in two components: every
Hermitian matrix odd for the velocity grading is generated by its single
complex upper-right entry. -/
theorem oddHermitian_eq_massOperator (B : Mat)
    (hH : B.IsHermitian)
    (hodd : velocity * B + B * velocity = 0) :
    B = massOperator (B 0 1) := by
  have h00raw := congrFun (congrFun hodd 0) 0
  have h11raw := congrFun (congrFun hodd 1) 1
  have h00 : B 0 0 = 0 := by
    simp [velocity, Matrix.mul_apply, Matrix.vecMul, dotProduct,
      Fin.sum_univ_two] at h00raw
    exact h00raw
  have h11 : B 1 1 = 0 := by
    simp [velocity, Matrix.mul_apply, Matrix.vecMul, dotProduct,
      Fin.sum_univ_two] at h11raw
    exact h11raw
  have h10raw := congrFun (congrFun hH 1) 0
  have h10 : B 1 0 = (starRingEnd ℂ) (B 0 1) := by
    simpa [Matrix.conjTranspose_apply] using h10raw.symm
  ext i j
  fin_cases i <;> fin_cases j <;> simp [massOperator, h00, h11, h10]

/-- Consequently every odd Hermitian two-component rest operator squares to
the squared modulus of its unique complex coordinate. -/
theorem oddHermitian_sq (B : Mat)
    (hH : B.IsHermitian)
    (hodd : velocity * B + B * velocity = 0) :
    B * B = complexAbsSq (B 0 1) • (1 : Mat) := by
  rw [oddHermitian_eq_massOperator B hH hodd, massOperator_sq]
  simp [massOperator]

/-- Proper-orthochronous Lorentz covariance in spinor form: the mass operator
is invariant under the defining `SL(2,C)` action on both null spinors. -/
theorem massOperator_sl2_invariant
    (A : Mat) (hA : A.det = 1) (psi phi : CSpinor) :
    massOperator (spinorWedge (actSpinor A psi) (actSpinor A phi)) =
      massOperator (spinorWedge psi phi) := by
  rw [spinorWedge_sl2_invariant A hA]

/-- Nondegenerate exact control: the standard basis pair produces unit squared
rest mass and a nonzero odd mass operator. -/
theorem unit_control :
    let psi : CSpinor := ![1, 0]
    let phi : CSpinor := ![0, 1]
    spinorWedge psi phi = 1 ∧
      (massOperator (spinorWedge psi phi) *
        massOperator (spinorWedge psi phi)) 0 0 = 1 ∧
      massOperator (spinorWedge psi phi) ≠ 0 := by
  dsimp
  constructor
  · norm_num [spinorWedge]
  constructor
  · norm_num [spinorWedge, massOperator, Matrix.mul_apply]
  · intro h
    have h01 := congrFun (congrFun h 0) 1
    norm_num [massOperator, spinorWedge] at h01

/-- Degenerate control: a collinear pair has zero wedge and zero rest operator. -/
theorem collinear_control :
    let psi : CSpinor := ![1, ((2 : ℝ) : ℂ)]
    let phi : CSpinor := ![((3 : ℝ) : ℂ), ((6 : ℝ) : ℂ)]
    spinorWedge psi phi = 0 ∧ massOperator (spinorWedge psi phi) = 0 := by
  dsimp
  constructor
  · norm_num [spinorWedge]
  · ext i j
    fin_cases i <;> fin_cases j <;> norm_num [spinorWedge, massOperator]

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.pair_diracSymbol_sq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms pair_diracSymbol_sq

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.phase_covariance' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms phase_covariance

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.massOperator_eq_zero_iff_collinear' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms massOperator_eq_zero_iff_collinear

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.oddHermitian_eq_massOperator' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms oddHermitian_eq_massOperator

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.massOperator_sl2_invariant' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms massOperator_sl2_invariant

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.unit_control' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms unit_control

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassOperator.collinear_control' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms collinear_control

end PhysicsSM.Draft.NullEdge.PluckerMassOperator
