import PhysicsSM.Draft.NullEdge.PlueckerWindingDerived
import PhysicsSM.Draft.NullEdge.RingHolonomySpectrum

/-!
# From derived Pluecker turning to a free ring-spectrum obstruction

The two-site phase-defect Hamiltonian transports the mass phase through a
half-phase link `w`, with the physical mismatch depending on `w^2`. This module
uses the same convention on a three-cycle. The half-link associated to a
derived principal phase increment `delta` is `exp(i delta / 2)`. Therefore a
Pluecker field with total turning `2 pi` has half-link holonomy `-1`.

Composing that identity with `RingHolonomySpectrum` gives a free one-particle
spectral discriminator: every derived three-site winding-one field has cubic
trace `-6` and cannot be unitarily conjugate to the trivial `+1`-holonomy ring.

This is a finite reduced transport-sector theorem. It does not claim a
topologically protected localized mode or that the unrestricted two-channel
connection has no additional invariants.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.PlueckerRingHolonomyBridge

open Matrix Complex

open PhysicsSM.Draft.NullEdge.PlueckerWindingDerived
open PhysicsSM.Draft.NullEdge.RingHolonomySpectrum

/-- Half-phase link used by the phase-defect Hamiltonian convention. -/
def halfLink (delta : Real) : Complex :=
  Complex.exp (((delta / 2 : Real) : Complex) * Complex.I)

/-- Half-links turn addition of real phase increments into multiplication. -/
theorem halfLink_add (a b : Real) : halfLink (a + b) = halfLink a * halfLink b := by
  rw [halfLink, halfLink, halfLink, ← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- Three half-links with total turning `2 pi` have holonomy `-1`. -/
theorem halfLink_three_eq_neg_one_of_sum_eq_two_pi (a b c : Real)
    (hsum : a + b + c = 2 * Real.pi) :
    halfLink a * halfLink b * halfLink c = -1 := by
  rw [← halfLink_add, ← halfLink_add]
  unfold halfLink
  rw [hsum]
  rw [show (2 * Real.pi) / 2 = Real.pi by ring]
  exact Complex.exp_pi_mul_I

/-- A three-site Pluecker field determines the three half-phase links used by
the reduced ring Hamiltonian. -/
def derivedHalfLink3 (z : ZMod 3 → Complex) (p : ZMod 3) : Complex :=
  halfLink (linkIncrement z p)

/-- Exact bridge from derived winding one to `-1` half-link holonomy. -/
theorem derivedHalfLink3_holonomy_eq_neg_one (z : ZMod 3 → Complex)
    (hturn : totalTurning z = 2 * Real.pi) :
    derivedHalfLink3 z 0 * derivedHalfLink3 z 1 * derivedHalfLink3 z 2 = -1 := by
  apply halfLink_three_eq_neg_one_of_sum_eq_two_pi
  change (∑ p : Fin 3, linkIncrement z p) = 2 * Real.pi at hturn
  rw [Fin.sum_univ_three] at hturn
  exact hturn

/-- Reduced free Hamiltonian generated by the three derived half-links. -/
def derivedH3 (z : ZMod 3 → Complex) : Mat3 :=
  H3 (derivedHalfLink3 z 0) (derivedHalfLink3 z 1) (derivedHalfLink3 z 2)

/-- Derived winding one fixes the cubic free-spectrum witness to `-6`. -/
theorem derivedH3_trace_cube_eq_neg_six (z : ZMod 3 → Complex)
    (hturn : totalTurning z = 2 * Real.pi) :
    (derivedH3 z * derivedH3 z * derivedH3 z).trace = -6 := by
  rw [derivedH3, trace_cube_H3, derivedHalfLink3_holonomy_eq_neg_one z hturn]
  norm_num

/-- The free ring generated by a derived winding-one Pluecker field is not
unitarily conjugate to the trivial-holonomy ring. -/
theorem derivedH3_not_unitarily_conjugate_to_trivial
    (z : ZMod 3 → Complex) (hturn : totalTurning z = 2 * Real.pi) :
    ¬ ∃ W : Mat3, (Wᴴ) * W = 1 ∧ derivedH3 z = W * H3 1 1 1 * Wᴴ := by
  apply not_unitarily_conjugate_to_plus_of_trace_cube_ne
  rw [derivedH3_trace_cube_eq_neg_six z hturn,
    threeSite_holonomy_changes_cubic_trace.1]
  norm_num

/-- Explicit three-site winding-one Pluecker field with increments
`pi/2`, `pi/2`, and `pi`. -/
def windingOneField3 (p : ZMod 3) : Complex := Complex.I ^ p.val

/-- Non-vacuity: the explicit field has total turning exactly `2 pi`. -/
theorem windingOneField3_totalTurning :
    totalTurning windingOneField3 = 2 * Real.pi := by
  unfold totalTurning windingOneField3
  simp [linkIncrement]
  erw [Fin.sum_univ_three]
  norm_num [ZMod.val, Complex.arg_I, Complex.arg_neg_one]
  ring

/-- Explicit derived free-spectrum obstruction. -/
theorem windingOneField3_not_unitarily_conjugate_to_trivial :
    ¬ ∃ W : Mat3, (Wᴴ) * W = 1 ∧
      derivedH3 windingOneField3 = W * H3 1 1 1 * Wᴴ := by
  exact derivedH3_not_unitarily_conjugate_to_trivial
    windingOneField3 windingOneField3_totalTurning

end PhysicsSM.Draft.NullEdge.PlueckerRingHolonomyBridge
