import PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificate

/-!
# On-demand guard for the exact stationary-Weyl elimination certificate

The generated certificate contains three large rational quotient polynomials.
Its proof is kernel checked by exact `ring` normalization, but rebuilding it is
substantially heavier than ordinary draft modules. Keep this guard out of the
draft root and the aggregate overnight guard; rebuild it explicitly when the
certificate or its generator changes:

```text
lake build PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificateGuard
```

Provenance: generated by
`Scripts/oracle/certify_stationary_weyl_tangent_elimination.py` from an exact
SymPy 1.14 lift over `QQ[tx,ty,tz]`. The chart-clearing factor
`(1 + tz^2)^2` is mandatory.
-/

namespace PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificateGuard

/-- info: 'PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificate.correctedEliminationCertificate' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificate.correctedEliminationCertificate

/-- info: 'PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificate.eliminationFactorNecessaryOfNumeratorsZero' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificate.eliminationFactorNecessaryOfNumeratorsZero

end PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCertificateGuard
