import Mathlib

/-!
# Exact localized modes at Pluecker sign walls (Paper C pillar 3 witness)

Overnight publication run 2026-07-11, Fable lane F2.  All data below was
generated by exact rational arithmetic (sympy oracle, scratchpad
`wall_mode_exact.py`) and verified symbolically before submission; every
proof is pure literal arithmetic with no search.

Physics.  `wallWalk` is the 1+1 split-step Dirac walk on an 8-site ring
whose real Pluecker mass field carries the 3-4-5 coin (cos = 4/5,
sin = 3/5) with a SIGN WALL between sites 3|4 and 7|0 (the field is
+m on sites 0-3 and -m on sites 4-7; the sign change is the collinearity
crossing of the underlying spinor pair field, `wallField` below).
`constWalk` is the zero-wall control (constant +m).

Results to prove:
* T1/T2: the explicit vectors `modePlus`/`modeMinus` are EXACT eigenvectors
  of `wallWalk` with eigenvalues `+1` and `-1` - Jackiw-Rebbi-type bound
  states pinned at finite size with rational data;
* T3: `modePlus` is localized at the 3|4 wall: its site probability at
  sites 3 and 4 equals `256/5`, while at the antipodal sites 0 and 7 it
  equals `1` (a factor `256/5` concentration);
* T4: the zero-wall control has NO `+1` or `-1` eigenvector: explicit
  two-sided inverse certificates `certMinus`/`certPlus` for
  `constWalk -+ 1`;
* T5: the wall sign profile is the Pluecker coordinate of an explicit
  primitive spinor pair field (derivation, not assignment).

Prohibited weakenings: do not replace exact eigenvector identities by
spectral approximations; do not drop the zero-wall control; do not change
any literal.  Suggested proof route: `Matrix.mulVec` / matrix product
unfolding via `Fin.sum_univ_succ` (or `Finset.sum_fin_eq_sum_range`) then
`Complex.ext_iff` + `norm_num` entrywise; `funext i; fin_cases i` to split
the sixteen coordinates.

Provenance: second-family C witnesses.  Seed statements and all literal
data generated and verified by exact rational/sympy oracle by Fable, EXCEPT
the localization constants of T3, which were eyeballed from decimals and
WRONG (256/5 vs the exact 3277/64) - the erratum is documented in the
parked comment below; proofs and the T3 correction by Aristotle project
`79d2a55a-71b9-41fa-8bf9-1065f07bc0ca` (task cancelled at the stall
boundary after the snapshot was already complete); integrated with local
kernel re-check (exit 0).  Family: NON-palindromic W = S.C complex-coin
ring (distinct from the K6 palindromic family of
ModeInvariantHalfWinding; see the run's family-consistency note).  Exact
Q(i) eigenvectors for both +-1 modes; an exact four-site localization
comparison for the displayed +1 mode; and two-sided inverse certificates
for the zero-wall control.
Lean 4.28.0.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.WallModeWitness

open Matrix

set_option maxHeartbeats 20000000

def wallWalk : Matrix (Fin 16) (Fin 16) Complex :=
  !![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (3 / 5) * Complex.I;
    0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, (3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 / 5) * Complex.I, (4 / 5), 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (3 / 5) * Complex.I, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 / 5) * Complex.I, (4 / 5);
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (3 / 5) * Complex.I, 0, 0;
    (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def constWalk : Matrix (Fin 16) (Fin 16) Complex :=
  !![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I;
    0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5), 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0, 0, 0;
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-3 / 5) * Complex.I, (4 / 5);
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (4 / 5), (-3 / 5) * Complex.I, 0, 0;
    (-3 / 5) * Complex.I, (4 / 5), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def certMinus : Matrix (Fin 16) (Fin 16) Complex :=
  !![(-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I;
    (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85);
    (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I;
    (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17);
    (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I;
    (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85);
    (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I;
    (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0;
    0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I;
    (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85);
    (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I;
    (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17);
    (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I;
    (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2), (257 / 510) * Complex.I, (-21 / 85);
    (21 / 85), (2 / 15) * Complex.I, (2 / 17), (4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (-2 / 17), (13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (-1 / 2), (13 / 51) * Complex.I;
    (257 / 510) * Complex.I, (-21 / 85), (13 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (-4 / 85), (4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (4 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (21 / 85), (13 / 51) * Complex.I, (-1 / 2)]

def certPlus : Matrix (Fin 16) (Fin 16) Complex :=
  !![(1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I;
    (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85);
    (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I;
    (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17);
    (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I;
    (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85);
    (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I;
    (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0;
    0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I;
    (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85);
    (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I;
    (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17);
    (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I, (21 / 85), (2 / 15) * Complex.I;
    (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2), (257 / 510) * Complex.I, (-21 / 85);
    (21 / 85), (2 / 15) * Complex.I, (-2 / 17), (-4 / 51) * Complex.I, (4 / 85), (16 / 255) * Complex.I, 0, (-4 / 51) * Complex.I, (-4 / 85), (2 / 15) * Complex.I, (2 / 17), (-13 / 51) * Complex.I, (-21 / 85), (257 / 510) * Complex.I, (1 / 2), (-13 / 51) * Complex.I;
    (257 / 510) * Complex.I, (-21 / 85), (-13 / 51) * Complex.I, (2 / 17), (2 / 15) * Complex.I, (-4 / 85), (-4 / 51) * Complex.I, 0, (16 / 255) * Complex.I, (4 / 85), (-4 / 51) * Complex.I, (-2 / 17), (2 / 15) * Complex.I, (21 / 85), (-13 / 51) * Complex.I, (1 / 2)]

def modePlus : Fin 16 -> Complex :=
  ![(4 / 5), (3 / 5) * Complex.I, 1, (3 / 2) * Complex.I, (17 / 10), (63 / 20) * Complex.I, (13 / 4), (51 / 8) * Complex.I, (257 / 40), (63 / 20) * Complex.I, (13 / 4), (3 / 2) * Complex.I, (17 / 10), (3 / 5) * Complex.I, 1, 0]

def modeMinus : Fin 16 -> Complex :=
  ![(-4 / 5), (-3 / 5) * Complex.I, 1, (3 / 2) * Complex.I, (-17 / 10), (-63 / 20) * Complex.I, (13 / 4), (51 / 8) * Complex.I, (-257 / 40), (-63 / 20) * Complex.I, (13 / 4), (3 / 2) * Complex.I, (-17 / 10), (-3 / 5) * Complex.I, 1, 0]


/-- Site-dependent primitive spinor pair whose Pluecker coordinate is the
wall profile: psi = (1,0), phi x = (0, sign(x) * (3/5)). -/
def wallField (x : Fin 8) : Complex :=
  if x.val < 4 then (3 / 5 : Complex) else (-(3 / 5) : Complex)

def wallSpinorPsi (_ : Fin 8) : Fin 2 -> Complex := ![1, 0]

def wallSpinorPhi (x : Fin 8) : Fin 2 -> Complex := ![0, wallField x]

/-- **T5 (derived wall).**  The sign-wall profile is the spinor wedge of the
explicit pair field: the defect is a collinearity crossing, not an assigned
label. -/
theorem wallField_is_pluecker (x : Fin 8) :
    wallSpinorPsi x 0 * wallSpinorPhi x 1
      - wallSpinorPsi x 1 * wallSpinorPhi x 0 = wallField x := by
  simp [wallSpinorPsi, wallSpinorPhi]

/-- **T1 (exact +1 bound state).** -/
theorem wallWalk_modePlus :
    wallWalk.mulVec modePlus = modePlus := by
  funext i
  fin_cases i <;>
    simp only [wallWalk, modePlus, Matrix.mulVec, dotProduct, Fin.sum_univ_succ,
      Fin.sum_univ_zero, Matrix.cons_val', Matrix.cons_val_zero,
      Matrix.cons_val_fin_one, Matrix.of_apply,
      Matrix.empty_val', Matrix.cons_val_succ] <;>
    norm_num [Complex.ext_iff]

/-- **T2 (exact -1 bound state).** -/
theorem wallWalk_modeMinus :
    wallWalk.mulVec modeMinus = (-1 : Complex) • modeMinus := by
  funext i
  fin_cases i <;>
    simp only [wallWalk, modeMinus, Matrix.mulVec, dotProduct, Fin.sum_univ_succ,
      Fin.sum_univ_zero, Matrix.cons_val', Matrix.cons_val_zero,
      Matrix.cons_val_fin_one, Matrix.of_apply,
      Matrix.empty_val', Matrix.cons_val_succ, Pi.smul_apply,
      smul_eq_mul] <;>
    norm_num [Complex.ext_iff]

/-- Site probability of a two-component-per-site vector. -/
def siteProb (v : Fin 16 -> Complex) (x : Fin 8) : Real :=
  Complex.normSq (v ⟨2 * x.val, by omega⟩)
    + Complex.normSq (v ⟨2 * x.val + 1, by omega⟩)

/-
**T3 (wall localization) — ORIGINAL STATEMENT (numerically FALSE, kept for the record).**

The original claim asserted the wall-site probability equals `256/5`.  This is
not exactly true for the (exactly verified) eigenvector `modePlus`.  The true
value is
  `siteProb modePlus 3 = (13/4)^2 + (51/8)^2 = 169/16 + 2601/64 = 3277/64`,
and likewise `siteProb modePlus 4 = (257/40)^2 + (63/20)^2 = 3277/64`.
Since `3277/64 = 16385/320` while `256/5 = 16384/320`, the stated value is off
by exactly `1/320`.  (`256/5` is the intended approximate concentration factor,
not the exact rational site probability.)  The antipodal values (`= 1`) are
correct.  See `modePlus_localized` below for the corrected, proved statement.

theorem modePlus_localized_original :
    siteProb modePlus 3 = 256 / 5 ∧ siteProb modePlus 4 = 256 / 5 ∧
    siteProb modePlus 0 = 1 ∧ siteProb modePlus 7 = 1 := by
  sorry
-/

/-- **T3 (wall localization, corrected).**  The +1 mode concentrates at the
3|4 wall: the exact site probability is `3277/64` there (≈ `256/5`, the
intended concentration factor) versus `1` at the antipodal sites 0 and 7. -/
theorem modePlus_localized :
    siteProb modePlus 3 = 3277 / 64 ∧ siteProb modePlus 4 = 3277 / 64 ∧
    siteProb modePlus 0 = 1 ∧ siteProb modePlus 7 = 1 := by
  refine ⟨?_, ?_, ?_, ?_⟩ <;>
    simp only [siteProb, modePlus, Complex.normSq_apply] <;> norm_num

/-- Certificate identity `(constWalk - 1) * certMinus = 1` (right inverse).

The left inverse `certMinus * (constWalk - 1) = 1` follows for free from this
by `mul_eq_one_comm` (a right inverse of a square matrix is a left inverse). -/
theorem constWalk_sub_one_mul_certMinus :
    (constWalk - 1) * certMinus = (1 : Matrix (Fin 16) (Fin 16) Complex) := by
  rw [sub_mul, one_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp only [Matrix.sub_apply, Matrix.mul_apply, Matrix.one_apply, constWalk, certMinus,
      Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.cons_val_succ,
      Matrix.of_apply, Matrix.cons_val_fin_one, Fin.isValue, Fin.reduceFinMk] <;>
    norm_num [Complex.ext_iff, Fin.ext_iff, apply_ite Complex.re, apply_ite Complex.im]

/-- Certificate identity `(constWalk + 1) * certPlus = 1` (right inverse).

The left inverse `certPlus * (constWalk + 1) = 1` follows from `mul_eq_one_comm`. -/
theorem constWalk_add_one_mul_certPlus :
    (constWalk + 1) * certPlus = (1 : Matrix (Fin 16) (Fin 16) Complex) := by
  rw [add_mul, one_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp only [Matrix.add_apply, Matrix.mul_apply, Matrix.one_apply, constWalk, certPlus,
      Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.cons_val_succ,
      Matrix.of_apply, Matrix.cons_val_fin_one, Fin.isValue, Fin.reduceFinMk] <;>
    norm_num [Complex.ext_iff, Fin.ext_iff, apply_ite Complex.re, apply_ite Complex.im]

/-- **T4 (zero-wall control).**  The constant-field walk has no exact `+1`
or `-1` mode: two-sided inverse certificates for `constWalk -+ 1`.  The two
left-inverse identities are obtained from the right-inverse ones via
`mul_eq_one_comm` (square matrices are Dedekind-finite). -/
theorem constWalk_gap_certificates :
    (constWalk - 1) * certMinus = 1 ∧ certMinus * (constWalk - 1) = 1 ∧
    (constWalk + 1) * certPlus = 1 ∧ certPlus * (constWalk + 1) = 1 :=
  ⟨constWalk_sub_one_mul_certMinus,
    mul_eq_one_comm.mp constWalk_sub_one_mul_certMinus,
    constWalk_add_one_mul_certPlus,
    mul_eq_one_comm.mp constWalk_add_one_mul_certPlus⟩

/-- **T4' (control corollary).**  Hence no nonzero vector satisfies
`constWalk.mulVec v = v` or `constWalk.mulVec v = -v`. -/
theorem constWalk_no_pinned_modes :
    (∀ v : Fin 16 -> Complex, constWalk.mulVec v = v -> v = 0) ∧
    (∀ v : Fin 16 -> Complex, constWalk.mulVec v = (-1 : Complex) • v -> v = 0) := by
  obtain ⟨_, hMinus, _, hPlus⟩ := constWalk_gap_certificates
  constructor
  · intro v hv
    have key : (constWalk - 1) *ᵥ v = 0 := by
      rw [sub_mulVec, hv, one_mulVec, sub_self]
    have h : certMinus *ᵥ ((constWalk - 1) *ᵥ v) = certMinus *ᵥ (0 : Fin 16 → Complex) := by
      rw [key]
    rw [mulVec_mulVec, hMinus, one_mulVec, mulVec_zero] at h
    exact h
  · intro v hv
    have key : (constWalk + 1) *ᵥ v = 0 := by
      rw [add_mulVec, hv, one_mulVec, neg_one_smul, neg_add_cancel]
    have h : certPlus *ᵥ ((constWalk + 1) *ᵥ v) = certPlus *ᵥ (0 : Fin 16 → Complex) := by
      rw [key]
    rw [mulVec_mulVec, hPlus, one_mulVec, mulVec_zero] at h
    exact h

end PhysicsSM.Draft.NullEdge.WallModeWitness
