import PhysicsSM.Draft.NullEdge.PairModularSelection
import PhysicsSM.Draft.NullEdge.PluckerMassOperatorExponential

/-!
# Active-pair exponential bridge

The quartic Fock generator `Kop z` acts nontrivially on the two coordinates
`lowPair` and `highPair`. This module proves that its action on those
coordinates is exactly the canonical Pluecker rest matrix `massOperator z`.
It then composes that bridge with the matrix Euler theorem to show that the
corresponding `Uop` cosine-sine evolution is the genuine matrix exponential on
the active pair sector.

This is an active-coordinate theorem. It does not construct the exponential of
`Kop` as an endomorphism of the full sixteen-dimensional Fock space. Off-sector
behavior and any full operator identity remain separate work.

Provenance: in-project composition of the live `Kop_apply` and `Uop` APIs with
the independently replayed Aristotle S1 theorem in
`PluckerMassOperatorExponential`.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.PairActiveSectorExponential

open Matrix
open PhysicsSM.Draft.NullEdge.FiniteCARFockBasic
open PhysicsSM.Draft.NullEdge.PlueckerQuarticInteraction
open PhysicsSM.Draft.NullEdge.PlueckerPairGenerator
open PhysicsSM.Draft.NullEdge.PluckerMassOperator
open PhysicsSM.Draft.NullEdge.PluckerMassDynamics
open PhysicsSM.Draft.NullEdge.PluckerMassOperatorExponential

/-- Extract the ordered `(lowPair, highPair)` coordinates of a Fock state. -/
def pairCoordinates (psi : Fock (Fin 4)) : Fin 2 -> Complex :=
  ![psi lowPair, psi highPair]

/-- On active coordinates, the quartic generator is exactly the canonical
Pluecker rest matrix. -/
theorem pairCoordinates_Kop (z : Complex) (psi : Fock (Fin 4)) :
    pairCoordinates (Kop z psi) =
      (massOperator z).mulVec (pairCoordinates psi) := by
  ext i
  fin_cases i <;>
    simp +decide [pairCoordinates, Kop_apply, massOperator, Matrix.mulVec,
      dotProduct, Fin.sum_univ_two]

/-- The closed-form Fock evolution, restricted to active coordinates, is the
matrix exponential generated by the canonical Pluecker rest operator. -/
theorem pairCoordinates_Uop_exp (z : Complex) (a : Real) (hz : z ≠ 0)
    (psi : Fock (Fin 4)) :
    pairCoordinates
        (Uop (Real.cos (a * ‖z‖)) (Real.sin (a * ‖z‖)) z ‖z‖ psi) =
      (NormedSpace.exp ((-(a : Complex) * Complex.I) • massOperator z)).mulVec
        (pairCoordinates psi) := by
  rw [exp_eq_massCoin z a hz]
  have hcos :
      Complex.cos ((a : Complex) * (‖z‖ : Complex)) =
        (Real.cos (a * ‖z‖) : Complex) := by
    rw [← Complex.ofReal_mul, ← Complex.ofReal_cos]
  have hsin :
      Complex.sin ((a : Complex) * (‖z‖ : Complex)) =
        (Real.sin (a * ‖z‖) : Complex) := by
    rw [← Complex.ofReal_mul, ← Complex.ofReal_sin]
  have hmassLow :
      (massCoin z a).mulVec (pairCoordinates psi) 0 =
        Complex.cos ((a : Complex) * (‖z‖ : Complex)) * psi lowPair -
          (Complex.I * Complex.sin ((a : Complex) * (‖z‖ : Complex)) /
            (‖z‖ : Complex)) * (z * psi highPair) := by
    simp [massCoin, pairCoordinates, massOperator, Matrix.mulVec, dotProduct,
      Fin.sum_univ_two]
    ring
  have hmassHigh :
      (massCoin z a).mulVec (pairCoordinates psi) 1 =
        Complex.cos ((a : Complex) * (‖z‖ : Complex)) * psi highPair -
          (Complex.I * Complex.sin ((a : Complex) * (‖z‖ : Complex)) /
            (‖z‖ : Complex)) * ((starRingEnd Complex) z * psi lowPair) := by
    simp [massCoin, pairCoordinates, massOperator, Matrix.mulVec, dotProduct,
      Fin.sum_univ_two]
    ring
  ext i
  fin_cases i
  · change
      Uop (Real.cos (a * ‖z‖)) (Real.sin (a * ‖z‖)) z ‖z‖ psi lowPair =
        (massCoin z a).mulVec (pairCoordinates psi) 0
    rw [Uop_low, hmassLow]
    rw [hcos, hsin]
    ring
  · change
      Uop (Real.cos (a * ‖z‖)) (Real.sin (a * ‖z‖)) z ‖z‖ psi highPair =
        (massCoin z a).mulVec (pairCoordinates psi) 1
    rw [Uop_high, hmassHigh]
    rw [hcos, hsin]
    ring

/-- Nonzero control: the active-coordinate generator moves the high-pair basis
state when the Pluecker coordinate is nonzero. -/
theorem active_generator_nonzero (z : Complex) (hz : z ≠ 0) :
    pairCoordinates (Kop z (basisVec highPair)) ≠ 0 := by
  rw [pairCoordinates_Kop]
  intro hzero
  have hcomponent := congrFun hzero 0
  simp [pairCoordinates, massOperator, Matrix.mulVec, dotProduct,
    Fin.sum_univ_two, basisVec, lowPair, highPair] at hcomponent
  exact hz hcomponent

/-- At equal modulus, the genuine active-sector exponential distinguishes the
phases `3+4i` and `5` on the low-pair input. -/
theorem active_exponential_phase_sensitive :
    ((NormedSpace.exp
        ((-((Real.pi / 10 : Real) : Complex) * Complex.I) •
          massOperator (3 + 4 * Complex.I))).mulVec
        (pairCoordinates (basisVec lowPair))) 1 ≠
      ((NormedSpace.exp
        ((-((Real.pi / 10 : Real) : Complex) * Complex.I) •
          massOperator (5 : Complex))).mulVec
        (pairCoordinates (basisVec lowPair))) 1 := by
  have hnormLeft : ‖(3 + 4 * Complex.I : Complex)‖ = 5 := by
    rw [Complex.norm_def]
    norm_num [Complex.normSq, Complex.sq_norm]
  have hnormRight : ‖(5 : Complex)‖ = 5 := by
    norm_num
  have hsin : Real.sin ((Real.pi / 10) * 5) = 1 := by
    rw [show Real.pi / 10 * 5 = Real.pi / 2 by ring]
    exact Real.sin_pi_div_two
  have hcos : Real.cos ((Real.pi / 10) * 5) = 0 := by
    rw [show Real.pi / 10 * 5 = Real.pi / 2 by ring]
    exact Real.cos_pi_div_two
  have hleft := congrFun
    (pairCoordinates_Uop_exp (3 + 4 * Complex.I) (Real.pi / 10)
      (by norm_num [Complex.ext_iff]) (basisVec lowPair)) 1
  have hright := congrFun
    (pairCoordinates_Uop_exp (5 : Complex) (Real.pi / 10)
      (by norm_num) (basisVec lowPair)) 1
  rw [hnormLeft, hcos, hsin] at hleft
  rw [hnormRight, hcos, hsin] at hright
  change
    Uop 0 1 (3 + 4 * Complex.I) 5 (basisVec lowPair) highPair = _ at hleft
  change
    Uop 0 1 (5 : Complex) 5 (basisVec lowPair) highPair = _ at hright
  intro heq
  apply PhysicsSM.Draft.NullEdge.PairModularSelection.pair_evolution_phase_sensitive
  calc
    Uop 0 1 (3 + 4 * Complex.I) 5 (basisVec lowPair) highPair = _ := hleft
    _ = _ := heq
    _ = Uop 0 1 (5 : Complex) 5 (basisVec lowPair) highPair := hright.symm

/-- info: 'PhysicsSM.Draft.NullEdge.PairActiveSectorExponential.pairCoordinates_Kop' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms pairCoordinates_Kop

/-- info: 'PhysicsSM.Draft.NullEdge.PairActiveSectorExponential.pairCoordinates_Uop_exp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms pairCoordinates_Uop_exp

/-- info: 'PhysicsSM.Draft.NullEdge.PairActiveSectorExponential.active_generator_nonzero' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms active_generator_nonzero

/-- info: 'PhysicsSM.Draft.NullEdge.PairActiveSectorExponential.active_exponential_phase_sensitive' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms active_exponential_phase_sensitive

end PhysicsSM.Draft.NullEdge.PairActiveSectorExponential
