import PhysicsSM.Draft.NullEdge.PluckerMassOperator

/-!
# Spectral and dynamical consequences of the Pluecker mass operator

This module extends the canonical `massOperator` API with three consequences
needed by the unitary-walk manuscript:

* explicit rest eigenvectors with eigenvalues `|z|` and `-|z|`;
* invariance of the Gram matrix and wedge magnitude under a right-unitary
  change of two-spinor decomposition;
* an exactly unitary one-parameter mass coin with a strict group law.

The last construction is the algebraic form of `exp(-i a B(z))`. It retains
the complex orientation of `z` in its off-diagonal amplitudes while its
spectrum depends only on `|z|`.

Provenance: theorem targets selected during the 2026-07-10 manuscript review.
Proofs clean-room ported from Aristotle project
`c8b24c90-9957-40a3-aa57-8f34fddb8286` into the canonical project API and
checked under Lean 4.28.0.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.PluckerMassDynamics

open Matrix Complex
open PhysicsSM.Draft.NullEdge.PluckerMassOperator

/-- The nonzero Pluecker coordinate supplies explicit positive- and
negative-rest-energy eigenvectors. -/
theorem rest_eigenvectors (z : ℂ) :
    (massOperator z).mulVec ![z, (‖z‖ : ℂ)] =
      (‖z‖ : ℂ) • ![z, (‖z‖ : ℂ)] ∧
    (massOperator z).mulVec ![z, -(‖z‖ : ℂ)] =
      (-(‖z‖ : ℂ)) • ![z, -(‖z‖ : ℂ)] ∧
    (z ≠ 0 → ![z, (‖z‖ : ℂ)] ≠ 0) := by
  have hzz : starRingEnd ℂ z * z = (‖z‖ : ℂ) * (‖z‖ : ℂ) := by
    rw [mul_comm, Complex.mul_conj]
    norm_cast
    rw [Complex.normSq_eq_norm_sq]
    ring
  refine ⟨?_, ?_, ?_⟩
  · ext i
    fin_cases i <;>
      simp [massOperator, Matrix.mulVec, dotProduct, Fin.sum_univ_two] <;>
      ring_nf <;> rw [hzz] <;> ring
  · ext i
    fin_cases i <;>
      simp [massOperator, Matrix.mulVec, dotProduct, Fin.sum_univ_two] <;>
      ring_nf <;> rw [hzz] <;> ring
  · intro hz hcontra
    have h0 : (![z, (‖z‖ : ℂ)]) 0 = 0 := by
      rw [hcontra]
      rfl
    simp only [Matrix.cons_val_zero] at h0
    exact hz h0

/-- A right-unitary change of the two-spinor column matrix leaves its Gram
matrix fixed and changes its determinant only by a unit-modulus phase. -/
theorem decomposition_independence (M V : Mat) (hV : V * Vᴴ = 1) :
    (M * V) * (M * V)ᴴ = M * Mᴴ ∧
      (M * V).det = V.det * M.det ∧
      ‖V.det‖ = 1 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [Matrix.conjTranspose_mul]
    rw [show M * V * (Vᴴ * Mᴴ) = M * (V * Vᴴ) * Mᴴ by noncomm_ring]
    rw [hV]
    simp
  · rw [Matrix.det_mul, mul_comm]
  · have hdet : V.det * starRingEnd ℂ (V.det) = 1 := by
      have h := congrArg Matrix.det hV
      rw [Matrix.det_mul, Matrix.det_conjTranspose, Matrix.det_one] at h
      exact h
    have hns : Complex.normSq V.det = 1 := by
      have h := Complex.mul_conj V.det
      rw [hdet] at h
      exact_mod_cast h.symm
    rw [Complex.normSq_eq_norm_sq] at hns
    nlinarith [norm_nonneg V.det, hns]

/-- The exact mass coin generated by the Pluecker rest operator. -/
def massCoin (z : ℂ) (a : ℝ) : Mat :=
  (Complex.cos (a * ‖z‖)) • (1 : Mat) -
    (Complex.I * Complex.sin (a * ‖z‖) / (‖z‖ : ℂ)) • massOperator z

/-- For nonzero `z`, the derived mass coin is unitary and obeys the exact
one-parameter group law. -/
theorem massCoin_unitary_group (z : ℂ) (hz : z ≠ 0) (a b : ℝ) :
    massCoin z a * (massCoin z a)ᴴ = 1 ∧
      massCoin z a * massCoin z b = massCoin z (a + b) := by
  have hn : (‖z‖ : ℂ) ≠ 0 := by
    simp only [ne_eq, Complex.ofReal_eq_zero, norm_eq_zero]
    exact hz
  have hzz1 : starRingEnd ℂ z * z = (‖z‖ : ℂ) * (‖z‖ : ℂ) := by
    rw [mul_comm, Complex.mul_conj]
    norm_cast
    rw [Complex.normSq_eq_norm_sq]
    ring
  have hzz2 : z * starRingEnd ℂ z = (‖z‖ : ℂ) * (‖z‖ : ℂ) := by
    rw [Complex.mul_conj]
    norm_cast
    rw [Complex.normSq_eq_norm_sq]
    ring
  constructor
  · have hcc : starRingEnd ℂ (Complex.cos (↑a * ↑‖z‖)) =
        Complex.cos (↑a * ↑‖z‖) := by
      rw [← Complex.ofReal_mul, ← Complex.ofReal_cos, Complex.conj_ofReal]
    have hss : starRingEnd ℂ (Complex.sin (↑a * ↑‖z‖)) =
        Complex.sin (↑a * ↑‖z‖) := by
      rw [← Complex.ofReal_mul, ← Complex.ofReal_sin, Complex.conj_ofReal]
    have hpyth :
        Complex.cos (↑a * ↑‖z‖) * Complex.cos (↑a * ↑‖z‖) +
          Complex.sin (↑a * ↑‖z‖) * Complex.sin (↑a * ↑‖z‖) = 1 := by
      have h := Complex.sin_sq_add_cos_sq (↑(a * ‖z‖) : ℂ)
      push_cast at h ⊢
      ring_nf
      ring_nf at h
      linear_combination h
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [massCoin, massOperator, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.one_apply, Matrix.sub_apply, Matrix.smul_apply, sub_apply,
        map_mul, map_div₀, Complex.conj_I, hcc, hss] <;>
      field_simp <;>
      first
      | linear_combination (↑‖z‖ : ℂ) ^ 2 * hpyth +
          (-(Complex.sin (↑a * ↑‖z‖)) ^ 2 * Complex.I ^ 2) * hzz2 +
          (-(Complex.sin (↑a * ↑‖z‖)) ^ 2 * (↑‖z‖ : ℂ) ^ 2) * Complex.I_sq
      | linear_combination (↑‖z‖ : ℂ) ^ 2 * hpyth +
          (-(Complex.sin (↑a * ↑‖z‖)) ^ 2 * Complex.I ^ 2) * hzz1 +
          (-(Complex.sin (↑a * ↑‖z‖)) ^ 2 * (↑‖z‖ : ℂ) ^ 2) * Complex.I_sq
      | ring
  · have hca : Complex.cos ((↑a + ↑b : ℂ) * ↑‖z‖) =
        Complex.cos (↑a * ↑‖z‖) * Complex.cos (↑b * ↑‖z‖) -
          Complex.sin (↑a * ↑‖z‖) * Complex.sin (↑b * ↑‖z‖) := by
      rw [add_mul, Complex.cos_add]
    have hsa : Complex.sin ((↑a + ↑b : ℂ) * ↑‖z‖) =
        Complex.sin (↑a * ↑‖z‖) * Complex.cos (↑b * ↑‖z‖) +
          Complex.cos (↑a * ↑‖z‖) * Complex.sin (↑b * ↑‖z‖) := by
      rw [add_mul, Complex.sin_add]
    ext i j
    fin_cases i <;> fin_cases j
    all_goals simp [massCoin, massOperator, Matrix.mul_apply,
      Fin.sum_univ_two, Matrix.one_apply, Matrix.sub_apply,
      Matrix.smul_apply, sub_apply, hca, hsa]
    all_goals set ca := Complex.cos (↑a * ↑‖z‖)
    all_goals set cb := Complex.cos (↑b * ↑‖z‖)
    all_goals set sa := Complex.sin (↑a * ↑‖z‖)
    all_goals set sb := Complex.sin (↑b * ↑‖z‖)
    all_goals clear_value ca cb sa sb
    all_goals field_simp
    all_goals
      first
      | linear_combination (sa * sb * Complex.I ^ 2) * hzz2 +
          (sa * sb * (↑‖z‖ : ℂ) ^ 2) * Complex.I_sq
      | linear_combination (sa * sb * Complex.I ^ 2) * hzz1 +
          (sa * sb * (↑‖z‖ : ℂ) ^ 2) * Complex.I_sq
      | ring

/-- A real quadratic form on Hermitian `2 x 2` coordinates that vanishes on
every positive rank-one matrix is a scalar multiple of the determinant. -/
theorem hermitian_determinant_uniqueness
    (Q : ℝ → ℝ → ℝ → ℝ → ℝ)
    (hquad : ∃ c : Fin 10 → ℝ, ∀ p q r s,
      Q p q r s = c 0 * p ^ 2 + c 1 * q ^ 2 + c 2 * r ^ 2 + c 3 * s ^ 2 +
        c 4 * p * q + c 5 * p * r + c 6 * p * s + c 7 * q * r +
        c 8 * q * s + c 9 * r * s)
    (hnull : ∀ v : Fin 2 → ℂ,
      Q (Complex.normSq (v 0)) (Complex.normSq (v 1))
        ((v 0 * starRingEnd ℂ (v 1)).re)
        ((v 0 * starRingEnd ℂ (v 1)).im) = 0) :
    ∃ a : ℝ, ∀ p q r s,
      Q p q r s = a * (p * q - r ^ 2 - s ^ 2) := by
  obtain ⟨c, hc⟩ := hquad
  have e1 := hnull ![1, 0]
  have e2 := hnull ![0, 1]
  have e3 := hnull ![1, 1]
  have e4 := hnull ![1, -1]
  have e5 := hnull ![1, Complex.I]
  have e6 := hnull ![1, -Complex.I]
  have e7 := hnull ![2, 1]
  have e8 := hnull ![2, Complex.I]
  have e9 := hnull ![1, 1 - Complex.I]
  simp only [hc] at e1 e2 e3 e4 e5 e6 e7 e8 e9
  simp [Complex.normSq] at e1 e2 e3 e4 e5 e6 e7 e8 e9
  norm_num at e1 e2 e3 e4 e5 e6 e7 e8 e9
  have hc0 : c 0 = 0 := by linarith
  have hc1 : c 1 = 0 := by linarith
  have hc5 : c 5 = 0 := by linarith
  have hc7 : c 7 = 0 := by linarith
  have hc6 : c 6 = 0 := by linarith
  have hc8 : c 8 = 0 := by linarith
  have hc2 : c 2 = -c 4 := by linarith
  have hc3 : c 3 = -c 4 := by linarith
  have hc9 : c 9 = 0 := by linarith
  refine ⟨c 4, fun p q r s => ?_⟩
  rw [hc, hc0, hc1, hc2, hc3, hc5, hc6, hc7, hc8, hc9]
  ring

/-! ## Build-enforced assumption-footprint guards -/

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassDynamics.rest_eigenvectors' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms rest_eigenvectors

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassDynamics.decomposition_independence' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms decomposition_independence

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassDynamics.massCoin_unitary_group' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms massCoin_unitary_group

/-- info: 'PhysicsSM.Draft.NullEdge.PluckerMassDynamics.hermitian_determinant_uniqueness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms hermitian_determinant_uniqueness

end PhysicsSM.Draft.NullEdge.PluckerMassDynamics
