import Mathlib

/-!
# Finite diagonal-plus-causal massive resolvent

This focused handoff generalizes the strictly off-diagonal retarded series to a
massless kernel with a diagonal term,

`G0 = b * I + N`,

where `N` is nilpotent. This is the finite algebraic shape relevant to a
truncated link exponential, whose constant term is the identity. The massive
scattering response is `G0 * (I + c * G0)^{-1}`.

No continuum limit or identification with a physical Green function is
claimed. Matrix rows are targets and columns are sources.
-/

noncomputable section

namespace FiniteDiagonalCausalResolvent

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Finite geometric candidate for the inverse of `a * I + N`. -/
def nilpotentInverse
    (a : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (a⁻¹) • ∑ k ∈ Finset.range H, (-a⁻¹) ^ k • N ^ k

/-- A scalar plus an `H`-nilpotent matrix times the finite inverse is exactly
the identity. -/
theorem scalar_add_nilpotent_mul_inverse
    (a : Real) (N : Matrix V V Real) (H : Nat)
    (ha : a ≠ 0) (hNil : N ^ H = 0) :
    (a • (1 : Matrix V V Real) + N) * nilpotentInverse a N H = 1 := by
  sorry

/-- The same finite inverse is also a right inverse. -/
theorem inverse_mul_scalar_add_nilpotent
    (a : Real) (N : Matrix V V Real) (H : Nat)
    (ha : a ≠ 0) (hNil : N ^ H = 0) :
    nilpotentInverse a N H * (a • (1 : Matrix V V Real) + N) = 1 := by
  sorry

/-- Massive scattering response generated by `G0 = b * I + N`. -/
def massiveScatteringResponse
    (b c : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (b • (1 : Matrix V V Real) + N) *
    nilpotentInverse (1 + c * b) (c • N) H

/-- Exact left resolvent for a diagonal-plus-nilpotent massless kernel. -/
theorem one_add_massless_mul_massiveScatteringResponse
    (b c : Real) (N : Matrix V V Real) (H : Nat)
    (hDen : 1 + c * b ≠ 0) (hNil : N ^ H = 0) :
    (1 + c • (b • (1 : Matrix V V Real) + N)) *
        massiveScatteringResponse b c N H =
      b • (1 : Matrix V V Real) + N := by
  sorry

/-- Exact right resolvent for the same response. -/
theorem massiveScatteringResponse_mul_one_add_massless
    (b c : Real) (N : Matrix V V Real) (H : Nat)
    (hDen : 1 + c * b ≠ 0) (hNil : N ^ H = 0) :
    massiveScatteringResponse b c N H *
        (1 + c • (b • (1 : Matrix V V Real) + N)) =
      b • (1 : Matrix V V Real) + N := by
  sorry

/-- Primitive link kernel on the chain `0 -> 1 -> 2`. -/
def threeLinkKernel : Matrix (Fin 3) (Fin 3) Real :=
  !![0, 0, 0; 1, 0, 0; 0, 1, 0]

/-- Off-diagonal part of the exact finite exponential of the cube-zero link
kernel: `exp(L) = I + L + (1/2)L^2`. -/
def threeExpOffDiagonal : Matrix (Fin 3) (Fin 3) Real :=
  threeLinkKernel + (1 / 2 : Real) • threeLinkKernel ^ 2

/-- Nonvacuous diagonal-kernel control. The primitive link has no endpoint
entry, the truncated exponential has endpoint entry `1/2`, and at scattering
coefficient `c = 2` the massive response has endpoint entry `-1/54`. -/
theorem threeLink_exponential_massive_witness :
    threeLinkKernel 2 0 = 0 ∧
      (1 + threeExpOffDiagonal) 2 0 = 1 / 2 ∧
      threeExpOffDiagonal ^ 3 = 0 ∧
      massiveScatteringResponse 1 2 threeExpOffDiagonal 3 2 0 = -1 / 54 := by
  sorry

end FiniteDiagonalCausalResolvent

end
