/-!
# Oracle.BranchingFixtures

CAS-generated branching rule fixtures.

Branching rules describe how representations decompose under subalgebra restriction.
Fixtures here are generated by LieART, SageMath Weyl character ring, and similar.

(Empty — fixtures to be added.)
-/

namespace PhysicsSM.Oracle.BranchingFixtures

end PhysicsSM.Oracle.BranchingFixtures
