/-!
# Oracle.GammaFixtures

CAS-generated gamma matrix identity fixtures.

Gamma matrix trace identities and spinor algebra results generated by FeynCalc,
SymPy, or similar tools, used to validate Lean-side gamma matrix definitions.

Note: FeynCalc is GPL-3.0. Fixtures are numeric/symbolic results only; no FeynCalc
source code is incorporated into this repository.

(Empty — fixtures to be added.)
-/

namespace PhysicsSM.Oracle.GammaFixtures

end PhysicsSM.Oracle.GammaFixtures
