/-!
# Oracle.RootFixtures

CAS-generated root system fixtures.

This module contains expected values for root system data generated by external
CAS tools, used for validating Lean-side executable definitions.

Oracle backends: LieART, SageMath, OSCAR.jl, Lie.jl.

## Fixture format

Each fixture records:
- Tool name and version (or commit)
- Input command / script
- Input conventions
- Expected output (numeric or symbolic)
- License status of the tool
- Whether CI checks this fixture

## Current fixtures

(Empty — fixtures to be added as Lean-side definitions are developed.)
-/

namespace PhysicsSM.Oracle.RootFixtures

end PhysicsSM.Oracle.RootFixtures
