import Mathlib
import PhysicsSM.Algebra.Jordan.InnerDerivationLieAlgebra

/-!
# Algebra.Jordan.InnerDerivationJacobiLie

Jacobi identity and Lie algebra structure for inner derivations of `h₃(𝕆)`.

## Overview

This file proves the Jacobi identity for the commutator bracket on
`H3ODerivation`, formalizes the inner derivation subspace, and bundles
the bilinearity of the inner derivation map.

## Main results

- `H3ODerivation_jacobi` — the Jacobi identity for derivation commutators.
- `innerDerivationSet` — the set of individual inner derivations `D_{a,b}`.
- `innerDerivationSubspace` — the linear span of inner derivations.
- `innerDerivationSubspace_closed_bracket` — closure of the span under bracket.
- `innerDerivationBilinearMap` — the inner derivation as a bilinear map.
- `innerDerivationJacobiLiePackage` — bundled package of the above.

## Claim boundary

This file proves the Jacobi identity and Lie subalgebra structure of inner
derivations. It does **not** prove:
- That inner derivations span all of `Der(h₃(𝕆))`.
- The dimension formula `dim InnDer(h₃(𝕆)) = 52 = dim f₄`.
- The isomorphism `InnDer(h₃(𝕆)) ≅ f₄`.

## Status

Trusted module — no `s o r r y`.
-/

namespace PhysicsSM.Algebra.Jordan.H3O

open PhysicsSM.Algebra.Jordan.Derivation
open PhysicsSM.Algebra.Jordan.H3OJordan

local infixl:70 " ○ " => jordanProduct

/-! ## Jacobi identity -/

/-- The Jacobi identity for the commutator bracket on `H3ODerivation`:
`⁅⁅D, E⁆, F⁆ + ⁅⁅E, F⁆, D⁆ + ⁅⁅F, D⁆, E⁆ = 0`. -/
theorem H3ODerivation_jacobi (D E F : H3ODerivation) :
    ⁅⁅D, E⁆, F⁆ + ⁅⁅E, F⁆, D⁆ + ⁅⁅F, D⁆, E⁆ = 0 := by
  refine' H3ODerivation.ext _
  simp +decide [H3ODerivation.toFun, H3ODerivation.map_sub,
    H3ODerivation.map_add, H3ODerivation.map_smul,
    H3ODerivation.leibniz']
  intros; abel_nf

/-! ## Inner derivation subspace -/

/-- The set of individual inner derivations: `{D_{a,b} | a b : H₃(𝕆)}`. -/
def innerDerivationSet : Set H3ODerivation :=
  {G | ∃ a b : H3O, G = innerDerivation a b}

/-- The linear span of inner derivations, i.e. the submodule of `H3ODerivation`
generated by all `D_{a,b}`. This is the carrier of the inner derivation Lie
subalgebra. -/
noncomputable def innerDerivationSubspace : Submodule ℝ H3ODerivation :=
  Submodule.span ℝ innerDerivationSet

/-- An individual inner derivation belongs to the span. -/
theorem innerDerivation_mem_subspace (a b : H3O) :
    innerDerivation a b ∈ innerDerivationSubspace :=
  Submodule.subset_span ⟨a, b, rfl⟩

/-- The commutator bracket of two inner derivations lies in the inner
derivation span. -/
theorem innerDerivationSet_bracket_in_span
    {D E : H3ODerivation}
    (hD : D ∈ innerDerivationSet)
    (hE : E ∈ innerDerivationSet) :
    ⁅D, E⁆ ∈ innerDerivationSubspace := by
  obtain ⟨a, b, rfl⟩ := hD
  obtain ⟨c, d, rfl⟩ := hE
  rw [innerDerivation_commutator_formula]
  exact Submodule.add_mem _
    (innerDerivation_mem_subspace _ _)
    (innerDerivation_mem_subspace _ _)

/-
The inner derivation span is closed under the commutator bracket:
for any two elements of the span, their bracket is again in the span.

This is the key Lie subalgebra closure property. The proof proceeds by
induction on the span, using the commutator formula and bilinearity.
-/
theorem innerDerivationSubspace_closed_bracket
    {D E : H3ODerivation}
    (hD : D ∈ innerDerivationSubspace)
    (hE : E ∈ innerDerivationSubspace) :
    ⁅D, E⁆ ∈ innerDerivationSubspace := by
  refine' Submodule.span_induction _ _ _ _ hD;
  · refine' Submodule.span_induction _ _ _ _ hE;
    · exact fun x hx y hy => innerDerivationSet_bracket_in_span hy hx;
    · simp +decide [ LieRing.of_associative_ring_bracket ];
    · intro x y hx hy hx' hy' z hz; simp_all +decide [ Submodule.add_mem_iff_right, Submodule.add_mem_iff_left ] ;
    · intro a x hx hx' y hy; simp_all +decide [ Submodule.smul_mem, Submodule.add_mem ] ;
  · simp +decide [ Submodule.zero_mem ];
  · simp +contextual [ LieRing.of_associative_ring_bracket ];
    exact fun x y hx hy hx' hy' => Submodule.add_mem _ hx' hy';
  · simp +contextual [ Submodule.smul_mem, lie_smul ]

/-! ## Bilinear map -/

/-- The inner derivation map as a bilinear map `H₃(O) × H₃(O) → Der(H₃(O))`. -/
noncomputable def innerDerivationBilinearMap :
    H3O →ₗ[ℝ] H3O →ₗ[ℝ] H3ODerivation where
  toFun a := {
    toFun := fun b => innerDerivation a b
    map_add' := innerDerivation_add_right a
    map_smul' := fun r b => innerDerivation_smul_right r a b }
  map_add' a₁ a₂ := by
    apply LinearMap.ext; intro b
    exact innerDerivation_add_left a₁ a₂ b
  map_smul' r a := by
    apply LinearMap.ext; intro b
    exact innerDerivation_smul_left r a b

/-! ## Bundled package -/

/-- Bundled package of the Jacobi identity, bracket closure, and bilinearity
for inner derivations of `h₃(𝕆)`. -/
structure InnerDerivationJacobiLiePackage where
  /-- Jacobi identity for `H3ODerivation` commutators. -/
  jacobi : ∀ D E F : H3ODerivation,
      ⁅⁅D, E⁆, F⁆ + ⁅⁅E, F⁆, D⁆ + ⁅⁅F, D⁆, E⁆ = 0
  /-- The inner derivation span is closed under brackets. -/
  bracket_closure : ∀ D E : H3ODerivation,
      D ∈ innerDerivationSubspace →
      E ∈ innerDerivationSubspace →
      ⁅D, E⁆ ∈ innerDerivationSubspace
  /-- The inner derivation map is bilinear. -/
  bilinear : H3O →ₗ[ℝ] H3O →ₗ[ℝ] H3ODerivation

/-- The bundled Jacobi–Lie package for inner derivations of `h₃(𝕆)`. -/
noncomputable def innerDerivationJacobiLiePackage :
    InnerDerivationJacobiLiePackage where
  jacobi := H3ODerivation_jacobi
  bracket_closure _ _ hD hE := innerDerivationSubspace_closed_bracket hD hE
  bilinear := innerDerivationBilinearMap

end PhysicsSM.Algebra.Jordan.H3O
