import Mathlib.Tactic

/-!
# P9 block-aliasing guardrail

This focused file isolates a tiny finite-algebra warning from the P9 offset
pilot: a fixed block-averaging coarse map can annihilate a mode purely because
the mode has zero sum inside the block. Such a zero is a coarse-map alignment
fact, not by itself a physical source-visibility signal.
-/

noncomputable section

open scoped BigOperators

namespace NullEdgeP9BlockAliasingGuardrail

abbrev Vec4 := Fin 4 -> Real

/-- The block-averaging row used by a size-4 coarse map with `1 / sqrt(4)` scale. -/
def blockAverage4 (x : Vec4) : Real :=
  (Finset.univ.sum fun i : Fin 4 => x i) / 2

/-- Rank-one kernel generated by a single mode. -/
def rankOneKernel4 (x : Vec4) : Fin 4 -> Fin 4 -> Real :=
  fun i j => x i * x j

/-- The one-cell coarse trace after applying the block-average row. -/
def blockAverageCoarseTrace4 (x : Vec4) : Real :=
  blockAverage4 x * blockAverage4 x

/-- The coarse trace of a rank-one mode is the square of the block average. -/
theorem blockAverageCoarseTrace4_eq_average_sq (x : Vec4) :
    blockAverageCoarseTrace4 x = blockAverage4 x ^ 2 := by
  sorry

/-- A mode with zero within-block sum is invisible to this block-average trace. -/
theorem blockAverage4_eq_zero_of_sum_zero
    (x : Vec4)
    (h : (Finset.univ.sum fun i : Fin 4 => x i) = 0) :
    blockAverage4 x = 0 := by
  sorry

/-- The same aligned zero-sum mode has zero coarse rank-one trace. -/
theorem blockAverageCoarseTrace4_eq_zero_of_sum_zero
    (x : Vec4)
    (h : (Finset.univ.sum fun i : Fin 4 => x i) = 0) :
    blockAverageCoarseTrace4 x = 0 := by
  sorry

/-- The block-average rank-one coarse trace is always nonnegative. -/
theorem blockAverageCoarseTrace4_nonneg (x : Vec4) :
    0 <= blockAverageCoarseTrace4 x := by
  sorry

end NullEdgeP9BlockAliasingGuardrail

end
