import CodeLatticeE8.E8.HammingConstruction
import CodeLatticeE8.Code.Hamming844WeightEnumerator
import CodeLatticeE8.ConstructionA.ThetaLift

/-!
# Construction A theta convolution for the extended Hamming [8,4,4] code

This module proves that the theta-series shell counts of the Construction A
lattice attached to the extended Hamming `[8,4,4]` code decompose as a Hamming
weight-distribution convolution:

```text
|{z ∈ Λ_A : sqNorm z = s}| =
    W₀ · contrib(0, s) + W₄ · contrib(4, s) + W₈ · contrib(8, s)
```

where `Ww` is the number of codewords of weight `w` and `contrib(w, s)` is
the number of integer 8-vectors that lift the canonical binary vector of
weight `w` and have squared norm `s`.

The proof partitions the shell by the mod-two reduction of each lattice vector,
then uses a coordinate-permutation argument to show that all codewords of the
same weight contribute equally.

## Conventions

- `sqNorm z = ∑ᵢ zᵢ²` is the **unscaled** integer squared norm.
- The shell index `s : ℕ` is the unscaled squared norm; the theta index is
  `s / 4` (by the doubly-even property, shells are nonzero only when `4 ∣ s`).

-/

set_option linter.style.longLine false
-- The central permutation and disjoint-union proofs are intentionally written
-- as readable tactic scripts.  These local linter suppressions keep the build
-- output quiet while preserving the proof term generated by the kernel.
set_option linter.style.setOption false
set_option linter.flexible false
set_option linter.style.multiGoal false

open CodeLatticeE8.ConstructionA
open CodeLatticeE8.Code
open CodeLatticeE8.E8

namespace CodeLatticeE8

/-! ## Definitions -/

/-- The Construction A shell at unscaled squared norm `s` for the extended
Hamming code. -/
def constructionAShellSet (s : ℕ) : Set (Fin 8 → ℤ) :=
  {z | z ∈ hammingConstructionA ∧ sqNorm z = ↑s}

/-- The fiber over a specific binary vector: integer 8-vectors whose mod-two
reduction is `c` and whose squared norm is `s`. -/
def fiberOverCodeword (c : BinaryVector 8) (s : ℕ) : Set (Fin 8 → ℤ) :=
  {z | reduceModTwo z = c ∧ sqNorm z = ↑s}

/-- The canonical binary vector of weight `w`: ones in the first `w`
positions, zeros elsewhere. -/
def canonBinaryVec8 (w : ℕ) : BinaryVector 8 :=
  fun i => if i.val < w then 1 else 0

/-- The weight contribution convolution: the number of integer lifts of the
canonical weight-`w` binary vector with squared norm `s`. -/
noncomputable def weightContribConvolution (w s : ℕ) : ℕ :=
  Set.ncard (fiberOverCodeword (canonBinaryVec8 w) s)

/-! ## Shell partition by codeword -/

private theorem shell_eq_biUnion (s : ℕ) :
    constructionAShellSet s =
      ⋃ c ∈ extendedHamming8Finset, fiberOverCodeword c s := by
  ext z
  simp [constructionAShellSet, fiberOverCodeword, hammingConstructionA]
  exact fun hz_code => by rw [← mem_extendedHamming8Finset_iff]

private theorem fibers_pairwiseDisjoint (s : ℕ) :
    (extendedHamming8Finset : Set (BinaryVector 8)).PairwiseDisjoint
      (fun c => fiberOverCodeword c s) := by
  intro c₁ hc₁ c₂ hc₂ hne
  simp_all +decide [Set.disjoint_left, fiberOverCodeword]

private theorem fiber_finite (c : BinaryVector 8) (s : ℕ) :
    Set.Finite (fiberOverCodeword c s) := by
  refine Set.Finite.subset (Set.finite_Icc (-s : Fin 8 → ℤ) s) ?_
  intro z hz
  obtain ⟨hz_code, hz_sq⟩ := hz
  have hz_bound : ∀ i, abs (z i) ≤ s := by
    intro i
    have hcoord_sq_le : z i ^ 2 ≤ s :=
      hz_sq ▸ Finset.single_le_sum (fun j hj => sq_nonneg (z j)) (Finset.mem_univ i)
    exact abs_le.mpr ⟨by nlinarith, by nlinarith⟩
  exact ⟨fun i => neg_le_of_abs_le (hz_bound i), fun i => le_of_abs_le (hz_bound i)⟩

/-! ## Auxiliary: ncard of finite disjoint biUnion -/

private theorem ncard_biUnion_of_disjoint_finite
    {α β : Type*} {S : Finset α} {f : α → Set β}
    (hd : (S : Set α).PairwiseDisjoint f)
    (hf : ∀ a ∈ S, (f a).Finite) :
    (⋃ a ∈ S, f a).ncard = ∑ a ∈ S, (f a).ncard := by
  nontriviality
  nontriviality
  induction S using Finset.induction <;> simp_all +decide
  · rw [@Set.ncard_union_eq]
    · rename_i a s ha ih
      exact congr_arg _ (ih fun x hx y hy hxy =>
        hd (Set.mem_insert_of_mem a hx) (Set.mem_insert_of_mem a hy) hxy)
    · rename_i a s ha ih
      simp_all +decide [Set.disjoint_left, Set.mem_iUnion]
      exact fun x hx y hy hxy =>
        Set.disjoint_left.mp (hd (Set.mem_insert _ _)
          (Set.mem_insert_of_mem _ hy) (by
            intro hay
            subst hay
            exact ha hy)) hx hxy
    · exact hf.1
    · exact Set.Finite.biUnion (Finset.finite_toSet _) hf.2
  · exact Classical.decEq α

private theorem shell_ncard_eq_sum (s : ℕ) :
    Set.ncard (constructionAShellSet s) =
      ∑ c ∈ extendedHamming8Finset, Set.ncard (fiberOverCodeword c s) := by
  rw [shell_eq_biUnion]
  exact ncard_biUnion_of_disjoint_finite (fibers_pairwiseDisjoint s)
    (fun c hc => fiber_finite c s)

/-! ## Permutation invariance of sqNorm and reduceModTwo -/

private theorem sqNorm_comp_equiv (z : Fin 8 → ℤ) (σ : Equiv.Perm (Fin 8)) :
    sqNorm (z ∘ σ) = sqNorm z :=
  Equiv.sum_comp σ fun i => z i ^ 2

private theorem reduceModTwo_comp_equiv (z : Fin 8 → ℤ) (σ : Equiv.Perm (Fin 8)) :
    reduceModTwo (z ∘ σ) = reduceModTwo z ∘ σ :=
  rfl

/-! ## Fiber ncard is permutation-invariant -/

private theorem fiber_ncard_comp_perm
    (c : BinaryVector 8) (σ : Equiv.Perm (Fin 8)) (s : ℕ) :
    Set.ncard (fiberOverCodeword (c ∘ σ) s) =
      Set.ncard (fiberOverCodeword c s) := by
  fapply Set.ncard_congr
  use fun a ha => a ∘ σ.symm
  · simp +contextual [fiberOverCodeword, reduceModTwo_comp_equiv]
    exact fun a ha₁ ha₂ =>
      ⟨funext fun i => by simp +decide, by rw [sqNorm_comp_equiv a σ.symm]; exact ha₂⟩
  · exact fun a b ha hb h => funext fun i => by simpa using congr_fun h (σ i)
  · intro b hb; use b ∘ σ; simp_all +decide [fiberOverCodeword]
    simp_all +decide [funext_iff, reduceModTwo, sqNorm]
    rw [← hb.2, Equiv.sum_comp σ fun i => b i ^ 2]

/-! ## Same-weight binary vectors are related by a permutation -/

/-- Any two binary vectors over `ZMod 2` with the same Hamming weight are
related by a coordinate permutation.  The proof constructs the permutation
via `Equiv.sumCompl`, using separate bijections on the support and its
complement. -/
private theorem exists_perm_of_same_hammingWeight
    (c₁ c₂ : BinaryVector 8)
    (hw : hammingWeight c₁ = hammingWeight c₂) :
    ∃ σ : Equiv.Perm (Fin 8), c₂ = c₁ ∘ σ := by
  revert c₁ c₂
  have h_perm : ∀ (c₁ c₂ : Fin 8 → Bool),
      (∑ i, if c₁ i then 1 else 0) = (∑ i, if c₂ i then 1 else 0) →
      ∃ σ : Equiv.Perm (Fin 8), ∀ i, c₂ i = c₁ (σ i) := by
    intro c₁ c₂ h
    set S₁ := Finset.univ.filter (fun i => c₁ i = true)
    set S₂ := Finset.univ.filter (fun i => c₂ i = true)
    obtain ⟨σ₁, _⟩ : ∃ σ₁ : S₁ ≃ S₂, True := by
      simp +zetaDelta at *
      exact ⟨Fintype.equivOfCardEq <| by simpa [Fintype.card_subtype] using h⟩
    obtain ⟨σ₂, _⟩ : ∃ σ₂ : { i : Fin 8 // i ∉ S₁ } ≃ { i : Fin 8 // i ∉ S₂ }, True := by
      have h_card_compl : Finset.card (Finset.univ \ S₁) = Finset.card (Finset.univ \ S₂) := by
        have h_card_support : S₁.card = S₂.card := by
          subst S₁
          subst S₂
          simpa using h
        simp [Finset.card_sdiff, h_card_support]
      exact ⟨Fintype.equivOfCardEq <| by simpa [Finset.card_sdiff] using h_card_compl, trivial⟩
    obtain ⟨σ, hσ⟩ : ∃ σ : Fin 8 ≃ Fin 8, ∀ i, i ∈ S₁ ↔ σ i ∈ S₂ :=
      ⟨Equiv.sumCompl (fun i => i ∈ S₁) |>.symm.trans
        (σ₁.sumCongr σ₂) |>.trans (Equiv.sumCompl (fun i => i ∈ S₂)), by
          intro i; by_cases hi : i ∈ S₁ <;> simp +decide [hi]
          exact σ₂ ⟨i, hi⟩ |>.2⟩
    use σ.symm
    intro i
    specialize hσ (σ.symm i)
    simpa [S₁, S₂] using hσ.symm
  intro c₁ c₂ h
  specialize h_perm (fun i => c₁ i = 1) (fun i => c₂ i = 1)
  simp_all +decide [hammingWeight]
  convert h_perm _
  · simp +decide [funext_iff, ZMod]
    grind
  · convert h using 2 <;> ext i <;>
      rcases Fin.exists_fin_two.mp ⟨c₁ i, rfl⟩ with h₁ | h₁ <;>
      rcases Fin.exists_fin_two.mp ⟨c₂ i, rfl⟩ with h₂ | h₂ <;>
      simp [h₁, h₂]

/-! ## Fiber ncard depends only on weight -/

private theorem fiber_ncard_eq_of_weight
    (c₁ c₂ : BinaryVector 8) (s : ℕ)
    (hw : hammingWeight c₁ = hammingWeight c₂) :
    Set.ncard (fiberOverCodeword c₁ s) =
      Set.ncard (fiberOverCodeword c₂ s) := by
  obtain ⟨σ, hσ⟩ := exists_perm_of_same_hammingWeight c₁ c₂ hw
  rw [hσ, fiber_ncard_comp_perm]

/-! ## Grouping the sum by weight class -/

private theorem canonBinaryVec8_weight_zero :
    hammingWeight (canonBinaryVec8 0) = 0 := by
  simp [canonBinaryVec8, hammingWeight]

private theorem canonBinaryVec8_weight_four :
    hammingWeight (canonBinaryVec8 4) = 4 := by
  simp [canonBinaryVec8, hammingWeight]
  decide

private theorem canonBinaryVec8_weight_eight :
    hammingWeight (canonBinaryVec8 8) = 8 := by
  simp [canonBinaryVec8, hammingWeight]

/-- Grouping the codeword sum by weight class. -/
private theorem sum_fibers_eq_weighted (s : ℕ) :
    ∑ c ∈ extendedHamming8Finset, Set.ncard (fiberOverCodeword c s) =
      extendedHamming8WeightDist 0 * weightContribConvolution 0 s +
      extendedHamming8WeightDist 4 * weightContribConvolution 4 s +
      extendedHamming8WeightDist 8 * weightContribConvolution 8 s := by
  have h_split :
      ∑ c ∈ extendedHamming8Finset, (fiberOverCodeword c s).ncard =
      ∑ w ∈ ({0, 4, 8} : Finset ℕ),
        ∑ c ∈ extendedHamming8Finset.filter (fun c => hammingWeight c = w),
          (fiberOverCodeword c s).ncard := by
    rw [← Finset.sum_biUnion]
    · rw [show (Finset.biUnion {0, 4, 8}
          fun w => Finset.filter (fun c => hammingWeight c = w)
            extendedHamming8Finset) = extendedHamming8Finset from ?_]
      decide +revert
    · exact fun x _ y _ hxy =>
        Finset.disjoint_left.mpr fun z hz₁ hz₂ => hxy <| by
          have hx_weight : hammingWeight z = x := (Finset.mem_filter.mp hz₁).2
          have hy_weight : hammingWeight z = y := (Finset.mem_filter.mp hz₂).2
          exact hx_weight.symm.trans hy_weight
  have h_replace : ∀ w ∈ ({0, 4, 8} : Finset ℕ),
      ∑ c ∈ extendedHamming8Finset.filter (fun c => hammingWeight c = w),
        (fiberOverCodeword c s).ncard =
      (extendedHamming8Finset.filter (fun c => hammingWeight c = w)).card *
        weightContribConvolution w s := by
    intro w hw
    have h_eq : ∀ c ∈ extendedHamming8Finset.filter (fun c => hammingWeight c = w),
        (fiberOverCodeword c s).ncard = weightContribConvolution w s := by
      intro c hc
      have h_weight : hammingWeight c = w := by grind
      apply fiber_ncard_eq_of_weight c (canonBinaryVec8 w) s
      fin_cases hw <;> simp +decide [h_weight]
    simpa using Finset.sum_congr rfl h_eq
  rw [h_split, Finset.sum_congr rfl h_replace]
  simp +decide [extendedHamming8WeightDist, mul_comm, Finset.filter_filter,
    extendedHamming8Finset]
  ring

/-! ## Main theorem -/

/--
**Construction A shell count as weight-distribution convolution.**

For the Construction A lattice attached to the extended Hamming `[8,4,4]` code,
the number of lattice vectors at unscaled squared norm `s` equals the
weight-distribution–weighted sum of per-weight lift counts:

```text
|shell(s)| = 1 · contrib(0, s) + 14 · contrib(4, s) + 1 · contrib(8, s).
```

Here `contrib(w, s)` counts integer 8-vectors whose first `w` coordinates are
odd, last `8 − w` coordinates are even, and whose coordinate squares sum to `s`.
-/
theorem constructionAShellCount_eq_weight_distribution_convolution
    (s : ℕ) :
    Set.ncard (constructionAShellSet s) =
      extendedHamming8WeightDist 0 * weightContribConvolution 0 s +
      extendedHamming8WeightDist 4 * weightContribConvolution 4 s +
      extendedHamming8WeightDist 8 * weightContribConvolution 8 s := by
  rw [shell_ncard_eq_sum, sum_fibers_eq_weighted]

end CodeLatticeE8
