import Mathlib.LinearAlgebra.LinearIndependent.Lemmas
import Mathlib.Tactic
import PhysicsSM.Algebra.Furey.LadderOperators
import PhysicsSM.Algebra.Octonion.ComplexOctonion

/-!
# Algebra.Furey.MinimalLeftIdeal

The primitive idempotent and minimal left ideal in ℂ⊗𝕆.

## The idempotent omega

In Furey's construction (Baez convention), the primitive idempotent is built from
the privileged imaginary unit e_7. In our XOR convention, e_7 = e111.

The idempotent in Furey (arXiv:1806.00612) takes the form:
  omega = (1/2)(1 - i·e111)    (in complex scalar + imaginary octonion notation)

This satisfies omega * omega = omega (idempotent) and is minimal (primitive).

Note: The precise coefficient and sign depend on the normalization convention in
the paper. The definition here follows the convention that omega is a left-handed
projector. The ConventionBridge guarantees e111 = e_7 (Baez) in our basis.

## The minimal left ideal J

The minimal left ideal is:
  J = (ℂ⊗𝕆) * omega  (left multiplication by omega on all of ℂ⊗𝕆)

J is an 8-dimensional ℂ-subspace of ℂ⊗𝕆. As a left module over Cl(6)
(generated by the ladder operators), J carries a single irreducible
representation corresponding to one generation of SM fermions.

## Basis of J

A ℂ-basis of J consists of:
  omega  = (1 - i*e111)/2                         (anti-electron / electron Q=-1)
  v1     = alpha_1 * omega                        (anti-up-quark, colour r Q=-2/3)
  v2     = alpha_2 * omega                        (anti-up-quark, colour g Q=-2/3)
  v3     = alpha_3 * omega                        (anti-up-quark, colour b Q=-2/3)
  v4     = alpha_1 * (alpha_2 * omega)            (anti-down-quark, colour rg Q=-1/3)
  v5     = alpha_1 * (alpha_3 * omega)            (anti-down-quark, colour rb Q=-1/3)
  v6     = alpha_2 * (alpha_3 * omega)            (anti-down-quark, colour gb Q=-1/3)
  nu     = alpha_1 * (alpha_2 * (alpha_3 * omega))(neutrino Q=0)

(Notation adapted from Furey; see the paper for the precise identification with
particle quantum numbers.)

## Sources

Source: Furey, arXiv:1806.00612, Section 2.
Provenance: clean-room formalization.

## Prerequisites

- `PhysicsSM.Algebra.Octonion.ComplexOctonion`
- `PhysicsSM.Algebra.Furey.LadderOperators`

## Status

Milestone 6 (Furey-style algebraic SM structure) — In progress.
omega, 8 basis states, complete Cl(6) action table, number operators,
and charge assignments proved.

All theorems in this file are trusted finite-coordinate computations.  The
semantic interpretation as Standard Model particle content follows Furey's
convention and still requires human review before being treated as physics
content; the Lean kernel verifies only the explicitly stated algebraic
equalities over the project XOR basis.
-/

namespace PhysicsSM.Algebra.Furey.MinimalLeftIdeal

open PhysicsSM.Algebra.Octonion.ComplexOctonion
open PhysicsSM.Algebra.Octonion
open PhysicsSM.Algebra.Furey.LadderOperators

/-- The primitive idempotent omega = (1 - i*e111)/2. -/
noncomputable def omega : ComplexOctonion :=
  { re := { c0 := 1/2, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 }
    im := { c0 := 0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=-1/2 } }

/-
The proof pattern used throughout this file is deliberately repetitive:
`ext` splits equality of complex octonions into the 16 real coordinate goals,
`simp` unfolds the relevant explicit coordinate definitions and multiplication
tables, and `ring` closes the remaining polynomial identity over `ℝ`.

This style is verbose but useful in trusted non-associative code.  It makes
parenthesization visible in the theorem statement and avoids any hidden appeal
to an associative algebra hierarchy that the octonions do not satisfy.
-/
theorem omega_idempotent : omega * omega = omega := by
  ext <;> simp [omega] <;> ring

/-- The three dagger operators annihilate omega from the left. -/
theorem alpha1_dag_kills_omega : alpha1_dag * omega = 0 := by
  ext <;> simp [alpha1_dag, omega] <;> ring

theorem alpha2_dag_kills_omega : alpha2_dag * omega = 0 := by
  ext <;> simp [alpha2_dag, omega] <;> ring

theorem alpha3_dag_kills_omega : alpha3_dag * omega = 0 := by
  ext <;> simp [alpha3_dag, omega] <;> ring

-- The 8 basis states (Creation operators acting on vacuum)

/-- v1: alpha1 * omega - anti-up quark, colour r. -/
noncomputable def v1 : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=1/2, c5:=0, c6:=0, c7:=0 }
    im := { c0:=0, c1:=0, c2:=0, c3:=1/2, c4:=0, c5:=0, c6:=0, c7:=0 } }

/-- v2: alpha2 * omega - anti-up quark, colour g. -/
noncomputable def v2 : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=-1/2, c7:=0 }
    im := { c0:=0, c1:=1/2, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 } }

/-- v3: alpha3 * omega - anti-up quark, colour b. -/
noncomputable def v3 : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=-1/2, c6:=0, c7:=0 }
    im := { c0:=0, c1:=0, c2:=1/2, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 } }

/-- v4: alpha1 * (alpha2 * omega) - anti-down quark, colour rg. -/
noncomputable def v4 : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=-1/2, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 }
    im := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=1/2, c6:=0, c7:=0 } }

/-- v5: alpha1 * (alpha3 * omega) - anti-down quark, colour rb. -/
noncomputable def v5 : ComplexOctonion :=
  { re := { c0:=0, c1:=1/2, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 }
    im := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=-1/2, c7:=0 } }

/-- v6: alpha2 * (alpha3 * omega) - anti-down quark, colour gb. -/
noncomputable def v6 : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=0, c3:=-1/2, c4:=0, c5:=0, c6:=0, c7:=0 }
    im := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=-1/2, c5:=0, c6:=0, c7:=0 } }

/-- nu: neutrino state = alpha1 * (alpha2 * (alpha3 * omega)). -/
noncomputable def nu : ComplexOctonion :=
  { re := { c0:=0, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=-1/2 }
    im := { c0:=1/2, c1:=0, c2:=0, c3:=0, c4:=0, c5:=0, c6:=0, c7:=0 } }

theorem v1_eq : alpha1 * omega = v1 := by ext <;> simp [alpha1, omega, v1] <;> ring
theorem v2_eq : alpha2 * omega = v2 := by ext <;> simp [alpha2, omega, v2] <;> ring
theorem v3_eq : alpha3 * omega = v3 := by ext <;> simp [alpha3, omega, v3] <;> ring
theorem v4_eq : alpha1 * (alpha2 * omega) = v4 := by ext <;> simp [alpha1, alpha2, omega, v4] <;> ring
theorem v5_eq : alpha1 * (alpha3 * omega) = v5 := by ext <;> simp [alpha1, alpha3, omega, v5] <;> ring
theorem v6_eq : alpha2 * (alpha3 * omega) = v6 := by ext <;> simp [alpha2, alpha3, omega, v6] <;> ring
theorem nu_eq : alpha1 * (alpha2 * (alpha3 * omega)) = nu := by ext <;> simp [alpha1, alpha2, alpha3, omega, nu] <;> ring

-- Theorems: verify basis elements belong to the ideal (x * omega = x)
theorem omega_in_J : omega * omega = omega := omega_idempotent
theorem v1_in_J : v1 * omega = v1 := by ext <;> simp [v1, omega] <;> ring
theorem v2_in_J : v2 * omega = v2 := by ext <;> simp [v2, omega] <;> ring
theorem v3_in_J : v3 * omega = v3 := by ext <;> simp [v3, omega] <;> ring

/-- The three creation operators annihilate nu. -/
theorem alpha1_kills_nu : alpha1 * nu = 0 := by ext <;> simp [alpha1, nu] <;> ring
theorem alpha2_kills_nu : alpha2 * nu = 0 := by ext <;> simp [alpha2, nu] <;> ring
theorem alpha3_kills_nu : alpha3 * nu = 0 := by ext <;> simp [alpha3, nu] <;> ring

-- Cl(6) Action Table

/-
The following action table records left multiplication by the six Clifford
generators on the eight explicit states.  Because `ℂ ⊗ 𝕆` is non-associative,
each theorem is about exactly the parenthesized expression shown; for example,
`alpha1 * (alpha2 * omega)` is not silently interchanged with
`(alpha1 * alpha2) * omega`.
-/

theorem act_a1_omega : alpha1 * omega = v1 := v1_eq
theorem act_a1_v1 : alpha1 * v1 = 0 := by ext <;> norm_num [alpha1, v1]
theorem act_a1_v2 : alpha1 * v2 = v4 := by ext <;> norm_num [alpha1, v2, v4]
theorem act_a1_v3 : alpha1 * v3 = v5 := by ext <;> norm_num [alpha1, v3, v5]
theorem act_a1_v4 : alpha1 * v4 = 0 := by ext <;> norm_num [alpha1, v4]
theorem act_a1_v5 : alpha1 * v5 = 0 := by ext <;> norm_num [alpha1, v5]
theorem act_a1_v6 : alpha1 * v6 = nu := by ext <;> norm_num [alpha1, v6, nu]
theorem act_a1_nu : alpha1 * nu = 0 := alpha1_kills_nu

theorem act_a2_omega : alpha2 * omega = v2 := v2_eq
theorem act_a2_v1 : alpha2 * v1 = -v4 := by ext <;> norm_num [alpha2, v1, v4]
theorem act_a2_v2 : alpha2 * v2 = 0 := by ext <;> norm_num [alpha2, v2]
theorem act_a2_v3 : alpha2 * v3 = v6 := by ext <;> norm_num [alpha2, v3, v6]
theorem act_a2_v4 : alpha2 * v4 = 0 := by ext <;> norm_num [alpha2, v4]
theorem act_a2_v5 : alpha2 * v5 = -nu := by ext <;> norm_num [alpha2, v5, nu]
theorem act_a2_v6 : alpha2 * v6 = 0 := by ext <;> norm_num [alpha2, v6]
theorem act_a2_nu : alpha2 * nu = 0 := alpha2_kills_nu

theorem act_a3_omega : alpha3 * omega = v3 := v3_eq
theorem act_a3_v1 : alpha3 * v1 = -v5 := by ext <;> norm_num [alpha3, v1, v5]
theorem act_a3_v2 : alpha3 * v2 = -v6 := by ext <;> norm_num [alpha3, v2, v6]
theorem act_a3_v3 : alpha3 * v3 = 0 := by ext <;> norm_num [alpha3, v3]
theorem act_a3_v4 : alpha3 * v4 = nu := by ext <;> norm_num [alpha3, v4, nu]
theorem act_a3_v5 : alpha3 * v5 = 0 := by ext <;> norm_num [alpha3, v5]
theorem act_a3_v6 : alpha3 * v6 = 0 := by ext <;> norm_num [alpha3, v6]
theorem act_a3_nu : alpha3 * nu = 0 := alpha3_kills_nu

theorem act_a1d_omega : alpha1_dag * omega = 0 := alpha1_dag_kills_omega
theorem act_a1d_v1 : alpha1_dag * v1 = omega := by ext <;> norm_num [alpha1_dag, v1, omega]
theorem act_a1d_v2 : alpha1_dag * v2 = 0 := by ext <;> norm_num [alpha1_dag, v2]
theorem act_a1d_v3 : alpha1_dag * v3 = 0 := by ext <;> norm_num [alpha1_dag, v3]
theorem act_a1d_v4 : alpha1_dag * v4 = v2 := by ext <;> norm_num [alpha1_dag, v4, v2]
theorem act_a1d_v5 : alpha1_dag * v5 = v3 := by ext <;> norm_num [alpha1_dag, v5, v3]
theorem act_a1d_v6 : alpha1_dag * v6 = 0 := by ext <;> norm_num [alpha1_dag, v6]
theorem act_a1d_nu : alpha1_dag * nu = v6 := by ext <;> norm_num [alpha1_dag, nu, v6]

theorem act_a2d_omega : alpha2_dag * omega = 0 := alpha2_dag_kills_omega
theorem act_a2d_v1 : alpha2_dag * v1 = 0 := by ext <;> norm_num [alpha2_dag, v1]
theorem act_a2d_v2 : alpha2_dag * v2 = omega := by ext <;> norm_num [alpha2_dag, v2, omega]
theorem act_a2d_v3 : alpha2_dag * v3 = 0 := by ext <;> norm_num [alpha2_dag, v3]
theorem act_a2d_v4 : alpha2_dag * v4 = -v1 := by ext <;> norm_num [alpha2_dag, v4, v1]
theorem act_a2d_v5 : alpha2_dag * v5 = 0 := by ext <;> norm_num [alpha2_dag, v5]
theorem act_a2d_v6 : alpha2_dag * v6 = v3 := by ext <;> norm_num [alpha2_dag, v6, v3]
theorem act_a2d_nu : alpha2_dag * nu = -v5 := by ext <;> norm_num [alpha2_dag, nu, v5]

theorem act_a3d_omega : alpha3_dag * omega = 0 := alpha3_dag_kills_omega
theorem act_a3d_v1 : alpha3_dag * v1 = 0 := by ext <;> norm_num [alpha3_dag, v1]
theorem act_a3d_v2 : alpha3_dag * v2 = 0 := by ext <;> norm_num [alpha3_dag, v2]
theorem act_a3d_v3 : alpha3_dag * v3 = omega := by ext <;> norm_num [alpha3_dag, v3, omega]
theorem act_a3d_v4 : alpha3_dag * v4 = 0 := by ext <;> norm_num [alpha3_dag, v4]
theorem act_a3d_v5 : alpha3_dag * v5 = -v1 := by ext <;> norm_num [alpha3_dag, v5, v1]
theorem act_a3d_v6 : alpha3_dag * v6 = -v2 := by ext <;> norm_num [alpha3_dag, v6, v2]
theorem act_a3d_nu : alpha3_dag * nu = v4 := by ext <;> norm_num [alpha3_dag, nu, v4]

-- Number operators and Charge

/-
The number operators are operator compositions:

  N_k(x) = alpha_k_dag * (alpha_k * x).

They are not products of a pre-composed algebra element with `x`.  This matters:
in the non-associative algebra, `(alpha_k_dag * alpha_k) * x` is a different
expression from `alpha_k_dag * (alpha_k * x)`.  The lemmas below therefore use
the action table as a two-step calculation whenever that keeps the proof
readable, and fall back to direct coordinate expansion for the signed cases.
-/

theorem N1_omega : alpha1_dag * (alpha1 * omega) = omega := by rw [act_a1_omega, act_a1d_v1]
theorem N1_v1 : alpha1_dag * (alpha1 * v1) = 0 := by ext <;> norm_num [alpha1_dag, alpha1, v1]
theorem N1_v2 : alpha1_dag * (alpha1 * v2) = v2 := by rw [act_a1_v2, act_a1d_v4]
theorem N1_v3 : alpha1_dag * (alpha1 * v3) = v3 := by rw [act_a1_v3, act_a1d_v5]
theorem N1_v4 : alpha1_dag * (alpha1 * v4) = 0 := by ext <;> norm_num [alpha1_dag, alpha1, v4]
theorem N1_v5 : alpha1_dag * (alpha1 * v5) = 0 := by ext <;> norm_num [alpha1_dag, alpha1, v5]
theorem N1_v6 : alpha1_dag * (alpha1 * v6) = v6 := by rw [act_a1_v6, act_a1d_nu]
theorem N1_nu : alpha1_dag * (alpha1 * nu) = 0 := by ext <;> norm_num [alpha1_dag, alpha1, nu]

theorem N2_omega : alpha2_dag * (alpha2 * omega) = omega := by rw [act_a2_omega, act_a2d_v2]
theorem N2_v1 : alpha2_dag * (alpha2 * v1) = v1 := by ext <;> norm_num [alpha2_dag, alpha2, v1]
theorem N2_v2 : alpha2_dag * (alpha2 * v2) = 0 := by ext <;> norm_num [alpha2_dag, alpha2, v2]
theorem N2_v3 : alpha2_dag * (alpha2 * v3) = v3 := by rw [act_a2_v3, act_a2d_v6]
theorem N2_v4 : alpha2_dag * (alpha2 * v4) = 0 := by ext <;> norm_num [alpha2_dag, alpha2, v4]
theorem N2_v5 : alpha2_dag * (alpha2 * v5) = v5 := by ext <;> norm_num [alpha2_dag, alpha2, v5]
theorem N2_v6 : alpha2_dag * (alpha2 * v6) = 0 := by ext <;> norm_num [alpha2_dag, alpha2, v6]
theorem N2_nu : alpha2_dag * (alpha2 * nu) = 0 := by ext <;> norm_num [alpha2_dag, alpha2, nu]

theorem N3_omega : alpha3_dag * (alpha3 * omega) = omega := by rw [act_a3_omega, act_a3d_v3]
theorem N3_v1 : alpha3_dag * (alpha3 * v1) = v1 := by ext <;> norm_num [alpha3_dag, alpha3, v1]
theorem N3_v2 : alpha3_dag * (alpha3 * v2) = v2 := by ext <;> norm_num [alpha3_dag, alpha3, v2]
theorem N3_v3 : alpha3_dag * (alpha3 * v3) = 0 := by ext <;> norm_num [alpha3_dag, alpha3, v3]
theorem N3_v4 : alpha3_dag * (alpha3 * v4) = v4 := by rw [act_a3_v4, act_a3d_nu]
theorem N3_v5 : alpha3_dag * (alpha3 * v5) = 0 := by ext <;> norm_num [alpha3_dag, alpha3, v5]
theorem N3_v6 : alpha3_dag * (alpha3 * v6) = 0 := by ext <;> norm_num [alpha3_dag, alpha3, v6]
theorem N3_nu : alpha3_dag * (alpha3 * nu) = 0 := by ext <;> norm_num [alpha3_dag, alpha3, nu]

theorem charge_omega :
    alpha1_dag * (alpha1 * omega) + alpha2_dag * (alpha2 * omega)
    + alpha3_dag * (alpha3 * omega) = 3 • omega := by
  simp [N1_omega, N2_omega, N3_omega]
  ext <;> norm_num [omega]

theorem charge_v1 :
    alpha1_dag * (alpha1 * v1) + alpha2_dag * (alpha2 * v1)
    + alpha3_dag * (alpha3 * v1) = 2 • v1 := by
  simp [N1_v1, N2_v1, N3_v1]
  ext <;> norm_num [v1]

theorem charge_v2 :
    alpha1_dag * (alpha1 * v2) + alpha2_dag * (alpha2 * v2)
    + alpha3_dag * (alpha3 * v2) = 2 • v2 := by
  simp [N1_v2, N2_v2, N3_v2]
  ext <;> norm_num [v2]

theorem charge_v3 :
    alpha1_dag * (alpha1 * v3) + alpha2_dag * (alpha2 * v3)
    + alpha3_dag * (alpha3 * v3) = 2 • v3 := by
  simp [N1_v3, N2_v3, N3_v3]
  ext <;> norm_num [v3]

theorem charge_v4 :
    alpha1_dag * (alpha1 * v4) + alpha2_dag * (alpha2 * v4)
    + alpha3_dag * (alpha3 * v4) = 1 • v4 := by
  simp [N1_v4, N2_v4, N3_v4]

theorem charge_v5 :
    alpha1_dag * (alpha1 * v5) + alpha2_dag * (alpha2 * v5)
    + alpha3_dag * (alpha3 * v5) = 1 • v5 := by
  simp [N1_v5, N2_v5, N3_v5]

theorem charge_v6 :
    alpha1_dag * (alpha1 * v6) + alpha2_dag * (alpha2 * v6)
    + alpha3_dag * (alpha3 * v6) = 1 • v6 := by
  simp [N1_v6, N2_v6, N3_v6]

theorem charge_nu :
    alpha1_dag * (alpha1 * nu) + alpha2_dag * (alpha2 * nu)
    + alpha3_dag * (alpha3 * nu) = 0 := by
  simp [N1_nu, N2_nu, N3_nu]

-- Non-zero status

theorem omega_ne_zero : omega ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c0) h
  norm_num [omega] at hcoord

theorem v1_ne_zero : v1 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c4) h
  norm_num [v1] at hcoord

theorem v2_ne_zero : v2 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c6) h
  norm_num [v2] at hcoord

theorem v3_ne_zero : v3 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c5) h
  norm_num [v3] at hcoord

theorem v4_ne_zero : v4 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c2) h
  norm_num [v4] at hcoord

theorem v5_ne_zero : v5 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c1) h
  norm_num [v5] at hcoord

theorem v6_ne_zero : v6 ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c3) h
  norm_num [v6] at hcoord

theorem nu_ne_zero : nu ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c7) h
  norm_num [nu] at hcoord

-- ============================================================================
-- Linear independence of the 8 basis states over ℂ
-- ============================================================================

/-!
## Linear independence over ℂ

`basis_linear_independent` shows that the eight states

  omega, v1, v2, v3, v4, v5, v6, nu

form a **linearly independent set over ℂ** in `ComplexOctonion`.  Together
with the fact that each state is non-zero and that they are generated by the
Cl(6) action on omega, this confirms that J is (at least) 8-dimensional.

### Proof sketch

`Fintype.linearIndependent_iff` reduces the claim to showing that any
ℂ-linear combination `∑ gᵢ · basisᵢ = 0` forces every coefficient `gᵢ = 0`.
Each basis state has a *unique non-zero component* in its 16 real coordinates
(8 for the real octonion part, 8 for the imaginary part):

| State  | Unique non-zero coordinate |
|--------|---------------------------|
| omega  | re.c0 = 1/2              |
| v1     | re.c4 = 1/2              |
| v2     | re.c6 = -1/2             |
| v3     | re.c5 = -1/2             |
| v4     | re.c2 = -1/2             |
| v5     | re.c1 = 1/2              |
| v6     | re.c3 = -1/2             |
| nu     | re.c7 = -1/2             |

Because these *real-part* witnesses are all in distinct components, the
16×8 coordinate matrix (over ℝ) has a non-singular 8×8 minor, making the
set ℂ-linearly independent.

The proof uses `simp +decide` and `grind` to fully automate the coordinate
case analysis.  The `Module ℂ ComplexOctonion` instance (in
`PhysicsSM.Algebra.Octonion.ComplexOctonion`) provides the linear-algebra
typeclass context.

Source: argument verified via Python oracle; theorem proved by Aristotle
job 72a89d00-f09a-45b1-8e6d-fc151ffb6c7d.
-/

/-- The eight basis states of the minimal left ideal J are linearly independent
    over ℂ, confirming J is at least 8-dimensional as a ℂ-vector space. -/
theorem basis_linear_independent :
    LinearIndependent ℂ (fun i : Fin 8 =>
      match i with
      | 0 => omega
      | 1 => v1
      | 2 => v2
      | 3 => v3
      | 4 => v4
      | 5 => v5
      | 6 => v6
      | 7 => nu) := by
  rw [Fintype.linearIndependent_iff]
  intro g hg
  simp +decide [Fin.sum_univ_succ] at hg
  simp_all +decide [Complex.ext_iff, ComplexOctonion.ext_iff]
  simp_all +decide [omega, v1, v2, v3, v4, v5, v6, nu, Octonion.ext_iff]
  norm_num [Fin.forall_fin_succ] at *
  grind

-- SU(3) generators (Gell-Mann style, from ladder bilinears)
-- These act on the anti-up triplet {v1, v2, v3} and anti-down triplet {v4, v5, v6}

/-- T12: raises colour g->r (mode 2 → mode 1 generator)
    Acts as: v2 ↦ v1, v1 ↦ 0 on the triplet sector. -/
noncomputable def T12 : ComplexOctonion := alpha1 * alpha2_dag

/-- T21: raises colour r->g -/
noncomputable def T21 : ComplexOctonion := alpha2 * alpha1_dag

/-- T13: raises colour b->r -/
noncomputable def T13 : ComplexOctonion := alpha1 * alpha3_dag

/-- T31: raises colour r->b -/
noncomputable def T31 : ComplexOctonion := alpha3 * alpha1_dag

/-- T23: raises colour b->g -/
noncomputable def T23 : ComplexOctonion := alpha2 * alpha3_dag

/-- T32: raises colour g->b -/
noncomputable def T32 : ComplexOctonion := alpha3 * alpha2_dag

-- SU(3) action on anti-up triplet {v1, v2, v3}:
-- Prove T12 maps v2 -> v1, T21 maps v1 -> v2, etc.
-- These follow from the action table: alpha1*(alpha2_dag*v2) = alpha1*omega = v1
-- Note: in non-associative algebra, (alpha1 * alpha2_dag) * v2
--       is NOT the same as alpha1 * (alpha2_dag * v2) in general!
-- Use the explicit coordinate proofs:
-- The actual SU(3) action is via OPERATOR composition, not algebra product.
-- This section remains to be formalized.

/-! ## Complementary idempotent and arithmetic anomaly certificate -/

/--
The complementary primitive idempotent to `omega`.

In the project convention, `omega = (1/2) * (1 - i * e111)`. This definition
uses the opposite sign in the imaginary `e111` coordinate:
`omega_bar = (1/2) * (1 + i * e111)`.

This is an algebraic complement inside the concrete complex octonion model. The
charge-conjugation interpretation is recorded only as convention-level
documentation below; the theorems in this section are finite coordinate
identities and exact rational arithmetic.

Provenance: Aristotle job `68efb3f8-03cf-49d3-99ec-328690e68529`.
-/
noncomputable def omega_bar : ComplexOctonion :=
  { re := { c0 := 1 / 2, c1 := 0, c2 := 0, c3 := 0,
             c4 := 0, c5 := 0, c6 := 0, c7 := 0 }
    im := { c0 := 0, c1 := 0, c2 := 0, c3 := 0,
             c4 := 0, c5 := 0, c6 := 0, c7 := 1 / 2 } }

/-- The complementary idempotent squares to itself. -/
theorem omega_bar_idempotent : omega_bar * omega_bar = omega_bar := by
  ext <;> simp [omega_bar] <;> ring

/-- The two complementary idempotents add to the unit. -/
theorem omega_plus_omega_bar : omega + omega_bar = 1 := by
  ext <;> simp [omega, omega_bar] <;> ring

/-- The idempotent `omega` annihilates `omega_bar` on the left. -/
theorem omega_mul_omega_bar : omega * omega_bar = 0 := by
  ext <;> simp [omega, omega_bar] <;> ring

/-- The idempotent `omega_bar` annihilates `omega` on the left. -/
theorem omega_bar_mul_omega : omega_bar * omega = 0 := by
  ext <;> simp [omega_bar, omega] <;> ring

/-- The complementary idempotent is not the zero complex octonion. -/
theorem omega_bar_ne_zero : omega_bar ≠ 0 := by
  intro h
  have hcoord := congr_arg (fun x : ComplexOctonion => x.re.c0) h
  norm_num [omega_bar] at hcoord

/-!
### Candidate basis states for the complementary ideal

The following elements mirror the existing `omega`, `v1`, ..., `v6`, `nu`
states, but start from `omega_bar`. They are useful as named anchors for later
operator-level charge-conjugation theorems.

Important limitation: this file does not import
`PhysicsSM.Algebra.Furey.OperatorRepresentations`, because that file already
depends on `MinimalLeftIdeal.lean`. Charge-eigenvalue theorems for these
`omega_bar` states therefore belong in a downstream file, not here.
-/

/-- First one-particle state generated from `omega_bar`. -/
noncomputable def vbar1 : ComplexOctonion := alpha1 * omega_bar

/-- Second one-particle state generated from `omega_bar`. -/
noncomputable def vbar2 : ComplexOctonion := alpha2 * omega_bar

/-- Third one-particle state generated from `omega_bar`. -/
noncomputable def vbar3 : ComplexOctonion := alpha3 * omega_bar

/-- First two-particle state generated from `omega_bar`. -/
noncomputable def vbar4 : ComplexOctonion := alpha1 * (alpha2 * omega_bar)

/-- Second two-particle state generated from `omega_bar`. -/
noncomputable def vbar5 : ComplexOctonion := alpha1 * (alpha3 * omega_bar)

/-- Third two-particle state generated from `omega_bar`. -/
noncomputable def vbar6 : ComplexOctonion := alpha2 * (alpha3 * omega_bar)

/-- Three-particle state generated from `omega_bar`. -/
noncomputable def nu_bar : ComplexOctonion :=
  alpha1 * (alpha2 * (alpha3 * omega_bar))

/-!
### Exact rational anomaly arithmetic for `J` plus its complementary partner

The theorems below are intentionally arithmetic certificates. They do not prove
that the listed rational numbers are operator eigenvalues for every state in
this file. The existing charge table for `J` is proved earlier from the number
operators; the complementary-sector signs are recorded here as the conventional
charge-conjugate arithmetic target for a later operator-level proof.
-/

/-- Sum of electric charges over the existing `J` charge table. -/
theorem charge_sum_J :
    (-1 : Rat) + (-2 / 3) + (-2 / 3) + (-2 / 3) +
      (-1 / 3) + (-1 / 3) + (-1 / 3) + 0 = -4 := by
  norm_num

/-- Sum of electric charges over the sign-reversed complementary table. -/
theorem charge_sum_Jbar :
    (1 : Rat) + (2 / 3) + (2 / 3) + (2 / 3) +
      (1 / 3) + (1 / 3) + (1 / 3) + 0 = 4 := by
  norm_num

/-- The linear electric-charge sum cancels between `J` and `Jbar`. -/
theorem anomaly_linear_Q : (-4 : Rat) + 4 = 0 := by
  norm_num

/-- Sum of cubed electric charges over the existing `J` charge table. -/
theorem cubic_charge_sum_J :
    (-1 : Rat) ^ 3 + (-2 / 3) ^ 3 + (-2 / 3) ^ 3 + (-2 / 3) ^ 3 +
      (-1 / 3) ^ 3 + (-1 / 3) ^ 3 + (-1 / 3) ^ 3 + 0 ^ 3 = -2 := by
  norm_num

/-- Sum of cubed electric charges over the sign-reversed complementary table. -/
theorem cubic_charge_sum_Jbar :
    (1 : Rat) ^ 3 + (2 / 3) ^ 3 + (2 / 3) ^ 3 + (2 / 3) ^ 3 +
      (1 / 3) ^ 3 + (1 / 3) ^ 3 + (1 / 3) ^ 3 + 0 ^ 3 = 2 := by
  norm_num

/-- The cubic electric-charge sum cancels between `J` and `Jbar`. -/
theorem anomaly_cubic_Q : (-2 : Rat) + 2 = 0 := by
  norm_num

/-- Sum of electric charges over the colored states of `J`. -/
theorem coloured_charge_sum_J :
    (-2 / 3 : Rat) + (-2 / 3) + (-2 / 3) +
      (-1 / 3) + (-1 / 3) + (-1 / 3) = -3 := by
  norm_num

/-- Sum of electric charges over the sign-reversed complementary colored table. -/
theorem coloured_charge_sum_Jbar :
    (2 / 3 : Rat) + (2 / 3) + (2 / 3) +
      (1 / 3) + (1 / 3) + (1 / 3) = 3 := by
  norm_num

/-- The mixed colored electric-charge sum cancels between `J` and `Jbar`. -/
theorem anomaly_su3_Q : (-3 : Rat) + 3 = 0 := by
  norm_num

/-!
### Candidate hypercharge table from an explicit weak-isospin target

The electric-charge values above come from the number-operator calculation.
The weak-isospin values in this section are target constants.  Hypercharge is
therefore computed here only after that target `T3` table has been supplied,
using the Standard Model convention `Y = 2 * (Q - T3)`.
-/

/-- Weak-isospin target value assigned to `omega`. -/
def T3_omega : Rat := -1 / 2

/-- Weak-isospin target value assigned to `v1`. -/
def T3_v1 : Rat := 0

/-- Weak-isospin target value assigned to `v2`. -/
def T3_v2 : Rat := 0

/-- Weak-isospin target value assigned to `v3`. -/
def T3_v3 : Rat := 0

/-- Weak-isospin target value assigned to `v4`. -/
def T3_v4 : Rat := 0

/-- Weak-isospin target value assigned to `v5`. -/
def T3_v5 : Rat := 0

/-- Weak-isospin target value assigned to `v6`. -/
def T3_v6 : Rat := 0

/-- Weak-isospin target value assigned to `nu`. -/
def T3_nu : Rat := 1 / 2

/-- Hypercharge target value `Y = 2 * (Q - T3)` for `omega`. -/
def Y_omega : Rat := 2 * ((-1 : Rat) - T3_omega)

/-- Hypercharge target value for `v1`. -/
def Y_v1 : Rat := 2 * ((-2 / 3 : Rat) - T3_v1)

/-- Hypercharge target value for `v2`. -/
def Y_v2 : Rat := 2 * ((-2 / 3 : Rat) - T3_v2)

/-- Hypercharge target value for `v3`. -/
def Y_v3 : Rat := 2 * ((-2 / 3 : Rat) - T3_v3)

/-- Hypercharge target value for `v4`. -/
def Y_v4 : Rat := 2 * ((-1 / 3 : Rat) - T3_v4)

/-- Hypercharge target value for `v5`. -/
def Y_v5 : Rat := 2 * ((-1 / 3 : Rat) - T3_v5)

/-- Hypercharge target value for `v6`. -/
def Y_v6 : Rat := 2 * ((-1 / 3 : Rat) - T3_v6)

/-- Hypercharge target value for `nu`. -/
def Y_nu : Rat := 2 * ((0 : Rat) - T3_nu)

/-- The hypercharge target for `omega` reduces to `-1`. -/
theorem Y_omega_val : Y_omega = -1 := by
  unfold Y_omega T3_omega
  norm_num

/-- The hypercharge target for `v1` reduces to `-4 / 3`. -/
theorem Y_v1_val : Y_v1 = -4 / 3 := by
  unfold Y_v1 T3_v1
  norm_num

/-- The hypercharge target for `v2` reduces to `-4 / 3`. -/
theorem Y_v2_val : Y_v2 = -4 / 3 := by
  unfold Y_v2 T3_v2
  norm_num

/-- The hypercharge target for `v3` reduces to `-4 / 3`. -/
theorem Y_v3_val : Y_v3 = -4 / 3 := by
  unfold Y_v3 T3_v3
  norm_num

/-- The hypercharge target for `v4` reduces to `-2 / 3`. -/
theorem Y_v4_val : Y_v4 = -2 / 3 := by
  unfold Y_v4 T3_v4
  norm_num

/-- The hypercharge target for `v5` reduces to `-2 / 3`. -/
theorem Y_v5_val : Y_v5 = -2 / 3 := by
  unfold Y_v5 T3_v5
  norm_num

/-- The hypercharge target for `v6` reduces to `-2 / 3`. -/
theorem Y_v6_val : Y_v6 = -2 / 3 := by
  unfold Y_v6 T3_v6
  norm_num

/-- The hypercharge target for `nu` reduces to `-1`. -/
theorem Y_nu_val : Y_nu = -1 := by
  unfold Y_nu T3_nu
  norm_num

/-- The two target lepton-doublet states have the same hypercharge. -/
theorem lepton_doublet_hypercharge : Y_omega = Y_nu := by
  rw [Y_omega_val, Y_nu_val]

/-- Sum of hypercharges over the two target weak-doublet states in `J`. -/
theorem doublet_hypercharge_sum_J : Y_omega + Y_nu = -2 := by
  rw [Y_omega_val, Y_nu_val]
  norm_num

/--
The mixed `SU(2)^2 U(1)_Y` target sum cancels between `J` and `Jbar`.
-/
theorem anomaly_su2_Y :
    Y_omega + Y_nu + (-(Y_omega + Y_nu)) = 0 := by
  ring

/-- Sum of cubed hypercharge target values over `J`. -/
theorem cubic_Y_sum_J :
    Y_omega ^ 3 + Y_nu ^ 3 + Y_v1 ^ 3 + Y_v2 ^ 3 + Y_v3 ^ 3 +
      Y_v4 ^ 3 + Y_v5 ^ 3 + Y_v6 ^ 3 = -10 := by
  rw [Y_omega_val, Y_nu_val, Y_v1_val, Y_v2_val, Y_v3_val,
    Y_v4_val, Y_v5_val, Y_v6_val]
  norm_num

/-- The cubic hypercharge target sum cancels between `J` and `Jbar`. -/
theorem anomaly_cubic_Y : (-10 : Rat) + 10 = 0 := by
  norm_num

/-- Sum of hypercharge target values over the colored states of `J`. -/
theorem coloured_Y_sum_J :
    Y_v1 + Y_v2 + Y_v3 + Y_v4 + Y_v5 + Y_v6 = -6 := by
  rw [Y_v1_val, Y_v2_val, Y_v3_val, Y_v4_val, Y_v5_val, Y_v6_val]
  norm_num

/-- The mixed colored hypercharge target sum cancels between `J` and `Jbar`. -/
theorem anomaly_su3_Y : (-6 : Rat) + 6 = 0 := by
  norm_num

/-- Number of target weak-doublet states in `J`. -/
def n_doublet_J : Nat := 2

/-- Number of target weak-doublet states in the complementary sector. -/
def n_doublet_Jbar : Nat := 2

/-- The combined target weak-doublet count is even. -/
theorem witten_su2_anomaly_free :
    Even (n_doublet_J + n_doublet_Jbar) := by
  unfold n_doublet_J n_doublet_Jbar
  decide

/--
Bundled exact-arithmetic anomaly certificate for the `J` plus `Jbar` target
charge table.

This theorem is an arithmetic checkpoint, not yet the final operator-level
physics theorem. The missing bridge is to prove, in a downstream module, that
the listed `Jbar` and weak-isospin target values are eigenvalues of the
appropriate project operators.
-/
theorem furey_generation_anomaly_free :
    (-4 : Rat) + 4 = 0 ∧
    (-2 : Rat) + 2 = 0 ∧
    (-3 : Rat) + 3 = 0 ∧
    (Y_omega + Y_nu + (-(Y_omega + Y_nu)) = 0) ∧
    (-10 : Rat) + 10 = 0 ∧
    (-6 : Rat) + 6 = 0 ∧
    Even (n_doublet_J + n_doublet_Jbar) := by
  refine ⟨by norm_num, by norm_num, by norm_num, by ring,
    by norm_num, by norm_num, ?_⟩
  exact witten_su2_anomaly_free


end PhysicsSM.Algebra.Furey.MinimalLeftIdeal
