import PhysicsSM.Algebra.Octonion.ComplexOctonion
import PhysicsSM.Algebra.Octonion.ConventionBridge

/-!
# Algebra.Furey.Basic

Overview of the Furey algebraic Standard Model construction in the project
XOR convention.

## Summary of the construction

Furey's program derives Standard Model gauge symmetries and particle quantum
numbers from the algebra of complexified octonions ℂ ⊗_ℝ 𝕆.

The key steps are:

1. **Ladder operators**: Three elements α₁, α₂, α₃ ∈ ℂ⊗𝕆 satisfying
   anticommutation relations `{αᵢ, αⱼ†} = δᵢⱼ` and nilpotency `αᵢ² = 0`.
   These generate a Clifford algebra Cl(6) by left multiplication.

2. **Minimal left ideal**: The ideal J ⊂ ℂ⊗𝕆 generated by a primitive
   idempotent ω. In the XOR convention, the privileged imaginary unit
   `e111` plays the role of Furey's `e₇`.

3. **Particle states**: Applying the ladder operators and their adjoints to
   a "vacuum" state ν = α₁α₂α₃ω recovers the quantum numbers of one
   generation of SM particles:
   - Anti-neutrino (colour singlet, charge 0)
   - Three anti-up quarks (colour triplet, charge 2/3)
   - Electron (colour singlet, charge −1)
   - Three down quarks (colour triplet, charge −1/3)
   and their antiparticles.

4. **Symmetry recovery**: The unbroken symmetries of the ladder-operator
   construction give SU(3)_c × U(1)_em, with SU(2)_L emerging from
   quaternionic structure or the second ideal.

## Convention alignment

All constructions here use the project XOR convention.
Furey's original Baez-convention formulas must be translated via
`PhysicsSM.Algebra.Octonion.ConventionBridge` before use.

In particular:
- Furey's "e₇" = our `e111` (both are index 7 in their respective conventions)
- Furey's ladder α₁ = (−e₅+i·e₄)/2 becomes (+e100+i·e011)/2 in XOR
  (note the sign change from e₅ → −e100)

See `PhysicsSM.Algebra.Furey.LadderOperators` for the explicit XOR definitions.

## Key sources

All formalization targets are clean-room derivations from the following papers.
No external code is copied.

| Citation key | Reference |
|---|---|
| furey_thesis_2016 | Furey, "Standard model physics from an algebra?", PhD thesis, U. Waterloo, 2016. arXiv:1611.09182 |
| furey_charge_2015 | Furey, "Charge quantization from a number operator", Phys. Lett. B 742 (2015) 195–199. arXiv:1603.04783 |
| furey_su3_2018 | Furey, "Three generations, two unbroken gauge symmetries, and one eight-dimensional algebra", Phys. Lett. B 785 (2018). arXiv:1805.06631 |
| furey_sm_2018 | Furey, "SU(3)_C × SU(2)_L × U(1)_Y (×U(1)_X) as a symmetry of division algebraic ladder operators", EPJC 78 (2018) 375. arXiv:1806.00612 |

## Module map

```
PhysicsSM.Algebra.Furey.Basic               ← this file
PhysicsSM.Algebra.Furey.LadderOperators     ← alpha_1, alpha_2, alpha_3
PhysicsSM.Algebra.Furey.MinimalLeftIdeal    ← primitive idempotent, ideal J
PhysicsSM.Algebra.Furey.OperatorRepresentations ← left-multiplication operators on J
PhysicsSM.Algebra.Furey.CliffordConnection ← Cl(6) from left multiplication
PhysicsSM.Algebra.Furey.SMStates           ← SM particle states in J
PhysicsSM.Algebra.Furey.QuantumNumbers     ← U(1) and SU(3) generators
```

## Status

Stub — structure and API to be defined in child modules.
-/

namespace PhysicsSM.Algebra.Furey

end PhysicsSM.Algebra.Furey
