import Mathlib
import PhysicsSM.Algebra.Furey.T3OpJbar
import PhysicsSM.Algebra.Furey.WeakIsospinDoublets
import PhysicsSM.Algebra.Furey.WeakIsospinLadder

/-!
# Derived weak-isospin ladder operators

This module gives an alternative, basis-decomposition construction of the
weak-isospin raising (`T⁺`) and lowering (`T⁻`) operators on the finite
`JbarWavefunction` space, and proves that they coincide with the
permutation-based definitions in `WeakIsospinLadder`.

## Construction

We define rank-1 "ket-bra" operators `ketbra i j` acting as `|i⟩⟨j|` on the
standard basis of `JbarWavefunction = Fin 8 → ℂ`, then express `T⁺` and `T⁻`
as explicit sums:

```text
T⁺ = |ν⟩⟨e| + |u_r⟩⟨d_r| + |u_g⟩⟨d_g| + |u_b⟩⟨d_b|
T⁻ = |e⟩⟨ν| + |d_r⟩⟨u_r| + |d_g⟩⟨u_g| + |d_b⟩⟨u_b|
```

## Main results

- `TPlusDerived`  / `TMinusDerived`  — spectral-decomposition definitions.
- `TPlusDerived_eq_TPlusEnd`  — derived raising operator equals `TPlusEnd`.
- `TMinusDerived_eq_TMinusEnd` — derived lowering operator equals
  `TMinusEnd`.
- `TPlusEnd_unique` — uniqueness: any continuous-linear endomorphism
  satisfying `[T₃, T] = T`, `[Y, T] = 0`, and the correct action on
  the four T₃ = −1/2 basis states, must equal `TPlusEnd`.
- `TMinusEnd_unique` — the analogous uniqueness for `TMinusEnd`.

## Claim boundary

This file characterizes the W± operators at the operator level on
`JbarWavefunction`. It does **not** derive them from Furey's octonionic
ladder operators α₁, α₂, α₃, because the necessary infrastructure is
not yet present:

1. **Missing Jbar action table**: the complete Cl(6) action table
   `alpha_k * vbar_j = …` for the Jbar basis states has not been
   formalized (only number-operator eigenvalues are proved in
   `AnomalyBridge`).

2. **Missing coordinate isomorphism**: there is no formalized linear
   isomorphism between `Submodule.span ℂ (Set.range JbarBasisState')`
   (the octonionic minimal left ideal) and `JbarWavefunction`
   (the coordinate representation `Fin 8 → ℂ`).

3. **Missing weak-isospin operator in ℂ⊗𝕆**: the weak-isospin T⁺
   operator arises from the quaternionic factor in ℂ⊗ℍ⊗𝕆 (or
   equivalently from a specific SU(2) symmetry of ℂ⊗𝕆 that is not
   the Cl(6) generated by the αₖ). No such operator definition
   exists in the Furey namespace yet.

Once items 1–3 are in place, the full derivation would:
- define `TPlusOctonionic` on `ComplexOctonion` using the relevant
  algebra element,
- prove its action on each `JbarBasisState'` matches the table,
- transport through the coordinate isomorphism to obtain
  `TPlusDerived`,
- conclude `TPlusDerived = TPlusEnd` via the theorems in this file.

## Status

Trusted module: no `sorry`, `admit`, `axiom`, `opaque`, or `unsafe`.
-/

namespace PhysicsSM.Algebra.Furey.WeakIsospinLadderDerived

open PhysicsSM.Algebra.Furey.ElectroweakBridge
open PhysicsSM.Algebra.Furey.OperatorElectroweakIdentity
open PhysicsSM.Algebra.Furey.T3OpJbar
open PhysicsSM.Algebra.Furey.WeakIsospinLadder
open Complex

/-! ## Rank-1 operators (ket-bra) -/

/-- The rank-1 linear map `|i⟩⟨j|` on `JbarWavefunction`:
    `(ketbraLM i j)(ψ) = ψ(j) • e_i`. -/
noncomputable def ketbraLM (i j : JbarState) :
    JbarWavefunction →ₗ[ℂ] JbarWavefunction where
  toFun := fun psi => psi j • JbarBasisState i
  map_add' := fun x y => by
    simp [Pi.add_apply, add_smul]
  map_smul' := fun c x => by
    simp [Pi.smul_apply, smul_eq_mul, smul_smul]

/-- The rank-1 continuous linear operator `|i⟩⟨j|` on
    `JbarWavefunction`. -/
noncomputable def ketbra (i j : JbarState) :
    JbarWavefunction →L[ℂ] JbarWavefunction where
  toLinearMap := ketbraLM i j
  cont := (ketbraLM i j).continuous_of_finiteDimensional

theorem ketbra_apply_def (i j : JbarState)
    (psi : JbarWavefunction) :
    ketbra i j psi = psi j • JbarBasisState i := rfl

/-! ## Derived T⁺ and T⁻ from spectral decomposition -/

/-- The weak-isospin raising operator, defined as a sum of rank-1
    operators:
    `T⁺ = |ν⟩⟨e| + |u_r⟩⟨d_r| + |u_g⟩⟨d_g| + |u_b⟩⟨d_b|`. -/
noncomputable def TPlusDerived :
    JbarWavefunction →L[ℂ] JbarWavefunction :=
  ketbra ⟨0, by omega⟩ ⟨7, by omega⟩ +
  ketbra ⟨4, by omega⟩ ⟨1, by omega⟩ +
  ketbra ⟨5, by omega⟩ ⟨2, by omega⟩ +
  ketbra ⟨6, by omega⟩ ⟨3, by omega⟩

/-- The weak-isospin lowering operator, defined as a sum of rank-1
    operators:
    `T⁻ = |e⟩⟨ν| + |d_r⟩⟨u_r| + |d_g⟩⟨u_g| + |d_b⟩⟨u_b|`. -/
noncomputable def TMinusDerived :
    JbarWavefunction →L[ℂ] JbarWavefunction :=
  ketbra ⟨7, by omega⟩ ⟨0, by omega⟩ +
  ketbra ⟨1, by omega⟩ ⟨4, by omega⟩ +
  ketbra ⟨2, by omega⟩ ⟨5, by omega⟩ +
  ketbra ⟨3, by omega⟩ ⟨6, by omega⟩

/-! ## Equivalence with permutation-based definitions -/

/-- The spectral-decomposition T⁺ equals the permutation-based
    `TPlusEnd`. -/
theorem TPlusDerived_eq_TPlusEnd :
    TPlusDerived = TPlusEnd := by
  ext psi s
  fin_cases s <;>
    simp +decide [TPlusDerived, ketbra_apply_def,
      JbarBasisState, TPlusEnd, tPlusLM, tPlusSource,
      Pi.smul_apply, smul_eq_mul]

/-- The spectral-decomposition T⁻ equals the permutation-based
    `TMinusEnd`. -/
theorem TMinusDerived_eq_TMinusEnd :
    TMinusDerived = TMinusEnd := by
  ext psi s
  fin_cases s <;>
    simp +decide [TMinusDerived, ketbra_apply_def,
      JbarBasisState, TMinusEnd, tMinusLM, tMinusSource,
      Pi.smul_apply, smul_eq_mul]

/-! ## Uniqueness of the raising operator

We show that `TPlusEnd` is the unique continuous-linear endomorphism
satisfying three conditions:
1. `[T₃, T] = T` (raising commutation relation).
2. `[Y, T] = 0` (hypercharge commutation).
3. Correct action on the four T₃ = −1/2 basis states.

Conditions 1–2 constrain T to map the T₃ = −1/2 eigenspace into the
T₃ = +1/2 eigenspace with Y-preservation. Condition 3 fixes the
remaining degrees of freedom (a 1×1 lepton block and a 3×3 quark
block).
-/

/-
Any endomorphism satisfying the raising commutation relation,
    hypercharge commutation, and the correct action on the four
    T₃ = −1/2 basis states equals `TPlusEnd`.
-/
theorem TPlusEnd_unique
    (T : JbarWavefunction →L[ℂ] JbarWavefunction)
    (h_comm_T3 : endComm T3End T = T)
    (_h_comm_Y : endComm targetYEnd T = 0)
    (h_e : T (JbarBasisState ⟨7, by omega⟩) =
      JbarBasisState ⟨0, by omega⟩)
    (h_d1 : T (JbarBasisState ⟨1, by omega⟩) =
      JbarBasisState ⟨4, by omega⟩)
    (h_d2 : T (JbarBasisState ⟨2, by omega⟩) =
      JbarBasisState ⟨5, by omega⟩)
    (h_d3 : T (JbarBasisState ⟨3, by omega⟩) =
      JbarBasisState ⟨6, by omega⟩) :
    T = TPlusEnd := by
  have h_T_plus_zero : ∀ s : JbarState, targetT3 s = (1 / 2 : ℚ) → T (JbarBasisState s) = 0 := by
    intro s hs
    have h_comm : (T3End ∘L T - T ∘L T3End) (JbarBasisState s) = T (JbarBasisState s) := by
      exact congr_arg ( fun f => f ( JbarBasisState s ) ) h_comm_T3;
    have h_comm : ∀ t : JbarState, (T3End (T (JbarBasisState s))) t = (1 / 2 : ℂ) * (T (JbarBasisState s)) t + (T (JbarBasisState s)) t := by
      intro t; replace h_comm := congr_arg ( fun f => f t ) h_comm; simp_all +decide [ sub_eq_iff_eq_add' ] ;
      rw [ show T3End ( JbarBasisState s ) = ( targetT3 s : ℂ ) • JbarBasisState s from T3End_eigenvalue s ] ; norm_num [ hs ];
    have h_comm : ∀ t : JbarState, (targetT3 t : ℂ) * (T (JbarBasisState s)) t = (1 / 2 : ℂ) * (T (JbarBasisState s)) t + (T (JbarBasisState s)) t := by
      convert h_comm using 1;
    have h_comm : ∀ t : JbarState, (targetT3 t : ℂ) ≠ (3 / 2 : ℂ) := by
      intro t; rw [ Ne.eq_def, eq_div_iff ] <;> norm_cast ;
      fin_cases t <;> norm_num [ targetT3 ];
    ext t; specialize h_comm t; specialize ‹∀ t : JbarState, (targetT3 t : ℂ) * T (JbarBasisState s) t = 1 / 2 * T (JbarBasisState s) t + T (JbarBasisState s) t› t; simp_all +decide [ sub_eq_iff_eq_add ] ;
    grind;
  have h_T_plus_basis : ∀ s : JbarState, T (JbarBasisState s) = TPlusEnd (JbarBasisState s) := by
    intro s
    by_cases hs : targetT3 s = (1 / 2 : ℚ);
    · fin_cases s <;> simp +decide [ * ] at hs ⊢;
      all_goals norm_num [ targetT3 ] at hs;
      · exact h_T_plus_zero 0 ( by norm_num [ targetT3 ] ) ▸ TPlusEnd_neutrino.symm ▸ rfl;
      · convert h_T_plus_zero ⟨ 4, by decide ⟩ _ using 1;
        · exact TPlusEnd_uQuark ⟨ 0, by decide ⟩;
        · simp [targetT3];
      · convert h_T_plus_zero 5 rfl using 1;
        exact TPlusEnd_uQuark 1;
      · exact h_T_plus_zero 6 ( by rfl ) ▸ TPlusEnd_uQuark 2 ▸ rfl;
    · rcases s with ⟨ _ | _ | _ | _ | _ | _ | _ | _ | s, hs ⟩ <;> norm_num at hs ⊢;
      all_goals norm_cast at *;
      · exact h_d1.trans ( TPlusEnd_dQuark 0 ▸ rfl );
      · exact h_d2.trans ( TPlusEnd_dQuark 1 |> Eq.symm );
      · exact h_d3.trans ( TPlusEnd_dQuark ⟨ 2, by decide ⟩ ▸ rfl );
      · exact h_e.trans ( TPlusEnd_electron.symm );
  ext x;
  rw [ show x = ∑ s : JbarState, x s • JbarBasisState s from ?_, map_sum, map_sum ];
  · simp +decide [ h_T_plus_basis ];
  · ext s; simp [JbarBasisState];
    simp +decide [ Pi.single_apply ]

/-
Any endomorphism satisfying the lowering commutation relation,
    hypercharge commutation, and the correct action on the four
    T₃ = +1/2 basis states equals `TMinusEnd`.
-/
theorem TMinusEnd_unique
    (T : JbarWavefunction →L[ℂ] JbarWavefunction)
    (h_comm_T3 : endComm T3End T = -T)
    (_h_comm_Y : endComm targetYEnd T = 0)
    (h_nu : T (JbarBasisState ⟨0, by omega⟩) =
      JbarBasisState ⟨7, by omega⟩)
    (h_u1 : T (JbarBasisState ⟨4, by omega⟩) =
      JbarBasisState ⟨1, by omega⟩)
    (h_u2 : T (JbarBasisState ⟨5, by omega⟩) =
      JbarBasisState ⟨2, by omega⟩)
    (h_u3 : T (JbarBasisState ⟨6, by omega⟩) =
      JbarBasisState ⟨3, by omega⟩) :
    T = TMinusEnd := by
  -- By Lemma 2, T annihilates T3=-1/2 states.
  have h_annihilate : ∀ s : JbarState,
        targetT3 s = -1 / 2 →
          T (JbarBasisState s) = 0 := by
    intro s hs
    have h_T_minus : ∀ t : JbarState,
        (targetT3 t + 3 / 2 : ℂ) *
          (T (JbarBasisState s)) t = 0 := by
      intro t
      have h_T_minus : (T3End (T (JbarBasisState s))) t -
          (T (T3End (JbarBasisState s))) t =
            -(T (JbarBasisState s)) t := by
        convert congr_arg (fun f =>
          f (JbarBasisState s) t) h_comm_T3 using 1
      have h_T_minus :
          T3End (JbarBasisState s) =
            (targetT3 s : ℂ) • JbarBasisState s :=
        T3End_eigenvalue s
      have h_T_minus :
          T3End (T (JbarBasisState s)) t =
            (targetT3 t : ℂ) *
              (T (JbarBasisState s)) t :=
        diagonalEnd_apply _ _ _
      simp_all +decide [ add_mul, sub_eq_iff_eq_add ];
      ring;
    have h_nonzero : ∀ t : JbarState,
        (targetT3 t + 3 / 2 : ℂ) ≠ 0 := by
      intro t
      fin_cases t <;> norm_num [targetT3]
    exact funext fun t =>
      eq_zero_of_ne_zero_of_mul_left_eq_zero
        (h_nonzero t) (h_T_minus t)
  refine ContinuousLinearMap.ext fun x => ?_
  obtain ⟨c, hc⟩ :
      ∃ c : Fin 8 → ℂ, x = ∑ i, c i • JbarBasisState i := by
    use fun i => x i
    ext i; simp +decide [JbarBasisState]
    simp +decide [Pi.single_apply]
  simp_all +decide [Fin.sum_univ_eight]
  erw [h_annihilate 1 (by rfl),
    h_annihilate 2 (by rfl),
    h_annihilate 3 (by rfl),
    h_annihilate 7 (by rfl)]
  norm_num [TMinusEnd_neutrino, TMinusEnd_electron,
    TMinusEnd_dQuark, TMinusEnd_uQuark]
  erw [TMinusEnd_neutrino, TMinusEnd_dQuark 0,
    TMinusEnd_dQuark 1, TMinusEnd_dQuark 2,
    TMinusEnd_uQuark 0, TMinusEnd_uQuark 1,
    TMinusEnd_uQuark 2, TMinusEnd_electron]
  norm_num [JbarBasisState]
  ring!

end PhysicsSM.Algebra.Furey.WeakIsospinLadderDerived
