import Mathlib

/-!
# Gate YM T3: abstract center-shift electric flux sectors

This draft module is the first kernel-checked response to the Fable Q3
redesign (`review:fable-q3-flux-sector`).  It has two finite-identity
layers:

* a finite configuration space equipped with flux-shift permutations;
* electric flux sectors as eigenconditions for those shifts;
* shift-invariant diagonal observables preserving electric sectors;
* shift-invariant finite transfer kernels preserving electric sectors by
  finite reindexing.
* a concrete finite-group torus link-field model with center-shift
  permutations and plaquette-holonomy invariance under those shifts.

This file still does not identify Q2's transfer matrix, build the D12 Hilbert
space, or prove a spectral statement.  Its concrete torus theorem says only
that local observables factoring through plaquette holonomies are invariant
under the center shifts, hence preserve the abstract electric sectors.

Provenance: `Sources/Null_Edge_Yang_Mills_Mass_Gap_Program.md`, section 14
Q3, and Fable call
`AgentTasks/model-calls/claude/2026-07-04-094925-fable-a-q3-flux-sector-20260704.md`.

Draft-trust: no `s o r r y`, no `n a t i v e _ d e c i d e`.
Claim label: **finite identity / sector bookkeeping**.
-/

noncomputable section

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateYM
namespace CenterFluxSector

/-- A family of flux-shift permutations of a finite configuration space.

For the intended Yang-Mills instance, `Shift` will be generated by central
flux insertions along the two fundamental cycles of a torus. -/
structure ShiftSystem (Config Shift : Type*) where
  shift : Shift -> Equiv.Perm Config

namespace ShiftSystem

variable {Config Shift : Type*}

/-- Apply one flux shift to a configuration. -/
def shiftConfig (S : ShiftSystem Config Shift) (z : Shift) (x : Config) : Config :=
  S.shift z x

/-- The induced shift operator on wavefunctions. -/
def shiftOp (S : ShiftSystem Config Shift) (z : Shift)
    (psi : Config -> Complex) : Config -> Complex :=
  fun x => psi (S.shiftConfig z x)

/-- An electric-flux sector is an eigenspace for every flux shift.

The function `character` records the eigenvalue for each shift.  In the
concrete center-flux instance it should come from a character of the finite
center-shift group; this abstract file does not need the group law. -/
def InElectricSector (S : ShiftSystem Config Shift)
    (character : Shift -> Complex) (psi : Config -> Complex) : Prop :=
  forall z x, psi (S.shiftConfig z x) = character z * psi x

/-- The constant-one wavefunction lies in the trivial electric sector. -/
theorem one_inElectricSector (S : ShiftSystem Config Shift) :
    InElectricSector S (fun _ => (1 : Complex)) (fun _ => (1 : Complex)) := by
  intro z x
  simp

/-- On a nonempty configuration space, the constant-one wavefunction is not
the zero wavefunction. -/
theorem one_wavefunction_ne_zero [Nonempty Config] :
    (fun _ : Config => (1 : Complex)) ≠ 0 := by
  intro h
  have h0 := congrFun h (Classical.choice (inferInstance : Nonempty Config))
  norm_num at h0

/-- A nonzero witness for the trivial electric sector on any nonempty
configuration space. This is only a non-vacuity check for the sector API. -/
theorem one_inElectricSector_nonzero [Nonempty Config]
    (S : ShiftSystem Config Shift) :
    InElectricSector S (fun _ => (1 : Complex)) (fun _ => (1 : Complex)) ∧
      (fun _ : Config => (1 : Complex)) ≠ 0 :=
  ⟨one_inElectricSector S, one_wavefunction_ne_zero⟩

/-! ### A two-point nontrivial-character witness -/

/-- The two-point flip action used as the minimal nontrivial electric-sector
witness. -/
def boolFlip (z x : Bool) : Bool :=
  if z then !x else x

/-- Flipping by a Boolean label is a permutation of the two-point
configuration space. -/
def boolFlipShiftEquiv (z : Bool) : Equiv.Perm Bool where
  toFun := boolFlip z
  invFun := boolFlip z
  left_inv x := by
    cases z <;> cases x <;> rfl
  right_inv x := by
    cases z <;> cases x <;> rfl

/-- The minimal two-point shift system. The nontrivial shift flips the two
configurations. -/
def boolFlipShiftSystem : ShiftSystem Bool Bool where
  shift := boolFlipShiftEquiv

/-- The sign character of the two-point shift system. -/
def boolSignCharacter (z : Bool) : Complex :=
  if z then -1 else 1

/-- The sign wavefunction on the two-point configuration space. -/
def boolSignWavefunction (x : Bool) : Complex :=
  if x then -1 else 1

/-- The sign character is genuinely nontrivial. -/
theorem boolSignCharacter_true_ne_one : boolSignCharacter true ≠ 1 := by
  norm_num [boolSignCharacter]

/-- The sign wavefunction is not the zero wavefunction. -/
theorem boolSignWavefunction_ne_zero : boolSignWavefunction ≠ 0 := by
  intro h
  have h0 := congrFun h false
  norm_num [boolSignWavefunction] at h0

/-- The sign wavefunction is an eigenvector for the Boolean flip shift system,
with eigenvalue given by the nontrivial sign character. -/
theorem boolSignWavefunction_inElectricSector :
    InElectricSector boolFlipShiftSystem boolSignCharacter
      boolSignWavefunction := by
  intro z x
  cases z <;> cases x <;>
    norm_num [boolFlipShiftSystem, ShiftSystem.shiftConfig,
      boolFlipShiftEquiv, boolFlip, boolSignCharacter, boolSignWavefunction]

/-- A compact nonzero witness for a genuinely nontrivial electric sector.
This is a finite bookkeeping model, not a cohomology or confinement theorem. -/
theorem boolSign_nontrivialElectricSector :
    InElectricSector boolFlipShiftSystem boolSignCharacter boolSignWavefunction ∧
      boolSignWavefunction ≠ 0 ∧ boolSignCharacter true ≠ 1 :=
  ⟨boolSignWavefunction_inElectricSector, boolSignWavefunction_ne_zero,
    boolSignCharacter_true_ne_one⟩

/-- A diagonal observable is shift-invariant when it is constant along all
flux-shift orbits.  Local plaquette holonomy functions are expected to be
instances in the concrete center-shift layer. -/
def ShiftInvariantObservable (S : ShiftSystem Config Shift)
    (O : Config -> Complex) : Prop :=
  forall z x, O (S.shiftConfig z x) = O x

/-- Multiplication by a diagonal observable. -/
def multiplyObservable (O psi : Config -> Complex) : Config -> Complex :=
  fun x => O x * psi x

/-- Shift-invariant diagonal observables preserve every electric-flux
sector. -/
theorem inElectricSector_multiplyObservable
    (S : ShiftSystem Config Shift) (character : Shift -> Complex)
    (O psi : Config -> Complex)
    (hO : ShiftInvariantObservable S O)
    (hpsi : InElectricSector S character psi) :
    InElectricSector S character (multiplyObservable O psi) := by
  intro z x
  unfold multiplyObservable
  rw [hO z x, hpsi z x]
  ring

/-- A finite transfer kernel acts by summing over the source configuration.

The convention is `K x y`: amplitude from source `y` to target `x`. -/
def applyKernel [Fintype Config] (K : Config -> Config -> Complex)
    (psi : Config -> Complex) : Config -> Complex :=
  fun x => ∑ y : Config, K x y * psi y

/-- A kernel is invariant under simultaneous flux shifts of source and
target configurations.  This is the finite-kernel commutation condition that
implies preservation of electric sectors. -/
def KernelInvariantUnderShifts (S : ShiftSystem Config Shift)
    (K : Config -> Config -> Complex) : Prop :=
  forall z x y, K (S.shiftConfig z x) (S.shiftConfig z y) = K x y

/-- A finite kernel invariant under flux shifts preserves every electric
sector. -/
theorem inElectricSector_applyKernel [Fintype Config]
    (S : ShiftSystem Config Shift) (K : Config -> Config -> Complex)
    (character : Shift -> Complex) (psi : Config -> Complex)
    (hK : KernelInvariantUnderShifts S K)
    (hpsi : InElectricSector S character psi) :
    InElectricSector S character (applyKernel K psi) := by
  intro z x
  unfold applyKernel
  calc
    (∑ y : Config, K (S.shiftConfig z x) y * psi y)
        = ∑ y : Config,
            K (S.shiftConfig z x) (S.shiftConfig z y) *
              psi (S.shiftConfig z y) := by
          simpa [shiftConfig] using
            (Equiv.sum_comp (S.shift z)
              (fun y : Config => K (S.shiftConfig z x) y * psi y)).symm
    _ = ∑ y : Config, K x y * (character z * psi y) := by
          apply Finset.sum_congr rfl
          intro y _hy
          rw [hK z x y, hpsi z y]
    _ = character z * ∑ y : Config, K x y * psi y := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro y _hy
          ring

end ShiftSystem

/-! ## Concrete finite-group torus center shifts -/

/-- A finite-group link field on an `Lx` by `Ly` periodic torus.

`hLink i j` is the horizontal link from `(i,j)` to `(i+1,j)`, and
`vLink i j` is the vertical link from `(i,j)` to `(i,j+1)`, with periodic
wrap implemented by `finRotate` in plaquette formulas. -/
structure TorusLinkFieldG (G : Type*) (Lx Ly : Nat) where
  hLink : Fin Lx -> Fin Ly -> G
  vLink : Fin Lx -> Fin Ly -> G
deriving Fintype

namespace TorusLinkFieldG

variable {G : Type*} {Lx Ly : Nat}

/-- Extensionality for concrete torus link fields. -/
@[ext]
theorem ext {U V : TorusLinkFieldG G Lx Ly}
    (hh : forall i j, U.hLink i j = V.hLink i j)
    (hv : forall i j, U.vLink i j = V.vLink i j) : U = V := by
  cases U with
  | mk Uh Uv =>
    cases V with
    | mk Vh Vv =>
      congr
      · funext i j
        exact hh i j
      · funext i j
        exact hv i j

end TorusLinkFieldG

variable {G : Type*} [Group G] {Lx Ly : Nat}

/-- Plaquette holonomy based at `(i,j)`, with counterclockwise convention:
bottom horizontal, right vertical, inverse top horizontal, inverse left
vertical. -/
def plaquetteHol (U : TorusLinkFieldG G Lx Ly) (i : Fin Lx) (j : Fin Ly) :
    G :=
  U.hLink i j * U.vLink (finRotate Lx i) j *
    (U.hLink i (finRotate Ly j))⁻¹ * (U.vLink i j)⁻¹

/-- The full plaquette-holonomy field of a torus link field. -/
def plaquetteField (U : TorusLinkFieldG G Lx Ly) :
    Fin Lx -> Fin Ly -> G :=
  fun i j => plaquetteHol U i j

/-- Central x-flux shift: multiply every horizontal link in column `i0` by
the central element `z`. -/
def xFluxShift (z : Subgroup.center G) (i0 : Fin Lx)
    (U : TorusLinkFieldG G Lx Ly) : TorusLinkFieldG G Lx Ly where
  hLink i j := if i = i0 then (z : G) * U.hLink i j else U.hLink i j
  vLink := U.vLink

/-- Central y-flux shift: multiply every vertical link in row `j0` by the
central element `z`. -/
def yFluxShift (z : Subgroup.center G) (j0 : Fin Ly)
    (U : TorusLinkFieldG G Lx Ly) : TorusLinkFieldG G Lx Ly where
  hLink := U.hLink
  vLink i j := if j = j0 then (z : G) * U.vLink i j else U.vLink i j

/-- The identity central element acts trivially as an x-flux shift. -/
@[simp]
theorem xFluxShift_one (i0 : Fin Lx) (U : TorusLinkFieldG G Lx Ly) :
    xFluxShift 1 i0 U = U := by
  ext i j <;> by_cases hi : i = i0 <;> simp [xFluxShift, hi]

/-- The identity central element acts trivially as a y-flux shift. -/
@[simp]
theorem yFluxShift_one (j0 : Fin Ly) (U : TorusLinkFieldG G Lx Ly) :
    yFluxShift 1 j0 U = U := by
  ext i j <;> by_cases hj : j = j0 <;> simp [yFluxShift, hj]

/-- X-flux shifts compose by multiplying their central labels. -/
theorem xFluxShift_mul (z w : Subgroup.center G) (i0 : Fin Lx)
    (U : TorusLinkFieldG G Lx Ly) :
    xFluxShift (z * w) i0 U = xFluxShift z i0 (xFluxShift w i0 U) := by
  ext i j <;> by_cases hi : i = i0 <;> simp [xFluxShift, hi, mul_assoc]

/-- Y-flux shifts compose by multiplying their central labels. -/
theorem yFluxShift_mul (z w : Subgroup.center G) (j0 : Fin Ly)
    (U : TorusLinkFieldG G Lx Ly) :
    yFluxShift (z * w) j0 U = yFluxShift z j0 (yFluxShift w j0 U) := by
  ext i j <;> by_cases hj : j = j0 <;> simp [yFluxShift, hj, mul_assoc]

/-- X- and y-flux shifts commute as operations on the concrete torus link
fields, since they touch horizontal and vertical link families respectively. -/
theorem xFluxShift_yFluxShift_comm (z w : Subgroup.center G)
    (i0 : Fin Lx) (j0 : Fin Ly) (U : TorusLinkFieldG G Lx Ly) :
    xFluxShift z i0 (yFluxShift w j0 U) =
      yFluxShift w j0 (xFluxShift z i0 U) := by
  ext i j <;> by_cases hi : i = i0 <;> by_cases hj : j = j0 <;>
    simp [xFluxShift, yFluxShift, hi, hj]

/-- Moving a central factor across two group elements and cancelling it with
its inverse.  This is the x-shift cancellation pattern in a plaquette. -/
theorem center_mul_two_mul_inv_cancel (z : Subgroup.center G) (a b c : G) :
    (z : G) * a * b * (c * (z : G)⁻¹) = a * b * c := by
  have hza : (z : G) * a = a * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 a).symm
  have hzb : (z : G) * b = b * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 b).symm
  have hzc : (z : G) * c = c * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 c).symm
  calc
    (z : G) * a * b * (c * (z : G)⁻¹)
        = a * (z : G) * b * (c * (z : G)⁻¹) := by rw [hza]
    _ = a * (b * (z : G)) * (c * (z : G)⁻¹) := by
          rw [← hzb]
          simp [mul_assoc]
    _ = a * b * ((z : G) * c * (z : G)⁻¹) := by
          simp [mul_assoc]
    _ = a * b * (c * (z : G) * (z : G)⁻¹) := by rw [hzc]
    _ = a * b * c := by simp [mul_assoc]

/-- Moving a central factor across the remaining plaquette factors and
cancelling it with its inverse.  This is the y-shift cancellation pattern. -/
theorem mul_center_mul_two_inv_cancel (z : Subgroup.center G) (a b c d : G) :
    a * ((z : G) * b) * c * (d * (z : G)⁻¹) =
      a * b * c * d := by
  have hzb : (z : G) * b = b * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 b).symm
  have hzc : (z : G) * c = c * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 c).symm
  have hzd : (z : G) * d = d * (z : G) :=
    (Subgroup.mem_center_iff.mp z.2 d).symm
  calc
    a * ((z : G) * b) * c * (d * (z : G)⁻¹)
        = a * (b * (z : G)) * c * (d * (z : G)⁻¹) := by
          rw [hzb]
    _ = a * b * ((z : G) * c) * (d * (z : G)⁻¹) := by
          simp [mul_assoc]
    _ = a * b * (c * (z : G)) * (d * (z : G)⁻¹) := by rw [hzc]
    _ = a * b * c * ((z : G) * d * (z : G)⁻¹) := by
          simp [mul_assoc]
    _ = a * b * c * (d * (z : G) * (z : G)⁻¹) := by rw [hzd]
    _ = a * b * c * d := by simp [mul_assoc]

/-- An x-flux shift is a permutation of the finite configuration space. -/
def xFluxShiftEquiv (z : Subgroup.center G) (i0 : Fin Lx) :
    Equiv.Perm (TorusLinkFieldG G Lx Ly) where
  toFun := xFluxShift z i0
  invFun := xFluxShift z⁻¹ i0
  left_inv U := by
    ext i j <;> by_cases hi : i = i0 <;> simp [xFluxShift, hi]
  right_inv U := by
    ext i j <;> by_cases hi : i = i0 <;> simp [xFluxShift, hi]

/-- A y-flux shift is a permutation of the finite configuration space. -/
def yFluxShiftEquiv (z : Subgroup.center G) (j0 : Fin Ly) :
    Equiv.Perm (TorusLinkFieldG G Lx Ly) where
  toFun := yFluxShift z j0
  invFun := yFluxShift z⁻¹ j0
  left_inv U := by
    ext i j <;> by_cases hj : j = j0 <;> simp [yFluxShift, hj]
  right_inv U := by
    ext i j <;> by_cases hj : j = j0 <;> simp [yFluxShift, hj]

/-- Central x-shifts preserve every plaquette holonomy. -/
theorem plaquetteHol_xFluxShift (z : Subgroup.center G) (i0 : Fin Lx)
    (U : TorusLinkFieldG G Lx Ly) (i : Fin Lx) (j : Fin Ly) :
    plaquetteHol (xFluxShift z i0 U) i j = plaquetteHol U i j := by
  by_cases hi : i = i0
  · subst i
    simpa [plaquetteHol, xFluxShift] using
      center_mul_two_mul_inv_cancel z
        (U.hLink i0 j)
        (U.vLink (finRotate Lx i0) j)
        ((U.hLink i0 (finRotate Ly j))⁻¹)
  · simp [plaquetteHol, xFluxShift, hi]

/-- Central y-shifts preserve every plaquette holonomy. -/
theorem plaquetteHol_yFluxShift (z : Subgroup.center G) (j0 : Fin Ly)
    (U : TorusLinkFieldG G Lx Ly) (i : Fin Lx) (j : Fin Ly) :
    plaquetteHol (yFluxShift z j0 U) i j = plaquetteHol U i j := by
  by_cases hj : j = j0
  · subst j
    simpa [plaquetteHol, yFluxShift] using
      mul_center_mul_two_inv_cancel z
        (U.hLink i j0)
        (U.vLink (finRotate Lx i) j0)
        ((U.hLink i (finRotate Ly j0))⁻¹)
        ((U.vLink i j0)⁻¹)
  · simp [plaquetteHol, yFluxShift, hj]

/-- A single generator of the torus center-shift family: either an x-shift by
a central element at a column, or a y-shift by a central element at a row. -/
inductive TorusCenterShift (G : Type*) [Group G] (Lx Ly : Nat) where
  | x : Subgroup.center G -> Fin Lx -> TorusCenterShift G Lx Ly
  | y : Subgroup.center G -> Fin Ly -> TorusCenterShift G Lx Ly

/-- The abstract `ShiftSystem` induced by the concrete torus center shifts. -/
def torusCenterShiftSystem (G : Type*) [Group G] (Lx Ly : Nat) :
    ShiftSystem (TorusLinkFieldG G Lx Ly) (TorusCenterShift G Lx Ly) where
  shift
    | TorusCenterShift.x z i0 => xFluxShiftEquiv z i0
    | TorusCenterShift.y z j0 => yFluxShiftEquiv z j0

/-- Every concrete center-shift generator preserves every plaquette holonomy. -/
theorem plaquetteHol_torusCenterShift
    (s : TorusCenterShift G Lx Ly) (U : TorusLinkFieldG G Lx Ly)
    (i : Fin Lx) (j : Fin Ly) :
    plaquetteHol
        ((torusCenterShiftSystem G Lx Ly).shiftConfig s U) i j =
      plaquetteHol U i j := by
  cases s with
  | x z i0 =>
      simpa [ShiftSystem.shiftConfig, torusCenterShiftSystem] using
        plaquetteHol_xFluxShift z i0 U i j
  | y z j0 =>
      simpa [ShiftSystem.shiftConfig, torusCenterShiftSystem] using
        plaquetteHol_yFluxShift z j0 U i j

/-- Any observable that factors through the full plaquette-holonomy field is
invariant under concrete torus center shifts.  This is the finite local
plaquette-algebra preservation input for Q3. -/
theorem shiftInvariant_of_factorsThroughPlaquettes
    (f : (Fin Lx -> Fin Ly -> G) -> Complex) :
    ShiftSystem.ShiftInvariantObservable
      (torusCenterShiftSystem G Lx Ly)
      (fun U : TorusLinkFieldG G Lx Ly => f (plaquetteField U)) := by
  intro s U
  apply congrArg f
  funext i j
  exact plaquetteHol_torusCenterShift s U i j

/-- Multiplication by a plaquette-field observable preserves every electric
sector for the concrete torus center-shift system. -/
theorem inElectricSector_multiplyPlaquetteObservable
    (character : TorusCenterShift G Lx Ly -> Complex)
    (f : (Fin Lx -> Fin Ly -> G) -> Complex)
    (psi : TorusLinkFieldG G Lx Ly -> Complex)
    (hpsi : ShiftSystem.InElectricSector
      (torusCenterShiftSystem G Lx Ly) character psi) :
    ShiftSystem.InElectricSector
      (torusCenterShiftSystem G Lx Ly) character
      (ShiftSystem.multiplyObservable
        (fun U : TorusLinkFieldG G Lx Ly => f (plaquetteField U)) psi) :=
  ShiftSystem.inElectricSector_multiplyObservable
    (torusCenterShiftSystem G Lx Ly) character
    (fun U : TorusLinkFieldG G Lx Ly => f (plaquetteField U)) psi
    (shiftInvariant_of_factorsThroughPlaquettes f) hpsi

end CenterFluxSector
end GateYM
end NullEdge
end Draft
end PhysicsSM
