import Mathlib

/-!
# Gate YM4: cyclicity prerequisite for the finite local sector

This draft module names the finite algebraic cyclicity condition that Q9 must
eventually instantiate after Q2 supplies the transfer Hilbert space and Q3
supplies the trivial-flux sector.

The condition is intentionally abstract. In a finite-dimensional sector,
"dense cyclic span" is represented by equality of submodules: applying the
local plaquette/operator algebra to the vacuum spans exactly the chosen sector.
This module proves no spectral gap and contains no transfer-matrix statement;
it only prevents the cyclicity prerequisite from being hidden as an unnamed
assumption in a later gap argument.
-/

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateYM
namespace CyclicityPrereq

variable {H : Type*} [AddCommGroup H] [Module ℂ H]

/-- The submodule generated from a vacuum vector by an operator algebra.

For the eventual Q9 use, `A` should be the local plaquette/operator algebra on
the finite transfer Hilbert space, and `vacuum` should be the transfer vacuum.
-/
noncomputable def cyclicSubmodule
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H) : Submodule ℂ H :=
  Submodule.span ℂ (Set.range fun T : A => (T : Module.End ℂ H) vacuum)

/-- The vacuum is always in the cyclic submodule generated by the local
algebra, because the identity operator belongs to any subalgebra. -/
theorem vacuum_mem_cyclicSubmodule
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H) :
    vacuum ∈ cyclicSubmodule A vacuum := by
  refine Submodule.subset_span ?_
  exact ⟨1, by simp⟩

/-- Enlarging the local operator algebra can only enlarge the cyclic
submodule generated from the same vacuum. -/
theorem cyclicSubmodule_mono
    {A B : Subalgebra ℂ (Module.End ℂ H)} (vacuum : H)
    (hAB : A ≤ B) :
    cyclicSubmodule A vacuum ≤ cyclicSubmodule B vacuum := by
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨T, rfl⟩
  refine Submodule.subset_span ?_
  exact ⟨⟨T.1, hAB T.2⟩, rfl⟩

/-- To prove the cyclic submodule lies in a sector, it suffices to check the
orbit of the vacuum under each operator of the algebra. -/
theorem cyclicSubmodule_le_iff
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H) :
    cyclicSubmodule A vacuum ≤ sector ↔
      ∀ T : A, (T : Module.End ℂ H) vacuum ∈ sector := by
  constructor
  · intro h T
    exact h (Submodule.subset_span ⟨T, rfl⟩)
  · intro h
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨T, rfl⟩
    exact h T

/-- An operator algebra preserves a candidate sector. -/
def PreservesSubmodule
    (A : Subalgebra ℂ (Module.End ℂ H)) (sector : Submodule ℂ H) : Prop :=
  ∀ T : A, ∀ v : H, v ∈ sector → (T : Module.End ℂ H) v ∈ sector

/-- If the local algebra preserves a sector and the vacuum is in that sector,
then the whole cyclic submodule generated from the vacuum lies in the sector.
This is only the easy inclusion; Q9 still needs the converse/cyclicity input. -/
theorem cyclicSubmodule_le_of_preserves
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H)
    (hpres : PreservesSubmodule A sector) (hv : vacuum ∈ sector) :
    cyclicSubmodule A vacuum ≤ sector := by
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨T, rfl⟩
  exact hpres T vacuum hv

/-- The named Q9 prerequisite: the local algebra is cyclic on the given sector.

In the finite-dimensional setting intended by Q9, this is the algebraic form of
density of the local algebra orbit of the vacuum in the trivial-flux/local
sector.
-/
def LocalAlgebraCyclicInSector
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H) : Prop :=
  cyclicSubmodule A vacuum = sector

/-- Cyclicity alone implies the vacuum lies in the sector, since it lies in
the generated cyclic submodule. The bundled prerequisite still records
`vacuum_mem` explicitly so later gap arguments cannot hide this hypothesis. -/
theorem vacuum_mem_of_cyclic
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H)
    (hcyc : LocalAlgebraCyclicInSector A vacuum sector) :
    vacuum ∈ sector := by
  rw [← hcyc]
  exact vacuum_mem_cyclicSubmodule A vacuum

/-- Cyclicity is equivalent to the two inclusions that later finite-gap
assembly proofs will usually prove separately. -/
theorem localAlgebraCyclicInSector_iff_le_and_ge
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H) :
    LocalAlgebraCyclicInSector A vacuum sector ↔
      cyclicSubmodule A vacuum ≤ sector ∧
        sector ≤ cyclicSubmodule A vacuum := by
  constructor
  · intro hcyc
    constructor
    · rw [hcyc]
    · rw [hcyc]
  · intro h
    exact le_antisymm h.1 h.2

/-- Cyclicity is equivalently the hard inclusion from the sector back into the
cyclic span, together with the check that every local-algebra orbit vector
stays in the sector. -/
theorem localAlgebraCyclicInSector_iff_orbit_subset_and_sector_le
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H) :
    LocalAlgebraCyclicInSector A vacuum sector ↔
      (∀ T : A, (T : Module.End ℂ H) vacuum ∈ sector) ∧
        sector ≤ cyclicSubmodule A vacuum := by
  rw [localAlgebraCyclicInSector_iff_le_and_ge, cyclicSubmodule_le_iff]

/-- If the local algebra preserves the sector and the vacuum lies in the
sector, then proving the sector is contained in the cyclic span is enough to
prove the named cyclicity prerequisite. -/
theorem localAlgebraCyclicInSector_of_preserves_of_sector_le
    (A : Subalgebra ℂ (Module.End ℂ H)) (vacuum : H)
    (sector : Submodule ℂ H)
    (hpres : PreservesSubmodule A sector) (hv : vacuum ∈ sector)
    (hsector : sector ≤ cyclicSubmodule A vacuum) :
    LocalAlgebraCyclicInSector A vacuum sector := by
  exact (localAlgebraCyclicInSector_iff_le_and_ge A vacuum sector).2
    ⟨cyclicSubmodule_le_of_preserves A vacuum sector hpres hv, hsector⟩

/-- Bundle of hypotheses that a future finite-gap assembly must expose.

This structure is not a theorem. It packages the exact point where a fake gap
argument could otherwise smuggle in cyclicity of local observables in the
trivial sector.
-/
structure LocalCyclicityPrereq (H : Type*) [AddCommGroup H] [Module ℂ H] where
  /-- Candidate local plaquette/operator algebra. -/
  localAlgebra : Subalgebra ℂ (Module.End ℂ H)
  /-- Vacuum vector. -/
  vacuum : H
  /-- Candidate trivial-flux/local sector. -/
  sector : Submodule ℂ H
  /-- The vacuum lies in the candidate sector. -/
  vacuum_mem : vacuum ∈ sector
  /-- The local algebra preserves the candidate sector. -/
  local_preserves_sector : PreservesSubmodule localAlgebra sector
  /-- The local algebra orbit of the vacuum spans the sector. -/
  cyclic : LocalAlgebraCyclicInSector localAlgebra vacuum sector

/-- The easy inclusion from the generated cyclic submodule to the sector,
extracted from a bundled Q9 prerequisite. -/
theorem cyclicSubmodule_le_sector_of_prereq
    (P : LocalCyclicityPrereq H) :
    cyclicSubmodule P.localAlgebra P.vacuum ≤ P.sector := by
  rw [P.cyclic]

/-- The hard cyclicity inclusion from the sector back into the generated
cyclic submodule, extracted from a bundled Q9 prerequisite. -/
theorem sector_le_cyclicSubmodule_of_prereq
    (P : LocalCyclicityPrereq H) :
    P.sector ≤ cyclicSubmodule P.localAlgebra P.vacuum := by
  rw [P.cyclic]

/-- Every local-algebra translate of the vacuum lies in the sector under a
bundled Q9 prerequisite. This is the orbit-level easy inclusion that future
assembly code can use without unfolding the bundle. -/
theorem orbit_mem_sector_of_prereq
    (P : LocalCyclicityPrereq H) (T : P.localAlgebra) :
    (T : Module.End ℂ H) P.vacuum ∈ P.sector :=
  P.local_preserves_sector T P.vacuum P.vacuum_mem

end CyclicityPrereq
end GateYM
end NullEdge
end Draft
end PhysicsSM
