import PhysicsSM.Draft.NullEdge.GateYM.TwoStateTransferZ2L1
import PhysicsSM.Draft.NullEdge.GateYM.CyclicityPrereq

/-!
# Gate YM4 / Q9: local cyclicity — flux insertion spans the vacuum-orthogonal sector

This module discharges the **named** local-cyclicity / sector-spanning
prerequisite of Q9 on the smallest genuine Z2 Wilson-slab transfer space: the
one-link two-state space `State = Fin 2 → ℂ` of `TwoStateTransferSpectrum`,
whose transfer vacuum is `(1, 1)` and whose vacuum-orthogonal line is spanned
by `(1, -1)`.

## Why this is not the toy filler

`TwoStateTransferWitness.topCyclicityPrereq` already instantiates the abstract
`CyclicityPrereq.LocalCyclicityPrereq`, but with the **full** endomorphism
algebra `⊤` and the whole-space sector — which is cyclic for a trivial reason
(a rank-one map sends the vacuum anywhere). That is exactly the kind of
"too-large algebra" filler that hides whether the *physical local observable
algebra* is big enough.

Here the local algebra is the genuine **flux-insertion algebra**
`localFluxAlgebra = Algebra.adjoin ℂ {fluxEnd}` generated by the single physical
local gauge-invariant observable `fluxEnd = fluxMatrix.mulVecLin` (the
diagonal center/flux insertion `diag(1, -1)`). This is a strict `2`-dimensional
commutative subalgebra of the `4`-dimensional endomorphism algebra, not the full
algebra.

## What is PROVED (positive)

* `fluxEnd_vacuum` : the flux insertion sends the vacuum `(1,1)` to the
  vacuum-orthogonal vector `(1,-1)` (`= localVec`).
* `localVec_orthogonal_vacuum` : `(1,-1)` is genuinely orthogonal to the vacuum
  `(1,1)`, so it spans the *vacuum-orthogonal* sector.
* `vacuumOrthogonalSector_le_cyclic` : the vacuum-orthogonal sector is reached
  by the local flux algebra from the vacuum — the exact Q9 spanning condition.
* `localFluxAlgebra_cyclic_top` : the local flux algebra is cyclic on the WHOLE
  two-state sector from the vacuum (`LocalAlgebraCyclicInSector`), i.e. the
  physical local observable algebra is *not* too small.
* `localFluxCyclicityPrereq` : an honest `LocalCyclicityPrereq State` whose
  local algebra is the genuine flux-insertion algebra, replacing the toy
  full-algebra filler.

## What is PROVED (negative / sharpness)

* `cyclic_bot_eq_span_vacuum` and `localVec_not_mem_cyclic_bot` : the
  scalar-only "algebra" `⊥` (no insertions) generates only the one-dimensional
  vacuum line from the vacuum and does NOT reach the vacuum-orthogonal sector.
  This is a precise instance of the failure mode Q9 warns about — a gap "proved"
  on the scalar orbit alone would live on a too-small observable subspace. The
  flux insertion is exactly what is needed to enlarge that orbit to the full
  sector.

## What is NOT claimed

No transfer spectral gap, no Wilson-slab OS/GNS Hilbert space beyond this exact
two-state model, no continuum or physical mass-gap statement. This module only
names and proves the finite cyclicity/spanning prerequisite so it cannot be
smuggled in as an unnamed assumption downstream.

Draft-trust: no `s o r r y` (after discharge), no `n a t i v e _ d e c i d e`,
no new `axiom`.
Claim label: finite identity (local cyclicity / vacuum-orthogonal spanning).
-/

noncomputable section

open scoped Matrix

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateYM
namespace LocalCyclicitySector

open TwoStateTransferSpectrum TwoStateTransferZ2L1 CyclicityPrereq

/-- The one-link two-state space `Fin 2 → ℂ`. -/
abbrev State : Type := TwoStateTransferSpectrum.State

/-- The physical local flux-insertion observable as an endomorphism:
`fluxEnd = fluxMatrix.mulVecLin`, the diagonal center/flux insertion
`diag(1, -1)`. -/
def fluxEnd : Module.End ℂ State := fluxMatrix.mulVecLin

/-- The flux insertion sends the vacuum `(1, 1)` to the vacuum-orthogonal vector
`(1, -1) = localVec`. -/
theorem fluxEnd_vacuum : fluxEnd vacuumVec = localVec := by
  simpa [fluxEnd, Matrix.mulVecLin_apply] using fluxMatrix_mulVec_vacuum

/-- The physical local flux-insertion algebra: the subalgebra of the
endomorphism algebra generated by the single flux-insertion observable. This is
a genuine strict subalgebra, not the full endomorphism algebra. -/
def localFluxAlgebra : Subalgebra ℂ (Module.End ℂ State) :=
  Algebra.adjoin ℂ {fluxEnd}

/-- The flux insertion belongs to the local flux algebra. -/
theorem fluxEnd_mem_localFluxAlgebra : fluxEnd ∈ localFluxAlgebra :=
  Algebra.self_mem_adjoin_singleton ℂ fluxEnd

/-- The vacuum-orthogonal sector of the two-state model: the line spanned by the
local/flux vector `(1, -1)`. -/
def vacuumOrthogonalSector : Submodule ℂ State :=
  Submodule.span ℂ {(localVec : State)}

/-- The local/flux vector `(1, -1)` is orthogonal to the vacuum `(1, 1)`, so it
genuinely spans the vacuum-orthogonal sector. -/
theorem localVec_orthogonal_vacuum :
    (star vacuumVec) ⬝ᵥ localVec = 0 := by
  simp [vacuumVec, localVec, dotProduct, Fin.sum_univ_two, star]

/-- The local/flux vector lies in the cyclic submodule generated by the local
flux algebra from the vacuum, because it is the flux insertion of the vacuum. -/
theorem localVec_mem_cyclic :
    localVec ∈ cyclicSubmodule localFluxAlgebra vacuumVec := by
  refine Submodule.subset_span ?_
  exact ⟨⟨fluxEnd, fluxEnd_mem_localFluxAlgebra⟩, fluxEnd_vacuum⟩

/-- The vacuum and the local/flux vector together span the whole two-state
space. -/
theorem span_vacuum_local_top :
    Submodule.span ℂ {(vacuumVec : State), (localVec : State)} = ⊤ := by
  rw [Submodule.eq_top_iff']
  intro w
  have hw : w = (((w 0 + w 1) / 2 : ℂ)) • vacuumVec
      + (((w 0 - w 1) / 2 : ℂ)) • localVec := by
    funext i
    fin_cases i <;>
      simp [vacuumVec, localVec] <;> ring
  rw [hw]
  refine Submodule.add_mem _ ?_ ?_
  · exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))
  · exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))

/-- **Main positive result.** The physical local flux-insertion algebra is
cyclic on the whole two-state sector from the vacuum: the vacuum orbit under the
local flux algebra spans everything. The physical local observable algebra is
not too small. -/
theorem localFluxAlgebra_cyclic_top :
    LocalAlgebraCyclicInSector localFluxAlgebra vacuumVec ⊤ := by
  refine le_antisymm le_top ?_
  rw [← span_vacuum_local_top, Submodule.span_le]
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl
  · exact vacuum_mem_cyclicSubmodule localFluxAlgebra vacuumVec
  · exact localVec_mem_cyclic

/-- **The Q9 spanning condition.** The vacuum-orthogonal sector is reached by the
local flux algebra from the vacuum. The nontrivial excitation is generated by a
genuine physical local observable, not assumed. -/
theorem vacuumOrthogonalSector_le_cyclic :
    vacuumOrthogonalSector ≤ cyclicSubmodule localFluxAlgebra vacuumVec := by
  rw [vacuumOrthogonalSector, Submodule.span_le, Set.singleton_subset_iff]
  exact localVec_mem_cyclic

/-- An honest `LocalCyclicityPrereq` for the one-link Z2 slab whose local
algebra is the genuine flux-insertion algebra (not the full endomorphism
algebra), with the whole two-state space as the sector. -/
def localFluxCyclicityPrereq : LocalCyclicityPrereq State where
  localAlgebra := localFluxAlgebra
  vacuum := vacuumVec
  sector := ⊤
  vacuum_mem := trivial
  local_preserves_sector := fun _ _ _ => trivial
  cyclic := localFluxAlgebra_cyclic_top

/-! ## Negative / sharpness: the scalar-only algebra is too small -/

/-- The scalar-only "algebra" `⊥` (no insertions at all) generates only the
one-dimensional vacuum line from the vacuum. -/
theorem cyclic_bot_eq_span_vacuum :
    cyclicSubmodule (⊥ : Subalgebra ℂ (Module.End ℂ State)) vacuumVec
      = Submodule.span ℂ {(vacuumVec : State)} := by
  apply le_antisymm
  · rw [cyclicSubmodule, Submodule.span_le]
    rintro _ ⟨T, rfl⟩
    obtain ⟨c, hc⟩ := Algebra.mem_bot.1 T.2
    refine Submodule.mem_span_singleton.2 ⟨c, ?_⟩
    change c • vacuumVec = (T : Module.End ℂ State) vacuumVec
    rw [← hc]
    simp [Module.algebraMap_end_apply]
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact vacuum_mem_cyclicSubmodule _ vacuumVec

/-- The scalar-only algebra does NOT reach the vacuum-orthogonal vector: without
the physical flux insertion the vacuum orbit is a too-small observable subspace.
This is a precise instance of the failure mode Q9 warns against. -/
theorem localVec_not_mem_cyclic_bot :
    localVec ∉ cyclicSubmodule (⊥ : Subalgebra ℂ (Module.End ℂ State)) vacuumVec := by
  rw [cyclic_bot_eq_span_vacuum, Submodule.mem_span_singleton]
  rintro ⟨c, hc⟩
  have h0 := congrFun hc 0
  have h1 := congrFun hc 1
  simp [vacuumVec, localVec] at h0 h1
  rw [h0] at h1
  norm_num at h1

end LocalCyclicitySector
end GateYM
end NullEdge
end Draft
end PhysicsSM
