import PhysicsSM.Draft.NullEdge.GateYM.FluxSectorZ2
import PhysicsSM.Draft.NullEdge.GateYM.TransferHilbertBlockShift

/-!
# Q2/Q3 bridge: concrete Z2 electric shifts for block OS spaces

This module instantiates the abstract block-shift bridge from
`TransferHilbertBlockShift.lean` on the concrete Z2 torus electric
center-shift generators from `FluxSectorZ2.lean`.

The result is deliberately narrow: any reflection-positive block weight that
depends on the positive, cut, and mirror configurations only through their
full plaquette-bit fields is invariant under simultaneous base electric
center shifts.  Therefore the block matrix `rpBlockMatrix` commutes with the
corresponding block shifts, and those shifts preserve the finite OS range
space from `TransferHilbert.lean`.

This still does not construct a physical transfer matrix, Hamiltonian, or
spectral gap.  It is the concrete Z2 adapter needed before a genuine
sector-correct transfer statement can be made.

Claim label: **finite identity / Q2-Q3 adapter**.  Draft-trust:
kernel-checked, no `s o r r y`.
-/

noncomputable section

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateYM
namespace TransferHilbertZ2Electric

open CenterFluxSector TransferHilbert TransferHilbertBlock
open TransferHilbertBlockShift

/-- The two base Z2 electric shifts used in `FluxSectorZ2`'s concrete
electric-sector projections. -/
inductive BaseElectricShift where
  | x
  | y
deriving DecidableEq, Fintype

/-- The concrete shift system generated by the base x- and y-center shifts on
Z2 torus link fields. -/
def baseElectricShiftSystem {Lx Ly : Nat} (hLx : 0 < Lx) (hLy : 0 < Ly) :
    ShiftSystem (FluxSectorZ2.TorusLinkField Lx Ly) BaseElectricShift where
  shift
    | BaseElectricShift.x =>
        FluxSectorZ2.TorusLinkField.xShiftEquiv
          (FluxSectorZ2.TorusLinkField.baseX hLx)
    | BaseElectricShift.y =>
        FluxSectorZ2.TorusLinkField.yShiftEquiv
          (FluxSectorZ2.TorusLinkField.baseY hLy)

/-- The base x-shift unfolds to `FluxSectorZ2.TorusLinkField.xShift`. -/
@[simp]
theorem baseElectricShiftSystem_shiftConfig_x {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    (baseElectricShiftSystem hLx hLy).shiftConfig BaseElectricShift.x U =
      FluxSectorZ2.TorusLinkField.xShift
        (FluxSectorZ2.TorusLinkField.baseX hLx) U := by
  rfl

/-- The base y-shift unfolds to `FluxSectorZ2.TorusLinkField.yShift`. -/
@[simp]
theorem baseElectricShiftSystem_shiftConfig_y {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    (baseElectricShiftSystem hLx hLy).shiftConfig BaseElectricShift.y U =
      FluxSectorZ2.TorusLinkField.yShift
        (FluxSectorZ2.TorusLinkField.baseY hLy) U := by
  rfl

/-- The full plaquette-bit field of a concrete Z2 torus link field. -/
def plaquetteBitField {Lx Ly : Nat}
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    Fin Lx -> Fin Ly -> Bool :=
  fun i j => FluxSectorZ2.TorusLinkField.plaquetteBit U i j

/-- Base electric shifts preserve the full plaquette-bit field. -/
theorem plaquetteBitField_shiftConfig {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (s : BaseElectricShift) (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    plaquetteBitField
        ((baseElectricShiftSystem hLx hLy).shiftConfig s U) =
      plaquetteBitField U := by
  funext i j
  cases s with
  | x =>
      simp [plaquetteBitField, FluxSectorZ2.TorusLinkField.plaquetteBit_xShift]
  | y =>
      simp [plaquetteBitField, FluxSectorZ2.TorusLinkField.plaquetteBit_yShift]

/-- A block weight that depends only on the three plaquette-bit fields
(positive, cut, mirror). -/
def plaquetteTripleWeight {Lx Ly : Nat}
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex)
    (a c b : FluxSectorZ2.TorusLinkField Lx Ly) : Complex :=
  F (plaquetteBitField a) (plaquetteBitField c) (plaquetteBitField b)

/-- Plaquette-field block weights are invariant under simultaneous base
electric shifts of the positive, cut, and mirror configurations. -/
theorem plaquetteTripleWeight_blockWeightInvariant {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex) :
    BlockWeightInvariantUnderShifts
      (baseElectricShiftSystem hLx hLy)
      (baseElectricShiftSystem hLx hLy)
      (plaquetteTripleWeight F) := by
  intro s a c b
  simp [plaquetteTripleWeight, plaquetteBitField_shiftConfig hLx hLy s]

/-- The block matrix of a plaquette-field Z2 weight commutes with the base
electric block shifts. -/
theorem rpBlockMatrix_commutes_baseElectricShifts {Lx Ly : Nat}
    [DecidableEq (FluxSectorZ2.TorusLinkField Lx Ly)]
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex) :
    KernelCommutesShifts
      (blockShiftSystem
        (baseElectricShiftSystem hLx hLy)
        (baseElectricShiftSystem hLx hLy))
      (rpBlockMatrix (plaquetteTripleWeight F)) := by
  classical
  exact rpBlockMatrix_commutes_blockShifts
    (baseElectricShiftSystem hLx hLy)
    (baseElectricShiftSystem hLx hLy)
    (plaquetteTripleWeight F)
    (plaquetteTripleWeight_blockWeightInvariant hLx hLy F)

/-- Base electric block shifts preserve the finite OS range space associated
to a plaquette-field Z2 block weight. -/
theorem shiftOp_preserves_rpHilbertSpace_z2PlaquetteBlock {Lx Ly : Nat}
    [DecidableEq (FluxSectorZ2.TorusLinkField Lx Ly)]
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex)
    (s : BaseElectricShift) :
    ∀ v, v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) →
      shiftOp
          (blockShiftSystem
            (baseElectricShiftSystem hLx hLy)
            (baseElectricShiftSystem hLx hLy))
          s v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) := by
  classical
  exact shiftOp_preserves_rpHilbertSpace_rpBlockMatrix
    (baseElectricShiftSystem hLx hLy)
    (baseElectricShiftSystem hLx hLy)
    (plaquetteTripleWeight F)
    (plaquetteTripleWeight_blockWeightInvariant hLx hLy F)
    s

/-- Four-term electric-sector projection on the block-index function space
`(cut configuration, positive/mirror configuration) -> Complex`.

This is the block-OS analogue of `FluxSectorZ2.TorusLinkField`'s
single-configuration electric projection: it averages over the simultaneous
base x/y center shifts of both block coordinates with the selected Z2
characters. -/
def blockElectricSectorProjection {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly) (ex ey : Bool)
    (psi :
      (FluxSectorZ2.TorusLinkField Lx Ly ×
        FluxSectorZ2.TorusLinkField Lx Ly) -> Complex) :
    (FluxSectorZ2.TorusLinkField Lx Ly ×
      FluxSectorZ2.TorusLinkField Lx Ly) -> Complex :=
  let S :=
    blockShiftSystem
      (baseElectricShiftSystem hLx hLy)
      (baseElectricShiftSystem hLx hLy)
  fun i =>
    (1 / 4 : Complex) *
      (psi i +
        FluxSectorZ2.TorusLinkField.z2Character ex *
          psi (S.shiftConfig BaseElectricShift.x i) +
        FluxSectorZ2.TorusLinkField.z2Character ey *
          psi (S.shiftConfig BaseElectricShift.y i) +
        FluxSectorZ2.TorusLinkField.z2Character ex *
          FluxSectorZ2.TorusLinkField.z2Character ey *
          psi
            (S.shiftConfig BaseElectricShift.x
              (S.shiftConfig BaseElectricShift.y i)))

/-- The block electric-sector projection preserves the finite OS range for
plaquette-field Z2 block weights.

This is still finite block-kernel infrastructure: it does not construct a
physical Wilson transfer matrix, but it says the concrete Q2 range model is
closed under the Q3 electric-sector projections for the plaquette-field block
weights currently available. -/
theorem blockElectricSectorProjection_preserves_rpHilbertSpace_z2PlaquetteBlock
    {Lx Ly : Nat} [DecidableEq (FluxSectorZ2.TorusLinkField Lx Ly)]
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex)
    (ex ey : Bool) :
    ∀ v, v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) ->
      blockElectricSectorProjection hLx hLy ex ey v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) := by
  classical
  intro v hv
  let S :=
    blockShiftSystem
      (baseElectricShiftSystem hLx hLy)
      (baseElectricShiftSystem hLx hLy)
  let M := rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F))
  have hx : shiftOp S BaseElectricShift.x v ∈ M :=
    shiftOp_preserves_rpHilbertSpace_z2PlaquetteBlock
      hLx hLy F BaseElectricShift.x v hv
  have hy : shiftOp S BaseElectricShift.y v ∈ M :=
    shiftOp_preserves_rpHilbertSpace_z2PlaquetteBlock
      hLx hLy F BaseElectricShift.y v hv
  have hxy : shiftOp S BaseElectricShift.y
      (shiftOp S BaseElectricShift.x v) ∈ M :=
    shiftOp_preserves_rpHilbertSpace_z2PlaquetteBlock
      hLx hLy F BaseElectricShift.y (shiftOp S BaseElectricShift.x v) hx
  have hproj :
      blockElectricSectorProjection hLx hLy ex ey v =
        (1 / 4 : Complex) •
          (v +
            FluxSectorZ2.TorusLinkField.z2Character ex •
              shiftOp S BaseElectricShift.x v +
            FluxSectorZ2.TorusLinkField.z2Character ey •
              shiftOp S BaseElectricShift.y v +
            (FluxSectorZ2.TorusLinkField.z2Character ex *
              FluxSectorZ2.TorusLinkField.z2Character ey) •
              shiftOp S BaseElectricShift.y
                (shiftOp S BaseElectricShift.x v)) := by
    funext i
    simp [blockElectricSectorProjection, S, shiftOp, shiftMatrix_mulVec]
  rw [hproj]
  exact M.smul_mem _
    (M.add_mem
      (M.add_mem
        (M.add_mem hv (M.smul_mem _ hx))
        (M.smul_mem _ hy))
      (M.smul_mem _ hxy))

end TransferHilbertZ2Electric
end GateYM
end NullEdge
end Draft
end PhysicsSM
