import PhysicsSM.Draft.NullEdge.GateYM.FluxSectorZ2
import PhysicsSM.Draft.NullEdge.GateYM.TransferHilbertBlockShift

/-!
# Q2/Q3 bridge: concrete Z2 electric shifts for block OS spaces

This module instantiates the abstract block-shift bridge from
`TransferHilbertBlockShift.lean` on the concrete Z2 torus electric
center-shift generators from `FluxSectorZ2.lean`.

The result is deliberately narrow: any reflection-positive block weight that
depends on the positive, cut, and mirror configurations only through their
full plaquette-bit fields is invariant under simultaneous base electric
center shifts.  Therefore the block matrix `rpBlockMatrix` commutes with the
corresponding block shifts, and those shifts preserve the finite OS range
space from `TransferHilbert.lean`.

This still does not construct a physical transfer matrix, Hamiltonian, or
spectral gap.  It is the concrete Z2 adapter needed before a genuine
sector-correct transfer statement can be made.

Claim label: **finite identity / Q2-Q3 adapter**.  Draft-trust:
kernel-checked, no `s o r r y`.
-/

noncomputable section

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateYM
namespace TransferHilbertZ2Electric

open CenterFluxSector TransferHilbert TransferHilbertBlock
open TransferHilbertBlockShift

/-- The two base Z2 electric shifts used in `FluxSectorZ2`'s concrete
electric-sector projections. -/
inductive BaseElectricShift where
  | x
  | y
deriving DecidableEq, Fintype

/-- The concrete shift system generated by the base x- and y-center shifts on
Z2 torus link fields. -/
def baseElectricShiftSystem {Lx Ly : Nat} (hLx : 0 < Lx) (hLy : 0 < Ly) :
    ShiftSystem (FluxSectorZ2.TorusLinkField Lx Ly) BaseElectricShift where
  shift
    | BaseElectricShift.x =>
        FluxSectorZ2.TorusLinkField.xShiftEquiv
          (FluxSectorZ2.TorusLinkField.baseX hLx)
    | BaseElectricShift.y =>
        FluxSectorZ2.TorusLinkField.yShiftEquiv
          (FluxSectorZ2.TorusLinkField.baseY hLy)

/-- The base x-shift unfolds to `FluxSectorZ2.TorusLinkField.xShift`. -/
@[simp]
theorem baseElectricShiftSystem_shiftConfig_x {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    (baseElectricShiftSystem hLx hLy).shiftConfig BaseElectricShift.x U =
      FluxSectorZ2.TorusLinkField.xShift
        (FluxSectorZ2.TorusLinkField.baseX hLx) U := by
  rfl

/-- The base y-shift unfolds to `FluxSectorZ2.TorusLinkField.yShift`. -/
@[simp]
theorem baseElectricShiftSystem_shiftConfig_y {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    (baseElectricShiftSystem hLx hLy).shiftConfig BaseElectricShift.y U =
      FluxSectorZ2.TorusLinkField.yShift
        (FluxSectorZ2.TorusLinkField.baseY hLy) U := by
  rfl

/-- The full plaquette-bit field of a concrete Z2 torus link field. -/
def plaquetteBitField {Lx Ly : Nat}
    (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    Fin Lx -> Fin Ly -> Bool :=
  fun i j => FluxSectorZ2.TorusLinkField.plaquetteBit U i j

/-- Base electric shifts preserve the full plaquette-bit field. -/
theorem plaquetteBitField_shiftConfig {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (s : BaseElectricShift) (U : FluxSectorZ2.TorusLinkField Lx Ly) :
    plaquetteBitField
        ((baseElectricShiftSystem hLx hLy).shiftConfig s U) =
      plaquetteBitField U := by
  funext i j
  cases s with
  | x =>
      simp [plaquetteBitField, FluxSectorZ2.TorusLinkField.plaquetteBit_xShift]
  | y =>
      simp [plaquetteBitField, FluxSectorZ2.TorusLinkField.plaquetteBit_yShift]

/-- A block weight that depends only on the three plaquette-bit fields
(positive, cut, mirror). -/
def plaquetteTripleWeight {Lx Ly : Nat}
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex)
    (a c b : FluxSectorZ2.TorusLinkField Lx Ly) : Complex :=
  F (plaquetteBitField a) (plaquetteBitField c) (plaquetteBitField b)

/-- Plaquette-field block weights are invariant under simultaneous base
electric shifts of the positive, cut, and mirror configurations. -/
theorem plaquetteTripleWeight_blockWeightInvariant {Lx Ly : Nat}
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex) :
    BlockWeightInvariantUnderShifts
      (baseElectricShiftSystem hLx hLy)
      (baseElectricShiftSystem hLx hLy)
      (plaquetteTripleWeight F) := by
  intro s a c b
  simp [plaquetteTripleWeight, plaquetteBitField_shiftConfig hLx hLy s]

/-- The block matrix of a plaquette-field Z2 weight commutes with the base
electric block shifts. -/
theorem rpBlockMatrix_commutes_baseElectricShifts {Lx Ly : Nat}
    [DecidableEq (FluxSectorZ2.TorusLinkField Lx Ly)]
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex) :
    KernelCommutesShifts
      (blockShiftSystem
        (baseElectricShiftSystem hLx hLy)
        (baseElectricShiftSystem hLx hLy))
      (rpBlockMatrix (plaquetteTripleWeight F)) := by
  classical
  exact rpBlockMatrix_commutes_blockShifts
    (baseElectricShiftSystem hLx hLy)
    (baseElectricShiftSystem hLx hLy)
    (plaquetteTripleWeight F)
    (plaquetteTripleWeight_blockWeightInvariant hLx hLy F)

/-- Base electric block shifts preserve the finite OS range space associated
to a plaquette-field Z2 block weight. -/
theorem shiftOp_preserves_rpHilbertSpace_z2PlaquetteBlock {Lx Ly : Nat}
    [DecidableEq (FluxSectorZ2.TorusLinkField Lx Ly)]
    (hLx : 0 < Lx) (hLy : 0 < Ly)
    (F : (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) ->
      (Fin Lx -> Fin Ly -> Bool) -> Complex)
    (s : BaseElectricShift) :
    ∀ v, v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) →
      shiftOp
          (blockShiftSystem
            (baseElectricShiftSystem hLx hLy)
            (baseElectricShiftSystem hLx hLy))
          s v ∈
        rpHilbertSpace (rpBlockMatrix (plaquetteTripleWeight F)) := by
  classical
  exact shiftOp_preserves_rpHilbertSpace_rpBlockMatrix
    (baseElectricShiftSystem hLx hLy)
    (baseElectricShiftSystem hLx hLy)
    (plaquetteTripleWeight F)
    (plaquetteTripleWeight_blockWeightInvariant hLx hLy F)
    s

end TransferHilbertZ2Electric
end GateYM
end NullEdge
end Draft
end PhysicsSM
