import Mathlib

open Matrix Complex

noncomputable section

namespace WindingBindingIntertwiner

abbrev WindingSpace := Fin 4 → ℂ
abbrev TargetSpace := Fin 3 → ℂ

/-- The winding-one truncation operator `C^4 -> C^3`. -/
def K : WindingSpace →ₗ[ℂ] TargetSpace :=
  LinearMap.funLeft ℂ ℂ (Fin.castAdd 1)

def protectedBasis : WindingSpace := Pi.single 3 1

theorem protectedBasis_mem_ker : protectedBasis ∈ LinearMap.ker K := by
  sorry

theorem protectedBasis_ne_zero : protectedBasis ≠ 0 := by
  sorry

/-- The protected winding kernel is exactly the last-coordinate line. -/
theorem windingKernel_eq_span (x : LinearMap.ker K) :
    x.1 = x.1 3 • protectedBasis := by
  sorry

/-- Exact phase-gauged carrier Hamiltonian at `d=(0,1,1), kappa=2`. -/
def carrierH : Matrix (Fin 3) (Fin 3) ℂ :=
  !![1, -2 * I, 0; 2 * I, 1, 0; 0, 0, 2]

def carrierOp : TargetSpace →ₗ[ℂ] TargetSpace := Matrix.mulVecLin carrierH

def carrierBoundVec : TargetSpace := ![1, -I, 0]

theorem carrierBoundVec_ne_zero : carrierBoundVec ≠ 0 := by
  sorry

theorem carrierBoundVec_eigen :
    carrierH.mulVec carrierBoundVec = (-1 : ℂ) • carrierBoundVec := by
  sorry

/-- The exact `-1` eigenspace. -/
def boundEigenspace : Submodule ℂ TargetSpace :=
  LinearMap.ker (carrierOp + LinearMap.id)

theorem carrierBoundVec_mem_eigenspace : carrierBoundVec ∈ boundEigenspace := by
  sorry

/-- The bound eigenspace is exactly the line generated by `carrierBoundVec`. -/
theorem boundEigenspace_eq_span (y : boundEigenspace) :
    y.1 = y.1 0 • carrierBoundVec := by
  sorry

/-- Read the protected coordinate and place it in the bound eigendirection. -/
def windingToBound : LinearMap.ker K →ₗ[ℂ] TargetSpace where
  toFun x := x.1 3 • carrierBoundVec
  map_add' := by intro x y; simp [add_smul]
  map_smul' := by intro c x; simp [mul_smul]

theorem windingToBound_intertwines (x : LinearMap.ker K) :
    carrierH.mulVec (windingToBound x) =
      (-1 : ℂ) • windingToBound x := by
  sorry

theorem windingToBound_injective : Function.Injective windingToBound := by
  sorry

def windingToBoundEigenspace : LinearMap.ker K →ₗ[ℂ] boundEigenspace :=
  LinearMap.codRestrict boundEigenspace windingToBound (by
    intro x
    change carrierOp (windingToBound x) + windingToBound x = 0
    rw [show carrierOp (windingToBound x) =
        carrierH.mulVec (windingToBound x) by rfl,
      windingToBound_intertwines]
    simp)

theorem windingToBoundEigenspace_bijective :
    Function.Bijective windingToBoundEigenspace := by
  sorry

/-- Exact equivalence of the protected winding line and bound eigenspace. -/
noncomputable def windingKernel_equiv_boundEigenspace :
    LinearMap.ker K ≃ₗ[ℂ] boundEigenspace :=
  LinearEquiv.ofBijective windingToBoundEigenspace
    windingToBoundEigenspace_bijective

theorem bound_below_free_threshold : (-1 : ℝ) < 1 := by norm_num

theorem winding_binding_intertwiner_verdict :
    protectedBasis ∈ LinearMap.ker K
      ∧ protectedBasis ≠ 0
      ∧ carrierBoundVec ≠ 0
      ∧ carrierH.mulVec carrierBoundVec = (-1 : ℂ) • carrierBoundVec
      ∧ Function.Injective windingToBound
      ∧ Function.Bijective windingToBoundEigenspace
      ∧ (-1 : ℝ) < 1 := by
  sorry

end WindingBindingIntertwiner
