import Mathlib

/-!
# Finite massive retarded link series

This focused package studies a finite matrix geometric series built from a
primitive retarded kernel `K`:

```text
G_m(H) = sum_{k=0}^{H-1} (-massSq)^k K^(k+1).
```

It proves the exact left and right resolvent identities, termination for a
nilpotent kernel, and a three-event link-chain witness in which the primitive
kernel has no direct endpoint hop while the mass-deformed series has a nonzero
two-hop contribution.

The algebra follows the causal-set massive-from-massless Green-function
template. It does not identify `K` with a continuum Green function, derive the
mass parameter, prove a continuum limit, or model an interacting Higgs field.
-/

noncomputable section

namespace MassiveRetardedLinkSeries

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Truncated massive retarded series generated by one primitive kernel. -/
def massiveRetardedSeries
    (K : Matrix V V Real) (massSq : Real) (H : Nat) : Matrix V V Real :=
  ∑ k ∈ Finset.range H, (-massSq) ^ k • K ^ (k + 1)

/-- Exact left resolvent identity, including the finite terminal remainder. -/
theorem one_add_mass_kernel_mul_series
    (K : Matrix V V Real) (massSq : Real) (H : Nat) :
    (1 + massSq • K) * massiveRetardedSeries K massSq H =
      K - (-massSq) ^ H • K ^ (H + 1) := by
  sorry

/-- Exact right resolvent identity. Powers of the one primitive kernel commute
with that kernel, so the same terminal remainder appears. -/
theorem series_mul_one_add_mass_kernel
    (K : Matrix V V Real) (massSq : Real) (H : Nat) :
    massiveRetardedSeries K massSq H * (1 + massSq • K) =
      K - (-massSq) ^ H • K ^ (H + 1) := by
  sorry

/-- Nilpotence removes the left terminal remainder exactly. -/
theorem one_add_mass_kernel_mul_series_of_nilpotent
    (K : Matrix V V Real) (massSq : Real) (H : Nat)
    (hNil : K ^ (H + 1) = 0) :
    (1 + massSq • K) * massiveRetardedSeries K massSq H = K := by
  sorry

/-- Nilpotence removes the right terminal remainder exactly. -/
theorem series_mul_one_add_mass_kernel_of_nilpotent
    (K : Matrix V V Real) (massSq : Real) (H : Nat)
    (hNil : K ^ (H + 1) = 0) :
    massiveRetardedSeries K massSq H * (1 + massSq • K) = K := by
  sorry

/-- For positive truncation length, zero mass leaves only the primitive
retarded kernel. -/
theorem massiveRetardedSeries_zero_mass
    (K : Matrix V V Real) (H : Nat) (hH : 0 < H) :
    massiveRetardedSeries K 0 H = K := by
  sorry

/-- Primitive link kernel on the three-event chain `0 -> 1 -> 2`. Matrix rows
are targets and columns are sources. -/
def threeLinkKernel : Matrix (Fin 3) (Fin 3) Real :=
  !![0, 0, 0; 1, 0, 0; 0, 1, 0]

/-- Nonvacuous multi-edge control. There is no primitive `0 -> 2` matrix
entry, but the square has unit `0 -> 1 -> 2` amplitude. The kernel is
cube-zero, and at `massSq = 1` the massive series has endpoint amplitude
`-1`, whereas its zero-mass value is zero. -/
theorem threeLink_massive_multiedge_witness :
    threeLinkKernel 2 0 = 0 ∧
      (threeLinkKernel ^ 2) 2 0 = 1 ∧
      threeLinkKernel ^ 3 = 0 ∧
      massiveRetardedSeries threeLinkKernel 1 3 2 0 = -1 ∧
      massiveRetardedSeries threeLinkKernel 0 3 2 0 = 0 := by
  sorry

end MassiveRetardedLinkSeries

end
