import Mathlib

/-!
# Modular selection: deriving the D2 generator from the Gibbs state

This file formalizes, for a **finite** null-edge program, the claim that the dynamics
layer D2 generator need not be *posited*: it is *selected* by the (max-entropy) Gibbs
state via the finite Tomita–Takesaki / modular flow.

Everything lives in finite-dimensional matrix algebras `Matrix N N ℂ`, so the modular
automorphism group is completely explicit and kernel-checkable.

## Main results

* `flow_scalar_shift` : the conjugation ("Heisenberg") flow generated by `M + c • 1`
  equals the one generated by `M` — a central (scalar) shift of the generator is
  invisible to the flow. This is the algebraic engine behind everything else.
* `modular_flow_of_gibbs` : for the finite Gibbs state `ρ = exp(-β B)/Z`, the modular
  flow `σ_t(X) = ρ^{it} X ρ^{-it}` **is** the `B`-generated flow
  `exp(-iβt B) X exp(iβt B)`.  The generator is `B` (up to the `β` time rescaling),
  *derived* from the state, not posited.
* `gibbs_modHam_exp` : certifies that the modular Hamiltonian used above really is
  `-log ρ` for the Gibbs state (so the modular unitary above really is `ρ^{it}`).
* `equipartition_generator` : (channel-GGE) for four independent commuting channel
  charges `Q_A, Q_C, Q_T, E`, the GGE generator
  `K = λ_A Q_A + λ_C Q_C + λ_T Q_T + λ_E E` is `B`-generated (equal to `ν•B + d•1`
  for some `ν, d`) **iff** the four channels equilibrate to one common inverse
  temperature `λ_A = λ_C = λ_T = λ_E`.
* `gge_flow_of_equipartition` : the forward flow corollary — a common temperature
  gives a genuinely `B`-generated modular flow.
* `conjectureJ_kill` : the KMS-selected generator on the `T2` sector (distinct
  channel shares) is provably **not** of the form `ν•B + d•1`, hence its modular
  flow is not `B`-generated.

## Boundary (honest scope)

This selects the generator **finitely**: the four-channel thermalization to a common
`β` is a genuine finite dynamics question answered here.  The reverse direction of the
equipartition criterion is proved at the *generator* level (`K = ν•B + d•1`), which is
exactly the statement "the flow generator is `B` up to a central shift".  The
continuum thermal-time hypothesis (Connes–Rovelli on an infinite algebra) is *not*
formalized and remains an imported physical input.
-/

open scoped BigOperators

namespace ModularSelection

section CoreAlgebra

variable {N : Type*} [Fintype N] [DecidableEq N]

/-- The matrix exponential of a scalar multiple of the identity is scalar. -/
theorem exp_scalar_one (d : ℂ) :
    NormedSpace.exp (d • (1 : Matrix N N ℂ)) = (Complex.exp d) • (1 : Matrix N N ℂ) := by
  have h1 : (d • (1 : Matrix N N ℂ)) = Matrix.diagonal (fun _ : N => d) := by
    ext i j; simp [Matrix.one_apply, Matrix.diagonal]
  rw [h1, Matrix.exp_diagonal]
  have h2 : NormedSpace.exp (fun _ : N => d) = (fun _ : N => Complex.exp d) := by
    rw [Pi.exp_def]; funext i; simp [Complex.exp_eq_exp_ℂ]
  rw [h2]; ext i j; simp [Matrix.diagonal, Matrix.one_apply, Matrix.smul_apply]

/-- `exp(b • (M + c • 1)) = exp(b c) • exp(b • M)`: the scalar part factors out. -/
theorem exp_smul_split (M : Matrix N N ℂ) (b c : ℂ) :
    NormedSpace.exp (b • (M + c • (1 : Matrix N N ℂ)))
      = (Complex.exp (b * c)) • NormedSpace.exp (b • M) := by
  have hbc : b • (M + c • (1 : Matrix N N ℂ)) = b • M + (b * c) • (1 : Matrix N N ℂ) := by
    rw [smul_add, smul_smul]
  rw [hbc, Matrix.exp_add_of_commute _ _ (((Commute.one_right M).smul_right (b * c)).smul_left b),
    exp_scalar_one, mul_smul_comm, mul_one]

/-- **Central-shift invariance of the conjugation flow.**  Shifting the generator
`M` by a central (scalar) term `c • 1` does not change the Heisenberg/modular flow. -/
theorem flow_scalar_shift (M X : Matrix N N ℂ) (c a : ℂ) :
    NormedSpace.exp (a • (M + c • (1 : Matrix N N ℂ))) * X
        * NormedSpace.exp ((-a) • (M + c • (1 : Matrix N N ℂ)))
      = NormedSpace.exp (a • M) * X * NormedSpace.exp ((-a) • M) := by
  rw [exp_smul_split, exp_smul_split]
  simp only [smul_mul_assoc, mul_smul_comm, smul_smul]
  rw [show Complex.exp ((-a) * c) * Complex.exp (a * c) = 1 by
        rw [← Complex.exp_add, show (-a) * c + a * c = 0 by ring]; exact Complex.exp_zero]
  rw [one_smul]

end CoreAlgebra

/-!
## Modular flow of the Gibbs state
-/

section Gibbs

variable {N : Type*} [Fintype N] [DecidableEq N]

/-- The (unnormalized) Gibbs weight `exp(-β B)`. -/
noncomputable def gibbsWeight (B : Matrix N N ℂ) (β : ℝ) : Matrix N N ℂ :=
  NormedSpace.exp ((-(β : ℂ)) • B)

/-- The partition function `Z = tr exp(-β B)`. -/
noncomputable def partition (B : Matrix N N ℂ) (β : ℝ) : ℂ :=
  (gibbsWeight B β).trace

/-- The finite Gibbs state `ρ = exp(-β B)/Z`. -/
noncomputable def gibbsState (B : Matrix N N ℂ) (β : ℝ) : Matrix N N ℂ :=
  (partition B β)⁻¹ • gibbsWeight B β

/-- The **modular Hamiltonian** `K = -log ρ = β B + (log Z) • 1` of the Gibbs state. -/
noncomputable def modHam (B : Matrix N N ℂ) (β : ℝ) : Matrix N N ℂ :=
  (β : ℂ) • B + (Complex.log (partition B β)) • (1 : Matrix N N ℂ)

/-- **Certification that `modHam` is `-log ρ`.**  For the Gibbs state with nonzero
partition function, `exp(-modHam) = ρ`.  This means the modular unitary
`ρ^{it} := exp(-it • modHam)` used below really is the modular unitary of `ρ`. -/
theorem gibbs_modHam_exp (B : Matrix N N ℂ) (β : ℝ) (hZ : partition B β ≠ 0) :
    NormedSpace.exp (-(modHam B β)) = gibbsState B β := by
  have hcomm : Commute ((-(β : ℂ)) • B) ((-(Complex.log (partition B β))) • (1 : Matrix N N ℂ)) :=
    ((Commute.one_right B).smul_right (-(Complex.log (partition B β)))).smul_left (-(β : ℂ))
  have hneg : -(modHam B β)
      = (-(β : ℂ)) • B + (-(Complex.log (partition B β))) • (1 : Matrix N N ℂ) := by
    simp only [modHam, neg_add, neg_smul]
  rw [hneg, Matrix.exp_add_of_commute _ _ hcomm, exp_scalar_one]
  rw [Complex.exp_neg, Complex.exp_log hZ]
  rw [gibbsState, gibbsWeight]
  rw [mul_smul_comm, mul_one]

/-- The modular unitary `ρ^{it} = exp(-it • K)` of the Gibbs state (Δ = ρ). -/
noncomputable def modUnitary (B : Matrix N N ℂ) (β : ℝ) (t : ℝ) : Matrix N N ℂ :=
  NormedSpace.exp ((-(Complex.I * (t : ℂ))) • modHam B β)

/-- The **modular flow** of the Gibbs state, `σ_t(X) = ρ^{it} X ρ^{-it}`. -/
noncomputable def modFlow (B : Matrix N N ℂ) (β : ℝ) (t : ℝ) (X : Matrix N N ℂ) : Matrix N N ℂ :=
  modUnitary B β t * X * modUnitary B β (-t)

/-- **Modular flow of the Gibbs state = `B`-generated flow (Conjecture J core).**

For the finite Gibbs state `ρ = exp(-β B)/Z`, the Tomita–Takesaki modular flow
`σ_t(X) = ρ^{it} X ρ^{-it}` equals the `B`-generated Heisenberg flow
`exp(-iβt B) X exp(iβt B)`.  The generator of D2 is therefore `B` (with the modular
time rescaled by `β`), *derived from the state* rather than posited. -/
theorem modular_flow_of_gibbs (B : Matrix N N ℂ) (β : ℝ) (t : ℝ) (X : Matrix N N ℂ) :
    modFlow B β t X
      = NormedSpace.exp ((-(Complex.I * (β : ℂ) * (t : ℂ))) • B) * X
          * NormedSpace.exp ((Complex.I * (β : ℂ) * (t : ℂ)) • B) := by
  rw [modFlow, modUnitary, modUnitary, modHam]
  simp only [Complex.ofReal_neg, mul_neg, neg_neg]
  -- apply the central-shift lemma with a = -(I t), M = β • B, c = log Z
  have key := flow_scalar_shift ((β : ℂ) • B) X (Complex.log (partition B β))
    (-(Complex.I * (t : ℂ)))
  rw [show (-(-(Complex.I * (t : ℂ)))) = Complex.I * (t : ℂ) by ring] at key
  rw [key]
  -- rewrite the scalars on B
  rw [smul_smul, smul_smul,
    show (-(Complex.I * (t : ℂ))) * (β : ℂ) = -(Complex.I * (β : ℂ) * (t : ℂ)) by ring,
    show (Complex.I * (t : ℂ)) * (β : ℂ) = Complex.I * (β : ℂ) * (t : ℂ) by ring]

end Gibbs

/-!
## Channel-GGE and equipartition

Four commuting, traceless, linearly independent channel charges on a 5-level system.
-/

section GGE

/-- Channel charge `Q_A`. -/
def QA : Matrix (Fin 5) (Fin 5) ℂ := Matrix.diagonal ![1, -1, 0, 0, 0]
/-- Channel charge `Q_C`. -/
def QC : Matrix (Fin 5) (Fin 5) ℂ := Matrix.diagonal ![0, 1, -1, 0, 0]
/-- Channel charge `Q_T`. -/
def QT : Matrix (Fin 5) (Fin 5) ℂ := Matrix.diagonal ![0, 0, 1, -1, 0]
/-- Channel charge `E`. -/
def EE : Matrix (Fin 5) (Fin 5) ℂ := Matrix.diagonal ![0, 0, 0, 1, -1]

/-- Total sector mass form `B = Q_A + Q_C + Q_T + E`. -/
def Bsum : Matrix (Fin 5) (Fin 5) ℂ := QA + QC + QT + EE

/-- The generalized Gibbs (GGE) generator with four channel chemical potentials. -/
def ggeGen (lA lC lT lE : ℂ) : Matrix (Fin 5) (Fin 5) ℂ :=
  lA • QA + lC • QC + lT • QT + lE • EE

/-- **Channel-GGE equipartition criterion.**

The GGE generator `K = λ_A Q_A + λ_C Q_C + λ_T Q_T + λ_E E` is `B`-generated — i.e. it
equals `ν • B + d • 1` for some scalars `ν, d` (a central shift of a multiple of `B`,
which is exactly the condition for its modular flow to be `B`-generated by
`flow_scalar_shift`) — **iff** the four channels equilibrate to a single common inverse
temperature `λ_A = λ_C = λ_T = λ_E`.  This is the finite "do the channels thermalize
to a common β?" question, answered affirmatively as the *only* way to recover a
`B`-generated flow. -/
theorem equipartition_generator (lA lC lT lE : ℂ) :
    (∃ ν d : ℂ, ggeGen lA lC lT lE = ν • Bsum + d • (1 : Matrix (Fin 5) (Fin 5) ℂ))
      ↔ (lA = lC ∧ lC = lT ∧ lT = lE) := by
  constructor
  · rintro ⟨ν, d, h⟩
    have e : ∀ i : Fin 5, (ggeGen lA lC lT lE) i i
        = (ν • Bsum + d • (1 : Matrix (Fin 5) (Fin 5) ℂ)) i i := fun i => by rw [h]
    have e0 := e 0; have e1 := e 1; have e2 := e 2; have e3 := e 3; have e4 := e 4
    simp only [ggeGen, Bsum, QA, QC, QT, EE, Matrix.add_apply, Matrix.smul_apply,
      Matrix.diagonal_apply_eq, Matrix.one_apply_eq, smul_eq_mul,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val] at e0 e1 e2 e3 e4
    norm_num at e0 e1 e2 e3 e4
    refine ⟨?_, ?_, ?_⟩
    · linear_combination (-(4:ℂ)/5) * e1 + (1:ℂ)/5*e0 + (1:ℂ)/5*e4 + (1:ℂ)/5*e2 + (1:ℂ)/5*e3
    · linear_combination (-(4:ℂ)/5) * e2 + (1:ℂ)/5*e0 + (1:ℂ)/5*e4 + (1:ℂ)/5*e1 + (1:ℂ)/5*e3
    · linear_combination (-(4:ℂ)/5) * e3 + (1:ℂ)/5*e0 + (1:ℂ)/5*e4 + (1:ℂ)/5*e1 + (1:ℂ)/5*e2
  · rintro ⟨h1, h2, h3⟩
    subst h1; subst h2; subst h3
    exact ⟨lA, 0, by simp [ggeGen, Bsum, smul_add]⟩

/-- **Forward flow corollary.**  When the four channels share a common inverse
temperature `ν`, the GGE modular flow is genuinely the `B`-generated flow. -/
theorem gge_flow_of_equipartition (ν : ℂ) (a : ℂ) (X : Matrix (Fin 5) (Fin 5) ℂ) :
    NormedSpace.exp (a • ggeGen ν ν ν ν) * X * NormedSpace.exp ((-a) • ggeGen ν ν ν ν)
      = NormedSpace.exp (a • (ν • Bsum)) * X * NormedSpace.exp ((-a) • (ν • Bsum)) := by
  have h : ggeGen ν ν ν ν = ν • Bsum := by
    simp only [ggeGen, Bsum, smul_add]
  rw [h]

/-- **Kill (Conjecture J).**  The KMS-selected generator on the `T2` sector, where the
four channel shares are genuinely distinct (here `1, 2, 3, 4`), is **not** of the form
`ν • B + d • 1` for any scalars.  Hence — by `flow_scalar_shift` / `equipartition_generator`
— its modular flow is *not* `B`-generated: no channel-share constraint short of full
equipartition recovers the posited `B`-flow. -/
theorem conjectureJ_kill :
    ¬ ∃ ν d : ℂ, ggeGen 1 2 3 4 = ν • Bsum + d • (1 : Matrix (Fin 5) (Fin 5) ℂ) := by
  rw [equipartition_generator]
  rintro ⟨h1, -, -⟩
  exact (by norm_num : (1 : ℂ) ≠ 2) h1

end GGE

end ModularSelection

-- Axiom audit
#print axioms ModularSelection.flow_scalar_shift
#print axioms ModularSelection.modular_flow_of_gibbs
#print axioms ModularSelection.gibbs_modHam_exp
#print axioms ModularSelection.equipartition_generator
#print axioms ModularSelection.gge_flow_of_equipartition
#print axioms ModularSelection.conjectureJ_kill
