import Mathlib

/-!
# Focused Cayley/Crank-Nicolson proof target

Mathlib-only extraction of the finite matrix problem. The resulting proofs will
be ported into the project module named in the accompanying task note.
-/

open Matrix Complex

namespace CayleyStandalone

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- Left-hand Crank-Nicolson matrix `I + i dt H / 2`. -/
noncomputable def cayleyA (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  1 + ((((dt / 2 : ℝ) : ℂ) * I) • H)

/-- Right-hand Crank-Nicolson matrix `I - i dt H / 2`. -/
noncomputable def cayleyB (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  1 - ((((dt / 2 : ℝ) : ℂ) * I) • H)

/-- Cayley transfer step generated by `H`. -/
noncomputable def cayleyStep (H : Matrix n n ℂ) (dt : ℝ) : Matrix n n ℂ :=
  (cayleyA H dt)⁻¹ * cayleyB H dt

/-- The Cayley step solves the cleared-denominator Crank-Nicolson update. -/
theorem cayleyStep_iff_linear_update (H : Matrix n n ℂ) (dt : ℝ)
    (hleft : cayleyA H dt * (cayleyA H dt)⁻¹ = 1)
    (hright : (cayleyA H dt)⁻¹ * cayleyA H dt = 1)
    (psi psi' : n -> ℂ) :
    psi' = (cayleyStep H dt).mulVec psi ↔
      (cayleyA H dt).mulVec psi' = (cayleyB H dt).mulVec psi := by
  sorry

/-- The linear update is exactly the finite Crank-Nicolson equation. -/
theorem linear_update_iff_crankNicolson (H : Matrix n n ℂ) (dt : ℝ)
    (psi psi' : n -> ℂ) :
    (cayleyA H dt).mulVec psi' = (cayleyB H dt).mulVec psi ↔
      I • (psi' - psi) =
        ((dt / 2 : ℝ) : ℂ) • H.mulVec (psi' + psi) := by
  sorry

/-- A Hermitian generator with explicit two-sided inverses gives a unitary
Cayley step. -/
theorem cayleyStep_unitary (H : Matrix n n ℂ) (dt : ℝ)
    (hH : H.IsHermitian)
    (hAleft : cayleyA H dt * (cayleyA H dt)⁻¹ = 1)
    (hAright : (cayleyA H dt)⁻¹ * cayleyA H dt = 1)
    (hBleft : cayleyB H dt * (cayleyB H dt)⁻¹ = 1)
    (hBright : (cayleyB H dt)⁻¹ * cayleyB H dt = 1) :
    cayleyStep H dt ∈ Matrix.unitaryGroup n ℂ := by
  sorry

/-! ## Exact two-level turn witness -/

noncomputable def sigmaX : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]
noncomputable def e0 : Fin 2 -> ℂ := ![1, 0]
noncomputable def e1 : Fin 2 -> ℂ := ![0, 1]

theorem sigmaX_sq : sigmaX * sigmaX = 1 := by
  sorry

theorem sigmaX_hermitian : sigmaX.IsHermitian := by
  sorry

/-- Exact inverse at `dt=2`: `(I+i sigmaX)^-1=(I-i sigmaX)/2`. -/
theorem sigmaX_cayley_inverse :
    (cayleyA sigmaX 2)⁻¹ = (1 / 2 : ℂ) • cayleyB sigmaX 2 := by
  sorry

/-- The exact Cayley step at `dt=2` is the nontrivial turn `-i sigmaX`. -/
theorem sigmaX_cayley_step :
    cayleyStep sigmaX 2 = (-I) • sigmaX := by
  sorry

/-- The generated step turns the first basis state into the second with phase
`-i`, so its transition amplitude is exactly nonzero. -/
theorem sigmaX_cayley_turns_basis :
    (cayleyStep sigmaX 2).mulVec e0 = (-I) • e1 ∧
      (cayleyStep sigmaX 2).mulVec e0 1 = -I ∧
      (cayleyStep sigmaX 2).mulVec e0 1 ≠ 0 := by
  sorry

theorem sigmaX_cayley_unitary :
    cayleyStep sigmaX 2 ∈ Matrix.unitaryGroup (Fin 2) ℂ := by
  sorry

end CayleyStandalone
