import Mathlib
import PhysicsSM.Spinor.SpinorTenfoldCAR

/-!
# Spinor.SpinorTenfoldCliffordGroup

The algebraic (even) Clifford group acting on the Fock spinor model: the
group-level entry point of the `Spin(10)` stabilizer program.

## Design decision: algebraic GSpin, no analysis

The group-level statements of `Sources/Spin10_stabilizer.txt` (Lemma S1
transitivity, Lemma S2 stabilizer, the Selector Theorem) need a concrete
group acting on the trusted Fock model `PhysicsSM.Spinor.SpinorTenfoldFock`.
We deliberately avoid Lie-group analysis (exponentials, connectedness):
instead, the group is generated **algebraically** by the invertible Clifford
operators of *anisotropic* vectors.

- For `v : V10` with `Q10 v ≠ 0` the Clifford operator `gammaEnd v` is a
  unit: the Clifford square relation
  `cliffordAction v (cliffordAction v psi) = Q10 v • psi`
  (trusted, `PhysicsSM.Spinor.SpinorTenfoldCAR`) gives the explicit inverse
  `(Q10 v)⁻¹ • gammaEnd v`.
- `evenCliffordGroup` is the subgroup of `(Module.End ℂ FockSpinor)ˣ`
  generated by **products of two** such units. This is the standard
  algebraic model of the even Clifford group `GSpin(10, ℂ)` in its spinor
  representation: even products preserve chirality, conjugation on the
  `gammaEnd` image is by (twisted) reflections, and over `ℂ` the
  Cartan-Dieudonne theorem makes these products cover the full special
  orthogonal action on `V10`.

`evenCliffordGroup` contains every nonzero scalar `c • 1` (see
`scalarUnit`): it is `GSpin`, not `Spin`. This is intentional - marked
transitivity statements ("`g` carries `psi` to `phi` exactly, not just
projectively") are *cleaner* with the scalars available, and the eventual
restriction to `Spin(10)` (spinor norm 1) can be cut out later via the main
anti-involution, which on this concrete model is the adjoint with respect
to the Chevalley pairing of `PhysicsSM.Spinor.SpinorTenfoldPurity`. Until
that refinement lands, theorems proved here are about `GSpin(10, ℂ)` and
must not be advertised as `Spin(10)` statements.

## Main declarations

- `gammaEnd` : the Clifford action as a linear endomorphism (`Module.End`).
- `gammaUnit` : the Clifford operator of an anisotropic vector, as a unit.
- `evenCliffordGroup` : the subgroup generated by pair products of units.
- `flipVec`, `flipUnit`, `flipSet` : the hyperbolic mode-flip vectors
  `e_i + f_i` (with `Q10 = 1`), their units, and the index bookkeeping.
- `scalarUnit` : every nonzero scalar `c • 1` realized inside
  `evenCliffordGroup` (as `gammaUnit (c • flipVec 0) * gammaUnit (flipVec 0)`).
- `reflectTwist` : the twisted reflection
  `u ↦ (B10 u v / Q10 v) • v - u`, which is what conjugation by a single
  `gammaUnit v` induces on the `gammaEnd` image (proved in the draft
  module `PhysicsSM.Draft.SpinorTenfoldCliffordConjAristotle`).
- `PreservesChirality` : the chirality-preservation predicate for
  endomorphisms.

## Successor modules (Aristotle wave 6)

- `PhysicsSM.Draft.SpinorTenfoldCliffordConjAristotle` : conjugation =
  twisted reflection, B10/Q10 invariance, chirality preservation of the
  even group, injectivity of `gammaEnd`.
- `PhysicsSM.Draft.SpinorTenfoldBasisOrbitAristotle` : mode-flip action on
  basis spinors and marked transitivity of `evenCliffordGroup` on the even
  wedge-monomial basis (the normal-form core of Lemma S1).

## Conventions

Everything follows the trusted Fock conventions of
`PhysicsSM.Spinor.SpinorTenfoldFock`: hyperbolic split `V10 = W ⊕ W*`,
`Q10 (a, b) = Σᵢ aᵢ bᵢ`, `B10 v w = Σᵢ (v₁ᵢ w₂ᵢ + v₂ᵢ w₁ᵢ)`, so
`B10 v v = 2 * Q10 v`. The Clifford square is `Q10`-normalized (not
`B10`-normalized): `gammaEnd v * gammaEnd v = Q10 v • 1`.

## Sources

- C. Chevalley, "The Algebraic Theory of Spinors and Clifford Algebras"
  (Clifford group, twisted conjugation).
- Internal research notes: `Sources/Spin10_stabilizer.txt`.
- Provenance: clean-room formalization; no external code copied.

Status: trusted - no `sorry`.
-/

noncomputable section

namespace PhysicsSM.Spinor.SpinorTenfold

/-! ## The Clifford action as a linear endomorphism -/

/-- The Clifford action of `v : V10`, packaged as a linear endomorphism of
the Fock spinor space. Multiplication in `Module.End ℂ FockSpinor` is
composition, so `gammaEnd v * gammaEnd w` is "act by `w`, then by `v`". -/
def gammaEnd (v : V10) : Module.End ℂ FockSpinor where
  toFun := cliffordAction v
  map_add' := cliffordAction_add_spinor v
  map_smul' c psi := cliffordAction_smul_spinor c v psi

@[simp] theorem gammaEnd_apply (v : V10) (psi : FockSpinor) :
    gammaEnd v psi = cliffordAction v psi := rfl

/-- `gammaEnd` is additive in the vector argument. -/
theorem gammaEnd_add (v w : V10) : gammaEnd (v + w) = gammaEnd v + gammaEnd w := by
  refine LinearMap.ext fun psi => ?_
  simp [cliffordAction_add_vec]

/-- `gammaEnd` is homogeneous in the vector argument. -/
theorem gammaEnd_smul (c : ℂ) (v : V10) : gammaEnd (c • v) = c • gammaEnd v := by
  refine LinearMap.ext fun psi => ?_
  simp [cliffordAction_smul_vec]

@[simp] theorem gammaEnd_zero : gammaEnd (0 : V10) = 0 := by
  refine LinearMap.ext fun psi => ?_
  simp

/-- The Clifford square relation in endomorphism form:
`gammaEnd v * gammaEnd v = Q10 v • 1`. This is the trusted
`cliffordAction_cliffordAction_self` of `SpinorTenfoldCAR`. -/
theorem gammaEnd_mul_self (v : V10) :
    gammaEnd v * gammaEnd v = Q10 v • (1 : Module.End ℂ FockSpinor) := by
  refine LinearMap.ext fun psi => ?_
  simp [Module.End.mul_apply, cliffordAction_cliffordAction_self]

/-- The polarized Clifford relation in endomorphism form:
`gammaEnd v * gammaEnd w + gammaEnd w * gammaEnd v = B10 v w • 1`. -/
theorem gammaEnd_mul_anticomm (v w : V10) :
    gammaEnd v * gammaEnd w + gammaEnd w * gammaEnd v
      = B10 v w • (1 : Module.End ℂ FockSpinor) := by
  refine LinearMap.ext fun psi => ?_
  simp [Module.End.mul_apply, cliffordAction_anticomm]

/-! ## Clifford units of anisotropic vectors -/

/-- The Clifford operator of an anisotropic vector (`Q10 v ≠ 0`) as a unit
of the endomorphism ring: the inverse is `(Q10 v)⁻¹ • gammaEnd v` by the
Clifford square relation. -/
def gammaUnit (v : V10) (hv : Q10 v ≠ 0) : (Module.End ℂ FockSpinor)ˣ where
  val := gammaEnd v
  inv := (Q10 v)⁻¹ • gammaEnd v
  val_inv := by
    rw [mul_smul_comm, gammaEnd_mul_self, smul_smul, inv_mul_cancel₀ hv, one_smul]
  inv_val := by
    rw [smul_mul_assoc, gammaEnd_mul_self, smul_smul, inv_mul_cancel₀ hv, one_smul]

@[simp] theorem gammaUnit_val (v : V10) (hv : Q10 v ≠ 0) :
    (gammaUnit v hv : Module.End ℂ FockSpinor) = gammaEnd v := rfl

@[simp] theorem gammaUnit_inv_val (v : V10) (hv : Q10 v ≠ 0) :
    (((gammaUnit v hv)⁻¹ : (Module.End ℂ FockSpinor)ˣ) : Module.End ℂ FockSpinor)
      = (Q10 v)⁻¹ • gammaEnd v := rfl

/-! ## The even Clifford group -/

/-- The generating set of the even Clifford group: products of **two**
anisotropic Clifford units. Even products preserve chirality (each single
`gammaEnd` flips it); products of two reflections generate the special
orthogonal action on vectors. -/
def pairUnitSet : Set (Module.End ℂ FockSpinor)ˣ :=
  {g | ∃ (v w : V10) (hv : Q10 v ≠ 0) (hw : Q10 w ≠ 0),
    g = gammaUnit v hv * gammaUnit w hw}

/-- The even Clifford group `GSpin(10, ℂ)` in its spinor representation:
the subgroup of units of `Module.End ℂ FockSpinor` generated by products
of two anisotropic Clifford units.

Note: this contains all nonzero scalars (`scalarUnit_mem`), so it is the
**general** spin group, not `Spin(10)` itself; see the module docstring. -/
def evenCliffordGroup : Subgroup (Module.End ℂ FockSpinor)ˣ :=
  Subgroup.closure pairUnitSet

/-- Pair products of anisotropic Clifford units generate (hence belong to)
the even Clifford group. -/
theorem gammaUnit_mul_gammaUnit_mem (v w : V10) (hv : Q10 v ≠ 0) (hw : Q10 w ≠ 0) :
    gammaUnit v hv * gammaUnit w hw ∈ evenCliffordGroup :=
  Subgroup.subset_closure ⟨v, w, hv, hw, rfl⟩

/-! ## Mode-flip vectors and units -/

/-- The hyperbolic mode-flip vector `e_i + f_i`: creation coefficient `1`
and annihilation coefficient `1` at index `i`, zero elsewhere. It is
anisotropic with `Q10 (flipVec i) = 1`, and its Clifford operator toggles
the occupation of mode `i` on basis spinors (proved in the basis-orbit
draft module). -/
def flipVec (i : Fin 5) : V10 :=
  (fun j => if j = i then 1 else 0, fun j => if j = i then 1 else 0)

@[simp] theorem Q10_flipVec (i : Fin 5) : Q10 (flipVec i) = 1 := by
  simp [Q10, flipVec]

/-- The mode-flip Clifford unit at index `i`. -/
def flipUnit (i : Fin 5) : (Module.End ℂ FockSpinor)ˣ :=
  gammaUnit (flipVec i) (by rw [Q10_flipVec]; exact one_ne_zero)

@[simp] theorem flipUnit_val (i : Fin 5) :
    (flipUnit i : Module.End ℂ FockSpinor) = gammaEnd (flipVec i) := rfl

/-- Products of two mode flips lie in the even Clifford group. -/
theorem flipUnit_mul_flipUnit_mem (i j : Fin 5) :
    flipUnit i * flipUnit j ∈ evenCliffordGroup :=
  gammaUnit_mul_gammaUnit_mem _ _ _ _

/-- The index bookkeeping for a mode flip: toggle membership of `i` in `T`.
`gammaEnd (flipVec i)` carries `basisSpinor T` to
`opSign i T • basisSpinor (flipSet i T)` (basis-orbit draft module). -/
def flipSet (i : Fin 5) (T : Finset (Fin 5)) : Finset (Fin 5) :=
  if i ∈ T then T.erase i else insert i T

/-! ## Scalars inside the even Clifford group -/

/-- Every nonzero scalar `c` is realized in the even Clifford group as the
pair product `gammaUnit (c • flipVec 0) * gammaUnit (flipVec 0)`, whose
value is `c • 1` (`scalarUnit_val`). This is the scale freedom that makes
*marked* (not merely projective) transitivity statements available. -/
def scalarUnit (c : ℂ) (hc : c ≠ 0) : (Module.End ℂ FockSpinor)ˣ :=
  gammaUnit (c • flipVec 0)
      (by rw [Q10_smul, Q10_flipVec, mul_one]; exact pow_ne_zero 2 hc)
    * gammaUnit (flipVec 0) (by rw [Q10_flipVec]; exact one_ne_zero)

theorem scalarUnit_mem (c : ℂ) (hc : c ≠ 0) : scalarUnit c hc ∈ evenCliffordGroup :=
  gammaUnit_mul_gammaUnit_mem _ _ _ _

@[simp] theorem scalarUnit_val (c : ℂ) (hc : c ≠ 0) :
    (scalarUnit c hc : Module.End ℂ FockSpinor) = c • (1 : Module.End ℂ FockSpinor) := by
  rw [scalarUnit, Units.val_mul, gammaUnit_val, gammaUnit_val, gammaEnd_smul,
    smul_mul_assoc, gammaEnd_mul_self, Q10_flipVec, one_smul]

/-! ## The twisted reflection -/

/-- The twisted reflection of `u` in the anisotropic vector `v`:
`reflectTwist v u = (B10 u v / Q10 v) • v - u`. Conjugating `gammaEnd u`
by `gammaUnit v` produces exactly `gammaEnd (reflectTwist v u)` (proved in
the conjugation draft module); it is minus the usual `B10`-orthogonal
reflection in the hyperplane `v^⊥`, preserves `B10` and `Q10`, and is an
involution.

When `Q10 v = 0` the value is junk (`division by zero`); every theorem
about `reflectTwist` carries the hypothesis `Q10 v ≠ 0`. -/
def reflectTwist (v u : V10) : V10 := (B10 u v / Q10 v) • v - u

/-! ## Chirality preservation -/

/-- An endomorphism preserves chirality if it maps even spinors to even
spinors and odd spinors to odd spinors. Every element of
`evenCliffordGroup` does (conjugation draft module): each generator is a
product of two chirality-*flipping* Clifford operators. -/
def PreservesChirality (g : Module.End ℂ FockSpinor) : Prop :=
  (∀ psi, IsEvenSpinor psi → IsEvenSpinor (g psi))
    ∧ (∀ psi, IsOddSpinor psi → IsOddSpinor (g psi))

end PhysicsSM.Spinor.SpinorTenfold

end
