import PhysicsSM.Spinor.SpinorTenfoldSO10Action
import PhysicsSM.Spinor.SpinorTenfoldWeakQuotientDescent

/-!
# A nonidentity so(10) generator on the marked-pair weak quotient

This module closes the first concrete action gate after
`SpinorTenfoldWeakQuotientDescent`. In the trusted hyperbolic-coordinate model
`V10 = W + W*`, the infinitesimal vector action generated by the bivector
`e_3 wedge f_4` preserves the first pure-spinor annihilator and its common
three-dimensional color axis. It therefore descends to the two-dimensional
quotient, where an explicit displacement of the `f_3` class proves that the
action is nonidentity.

Two controls show that the descent hypotheses are substantive: `e_3 wedge e_4`
fails to preserve the first annihilator, while `e_0 wedge f_3` preserves that
annihilator but fails to preserve the color axis.

Claim boundary: all preservation proofs are coordinate calculations for the
fixed normal-form marked pair. This is an infinitesimal complex-linear
`so(10)` action, not a constructed `Spin(10)` stabilizer, compact real form, or
physical `SU(2)_L` representation. The name "weak" remains motivational until
those later identifications are proved.

Provenance: theorem architecture and witnesses were proposed by Aristotle
project `ca38beab-2c0d-4a27-9d45-9fe61a601ebd`; this is a clean-room
composition against the live trusted APIs. No compiled evaluator is used.
-/

noncomputable section

namespace PhysicsSM.Spinor.SpinorTenfold

open scoped BigOperators

/-! ## Linear packaging of the vector action -/

private theorem B10_add_right_local (u v w : V10) :
    B10 u (v + w) = B10 u v + B10 u w := by
  unfold B10
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro i _
  simp only [Prod.fst_add, Prod.snd_add, Pi.add_apply]
  ring

/-- The existing `soAd v w` vector action packaged as a complex-linear map in
the acted-on vector. -/
def soAdLinear (v w : V10) : V10 →ₗ[Complex] V10 where
  toFun := soAd v w
  map_add' u u' := by
    simp only [soAd, B10_add_right_local]
    module
  map_smul' c u := by
    simp only [soAd, B10_smul_right, RingHom.id_apply]
    module

@[simp] theorem soAdLinear_apply (v w u : V10) :
    soAdLinear v w u = soAd v w u := rfl

/-! ## Hyperbolic basis vectors -/

/-- Creation-coordinate basis vector `e_i`. -/
def eMode (i : Fin 5) : V10 := (Pi.single i 1, 0)

/-- Annihilation-coordinate basis vector `f_i`. -/
def fMode (i : Fin 5) : V10 := (0, Pi.single i 1)

@[simp] theorem B10_eMode (i : Fin 5) (u : V10) :
    B10 (eMode i) u = u.2 i := by
  simp [B10, eMode, Pi.single_apply, ite_mul, Finset.sum_ite_eq']

@[simp] theorem B10_fMode (i : Fin 5) (u : V10) :
    B10 (fMode i) u = u.1 i := by
  simp [B10, fMode, Pi.single_apply, ite_mul, Finset.sum_ite_eq']

/-! ## The descending generator -/

/-- Coordinate-only: `soAd e_3 f_4` maps the first annihilator to itself. -/
theorem E34_mapsTo_vacuumAnnihilator :
    ∀ u ∈ annihilator vacuumSpinor,
      soAdLinear (eMode 3) (fMode 4) u ∈ annihilator vacuumSpinor := by
  intro u hu
  rw [mem_annihilator_vacuumSpinor_iff] at hu ⊢
  simp only [soAdLinear_apply, soAd, B10_fMode, B10_eMode, hu,
    Pi.zero_apply, zero_smul, zero_sub, Prod.fst_neg, Prod.smul_fst]
  simp [fMode]

/-- The `e_3 wedge f_4` generator restricted to the first annihilator. -/
def weakRaisingGenerator :
    VacuumAnnihilator →ₗ[Complex] VacuumAnnihilator :=
  (soAdLinear (eMode 3) (fMode 4)).restrict
    E34_mapsTo_vacuumAnnihilator

@[simp] theorem weakRaisingGenerator_coe (x : VacuumAnnihilator) :
    ((weakRaisingGenerator x : VacuumAnnihilator) : V10) =
      soAd (eMode 3) (fMode 4) (x : V10) := rfl

/-- Coordinate-only: the restricted generator preserves the common color
axis. On that axis the third annihilation coordinate vanishes, so the action
is zero. -/
theorem weakRaisingGenerator_preserves_color :
    ∀ x ∈ colorAxisInVacuum,
      weakRaisingGenerator x ∈ colorAxisInVacuum := by
  intro x hx
  change ((x : VacuumAnnihilator) : V10) ∈ colorAxisSubmodule at hx
  have hc := (mem_colorAxis_iff _).1 hx
  have hx1 : (x : V10).1 = 0 :=
    (mem_annihilator_vacuumSpinor_iff _).1 x.2
  have hx3 : (x : V10).2 (3 : Fin 5) = 0 := by
    simpa using hc.2.1
  have hzero : weakRaisingGenerator x = 0 := by
    apply Subtype.ext
    simp only [weakRaisingGenerator_coe, soAd, B10_fMode, B10_eMode,
      hx1, Pi.zero_apply, zero_smul, zero_sub]
    simp [hx3]
  rw [hzero]
  exact Submodule.zero_mem _

/-- The explicit third annihilation direction is moved outside its original
color-axis coset by the raising generator. -/
theorem weakRaisingGenerator_displacement_not_color :
    weakRaisingGenerator weakDirection3 - weakDirection3 ∉
      colorAxisInVacuum := by
  intro h
  change (((weakRaisingGenerator weakDirection3 - weakDirection3 :
    VacuumAnnihilator) : V10) ∈ colorAxisSubmodule) at h
  have hc := (mem_colorAxis_iff _).1 h
  have h3 := hc.2.1
  simp only [Submodule.coe_sub, weakRaisingGenerator_coe, soAd, B10_fMode,
    B10_eMode, Prod.snd_sub, Prod.smul_snd, Pi.sub_apply,
    Pi.smul_apply, smul_eq_mul] at h3
  simp [weakDirection3, fMode] at h3

/-- The explicit `so(10)` raising generator descends to a nonidentity operator
on the marked-pair weak quotient. Nonidentity is certified by the moved
`weakDirection3` class, not by a dimension count. -/
theorem weakRaisingGenerator_descend_ne_id :
    weakQuotientDescend weakRaisingGenerator
      weakRaisingGenerator_preserves_color ≠ LinearMap.id := by
  apply weakQuotientDescend_ne_id_of_exists
  exact ⟨weakDirection3, weakRaisingGenerator_displacement_not_color⟩

/-- Existential form of the first concrete nonidentity action gate. -/
theorem exists_nonidentity_so10_weakQuotient_action :
    ∃ (f : VacuumAnnihilator →ₗ[Complex] VacuumAnnihilator)
      (hcolor : ∀ x ∈ colorAxisInVacuum, f x ∈ colorAxisInVacuum),
      weakQuotientDescend f hcolor ≠ LinearMap.id :=
  ⟨weakRaisingGenerator, weakRaisingGenerator_preserves_color,
    weakRaisingGenerator_descend_ne_id⟩

/-! ## Non-preservation controls -/

/-- A creation-creation generator fails to preserve the first annihilator:
`soAd e_3 e_4` sends `f_4` to `e_3`. -/
theorem soAd_e3e4_not_preserves_vacuumAnnihilator :
    soAd (eMode 3) (eMode 4) (fMode 4) ∉
      annihilator vacuumSpinor := by
  intro h
  have hfst := (mem_annihilator_vacuumSpinor_iff _).1 h
  have h3 := congrFun hfst (3 : Fin 5)
  rw [soAd, B10_eMode, B10_eMode] at h3
  simp [eMode, fMode] at h3

/-- The mixed generator `soAd e_0 f_3` preserves the first annihilator but
does not preserve the color axis: it sends `f_0` to `-f_3`. -/
theorem soAd_e0f3_breaks_color_control :
    fMode 0 ∈ colorAxisSubmodule ∧
      soAd (eMode 0) (fMode 3) (fMode 0) ∉ colorAxisSubmodule := by
  constructor
  · rw [mem_colorAxis_iff]
    simp [IsColorAxisVector, fMode]
  · intro h
    have hc := (mem_colorAxis_iff _).1 h
    have h3 := hc.2.1
    rw [soAd, B10_fMode, B10_eMode] at h3
    simp [eMode, fMode] at h3

/-! ## Build-enforced assumption pins -/

/-- info: 'PhysicsSM.Spinor.SpinorTenfold.weakRaisingGenerator_descend_ne_id' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms weakRaisingGenerator_descend_ne_id

/-- info: 'PhysicsSM.Spinor.SpinorTenfold.exists_nonidentity_so10_weakQuotient_action' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms exists_nonidentity_so10_weakQuotient_action

/-- info: 'PhysicsSM.Spinor.SpinorTenfold.soAd_e3e4_not_preserves_vacuumAnnihilator' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms soAd_e3e4_not_preserves_vacuumAnnihilator

/-- info: 'PhysicsSM.Spinor.SpinorTenfold.soAd_e0f3_breaks_color_control' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms soAd_e0f3_breaks_color_control

end PhysicsSM.Spinor.SpinorTenfold
