import Mathlib

/-!
# Finite diagonal-plus-causal support decomposition

This focused handoff separates the diagonal contact term of a finite
diagonal-plus-causal scalar response from its strict-past propagation.
Matrix rows are targets and columns are sources.

No continuum limit or physical Green-function identification is claimed.
-/

noncomputable section

namespace FiniteDiagonalCausalSupport

open scoped BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- A finite transitive irreflexive relation. -/
structure FiniteStrictRelation (V : Type*) where
  before : V -> V -> Prop
  irreflexive : forall x, Not (before x x)
  transitive : forall {x y z}, before x y -> before y z -> before x z

/-- Entrywise strict-past support for target-source matrices. -/
def MatrixSupportedInStrictPast
    (C : FiniteStrictRelation V) (A : Matrix V V Real) : Prop :=
  forall target source, Not (C.before source target) -> A target source = 0

/-- Finite geometric candidate for the inverse of `a * I + N`. -/
def nilpotentInverse
    (a : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (a⁻¹) • ∑ k ∈ Finset.range H, (-a⁻¹) ^ k • N ^ k

/-- Massive scattering response generated by `G0 = b * I + N`. -/
def massiveScatteringResponse
    (b c : Real) (N : Matrix V V Real) (H : Nat) : Matrix V V Real :=
  (b • (1 : Matrix V V Real) + N) *
    nilpotentInverse (1 + c * b) (c • N) H

/-- Products of strict-past-supported matrices remain supported there. -/
theorem matrixSupportedInStrictPast_mul
    (C : FiniteStrictRelation V) {A B : Matrix V V Real}
    (hA : MatrixSupportedInStrictPast C A)
    (hB : MatrixSupportedInStrictPast C B) :
    MatrixSupportedInStrictPast C (A * B) := by
  sorry

/-- Positive powers preserve strict-past support. -/
theorem matrixSupportedInStrictPast_pow_succ
    (C : FiniteStrictRelation V) {A : Matrix V V Real}
    (hA : MatrixSupportedInStrictPast C A) (n : Nat) :
    MatrixSupportedInStrictPast C (A ^ (n + 1)) := by
  sorry

/-- The finite inverse differs from its diagonal contact term only by a
strict-past-supported matrix. -/
theorem nilpotentInverse_diagonalRemainder_supported
    (C : FiniteStrictRelation V) (a : Real) (N : Matrix V V Real) (H : Nat)
    (hH : 0 < H) (hN : MatrixSupportedInStrictPast C N) :
    MatrixSupportedInStrictPast C
      (nilpotentInverse a N H - a⁻¹ • (1 : Matrix V V Real)) := by
  sorry

/-- Headline split: the massive response has diagonal coefficient
`b / (1 + c*b)` and a strict-past-supported remainder. -/
theorem massiveScatteringResponse_diagonalRemainder_supported
    (C : FiniteStrictRelation V) (b c : Real)
    (N : Matrix V V Real) (H : Nat)
    (hH : 0 < H) (hN : MatrixSupportedInStrictPast C N) :
    MatrixSupportedInStrictPast C
      (massiveScatteringResponse b c N H -
        (b / (1 + c * b)) • (1 : Matrix V V Real)) := by
  sorry

/-- Every diagonal entry of the massive response is exactly the local contact
coefficient. -/
theorem massiveScatteringResponse_diagonal_eq
    (C : FiniteStrictRelation V) (b c : Real)
    (N : Matrix V V Real) (H : Nat)
    (hH : 0 < H) (hN : MatrixSupportedInStrictPast C N) (x : V) :
    massiveScatteringResponse b c N H x x = b / (1 + c * b) := by
  sorry

/-- Away from the diagonal, the response vanishes unless the source is in the
supplied strict past of the target. -/
theorem massiveScatteringResponse_offDiagonal_eq_zero_of_not_before
    (C : FiniteStrictRelation V) (b c : Real)
    (N : Matrix V V Real) (H : Nat)
    (hH : 0 < H) (hN : MatrixSupportedInStrictPast C N)
    (target source : V) (hne : source ≠ target)
    (hNotBefore : Not (C.before source target)) :
    massiveScatteringResponse b c N H target source = 0 := by
  sorry

end FiniteDiagonalCausalSupport

end
