import PhysicsSM.Draft.NullEdge.GateC1.TetrahedralBranchWindow

/-!
# Gate C1 tetrahedral lattice-duality / Brillouin-torus theorem (C244)

C240 proves the tetrahedral 16-branch count *under the assumption* that the four
coordinates `k_A` are independent `2*pi`-periodic Brillouin-torus angles.  This
module turns that assumption into a theorem by formalizing the finite
lattice-duality layer in three levels.

## Model (explicit)

The free null-edge translation group is the rank-4 abelian group
`Lambda_tet ≅ Z^4` generated by the four edge shifts `e_A = a · n_A`, where
`n_A = (1, v_A)` and `v_A` are the regular-tetrahedron vertices (`= w_A / √3`
with `w_A` the unscaled `±1` vertices of `TetrahedralBranchWindow`).

Its dual Brillouin torus is `Hom(Lambda_tet, U(1)) ≅ (R / 2*pi Z)^4`, with
independent coordinates `k_A` defined by the characters `T_A ↦ exp(i k_A)`.

We treat `p` as a **dual covector / character coordinate** on the lattice, *not*
as hypercubic Euclidean momentum: `k_A = p(e_A)` is the pairing of the character
`p` with the generator `e_A`, and the coordinate map is `p ↦ (n_A · p)_A`.  No
cubic Brillouin cell is imported.  Nullness of the `n_A` is part of the physical
interpretation and is *not* used as a relation among the four rank-4 translation
generators.

## The three levels

* **Level 1 (finite matrix).**  The `4 × 4` matrix `NtetMat` whose rows are
  `(1, w_A)` is invertible over `R` (`NtetMat_det = -16`, `NtetMat_isUnit_det`).
  Hence the homogeneous coordinate map `p ↦ NtetMat.mulVec p` is a real-linear
  equivalence `tetraLinearEquiv`, and `homogeneousTetraMap` is injective.

* **Level 2 (integer lattice).**  The same matrix over `Z` (`NtetMatZ`) has
  `det = -16`, so `NtetMatZ.mulVec` maps `Z^4` onto a sublattice of `Z^4` of
  index `|det| = 16` (`NtetMatZ_det_natAbs`).  See the normalization discussion.

* **Level 3 (torus).**  With the **period (dual) lattice** `nullEdgeDualLattice`
  defined as the kernel of the character map `p ↦ (exp(i (n_A · p)))_A`, the
  quotient `(R^4) ⧸ nullEdgeDualLattice` is `AddEquiv` to the torus
  `Fin 4 → AddCircle (2*pi)` (`tetraTorusEquiv`).  The period lattice is exactly
  the set of `p` with every `k_A = (NtetMat.mulVec p) A ∈ 2*pi*Z`
  (`mem_nullEdgeDualLattice`).

## Normalization / modeling notes

* **Which lattice?**  Over `Z`, the rows `(1, w_A)` generate a sublattice of
  `Z^4` of index `16`; they are *not* a primitive `Z`-basis of `Z^4`.  For the
  branch count one should take `Lambda_tet` to be the rank-4 lattice
  `span_Z {(1, w_A)}` *by definition* (equivalently the rescaled primitive
  lattice `span_Z {n_A}` with `n_A = (1, w_A/√3)`); this is a genuine modeling
  choice and is stated as such.  The integer index `16` is the determinant fact
  `NtetMatZ.det = -16`, not the branch count.

* **2*pi periodicity.**  The `k_A` are genuinely `2*pi`-periodic *independent*
  angles precisely because (i) `NtetMat` is invertible (independence) and
  (ii) the dual lattice is *defined* as the `2*pi*Z`-preimage
  (`mem_nullEdgeDualLattice`), which is the choice that makes `T_A ↦ exp(i k_A)`
  well defined on the torus.  No further normalization is needed.

* **Theorem vs. modeling assumption.**  Theorems: invertibility,
  determinant/index, and the torus `AddEquiv`.  Modeling assumptions: the
  identification of the physical translation lattice with `span_Z {n_A}` and the
  choice of the `2*pi`-period normalization of the characters.

No analytic, gauge, anomaly, determinant-line, Krein, or `GateC1_NU` claim is
made here.
-/

namespace PhysicsSM
namespace Draft
namespace NullEdge
namespace GateC1
namespace TetrahedralLatticeDuality

open scoped BigOperators Real
open Matrix

/-- Local abbreviation for the C240 unscaled `±1` tetrahedron vertices `w_A`. -/
abbrev wTetra := TetrahedralBranchWindow.wTetra

/--
The unscaled homogeneous tetrahedral coordinate map.

For coefficients `c_A`, this returns the four sums:

```text
sum_A c_A,
sum_A c_A w_A^0,
sum_A c_A w_A^1,
sum_A c_A w_A^2.
```

This is the finite matrix underlying the `p |-> (n_A dot p)_A` coordinate
change.  C240's `tetra_homogeneous_injective` proves that its kernel is zero.
-/
def homogeneousTetraMap (c : Fin 4 -> ℝ) : Fin 4 -> ℝ
  | 0 => c 0 + c 1 + c 2 + c 3
  | 1 => c 0 * wTetra 0 0 + c 1 * wTetra 1 0
      + c 2 * wTetra 2 0 + c 3 * wTetra 3 0
  | 2 => c 0 * wTetra 0 1 + c 1 * wTetra 1 1
      + c 2 * wTetra 2 1 + c 3 * wTetra 3 1
  | 3 => c 0 * wTetra 0 2 + c 1 * wTetra 1 2
      + c 2 * wTetra 2 2 + c 3 * wTetra 3 2

/-- Finite kernel theorem for the homogeneous tetrahedral coordinate map. -/
theorem homogeneousTetraMap_eq_zero_imp (c : Fin 4 -> ℝ)
    (h : homogeneousTetraMap c = 0) :
    c = 0 := by
  have h0 := congr_fun h 0
  have h1 := congr_fun h 1
  have h2 := congr_fun h 2
  have h3 := congr_fun h 3
  simp only [homogeneousTetraMap, Pi.zero_apply] at h0 h1 h2 h3
  obtain ⟨a0, a1, a2, a3⟩ :=
    TetrahedralBranchWindow.tetra_homogeneous_injective c h0 h1 h2 h3
  funext A
  fin_cases A <;> simp_all

/-- The homogeneous tetrahedral coordinate map is injective. -/
theorem homogeneousTetraMap_injective :
    Function.Injective homogeneousTetraMap := by
  intro c d hcd
  apply sub_eq_zero.mp
  apply homogeneousTetraMap_eq_zero_imp
  have e0 := congr_fun hcd 0
  have e1 := congr_fun hcd 1
  have e2 := congr_fun hcd 2
  have e3 := congr_fun hcd 3
  simp only [homogeneousTetraMap, Pi.zero_apply] at e0 e1 e2 e3
  funext A
  fin_cases A <;>
    simp only [homogeneousTetraMap, Pi.sub_apply, Pi.zero_apply, sub_mul] <;> linarith

/-! ## Level 1 — finite invertible matrix and the linear equivalence -/

/--
The `4 × 4` homogeneous tetrahedral matrix with rows `(1, w_A)`, `w_A` the
unscaled `±1` tetrahedron vertices from `TetrahedralBranchWindow`.

`homogeneousTetraMap` is exactly `NtetMat.mulVec` (see
`homogeneousTetraMap_eq_mulVec`).
-/
def NtetMat : Matrix (Fin 4) (Fin 4) ℝ :=
  !![1, 1, 1, 1;
     1, 1, -1, -1;
     1, -1, 1, -1;
     1, -1, -1, 1]

theorem homogeneousTetraMap_eq_mulVec (c : Fin 4 → ℝ) :
    homogeneousTetraMap c = NtetMat.mulVec c := by
  funext i
  fin_cases i <;>
    simp [homogeneousTetraMap, NtetMat, Matrix.mulVec, dotProduct,
      Fin.sum_univ_four, wTetra, TetrahedralBranchWindow.wTetra] <;> ring

/-- The homogeneous tetrahedral matrix has determinant `-16` (so `|det| = 16`). -/
theorem NtetMat_det : NtetMat.det = -16 := by
  rw [NtetMat, Matrix.det_succ_row_zero]
  simp [Fin.sum_univ_four, Matrix.det_fin_three, Matrix.submatrix_apply,
    Fin.succAbove, Fin.succ]
  norm_num

/-- The determinant is a unit of `R`, hence `NtetMat` is invertible. -/
theorem NtetMat_isUnit_det : IsUnit NtetMat.det := by
  rw [NtetMat_det]
  exact (isUnit_iff_ne_zero).mpr (by norm_num)

/-- `NtetMat` is invertible (as a matrix). -/
noncomputable instance : Invertible NtetMat :=
  NtetMat.invertibleOfIsUnitDet NtetMat_isUnit_det

/--
**Level 1 coordinate equivalence.**  The homogeneous tetrahedral coordinate map
`p ↦ NtetMat.mulVec p` is a real-linear equivalence on `R^4`.
-/
noncomputable def tetraLinearEquiv : (Fin 4 → ℝ) ≃ₗ[ℝ] (Fin 4 → ℝ) :=
  NtetMat.toLinearEquiv' (inferInstance)

theorem tetraLinearEquiv_apply (p : Fin 4 → ℝ) :
    tetraLinearEquiv p = NtetMat.mulVec p := by
  have h : (↑(NtetMat.toLinearEquiv' inferInstance) : (Fin 4 → ℝ) →ₗ[ℝ] _)
      = toLin' NtetMat := Matrix.toLinearEquiv'_apply NtetMat inferInstance
  rw [tetraLinearEquiv, ← Matrix.toLin'_apply NtetMat p, ← h]
  rfl

theorem tetraLinearEquiv_apply_eq_homogeneous (p : Fin 4 → ℝ) :
    tetraLinearEquiv p = homogeneousTetraMap p := by
  rw [tetraLinearEquiv_apply, homogeneousTetraMap_eq_mulVec]

/-! ## Level 2 — the integer lattice and its index -/

/-- The same homogeneous matrix over `Z`. -/
def NtetMatZ : Matrix (Fin 4) (Fin 4) ℤ :=
  !![1, 1, 1, 1;
     1, 1, -1, -1;
     1, -1, 1, -1;
     1, -1, -1, 1]

/--
**Level 2 determinant fact.**  Over `Z`, `NtetMatZ.det = -16`.  Consequently
`NtetMatZ.mulVec : Z^4 → Z^4` is injective with image a sublattice of `Z^4` of
index `|det| = 16` (the standard `AddSubgroup.index = |det|` fact for an
integral matrix).
-/
theorem NtetMatZ_det : NtetMatZ.det = -16 := by
  rw [NtetMatZ, Matrix.det_succ_row_zero]
  simp [Fin.sum_univ_four, Matrix.det_fin_three, Matrix.submatrix_apply,
    Fin.succAbove, Fin.succ]

/-- The absolute value of the integer determinant — the lattice index — is `16`. -/
theorem NtetMatZ_det_natAbs : NtetMatZ.det.natAbs = 16 := by
  rw [NtetMatZ_det]; rfl

/-! ## Level 3 — the dual Brillouin torus -/

/-- The dual Brillouin torus `(R / 2*pi Z)^4`. -/
abbrev Torus := Fin 4 → AddCircle (2 * Real.pi)

/--
The character / angle-coordinate map `p ↦ (exp(i k_A))_A`, written additively as
`p ↦ (k_A mod 2*pi)_A` with `k_A = (NtetMat.mulVec p) A`.

It is the linear equivalence `tetraLinearEquiv` followed by the coordinatewise
quotient `R ↠ R/2*pi*Z`, hence an additive group homomorphism.
-/
noncomputable def toTorusHom : (Fin 4 → ℝ) →+ Torus where
  toFun p := fun A =>
    (QuotientAddGroup.mk' (AddSubgroup.zmultiples (2 * Real.pi))) (tetraLinearEquiv p A)
  map_zero' := by
    funext A; simp
  map_add' := by
    intro p q
    funext A
    simp only [map_add, Pi.add_apply]

theorem toTorusHom_apply (p : Fin 4 → ℝ) (A : Fin 4) :
    toTorusHom p A = (((NtetMat.mulVec p) A : ℝ) : AddCircle (2 * Real.pi)) := by
  change (QuotientAddGroup.mk' (AddSubgroup.zmultiples (2 * Real.pi)))
      (tetraLinearEquiv p A) = _
  rw [tetraLinearEquiv_apply]
  rfl

/-- The angle-coordinate map is surjective onto the torus. -/
theorem toTorusHom_surjective : Function.Surjective toTorusHom := by
  intro t
  choose r hr using fun A =>
    QuotientAddGroup.mk'_surjective (AddSubgroup.zmultiples (2 * Real.pi)) (t A)
  obtain ⟨p, hp⟩ := tetraLinearEquiv.surjective r
  refine ⟨p, ?_⟩
  funext A
  change (QuotientAddGroup.mk' (AddSubgroup.zmultiples (2 * Real.pi)))
      (tetraLinearEquiv p A) = t A
  rw [hp]
  exact hr A

/--
**Definition: the null-edge period (dual) lattice.**  This is the kernel of the
character map, i.e. the set of character coordinates `p` for which every
`k_A = (NtetMat.mulVec p) A` is an integer multiple of `2*pi`.
-/
noncomputable def nullEdgeDualLattice : AddSubgroup (Fin 4 → ℝ) :=
  toTorusHom.ker

/-- The period lattice is exactly `{p : ∀ A, k_A ∈ 2*pi*Z}`. -/
theorem mem_nullEdgeDualLattice (p : Fin 4 → ℝ) :
    p ∈ nullEdgeDualLattice ↔
      ∀ A, ∃ n : ℤ, (NtetMat.mulVec p) A = (n : ℝ) * (2 * Real.pi) := by
  simp only [nullEdgeDualLattice, AddMonoidHom.mem_ker, funext_iff, Pi.zero_apply]
  refine forall_congr' (fun A => ?_)
  rw [toTorusHom_apply, QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_zmultiples_iff]
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨n, by rw [← hn, zsmul_eq_mul]⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, by rw [zsmul_eq_mul, hn]⟩

/--
**Level 3 torus theorem.**  The dual torus of the null-edge lattice is
`(R / 2*pi Z)^4`: the quotient of `R^4` by the period lattice
`nullEdgeDualLattice` is additively isomorphic to `Fin 4 → AddCircle (2*pi)`,
via the character map `p ↦ (exp(i (n_A · p)))_A`.
-/
noncomputable def tetraTorusEquiv :
    ((Fin 4 → ℝ) ⧸ nullEdgeDualLattice) ≃+ Torus :=
  QuotientAddGroup.quotientKerEquivOfSurjective toTorusHom toTorusHom_surjective

/-! ## Source-contract structures (from the C244 scaffold)

The structures below are retained from the original Codex scaffold.  As
originally written they were `Prop`-valued structures with `Prop`-valued *data*
fields, which Lean rejects (a `Prop` structure's fields must be proofs).  They
are therefore kept here in commented form, together with their replacement: the
concrete theorems above already discharge the contract —

* independence of the angle coordinates  : `tetraLinearEquiv` / `NtetMat_det`;
* `2*pi` periodicity of the angles        : `mem_nullEdgeDualLattice`;
* descent to / equivalence with the torus : `tetraTorusEquiv`.

```text
structure TetrahedralAngleCoordinateContract : Prop where
  lattice_is_span_of_null_edges : Prop
  dual_periods_are_two_pi : Prop
  angle_map_descends_to_torus : Prop
  angle_map_is_torus_equiv : Prop

structure IndependentTetrahedralAngles : Prop where
  contract : TetrahedralAngleCoordinateContract
  independent_angles : contract.angle_map_is_torus_equiv

theorem c240_lattice_duality_target_statement :
    (∃ _h : IndependentTetrahedralAngles, True) -> True := by
  intro _; trivial
```
-/

end TetrahedralLatticeDuality
end GateC1
end NullEdge
end Draft
end PhysicsSM
