import Mathlib

open scoped BigOperators
open Set Submodule

set_option autoImplicit false
set_option maxHeartbeats 8000000

namespace FrameBlindness

/-- A continuous orthogonal representation of a compact topological group. -/
structure CompactOrthogonalRepresentation (G V : Type*)
    [Group G] [TopologicalSpace G]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V] where
  toMonoidHom : G →* (V ≃ₗᵢ[ℝ] V)
  continuous : Continuous (fun p : G × V => toMonoidHom p.1 p.2)

namespace CompactOrthogonalRepresentation

variable {G V : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [NormedAddCommGroup V] [InnerProductSpace ℝ V]
  [FiniteDimensional ℝ V]

/-- The action associated to a representation. -/
def act (ρ : CompactOrthogonalRepresentation G V) (g : G) (v : V) : V :=
  ρ.toMonoidHom g v

@[simp] theorem act_one (ρ : CompactOrthogonalRepresentation G V) (v : V) :
    ρ.act 1 v = v := by
      simp [CompactOrthogonalRepresentation.act]

@[simp] theorem act_mul (ρ : CompactOrthogonalRepresentation G V) (g h : G) (v : V) :
    ρ.act (g * h) v = ρ.act g (ρ.act h v) := by
      unfold CompactOrthogonalRepresentation.act; simp +decide [ map_mul, ρ.toMonoidHom.map_mul ] ;

@[simp] theorem act_add (ρ : CompactOrthogonalRepresentation G V) (g : G) (v w : V) :
    ρ.act g (v + w) = ρ.act g v + ρ.act g w := by
      exact ρ.toMonoidHom g |>.map_add v w

@[simp] theorem act_smul (ρ : CompactOrthogonalRepresentation G V) (g : G) (a : ℝ) (v : V) :
    ρ.act g (a • v) = a • ρ.act g v := by
      exact ρ.toMonoidHom g |>.map_smul a v

@[simp] theorem inner_act_act (ρ : CompactOrthogonalRepresentation G V) (g : G) (v w : V) :
    inner ℝ (ρ.act g v) (ρ.act g w) = inner ℝ v w := by
      -- Apply the fact that ρ.act g is a linear isometry to conclude the proof.
      apply LinearIsometryEquiv.inner_map_map (ρ.toMonoidHom g) v w

/-- The orbit of a vector. -/
def orbit (ρ : CompactOrthogonalRepresentation G V) (v : V) : Set V :=
  {w | ∃ g : G, ρ.act g v = w}

/-- The subrepresentation generated by one orbit. -/
def orbitSpan (ρ : CompactOrthogonalRepresentation G V) (v : V) : Submodule ℝ V :=
  Submodule.span ℝ (ρ.orbit v)

/-- Equivariance (commutation with the group action). -/
def Invariant (ρ : CompactOrthogonalRepresentation G V) (C : V →L[ℝ] V) : Prop :=
  ∀ g v, C (ρ.act g v) = ρ.act g (C v)

/-- Quadratic variance associated to an operator. -/
def variance (C : V →L[ℝ] V) (v : V) : ℝ := inner ℝ v (C v)

/-
Invariance makes quadratic variance constant along every orbit.
-/
theorem variance_act (ρ : CompactOrthogonalRepresentation G V) (C : V →L[ℝ] V)
    (hC : ρ.Invariant C) (g : G) (v : V) :
    variance C (ρ.act g v) = variance C v := by
      unfold variance;
      rw [ ← ρ.inner_act_act g v ( C v ), hC ]

/-
For a positive semidefinite operator, zero quadratic variance means membership
in the operator kernel.
-/
theorem apply_eq_zero_of_variance_eq_zero (ρ : CompactOrthogonalRepresentation G V)
    (C : V →L[ℝ] V) (hC : C.IsPositive) {v : V} (hv : variance C v = 0) :
    C v = 0 := by
      -- By definition of $hC$, we know that $C$ is self-adjoint.
      have h_self_adjoint : ∀ u v : V, inner ℝ (C u) v = inner ℝ u (C v) := by
        convert hC.1 using 1;
      contrapose! hv;
      have h_var_pos : ∀ u : V, inner ℝ (C u) u ≥ 0 := by
        exact fun u => hC.2 u;
      have h_var_pos : ∀ u : V, inner ℝ (C u) u = 0 → C u = 0 := by
        intro u hu
        have h_var_pos : ∀ t : ℝ, inner ℝ (C (u + t • C u)) (u + t • C u) ≥ 0 := by
          exact fun t => h_var_pos _;
        have h_var_pos : ∀ t : ℝ, inner ℝ (C u) u + 2 * t * inner ℝ (C u) (C u) + t^2 * inner ℝ (C (C u)) (C u) ≥ 0 := by
          convert h_var_pos using 2 ; simp +decide [ hu, h_self_adjoint, inner_add_left, inner_add_right, inner_smul_left, inner_smul_right ] ; ring;
        have h_var_pos : inner ℝ (C u) (C u) = 0 := by
          by_cases h₂ : inner ℝ (C (C u)) (C u) = 0;
          · nlinarith [ h_var_pos ( -1 ), h_var_pos 1 ];
          · by_cases h₂ : inner ℝ (C (C u)) (C u) > 0;
            · nlinarith [ h_var_pos ( - ( inner ℝ ( C u ) ( C u ) ) / inner ℝ ( C ( C u ) ) ( C u ) ), mul_div_cancel₀ ( - ( inner ℝ ( C u ) ( C u ) ) ) ‹_› ];
            · exact False.elim <| h₂ <| lt_of_le_of_ne ( by solve_by_elim ) <| Ne.symm ‹_›;
        exact inner_self_eq_zero.mp h_var_pos;
      exact fun h => hv <| h_var_pos v <| by simpa [ h_self_adjoint ] using h;

/-
The kernel of an equivariant operator is stable under the group.
-/
theorem kernel_invariant (ρ : CompactOrthogonalRepresentation G V) (C : V →L[ℝ] V)
    (hC : ρ.Invariant C) (g : G) {v : V} (hv : v ∈ LinearMap.ker C.toLinearMap) :
    ρ.act g v ∈ LinearMap.ker C.toLinearMap := by
      simp_all +decide [ ContinuousLinearMap.coe_coe ];
      convert hC g v using 1 ; simp +decide [ hv ];
      exact Eq.symm ( map_zero _ )

/-
Suppression propagates from a vector to every point of its orbit.
-/
theorem suppresses_orbit (ρ : CompactOrthogonalRepresentation G V) (C : V →L[ℝ] V)
    (hpos : C.IsPositive) (hinv : ρ.Invariant C) {v : V} (hv : variance C v = 0)
    (g : G) : C (ρ.act g v) = 0 := by
      -- By the properties of the variance and the equivariance of $C$, we have $variance C (ρ.act g v) = variance C v$.
      have h_var_eq : variance C (ρ.act g v) = variance C v := by
        convert variance_act ρ C hinv g v;
      exact apply_eq_zero_of_variance_eq_zero ρ C hpos ( h_var_eq.trans hv )

/-
Suppression propagates to the entire orbit-generated subrepresentation.
-/
theorem orbitSpan_le_kernel (ρ : CompactOrthogonalRepresentation G V) (C : V →L[ℝ] V)
    (hpos : C.IsPositive) (hinv : ρ.Invariant C) {v : V} (hv : variance C v = 0) :
    ρ.orbitSpan v ≤ LinearMap.ker C.toLinearMap := by
      exact Submodule.span_le.mpr ( Set.range_subset_iff.mpr fun g => LinearMap.mem_ker.mpr ( suppresses_orbit ρ C hpos hinv hv g ) )

/-
Frame-blindness obstruction for a compact continuous group.
-/
theorem no_single_mode_suppression (ρ : CompactOrthogonalRepresentation G V)
    (C : V →L[ℝ] V) (hpos : C.IsPositive) (hinv : ρ.Invariant C)
    {v : V} (hv : variance C v = 0) (hnotfixed : ∃ g : G, ρ.act g v ≠ v) :
    ∃ w ∈ ρ.orbitSpan v, w ≠ v ∧ C w = 0 := by
      refine' ⟨ _, Submodule.subset_span ⟨ hnotfixed.choose, rfl ⟩, hnotfixed.choose_spec, suppresses_orbit ρ C hpos hinv hv _ ⟩

end CompactOrthogonalRepresentation

section FiniteAverage

variable {H W : Type*} [Fintype H] [Group H]
  [NormedAddCommGroup W] [InnerProductSpace ℝ W] [FiniteDimensional ℝ W]
variable (ρ : H →* (W ≃ₗᵢ[ℝ] W))

/-- Conjugate an operator by an orthogonal transformation. -/
def conjugate (g : H) (C : W →L[ℝ] W) : W →L[ℝ] W :=
  (ρ g⁻¹).toContinuousLinearEquiv.toContinuousLinearMap ∘L C ∘L
    (ρ g).toContinuousLinearEquiv.toContinuousLinearMap

/-- The normalized finite-group average (the finite Haar bridge). -/
noncomputable def finiteAverage (C : W →L[ℝ] W) : W →L[ℝ] W :=
  ((Fintype.card H : ℝ)⁻¹) • ∑ g : H, conjugate ρ g C

/-
The finite average is equivariant.
-/
theorem finiteAverage_invariant (C : W →L[ℝ] W) (h : H) (v : W) :
    finiteAverage ρ C (ρ h v) = ρ h (finiteAverage ρ C v) := by
      simp [finiteAverage, conjugate, ρ.map_mul];
      rw [ ← Equiv.sum_comp ( Equiv.mulRight h⁻¹ ) ] ; simp +decide [ mul_assoc ];
      convert rfl using 2

/-
Averaging preserves positive semidefiniteness.
-/
theorem finiteAverage_isPositive (C : W →L[ℝ] W) (hC : C.IsPositive) :
    (finiteAverage ρ C).IsPositive := by
      refine' ⟨ _, fun x => _ ⟩;
      · intro x y; simp +decide [ finiteAverage ] ;
        simp +decide [ inner_sum, sum_inner, inner_smul_left, inner_smul_right ];
        apply Finset.sum_congr rfl;
        intro g _; have := hC.1; simp_all +decide [ conjugate, ContinuousLinearMap.comp_apply ] ;
        convert this ( ( ρ g ) x ) ( ( ρ g ) y ) using 1 ; simp +decide [ ← map_inv, ← map_mul ];
        · rw [ ← ( ρ g ).inner_map_map ] ; aesop;
        · rw [ ← ( ρ g ).inner_map_map ] ; simp +decide [ this ];
      · simp +decide [ finiteAverage, ContinuousLinearMap.reApplyInnerSelf ];
        -- By linearity of the inner product, we can pull the summation outside.
        suffices h_sum : 0 ≤ (∑ c : H, inner ℝ ((conjugate ρ c C) x) x) by
          convert mul_nonneg ( inv_nonneg.2 ( Nat.cast_nonneg ( Fintype.card H ) ) ) h_sum using 1;
          simp +decide [ inner_sum, inner_smul_left ];
          rw [ sum_inner ];
        -- By definition of conjugate, we have that $\langle \rho(c^{-1}) C \rho(c) x, x \rangle = \langle C \rho(c) x, \rho(c) x \rangle$.
        have h_conj : ∀ c : H, inner ℝ ((conjugate ρ c C) x) x = inner ℝ (C ((ρ c).toContinuousLinearEquiv.toContinuousLinearMap x)) ((ρ c).toContinuousLinearEquiv.toContinuousLinearMap x) := by
          intro c
          simp [conjugate];
          rw [ ← ( ρ c ).inner_map_map ] ; aesop;
        exact Finset.sum_nonneg fun c _ => h_conj c ▸ hC.2 _

/-
Variance after averaging is the normalized orbit average.
-/
theorem inner_finiteAverage (C : W →L[ℝ] W) (v : W) :
    inner ℝ v (finiteAverage ρ C v) =
      ((Fintype.card H : ℝ)⁻¹) * ∑ g : H, inner ℝ (ρ g v) (C (ρ g v)) := by
        unfold finiteAverage;
        simp +decide [ conjugate, inner_sum, inner_smul_left, inner_smul_right ];
        exact Finset.sum_congr rfl fun g _ => by rw [ ← ( ρ g ).inner_map_map ] ; simp +decide ;

/-
A zero positive average forces zero variance at every orbit sample.
-/
theorem finiteAverage_zero_forces_orbit_zero (C : W →L[ℝ] W) (hC : C.IsPositive)
    {v : W} (hv : inner ℝ v (finiteAverage ρ C v) = 0) (g : H) :
    inner ℝ (ρ g v) (C (ρ g v)) = 0 := by
      -- By inner_finiteAverage, we have inner ℝ v (finiteAverage ρ C v) = (Fintype.card H : ℝ)⁻¹ * ∑ g : H, inner ℝ (ρ g v) (C (ρ g v)).
      rw [inner_finiteAverage] at hv;
      -- Since the sum is zero and each term is non-negative, each term must be zero.
      have h_nonneg : ∀ g : H, 0 ≤ inner ℝ (ρ g v) (C (ρ g v)) := by
        exact fun g => ContinuousLinearMap.IsPositive.inner_nonneg_right hC (ρ g v)
      simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ]

end FiniteAverage

section Sharpness

open CompactOrthogonalRepresentation

/-
Sharpness data: the zero covariance invariantly kills the orbit span, while a
rank-one covariance can kill `v` but not another orbit point, hence is non-invariant.
-/
theorem sharpness_rankOne
    {G V : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    [FiniteDimensional ℝ V]
    (ρ : CompactOrthogonalRepresentation G V) (u v : V) (hu : u ≠ 0)
    (huv : inner ℝ u v = 0) (hmove : ∃ g : G, inner ℝ u (ρ.act g v) ≠ 0) :
    ∃ (Cinv Csel : V →L[ℝ] V),
      Cinv.IsPositive ∧ ρ.Invariant Cinv ∧
      ρ.orbitSpan v ≤ LinearMap.ker Cinv.toLinearMap ∧
      Csel.IsPositive ∧ ¬ ρ.Invariant Csel ∧ Csel v = 0 ∧ Csel u ≠ 0 := by
        use 0;
        simp +decide [ ContinuousLinearMap.IsPositive, Invariant ];
        refine' ⟨ _, _, _ ⟩;
        · simp +decide [ ContinuousLinearMap.reApplyInnerSelf ];
        · exact fun g => Eq.symm ( map_zero _ );
        · refine' ⟨ ( innerSL ℝ u ).smulRight u, _, _, _, _ ⟩ <;> simp_all +decide [ ContinuousLinearMap.reApplyInnerSelf ];
          · refine' ⟨ _, _ ⟩;
            · intro x y; simp +decide [ innerₛₗ_apply_apply, inner_smul_left, inner_smul_right ] ; ring;
              rw [ real_inner_comm x u, mul_comm ];
            · simp +decide [ inner_smul_left, inner_smul_right ];
              exact fun x => mul_self_nonneg _;
          · obtain ⟨ g, hg ⟩ := hmove; use g, v; simp_all +decide [ innerSL_apply_apply, inner_smul_left, inner_smul_right ] ;

/-
Concrete sharpness example: the compact circle group rotates the real plane `ℂ`.
The invariant zero covariance suppresses the whole orbit-span, while a rank-one
covariance suppresses the imaginary line but not the real axis.
-/
theorem circle_rotation_sharpness :
    ∃ (ρ : CompactOrthogonalRepresentation Circle ℂ)
      (Cinv Csel : ℂ →L[ℝ] ℂ) (v : ℂ),
      (∃ g : Circle, ρ.act g v ≠ v) ∧
      Cinv.IsPositive ∧ ρ.Invariant Cinv ∧
      ρ.orbitSpan v ≤ LinearMap.ker Cinv.toLinearMap ∧
      Csel.IsPositive ∧ ¬ ρ.Invariant Csel ∧ Csel v = 0 ∧ Csel 1 ≠ 0 := by
        refine' ⟨ _, _, _, Complex.I, _, _, _, _, _ ⟩;
        refine' { toMonoidHom := rotation, continuous := _ };
        rotate_left;
        exact 0;
        refine' ( innerSL ℝ 1 ).smulRight 1;
        all_goals norm_num [ CompactOrthogonalRepresentation.Invariant, CompactOrthogonalRepresentation.orbitSpan ];
        all_goals norm_num [ CompactOrthogonalRepresentation.act ];
        · refine' ⟨ ⟨ Complex.I, _ ⟩, _ ⟩;
          all_goals norm_num [ Submonoid.unitSphere, Complex.ext_iff ];
        · refine' ⟨ _, ⟨ ⟨ Complex.I, _ ⟩, 1, _ ⟩ ⟩ <;> norm_num [ Complex.ext_iff ];
          · constructor;
            · intro x y; simp +decide [ innerSL_apply_apply ] ;
            · simp +decide [ ContinuousLinearMap.reApplyInnerSelf ];
              exact fun x => mul_self_nonneg _;
          · norm_num [ Submonoid.unitSphere ];
        · fun_prop

end Sharpness

end FrameBlindness
