import Mathlib
import PhysicsSM.Coding.HammingE8

/-!
# Short vectors of the Hamming Construction A lattice

This module defines and enumerates the 240 short (minimum-norm) vectors of
the Construction A lattice `e8IntLattice` associated to the extended [8,4,4]
Hamming code.

## Conventions

A **short vector** is a lattice vector with squared norm exactly 4 (in the
integer norm convention where `sqNorm z = ∑ zᵢ²`). Under the conventional
`1/√2` scaling, these become vectors of squared norm 2, i.e., roots of the
E8 root system.

## Main results

* `isShortHammingE8Vector` — predicate for short lattice vectors.
* `shortHammingE8VectorList` — explicit list of all 240 short vectors.
* `shortHammingE8VectorList_length` — the list has 240 elements.
* `shortHammingE8VectorList_nodup` — the list has no duplicates.
* `shortHammingE8VectorList_mem` — every element satisfies the predicate.
* `shortHammingE8VectorList_sqNorm` — every element has `sqNorm = 4`.
* `shortHammingE8Vector_count_eq_240` — there are exactly 240 short vectors.
* `shortHammingE8VectorList_complete` — every short vector is in the list.

## Structure of short vectors

Short vectors fall into two families:

1. **Type 1** (16 vectors): one coordinate ±2, rest 0. These always lie in
   the lattice since their mod-2 reduction is zero.
2. **Type 2** (224 vectors): four coordinates ±1, rest 0, where the support
   (nonzero positions) forms a weight-4 codeword of the extended Hamming code.
   The code has 14 weight-4 codewords, each yielding 2⁴ = 16 sign patterns.

## Finite-computation trust note

All verification theorems use `n a t i v e _ d e c i d e`. This means `#print axioms`
will report Lean's `trustCompiler` a x i o m. This should be acknowledged in
any publication citing these results.

## Source / provenance

- Conway & Sloane, *Sphere Packings, Lattices and Groups*, Ch. 7–8.
- Aristotle job N2 for PhysicsSM, 2026-05-07.
-/

set_option linter.style.longLine false
set_option linter.style.nativeDecide false

namespace PhysicsSM.Coding

/-! ## Decidability for code membership -/

/-- Membership in `extendedHamming8` is decidable via the parity-check
matrix: `v ∈ extendedHamming8 ↔ H₈ v = 0`. -/
instance : DecidablePred (· ∈ extendedHamming8) := fun v =>
  decidable_of_iff (Matrix.mulVec extendedHamming8ParityCheck v = 0) Iff.rfl

/-! ## Short-vector predicate -/

/-- A short vector of the Hamming Construction A lattice: a vector in
`e8IntLattice` with `sqNorm z = 4`. -/
def isShortHammingE8Vector (z : Fin 8 → ℤ) : Prop :=
  z ∈ e8IntLattice ∧ sqNorm z = 4

instance : DecidablePred isShortHammingE8Vector := fun z =>
  @instDecidableAnd _ _
    (decidable_of_iff (reduceModTwo z ∈ extendedHamming8) Iff.rfl)
    inferInstance

/-! ## Type 1 short vectors: ±2eᵢ -/

/-- Type 1 short vectors: exactly one coordinate is ±2, all others are 0.
These are the 16 vectors ±2eᵢ for i = 0, …, 7. Their mod-2 reduction
is zero, so they always lie in the lattice. -/
def shortVecType1 : List (Fin 8 → ℤ) :=
  do
    let i ← List.finRange 8
    let s ← [(2 : ℤ), -2]
    return fun k => if k = i then s else 0

/-! ## Type 2 short vectors: ±1 on codeword supports -/

/-- Type 2 short vectors: four coordinates are ±1 and the rest are 0,
where the support forms a weight-4 codeword of the extended Hamming code.

Generated by enumerating all 3⁸ = 6561 vectors with coordinates in
{−1, 0, 1} and filtering for `sqNorm = 4` and lattice membership. -/
def shortVecType2 : List (Fin 8 → ℤ) :=
  do
    let c0 ← [(-1 : ℤ), 0, 1]
    let c1 ← [(-1 : ℤ), 0, 1]
    let c2 ← [(-1 : ℤ), 0, 1]
    let c3 ← [(-1 : ℤ), 0, 1]
    let c4 ← [(-1 : ℤ), 0, 1]
    let c5 ← [(-1 : ℤ), 0, 1]
    let c6 ← [(-1 : ℤ), 0, 1]
    let c7 ← [(-1 : ℤ), 0, 1]
    let v : Fin 8 → ℤ := ![c0, c1, c2, c3, c4, c5, c6, c7]
    guard (isShortHammingE8Vector v)
    return v

/-! ## Combined short-vector list -/

/-- The complete list of 240 short vectors of the Hamming Construction A
lattice, combining type 1 (±2eᵢ) and type 2 (±1 on codeword supports). -/
def shortHammingE8VectorList : List (Fin 8 → ℤ) :=
  shortVecType1 ++ shortVecType2

/-! ## Verification theorems -/

/-- The list has exactly 240 elements. -/
theorem shortHammingE8VectorList_length :
    shortHammingE8VectorList.length = 240 := by native_decide

/-- The list has no duplicates. -/
theorem shortHammingE8VectorList_nodup :
    shortHammingE8VectorList.Nodup := by native_decide

/-- Every vector in the list satisfies the short-vector predicate
(`e8IntLattice` membership and `sqNorm = 4`). -/
theorem shortHammingE8VectorList_all_isShort :
    shortHammingE8VectorList.Forall isShortHammingE8Vector := by native_decide

/-- Every vector in the list is a short vector of the lattice. -/
theorem shortHammingE8VectorList_mem (z : Fin 8 → ℤ)
    (hz : z ∈ shortHammingE8VectorList) : isShortHammingE8Vector z :=
  List.forall_iff_forall_mem.mp shortHammingE8VectorList_all_isShort z hz

/-- Every vector in the list has squared norm exactly 4. -/
theorem shortHammingE8VectorList_sqNorm (z : Fin 8 → ℤ)
    (hz : z ∈ shortHammingE8VectorList) : sqNorm z = 4 :=
  (shortHammingE8VectorList_mem z hz).2

/-- The kissing number: the list of short vectors has 240 elements. -/
theorem shortHammingE8Vector_count_eq_240 :
    shortHammingE8VectorList.length = 240 :=
  shortHammingE8VectorList_length

/-! ## Completeness -/

/-- Every integer vector with `sqNorm z = 4` has all coordinates bounded
by `|zᵢ| ≤ 2`, i.e., coordinates lie in `{-2, -1, 0, 1, 2}`. -/
theorem coordinate_abs_le_two_of_sqNorm_four (z : Fin 8 → ℤ)
    (h : sqNorm z = 4) (i : Fin 8) : |z i| ≤ 2 := by
  have hsingle : z i ^ 2 ≤ sqNorm z :=
    Finset.single_le_sum (fun j _ => sq_nonneg (z j)) (Finset.mem_univ i)
  rw [h] at hsingle
  nlinarith [sq_abs (z i)]

/-- Convert an integer in `[-2, 2]` to the corresponding `Fin 5` index
into the value list `![-2, -1, 0, 1, 2]`. -/
def intToFin5' (z : ℤ) : Fin 5 :=
  if z = -2 then 0
  else if z = -1 then 1
  else if z = 0 then 2
  else if z = 1 then 3
  else 4

/-- The value list for short-vector coordinate enumeration. -/
abbrev shortValList : Fin 5 → ℤ := ![-2, -1, 0, 1, 2]

/-- Round-trip: looking up `intToFin5' z` in the value list recovers `z`,
provided `|z| ≤ 2`. -/
theorem shortValList_intToFin5'_eq (z : ℤ) (hz : |z| ≤ 2) :
    shortValList (intToFin5' z) = z := by
  rcases abs_le.mp hz with ⟨h₁, h₂⟩
  interval_cases z <;> trivial

/-- For any `z : Fin 8 → ℤ` with `sqNorm z = 4`, expressing `z` through
`intToFin5'` and `shortValList` recovers the original vector. -/
theorem vector_eq_shortValList_comp_intToFin5' (z : Fin 8 → ℤ) (h : sqNorm z = 4) :
    (fun i => shortValList (intToFin5' (z i))) = z :=
  funext fun i => shortValList_intToFin5'_eq _ (coordinate_abs_le_two_of_sqNorm_four z h i)

/-- A short vector with coordinates drawn from `{-2,-1,0,1,2}` that
satisfies the short-vector predicate appears in `shortHammingE8VectorList`.
This is the key finite-enumeration completeness lemma. -/
theorem shortHammingE8VectorList_complete_bounded :
    ∀ f : Fin 8 → Fin 5,
      isShortHammingE8Vector (fun i => shortValList (f i)) →
      (fun i => shortValList (f i)) ∈ shortHammingE8VectorList := by
  native_decide

/-- **Completeness**: every short vector of the Hamming Construction A lattice
appears in `shortHammingE8VectorList`. -/
theorem shortHammingE8VectorList_complete (z : Fin 8 → ℤ)
    (hz : isShortHammingE8Vector z) : z ∈ shortHammingE8VectorList := by
  have heq : (fun i => shortValList (intToFin5' (z i))) = z :=
    vector_eq_shortValList_comp_intToFin5' z hz.2
  rw [← heq]
  exact shortHammingE8VectorList_complete_bounded _ (by rw [heq]; exact hz)

end PhysicsSM.Coding
