import Mathlib

/-!
# Discrete winding derived from a local Pluecker field

Paper C pillar 1 (overnight publication run 2026-07-11, Fable lane).

Context.  The null-edge program derives a Dirac mass coin from a local
complex Pluecker coordinate `z p = psi p /\ phi p` of two primitive null
spinors at each site `p` of a finite cycle.  A kernel-checked no-go
(`GlobalPhaseWindingNoGo`, reproduced below as `rawPhaseIncrement`) shows a
globally lifted real phase always has zero winding, and a previously
*supplied* three-link field realizes winding one.  The missing bridge, and
this job's target, is to DERIVE the patched link data from the local field
itself: define the link increment as the principal argument of the ratio of
neighboring Pluecker values, prove the total turning is an exact integer
multiple of `2 * pi`, exhibit a winding-one field generated by primitive
spinors, and recover the global-lift no-go for the derived data.

No gauge field, branch choice, or link variable is supplied by hand
anywhere: every increment is computed from `z` alone.

Success = all six theorems below proved with no proof holes
(kernel-checked; expected axioms only `propext`, `Classical.choice`,
`Quot.sound`).

Prohibited weakenings:
- do not replace `Complex.arg` of the ratio by an abstractly supplied
  increment field;
- do not assume `z` has constant modulus, and do not normalize `z`;
- do not restrict the integrality theorem to special `L` (witnesses may fix
  `L = 4`);
- do not change `2 * Real.pi * w` to a real (non-integer) multiple.

Suggested route for `totalTurning_int_multiple`: the cyclic product of the
ratios telescopes to `1` (reindex by `Equiv.addRight 1`); cast the sum of
principal arguments to `Real.Angle`, where `Complex.arg` is additive over
products of nonzero factors; conclude the real sum lies in `2 * pi * Int`.
-/

noncomputable section

open scoped BigOperators

namespace PlueckerWinding

/-- Site-dependent primitive spinor pair on a finite cycle. -/
structure SpinorPairField (L : Nat) [NeZero L] where
  psi : ZMod L -> (Fin 2 -> Complex)
  phi : ZMod L -> (Fin 2 -> Complex)

/-- The local Pluecker coordinate (oriented spinor area) of the pair field. -/
def plueckerField {L : Nat} [NeZero L] (F : SpinorPairField L)
    (p : ZMod L) : Complex :=
  F.psi p 0 * F.phi p 1 - F.psi p 1 * F.phi p 0

/-- Link increment DERIVED from a site field: the principal argument of the
ratio across the edge `p -> p + 1`.  This is the object that was previously
supplied by hand as abstract link data. -/
def linkIncrement {L : Nat} [NeZero L] (z : ZMod L -> Complex)
    (p : ZMod L) : Real :=
  Complex.arg (z (p + 1) / z p)

/-- Total turning of the field around the finite cycle. -/
def totalTurning {L : Nat} [NeZero L] (z : ZMod L -> Complex) : Real :=
  ∑ p : ZMod L, linkIncrement z p

/-- Raw one-edge difference of a globally defined real phase lift
(reproduced from the project's `GlobalPhaseWindingNoGo`; do not modify). -/
def rawPhaseIncrement {L : Nat} (theta : ZMod L -> Real) (p : ZMod L) : Real :=
  theta (p + 1) - theta p

/-- **T1 (integrality).**  For a nowhere-zero field, the total turning is an
exact integer multiple of `2 * pi`. -/
theorem totalTurning_int_multiple {L : Nat} [NeZero L]
    (z : ZMod L -> Complex) (hz : ∀ p, z p ≠ 0) :
    ∃ w : Int, totalTurning z = 2 * Real.pi * (w : Real) := by
  sorry

/-- **T2 (constant control).**  A constant nonzero field has zero total
turning. -/
theorem totalTurning_const {L : Nat} [NeZero L] (c : Complex) (hc : c ≠ 0) :
    totalTurning (fun _ : ZMod L => c) = 0 := by
  sorry

/-- **T3 (global chiral covariance).**  Multiplying the whole field by one
fixed unit phase does not change any derived link increment, hence not the
total turning.  This is the statement that the derived data is invariant
under the walk's global chiral conjugation. -/
theorem linkIncrement_global_phase {L : Nat} [NeZero L]
    (z : ZMod L -> Complex) (u : Complex) (hu : u ≠ 0) (p : ZMod L) :
    linkIncrement (fun q => u * z q) p = linkIncrement z p := by
  sorry

/-- The winding-one witness field on the four-cycle: `z p = I ^ p.val`.
Every ratio equals `I`, whose principal argument is `pi / 2`. -/
def windingOneField (p : ZMod 4) : Complex :=
  Complex.I ^ (p.val)

/-- **T4 (winding-one witness).**  The derived total turning of the explicit
four-site field is exactly `2 * pi`: the previously supplied patched link
data is now generated by a local field. -/
theorem windingOneField_totalTurning :
    totalTurning windingOneField = 2 * Real.pi := by
  sorry

/-- **T5 (derived no-go bridge).**  If the derived link increments of a
nowhere-zero field all agree with the raw increments of some globally
defined real phase, the total turning is zero.  Combined with T4, the
winding-one field provably carries patched data with no global lift. -/
theorem totalTurning_eq_zero_of_global_lift {L : Nat} [NeZero L]
    (z : ZMod L -> Complex) (theta : ZMod L -> Real)
    (h : ∀ p, linkIncrement z p = rawPhaseIncrement theta p) :
    totalTurning z = 0 := by
  sorry

/-- Primitive-spinor generator for the winding-one field:
`psi = (1, 0)` and `phi p = (0, I ^ p.val)` give
`plueckerField = windingOneField`.  The patched data therefore comes from
null spinors, not from a supplied gauge field. -/
def windingOneSpinors : SpinorPairField 4 where
  psi := fun _ => ![1, 0]
  phi := fun p => ![0, Complex.I ^ (p.val)]

/-- **T6 (spinor derivation).**  The winding-one field is the Pluecker
coordinate of an explicit primitive spinor pair field. -/
theorem windingOneSpinors_pluecker :
    plueckerField windingOneSpinors = windingOneField := by
  sorry

end PlueckerWinding
