import Mathlib
import PhysicsSM.Spinor.PluckerMass

/-!
# Draft.NullEdgeQuantumMeasureFiniteAristotle

This Aristotle handoff builds a finite quantum-measure/decoherence-functional
bridge for the null-edge causal graph program.

The intended physics connection is modest but important: finite visible
Pluecker mass should sit inside the same algebraic world as Sorkin-style
quantum measure theory.  Here a finite event has amplitude
`sum x in A, amp x`; its quantum measure is the squared modulus of that
amplitude; and its decoherence functional is the rank-one Gram functional
`alpha(A) conj(alpha(B))`.

The ambitious theorem targets are:

* the grade-2 quantum-measure sum rule for three disjoint finite events;
* strong positivity of the finite decoherence Gram matrix;
* tensor-product closure on rectangular events.

Claim boundary:

* all statements are finite `Finset` algebra;
* this file does not assert a continuum path integral or analytic measure;
* the decoherence functional here is the rank-one amplitude model, used as a
  finite algebraic baseline before adding richer histories.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdgeQuantumMeasureFinite

open BigOperators
open Complex
open PhysicsSM.Spinor.PluckerMass

variable {Omega Lambda : Type*}

/-- A finite event is represented by a finite set of outcomes. -/
abbrev FiniteEvent (Omega : Type*) := Finset Omega

/-- The total amplitude of a finite event. -/
def eventAmplitude [DecidableEq Omega]
    (amp : Omega -> Complex) (A : FiniteEvent Omega) : Complex :=
  A.sum amp

/-- Quantum measure associated to a finite amplitude model. -/
def qMeasure [DecidableEq Omega]
    (amp : Omega -> Complex) (A : FiniteEvent Omega) : Complex :=
  complexAbsSq (eventAmplitude amp A)

/-- Rank-one decoherence functional generated by finite amplitudes. -/
def decoherenceFunctional [DecidableEq Omega]
    (amp : Omega -> Complex)
    (A B : FiniteEvent Omega) : Complex :=
  eventAmplitude amp A * (starRingEnd Complex) (eventAmplitude amp B)

/-- The diagonal of the decoherence functional is the quantum measure. -/
theorem decoherenceFunctional_diag_eq_qMeasure [DecidableEq Omega]
    (amp : Omega -> Complex) (A : FiniteEvent Omega) :
    decoherenceFunctional amp A A = qMeasure amp A := by
  rfl

/-- The finite decoherence functional is Hermitian. -/
theorem decoherenceFunctional_hermitian [DecidableEq Omega]
    (amp : Omega -> Complex) (A B : FiniteEvent Omega) :
    decoherenceFunctional amp B A =
      (starRingEnd Complex) (decoherenceFunctional amp A B) := by
  unfold decoherenceFunctional
  simp [map_mul, mul_comm]

/-- Event amplitudes are additive on disjoint finite unions. -/
theorem eventAmplitude_union_of_disjoint [DecidableEq Omega]
    (amp : Omega -> Complex) (A B : FiniteEvent Omega)
    (hAB : Disjoint A B) :
    eventAmplitude amp (A ∪ B) =
      eventAmplitude amp A + eventAmplitude amp B := by
  sorry

/-- The decoherence functional is additive in its left event argument. -/
theorem decoherenceFunctional_union_left_of_disjoint [DecidableEq Omega]
    (amp : Omega -> Complex) (A B C : FiniteEvent Omega)
    (hAB : Disjoint A B) :
    decoherenceFunctional amp (A ∪ B) C =
      decoherenceFunctional amp A C + decoherenceFunctional amp B C := by
  sorry

/-- The decoherence functional is additive in its right event argument. -/
theorem decoherenceFunctional_union_right_of_disjoint [DecidableEq Omega]
    (amp : Omega -> Complex) (A B C : FiniteEvent Omega)
    (hAB : Disjoint A B) :
    decoherenceFunctional amp C (A ∪ B) =
      decoherenceFunctional amp C A + decoherenceFunctional amp C B := by
  sorry

/--
Finite grade-2 quantum-measure sum rule for three pairwise-disjoint events.
-/
theorem qMeasure_grade2_sum_rule_of_pairwise_disjoint [DecidableEq Omega]
    (amp : Omega -> Complex) (A B C : FiniteEvent Omega)
    (hAB : Disjoint A B) (hAC : Disjoint A C) (hBC : Disjoint B C) :
    qMeasure amp ((A ∪ B) ∪ C) =
      qMeasure amp (A ∪ B) + qMeasure amp (A ∪ C) +
        qMeasure amp (B ∪ C) -
        qMeasure amp A - qMeasure amp B - qMeasure amp C := by
  sorry

/-! ## Strong positivity -/

/-- Finite decoherence Gram matrix on a list of events. -/
def decoherenceMatrix [DecidableEq Omega] {n : Nat}
    (amp : Omega -> Complex) (events : Fin n -> FiniteEvent Omega) :
    Matrix (Fin n) (Fin n) Complex :=
  fun i j => decoherenceFunctional amp (events i) (events j)

/-- Quadratic form associated to the finite decoherence Gram matrix. -/
def decoherenceQuadraticForm [DecidableEq Omega] {n : Nat}
    (amp : Omega -> Complex) (events : Fin n -> FiniteEvent Omega)
    (c : Fin n -> Complex) : Complex :=
  Finset.univ.sum fun i : Fin n =>
    Finset.univ.sum fun j : Fin n =>
      (starRingEnd Complex) (c i) *
        decoherenceMatrix amp events i j * c j

/--
The finite decoherence quadratic form is a squared modulus.
-/
theorem decoherenceQuadraticForm_eq_absSq [DecidableEq Omega] {n : Nat}
    (amp : Omega -> Complex) (events : Fin n -> FiniteEvent Omega)
    (c : Fin n -> Complex) :
    decoherenceQuadraticForm amp events c =
      complexAbsSq
        (Finset.univ.sum fun i : Fin n =>
          (starRingEnd Complex) (c i) *
            eventAmplitude amp (events i)) := by
  sorry

/-- Strong positivity of the finite rank-one decoherence functional. -/
theorem decoherenceFunctional_stronglyPositive_gram [DecidableEq Omega]
    {n : Nat} (amp : Omega -> Complex)
    (events : Fin n -> FiniteEvent Omega) (c : Fin n -> Complex) :
    0 <= (decoherenceQuadraticForm amp events c).re := by
  rw [decoherenceQuadraticForm_eq_absSq]
  rw [complexAbsSq_eq_ofReal_normSq, Complex.ofReal_re]
  exact Complex.normSq_nonneg _

/-! ## Tensor-product closure on rectangular finite events -/

/-- Product amplitude on a finite product outcome space. -/
def productAmplitude
    (ampA : Omega -> Complex) (ampB : Lambda -> Complex) :
    Omega × Lambda -> Complex :=
  fun x => ampA x.1 * ampB x.2

/-- Event amplitudes factor on rectangular events. -/
theorem eventAmplitude_product [DecidableEq Omega] [DecidableEq Lambda]
    (ampA : Omega -> Complex) (ampB : Lambda -> Complex)
    (A : FiniteEvent Omega) (B : FiniteEvent Lambda) :
    eventAmplitude (productAmplitude ampA ampB) (A.product B) =
      eventAmplitude ampA A * eventAmplitude ampB B := by
  sorry

/--
The rank-one decoherence functional is closed under tensor products on
rectangular finite events.
-/
theorem decoherenceFunctional_product_rectangle
    [DecidableEq Omega] [DecidableEq Lambda]
    (ampA : Omega -> Complex) (ampB : Lambda -> Complex)
    (A C : FiniteEvent Omega) (B D : FiniteEvent Lambda) :
    decoherenceFunctional (productAmplitude ampA ampB)
      (A.product B) (C.product D) =
      decoherenceFunctional ampA A C *
        decoherenceFunctional ampB B D := by
  sorry

/-- Quantum measures multiply on rectangular finite events. -/
theorem qMeasure_product_rectangle
    [DecidableEq Omega] [DecidableEq Lambda]
    (ampA : Omega -> Complex) (ampB : Lambda -> Complex)
    (A : FiniteEvent Omega) (B : FiniteEvent Lambda) :
    qMeasure (productAmplitude ampA ampB) (A.product B) =
      qMeasure ampA A * qMeasure ampB B := by
  sorry

end PhysicsSM.Draft.NullEdgeQuantumMeasureFinite

end
