import PhysicsSM.Draft.NullEdge.CompositionCl10Probe
import PhysicsSM.Draft.NullEdge.CompositionColorCAR

/-!
# P5 stage B: the Cl(8) generator table on the Dixon carrier

**Goal.** Furey-Hughes 2210.10126 (appendix) and Todorov-Dubois-Violette
2206.06912 place three generations + gauge structure in `Cl(8)` generated by
the LEFT-multiplication algebra of `R (x) C (x) H (x) O`. This package's
Dixon carrier (`Dixon` = four `ComplexOctonion` H-slots) realizes the
colour `Cl(6)` as composition operators (`CompositionColorCAR`: the full
operator CAR for `alpha_i`, `alpha_i‡`). This job asks for the `Cl(8)`
EXTENSION: two additional generators from the H-side left action, with the
full 8-generator Clifford anticommutation table kernel-checked.

## The candidate dictionary (pre-registered; correct it if the kernel says
otherwise - a corrected dictionary with a report is a success outcome)

Hermitian colour generators (`ComplexOctonion` level, co-lifted to `Dixon`):
`G_k = alpha_k + alpha_k‡` and `G_{k+3} = i (alpha_k - alpha_k‡)` for
`k = 1, 2, 3` - the standard hermitian combinations; their pairwise Clifford
relations `{G_A, G_B} = 2 delta_AB` (as operators, evaluated via the landed
`opCAR` identities; the diagonal normalization may come out as `2 delta_AB`
times the identity map - state exactly what the kernel gives).

H-side generators: define the LEFT quaternion actions on the Dixon slots
`L1 <d0, d1, d2, d3> = <-d1, d0, d3, -d2>` (left mult by `i_1`),
`L2 <d0, d1, d2, d3> = <-d2, -d3, d0, d1>` (left mult by `i_2`)
(fix the sign conventions against the repo's `R1`/`R2` right actions - the
left action must commute with the right actions `R1`/`R2`/`R3`; verify).
The colour volume element `chi = G_1 G_2 G_3 G_4 G_5 G_6` (operator
composition; compute its square and its anticommutation with each `G_A`).
Candidates: `G_7 = co chi o L1-twist`, `G_8 = co chi o L2-twist` - i.e. the
chirality-twisted H-left-mults, the standard tensor-product Clifford
extension pattern. If the twist normalization (`chi^2 = +-1`) forces an `i`
factor, insert it and report.

## Tasks

1. Define the six colour generators and kernel-check their Clifford table
   (free-`z` statements at `ComplexOctonion` level, using the landed
   `opCAR`/mixed-CAR identities; state the exact diagonal value).
2. Define `L1`, `L2` and verify they commute with `R1`, `R2`, `R3`
   (left/right quaternion actions commute - free-`d` statements).
3. Define `chi` and kernel-check `chi` anticommutes with each `G_A`
   (`A = 1..6`) and compute `chi o chi` (state the exact sign).
4. Define `G_7`, `G_8` per the dictionary (with any needed `i`-correction)
   and kernel-check the FULL `8 x 8` table: `{G_A, G_B} = 2 delta_AB` (times
   the identity, with the exact normalization stated), for
   `A, B in {1..8}` - the `Cl(8)` generation claim on this carrier.
5. If a slot of the table fails for every natural variant, REPORT the
   failing pattern prominently (honest outcome; the dictionary hypothesis
   dies, the kernel facts stand).

Constraints: no new axioms; no n a t i v e _ d e c i d e; standard axiom
set; follow the landed proof style (coordinatewise `ext`/`simp` with
definitional lemma lists; the free-variable methodology; few heavy proofs
per section).
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.CompositionCl8Generation

-- Definitions and the graded task list are in the module docstring;
-- everything below is TO BE CONSTRUCTED by this job.

end PhysicsSM.Draft.NullEdge.CompositionCl8Generation
