import PhysicsSM.Draft.NullEdge.HNUPlueckerMassiveStay
import PhysicsSM.Draft.NullEdge.HNUManyStepContinuumLive
import PhysicsSM.Draft.NullEdge.ComplexPlueckerRateTransfer
import PhysicsSM.Draft.NullEdge.Carrier.CarrierUnitaryFlow

/-!
# Quantitative reduction for the massive HNU continuum limit

This draft isolates the missing finite-dimensional estimate needed to lift the
landed HNU Weyl changing-lattice theorem to the doubled massive Dirac walk.
The exact step is the live HNU endpoint in the Dirac basis, preceded by the
onsite Pluecker mass coin.  The comparison flow is generated by the sum of the
landed kinetic and complex-mass matrices.

The intended proof architecture follows Arrighi--Forets--Nesme,
arXiv:1307.3524, but the walk being estimated here is the HNU schedule rather
than their axis-split walk.  The analytic work is finite-dimensional:

1. identify the Pluecker coin with its exact mass exponential;
2. lift the landed two-component HNU remainder through block doubling and the
   unitary Dirac-basis change;
3. compare the product with the exponential of the summed generator;
4. telescope the one-step estimate using exact unitarity.

No position-space or changing-cell claim is made in this module.  Those are
successor compositions once the quantitative one-step bound is landed.
-/

noncomputable section

open Matrix Complex
open scoped Matrix.Norms.L2Operator

namespace PhysicsSM.Draft.NullEdge.HNUMassiveContinuumReduction

open HNUExactCore
open HNUManyStepContinuum
open HNUPlueckerMassiveStay
open Pluecker3Plus1ComplexMass

abbrev Mat4 := Matrix (Fin 4) (Fin 4) Complex

/-- Exact massive HNU step at continuum momentum `q` and microscopic time
increment `eps`. -/
def massiveWend (z : Complex) (q : Fin 3 -> Real) (eps : Real) : Mat4 :=
  massiveHNU z eps (fun i => eps * q i)

/-- Continuum massive Dirac generator selected by the live infrared tangent. -/
def massiveGenerator (z : Complex) (q : Fin 3 -> Real) : Mat4 :=
  kinetic4 q + mass4 z

/-- Exact continuum flow of the massive Dirac generator. -/
def massiveEflow (z : Complex) (q : Fin 3 -> Real) (t : Real) : Mat4 :=
  NormedSpace.exp ((-(t : Complex)) • (I • massiveGenerator z q))

/-- A conservative doubled-HNU coefficient.  The factor two permits the two
opposite-chirality blocks to be controlled by a triangle estimate, without
assuming a block-norm equality absent from the current Mathlib API. -/
def kineticRemainderC (q : Fin 3 -> Real) : Real :=
  2 * (Cbound q + qAbs q ^ 2 * Real.exp (qAbs q))

/-- Explicit coefficient for the massive one-step estimate. -/
def massiveRemainderC (z : Complex) (q : Fin 3 -> Real) : Real :=
  let b := norm z
  let k := qAbs q
  let ck := kineticRemainderC q
  b ^ 2 * Real.exp b + ck + b * (ck + k) +
    (k + b) ^ 2 * Real.exp (k + b)

/-
The closed Pluecker coin is the exact exponential of the actual complex
four-component rest generator.
-/
theorem massCoin4_eq_exp_mass4 (z : Complex) (hz : z ≠ 0) (eps : Real) :
    massCoin4 z eps =
      NormedSpace.exp ((-(eps : Complex)) • (I • mass4 z)) := by
  unfold massCoin4 mass4;
  have := @ComplexPlueckerRateTransfer.complexExactFlow_eq_exp_H4;
  convert this 0 0 0 z eps using 1 ; norm_num [ ComplexPlueckerRateTransfer.complexExactFlow ];
  · convert ComplexPlueckerRateTransfer.conjugates_real_factor_to_massCoin4 z hz eps |> Eq.symm using 1;
    · unfold massCoin4; norm_num [ Complex.ext_iff ] ; ring;
      unfold mass4;
      ext i j ; norm_num ; ring;
    · unfold ComplexPlueckerRateTransfer.realExactFlow; norm_num [ ComplexPlueckerRateTransfer.realFactor, Compact3Plus1DiracRate.exactFlow ] ;
      unfold Compact3Plus1DiracRate.factor; norm_num [ Compact3Plus1DiracRate.H ] ;
      unfold Compact3Plus1DiracRate.beta; norm_num [ ComplexPlueckerRateTransfer.phase ] ; ring;
      unfold beta; norm_num [ Matrix.mul_apply, Matrix.smul_eq_diagonal_mul ] ; ring;
      rw [ show ( !![-(eps * I * ‖z‖ : ℂ), 0, 0, 0; 0, -(eps * I * ‖z‖ : ℂ), 0, 0; 0, 0, eps * I * ‖z‖, 0; 0, 0, 0, eps * I * ‖z‖] : Matrix ( Fin 4 ) ( Fin 4 ) ℂ ) = ( eps * I * ‖z‖ : ℂ ) • !![-1, 0, 0, 0; 0, -1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] by ext i j; fin_cases i <;> fin_cases j <;> norm_num ];
      rw [ show ( !![-1, 0, 0, 0; 0, -1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] : Matrix ( Fin 4 ) ( Fin 4 ) ℂ ) = ( diagonal fun x => if x = 0 then -1 else if x = 1 then -1 else if x = 2 then 1 else 1 ) by ext i j; fin_cases i <;> fin_cases j <;> rfl ] ; norm_num [ NormedSpace.exp_eq_tsum ] ; ring;
      rw [ show ( NormedSpace.exp ( ( eps * I * ‖z‖ : ℂ ) • diagonal fun x : Fin 4 => if x = 0 then -1 else if x = 1 then -1 else 1 ) ) = diagonal ( fun x : Fin 4 => Complex.exp ( ( eps * I * ‖z‖ : ℂ ) * if x = 0 then -1 else if x = 1 then -1 else 1 ) ) from ?_ ] ; norm_num [ Complex.exp_re, Complex.exp_im, Complex.cos, Complex.sin ] ; ring;
      · congr! 2;
        ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.diagonal ] ; ring; all_goals ring;
      · convert ( Matrix.exp_diagonal _ ) using 1;
        rotate_right;
        exact fun x => ( eps * I * ‖z‖ ) * if x = 0 then -1 else if x = 1 then -1 else 1;
        all_goals try infer_instance;
        · congr! 1;
          ext i j ; by_cases hi : i = j <;> simp +decide [ hi ];
        · norm_num [ Complex.exp_eq_exp_ℂ, NormedSpace.exp_eq_tsum ];
  · unfold H4; norm_num [ Complex.ext_iff, beta, beta5 ] ;
    unfold mass4; norm_num [ Complex.ext_iff, beta, beta5 ] ;

/-
The operator norm of the complex rest generator is exactly the Pluecker
area magnitude.
-/
theorem norm_mass4 (z : Complex) : norm (mass4 z) = norm z := by
  -- By definition of the mass generating operator, it is normal.
  have h_mass_normal : mass4 z * (mass4 z)ᴴ = (mass4 z)ᴴ * mass4 z := by
    -- Since mass4 z is Hermitian, it commutes with its conjugate transpose by the properties of Hermitian matrices.
    have h_comm : (mass4 z).IsHermitian := by
      have := Pluecker3Plus1ComplexMass.mass4_hermitian_sq z; aesop;
    rw [ h_comm.eq ];
  have h_mass_norm : ‖mass4 z‖ ^ 2 = (norm z) ^ 2 := by
    have h_mass_norm : ‖mass4 z * (mass4 z)ᴴ‖ = ‖z‖ ^ 2 := by
      have h_mass_norm : mass4 z * (mass4 z)ᴴ = (Complex.normSq z : Complex) • (1 : Mat4) := by
        convert Pluecker3Plus1ComplexMass.mass4_hermitian_sq z |>.2 using 1;
        rw [ Pluecker3Plus1ComplexMass.mass4_hermitian_sq z |>.1 ];
      rw [ h_mass_norm, norm_smul ] ; norm_num [ Complex.normSq_eq_norm_sq ];
    grind +suggestions;
  rwa [ sq_eq_sq₀ ( norm_nonneg _ ) ( norm_nonneg _ ) ] at h_mass_norm

/-
The live Dirac kinetic generator has the expected `l1` momentum bound.
-/
theorem norm_kinetic4_le_qAbs (q : Fin 3 -> Real) :
    norm (kinetic4 q) <= qAbs q := by
  unfold kinetic4;
  refine' le_trans ( norm_add₃_le .. ) _;
  refine' le_trans _ ( show qAbs q ≥ ‖( q 0 : ℂ) • alpha1‖ + ‖( q 1 : ℂ) • alpha2‖ + ‖( q 2 : ℂ) • alpha3‖ from _ );
  · norm_num;
  · -- The norm of a Pauli matrix is 1.
    have h_norm_pauli : ∀ i : Fin 3, ‖alpha1‖ ≤ 1 ∧ ‖alpha2‖ ≤ 1 ∧ ‖alpha3‖ ≤ 1 := by
      refine' fun i => ⟨ _, _, _ ⟩ <;> refine' ContinuousLinearMap.opNorm_le_bound _ zero_le_one _ <;> norm_num [ EuclideanSpace.norm_eq, Fin.sum_univ_succ ];
      · simp +decide [ alpha1, Matrix.mulVec ];
        exact fun x => Real.sqrt_le_sqrt <| by linarith!;
      · simp +decide [ alpha2, Matrix.mulVec ];
        exact fun x => Real.sqrt_le_sqrt <| by linarith!;
      · simp +decide [ alpha3, Matrix.mulVec ];
        exact fun x => Real.sqrt_le_sqrt <| by linarith!;
    simp_all +decide [ norm_smul ];
    exact le_trans ( add_le_add_three ( mul_le_of_le_one_right ( abs_nonneg _ ) h_norm_pauli.1 ) ( mul_le_of_le_one_right ( abs_nonneg _ ) h_norm_pauli.2.1 ) ( mul_le_of_le_one_right ( abs_nonneg _ ) h_norm_pauli.2.2 ) ) ( by unfold qAbs; linarith )

/-- Upper-left embedding of a two-component matrix into the doubled chiral space. -/
def embedUpper (A : Matrix (Fin 2) (Fin 2) Complex) : Mat4 :=
  !![A 0 0, A 0 1, 0, 0;
     A 1 0, A 1 1, 0, 0;
     0, 0, 0, 0;
     0, 0, 0, 0]

/-- Lower-right embedding of a two-component matrix into the doubled chiral space. -/
def embedLower (A : Matrix (Fin 2) (Fin 2) Complex) : Mat4 :=
  !![0, 0, 0, 0;
     0, 0, 0, 0;
     0, 0, A 0 0, A 0 1;
     0, 0, A 1 0, A 1 1]

lemma norm_embedUpper_le (A : Matrix (Fin 2) (Fin 2) Complex) :
    norm (embedUpper A) <= norm A := by
  refine' ContinuousLinearMap.opNorm_le_bound _ ( norm_nonneg _ ) fun x => _;
  unfold toEuclideanLin; norm_num [ EuclideanSpace.norm_eq ] ;
  -- Apply the Cauchy-Schwarz inequality to the sum.
  have h_cauchy_schwarz : ‖(A.mulVec ![x.ofLp 0, x.ofLp 1]) 0‖ ^ 2 + ‖(A.mulVec ![x.ofLp 0, x.ofLp 1]) 1‖ ^ 2 ≤ ‖A‖ ^ 2 * (‖x.ofLp 0‖ ^ 2 + ‖x.ofLp 1‖ ^ 2) := by
    have h_cauchy_schwarz : ∀ (v : EuclideanSpace ℂ (Fin 2)), ‖A.toEuclideanLin v‖ ^ 2 ≤ ‖A‖ ^ 2 * ‖v‖ ^ 2 := by
      intro v
      have h_cauchy_schwarz : ‖A.toEuclideanLin v‖ ≤ ‖A‖ * ‖v‖ := by
        convert ContinuousLinearMap.le_opNorm ( Matrix.toEuclideanLin A |> LinearMap.toContinuousLinearMap ) v using 1;
      simpa only [ mul_pow ] using pow_le_pow_left₀ ( norm_nonneg _ ) h_cauchy_schwarz 2;
    convert h_cauchy_schwarz ( EuclideanSpace.single 0 ( x.ofLp 0 ) + EuclideanSpace.single 1 ( x.ofLp 1 ) ) using 1 <;> norm_num [ EuclideanSpace.norm_eq, Fin.sum_univ_two ] ; ring!;
    · rw [ Real.sq_sqrt <| by positivity ] ; norm_num [ Matrix.mulVec ] ; ring!;
    · exact Or.inl <| by rw [ Real.sq_sqrt <| by positivity ] ;
  rw [ Real.sqrt_le_iff ];
  simp_all +decide [ Fin.sum_univ_four, mul_pow ];
  simp_all +decide [ embedUpper, Matrix.mulVec ];
  exact ⟨ by positivity, by rw [ Real.sq_sqrt <| by positivity ] ; exact h_cauchy_schwarz.trans <| mul_le_mul_of_nonneg_left ( by nlinarith! ) <| sq_nonneg _ ⟩

lemma norm_embedLower_le (A : Matrix (Fin 2) (Fin 2) Complex) :
    norm (embedLower A) <= norm A := by
  refine' ContinuousLinearMap.opNorm_le_bound _ _ _;
  · positivity;
  · simp +decide [ EuclideanSpace.norm_eq, Matrix.mulVec ];
    intro x; rw [ Real.sqrt_le_iff ] ; simp +decide [ Fin.sum_univ_succ, dotProduct ] ; ring_nf ;
    refine' ⟨ by positivity, _ ⟩;
    rw [ Real.sq_sqrt <| by positivity ] ; ring_nf ;
    have h_norm_A : ∀ (x : EuclideanSpace ℂ (Fin 2)), ‖(Matrix.toEuclideanLin A) x‖ ^ 2 ≤ ‖A‖ ^ 2 * ‖x‖ ^ 2 := by
      intro x; exact (by
      have h_norm_A : ∀ (x : EuclideanSpace ℂ (Fin 2)), ‖(Matrix.toEuclideanLin A) x‖ ≤ ‖A‖ * ‖x‖ := by
        convert ContinuousLinearMap.le_opNorm ( Matrix.toEuclideanLin A |> ContinuousLinearMap.mk ) using 1;
      simpa only [ mul_pow ] using pow_le_pow_left₀ ( norm_nonneg _ ) ( h_norm_A x ) 2);
    simp_all +decide [ EuclideanSpace.norm_eq, Fin.sum_univ_two ];
    simp_all +decide [ embedLower, Matrix.mulVec ];
    have := h_norm_A ( EuclideanSpace.single 0 ( x.ofLp 2 ) + EuclideanSpace.single 1 ( x.ofLp 3 ) ) ; simp_all +decide [ mul_comm ] ;
    rw [ Real.sq_sqrt ( by positivity ), Real.sq_sqrt ( by positivity ) ] at this ; nlinarith [ norm_nonneg ( x.ofLp 0 ), norm_nonneg ( x.ofLp 1 ), norm_nonneg ( x.ofLp 2 ), norm_nonneg ( x.ofLp 3 ) ]

/-- Opposite-chirality Weyl generator before the Dirac-basis rotation. -/
def chiralKinetic (q : Fin 3 -> Real) : Mat4 :=
  let w := Hw q
  !![w 0 0, w 0 1, 0, 0;
     w 1 0, w 1 1, 0, 0;
     0, 0, -w 0 0, -w 0 1;
     0, 0, -w 1 0, -w 1 1]

lemma chiralKinetic_conjugate (q : Fin 3 -> Real) :
    diracBasis * chiralKinetic q * diracBasis.conjTranspose = kinetic4 q := by
  unfold chiralKinetic kinetic4;
  unfold diracBasis alpha1 alpha2 alpha3;
  ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Fin.sum_univ_succ ] <;> ring;
  all_goals norm_num [ Complex.ext_iff, sq, Hw, sx, sy, sz ] ; ring;
  all_goals norm_num ; ring;
  · norm_num;
  · norm_num;
  · norm_num;
  · norm_num

lemma doubledChiralEndpoint_sub_linear_bound (q : Fin 3 -> Real) (eps : Real)
    (heps : abs eps <= 1) :
    norm (doubledChiralEndpoint (fun i => eps * q i) -
      (1 + (-(eps : Complex)) • (I • chiralKinetic q))) <=
      kineticRemainderC q * eps ^ 2 := by
  unfold kineticRemainderC;
  unfold Cbound;
  convert norm_add_le ( embedUpper ( Wend q eps - firstOrder q eps ) ) ( embedLower ( Wend ( -q ) eps - firstOrder ( -q ) eps ) ) |> le_trans <| add_le_add ( norm_embedUpper_le _ ) ( norm_embedLower_le _ ) |> le_trans <| ?_ using 1;
  · convert rfl using 2;
    ext i j; fin_cases i <;> fin_cases j <;> simp +decide [ embedUpper, embedLower, doubledChiralEndpoint, chiralKinetic ] ; ring;
    all_goals unfold Wend firstOrder; norm_num [ Hw ] ; ring;
  · refine' le_trans ( add_le_add ( Wend_sub_firstOrder_bound q eps heps ) ( Wend_sub_firstOrder_bound ( -q ) eps heps ) ) _;
    unfold CM qAbs; norm_num [ abs_mul, abs_neg, abs_of_nonneg ] ; ring_nf; norm_num;
    exact le_of_sub_nonneg ( by ring_nf; positivity )

/-
Quantitative doubled-HNU remainder against the shared kinetic
linearization.  This is the HNU-specific analytic crux.
-/
theorem diracHNU_sub_linear_bound (q : Fin 3 -> Real) (eps : Real)
    (heps : abs eps <= 1) :
    norm (diracHNU (fun i => eps * q i) -
      (1 + (-(eps : Complex)) • (I • kinetic4 q))) <=
      kineticRemainderC q * eps ^ 2 := by
  refine' le_trans _ ( doubledChiralEndpoint_sub_linear_bound q eps heps );
  convert norm_mul_le ( diracBasis ) ( ( doubledChiralEndpoint ( fun i => eps * q i ) - ( 1 + - ( eps : ℂ ) • I • chiralKinetic q ) ) * diracBasis.conjTranspose ) |> le_trans <| mul_le_mul_of_nonneg_left ( norm_mul_le _ _ ) ( norm_nonneg _ ) using 1;
  · convert rfl using 2;
    simp +decide [ ← mul_assoc, ← chiralKinetic_conjugate ];
    simp +decide [ mul_sub, sub_mul, mul_assoc, diracHNU ];
    simp +decide [ mul_add, add_mul, mul_assoc, mul_left_comm, diracBasis_unitary ];
    exact diracBasis_unitary.2;
  · have h_norm_diracBasis : ‖diracBasis‖ = 1 := by
      convert CStarRing.norm_of_mem_unitary ( HNUPlueckerMassiveStay.diracBasis_unitary ) using 1;
    grind +suggestions

/-
The Pluecker coin has a second-order remainder against its mass
linearization.
-/
theorem massCoin4_sub_linear_bound (z : Complex) (hz : z ≠ 0) (eps : Real)
    (heps : abs eps <= 1) :
    norm (massCoin4 z eps -
      (1 + (-(eps : Complex)) • (I • mass4 z))) <=
      norm z ^ 2 * Real.exp (norm z) * eps ^ 2 := by
  have h_exp : ‖NormedSpace.exp ((-(eps : Complex)) • (I • mass4 z)) - (1 + (-(eps : Complex)) • (I • mass4 z))‖ ≤ (norm (-(eps : Complex) • (I • mass4 z))) ^ 2 * Real.exp (norm (-(eps : Complex) • (I • mass4 z))) := by
    have h_exp : ∀ X : Mat4, ‖NormedSpace.exp X - (1 + X)‖ ≤ ‖X‖ ^ 2 * Real.exp ‖X‖ := by
      convert HNUManyStepContinuum.norm_exp_sub_one_sub_le using 1;
      constructor <;> intro h X;
      · convert HNUManyStepContinuum.norm_exp_sub_one_sub_le X using 1;
      · convert norm_exp_sub_one_sub_le using 1;
        constructor <;> intros <;> norm_num [ sub_add_eq_sub_sub ] at *;
        · exact h _;
        · exact Compact3Plus1DiracRate.norm_exp_sub_one_sub_self_le X;
    exact h_exp _;
  simp_all +decide [ massCoin4_eq_exp_mass4, norm_smul ];
  refine le_trans h_exp ?_ ; norm_num [ norm_mass4 ] ; ring_nf ;
  rw [ sq_abs ] ; ring_nf ;
  exact mul_le_mul_of_nonneg_left ( Real.exp_le_exp.mpr ( mul_le_of_le_one_right ( norm_nonneg _ ) heps ) ) ( by positivity )

/-
The summed massive generator is Hermitian.
-/
theorem massiveGenerator_isHermitian (z : Complex) (q : Fin 3 -> Real) :
    (massiveGenerator z q).IsHermitian := by
  ext i j;
  simp [massiveGenerator, kinetic4, mass4];
  fin_cases i <;> fin_cases j <;> simp +decide [ alpha1, alpha2, alpha3, beta, beta5 ];
  all_goals simp +decide [ gamma5, Matrix.vecMul ]

/-
The summed generator is bounded by the displayed momentum-plus-mass
envelope.
-/
theorem norm_massiveGenerator_le (z : Complex) (q : Fin 3 -> Real) :
    norm (massiveGenerator z q) <= qAbs q + norm z := by
  convert norm_add_le ( kinetic4 q ) ( mass4 z ) |> le_trans <| add_le_add ( norm_kinetic4_le_qAbs q ) ( norm_mass4 z |> le_of_eq ) using 1

/-- The exact massive continuum flow is unitary. -/
theorem massiveEflow_mem_unitary (z : Complex) (q : Fin 3 -> Real) (t : Real) :
    massiveEflow z q t ∈ Matrix.unitaryGroup (Fin 4) Complex := by
  exact PhysicsSM.Draft.NullEdge.Carrier.CarrierUnitaryFlow.hermitian_flow_mem_unitaryGroup
    (massiveGenerator_isHermitian z q) t

/-- The exact massive HNU step is unitary away from the collinear boundary. -/
theorem massiveWend_mem_unitary (z : Complex) (hz : z ≠ 0)
    (q : Fin 3 -> Real) (eps : Real) :
    massiveWend z q eps ∈ Matrix.unitaryGroup (Fin 4) Complex := by
  exact massiveHNU_unitary z hz eps (fun i => eps * q i)

lemma norm_exp_sub_one_sub_le4 (X : Mat4) :
    norm (NormedSpace.exp X - 1 - X) <=
      norm X ^ 2 / 2 * Real.exp (norm X) := by
  -- We'll use the fact that the norm of a sum is less than or equal to the sum of the norms.
  have h_norm_sum : ‖NormedSpace.exp X - 1 - X‖ ≤ ∑' (k : ℕ), ‖(1 / (Nat.factorial (k + 2)) : ℂ) • X ^ (k + 2)‖ := by
    convert norm_tsum_le_tsum_norm _ using 1;
    · have h_exp : NormedSpace.exp X = ∑' (n : ℕ), (1 / (Nat.factorial n) : ℂ) • X ^ n := by
        grind +suggestions;
      rw [ h_exp, ← Summable.sum_add_tsum_nat_add 2 ];
      · norm_num [ Finset.sum_range_succ ];
        norm_num [ add_assoc, add_sub_assoc ];
      · refine' .of_norm _;
        norm_num [ norm_smul ];
        refine' Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => mul_le_mul_of_nonneg_left ( show ‖X ^ n‖ ≤ ‖X‖ ^ n from _ ) ( by positivity ) ) _;
        · induction n <;> simp_all +decide [ pow_succ' ];
          exact le_trans ( norm_mul_le _ _ ) ( mul_le_mul_of_nonneg_left ‹_› ( norm_nonneg _ ) );
        · field_simp;
          exact Real.summable_pow_div_factorial _;
    · simp [norm_smul];
      refine' Summable.of_nonneg_of_le ( fun n => mul_nonneg ( inv_nonneg.2 ( Nat.cast_nonneg _ ) ) ( norm_nonneg _ ) ) ( fun n => mul_le_mul_of_nonneg_left ( norm_pow_le' _ _ ) ( inv_nonneg.2 ( Nat.cast_nonneg _ ) ) ) _;
      · grind;
      · exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by exact mul_le_mul_of_nonneg_left ( pow_le_pow_left₀ ( by positivity ) ( show ‖X‖ ≤ ‖X‖ + 1 by linarith ) _ ) ( by positivity ) ) ( by simpa [ inv_mul_eq_div ] using summable_nat_add_iff 2 |>.2 <| Real.summable_pow_div_factorial _ );
  -- We'll use the fact that the norm of a product is less than or equal to the product of the norms.
  have h_norm_prod : ∀ k : ℕ, ‖(1 / (Nat.factorial (k + 2)) : ℂ) • X ^ (k + 2)‖ ≤ (‖X‖ ^ (k + 2)) / (Nat.factorial (k + 2)) := by
    intro k; rw [ norm_smul, norm_div ] ; norm_num ; ring_nf;
    rw [ mul_assoc ] ; gcongr;
    convert norm_pow_le' X ( by linarith : 2 + k ≥ 1 ) using 1 ; ring;
  refine le_trans h_norm_sum <| le_trans ( Summable.tsum_le_tsum h_norm_prod ?_ ?_ ) ?_;
  · exact Summable.of_nonneg_of_le ( fun k => norm_nonneg _ ) h_norm_prod ( by simpa using summable_nat_add_iff 2 |>.2 <| Real.summable_pow_div_factorial _ );
  · exact Real.summable_pow_div_factorial _ |> Summable.comp_injective <| add_left_injective 2;
  · rw [ Real.exp_eq_exp_ℝ ];
    rw [ NormedSpace.exp_eq_tsum_div ];
    rw [ ← tsum_mul_left ] ; refine' Summable.tsum_le_tsum _ _ _;
    · intro i; rw [ div_mul_div_comm ] ; rw [ div_le_div_iff₀ ] <;> first | positivity | ring_nf ; norm_cast ;
      norm_num [ add_comm, Nat.factorial ];
      exact le_of_sub_nonneg ( by ring_nf; positivity );
    · exact Real.summable_pow_div_factorial _ |> Summable.comp_injective <| add_left_injective 2;
    · exact Summable.mul_left _ <| Real.summable_pow_div_factorial _

lemma massiveEflow_sub_linear_bound (z : Complex) (q : Fin 3 -> Real)
    (eps : Real) (heps : abs eps <= 1) :
    norm ((1 + (-(eps : Complex)) • (I • massiveGenerator z q)) -
      massiveEflow z q eps) <=
      (qAbs q + norm z) ^ 2 * Real.exp (qAbs q + norm z) * eps ^ 2 := by
  let X : Mat4 := ((-(eps : Complex)) • (I • massiveGenerator z q))
  have h := norm_exp_sub_one_sub_le4 X
  have h_bounds :
      norm ((-(eps : Complex)) • (I • massiveGenerator z q)) <= qAbs q + norm z ∧
      norm ((-(eps : Complex)) • (I • massiveGenerator z q)) ^ 2 <=
        (qAbs q + norm z) ^ 2 * eps ^ 2 := by
    have hb : norm ((-(eps : Complex)) • (I • massiveGenerator z q)) <=
        abs eps * (qAbs q + norm z) := by
      convert mul_le_mul_of_nonneg_left (norm_massiveGenerator_le z q) (abs_nonneg eps) using 1
      norm_num [norm_smul]
    exact ⟨hb.trans (mul_le_of_le_one_left (add_nonneg (qAbs_nonneg q) (norm_nonneg z)) heps),
      by nlinarith [norm_nonneg ((-(eps : Complex)) • (I • massiveGenerator z q)),
        add_nonneg (qAbs_nonneg q) (norm_nonneg z), sq_abs eps]⟩
  have hmain : norm (NormedSpace.exp X - 1 - X) <=
      (qAbs q + norm z) ^ 2 * Real.exp (qAbs q + norm z) * eps ^ 2 :=
    h.trans (by
    refine le_trans (mul_le_mul_of_nonneg_right
      (div_le_self (sq_nonneg _) (by norm_num)) (Real.exp_nonneg _)) ?_
    rw [mul_right_comm]
    exact mul_le_mul h_bounds.2 (Real.exp_le_exp.mpr h_bounds.1)
      (by positivity) (by positivity))
  rw [← norm_neg]
  convert hmain using 1
  simp [X, massiveEflow]
  abel

lemma massiveWend_sub_linear_bound (z : Complex) (hz : z ≠ 0)
    (q : Fin 3 -> Real) (eps : Real) (heps : abs eps <= 1) :
    norm (massiveWend z q eps -
      (1 + (-(eps : Complex)) • (I • massiveGenerator z q))) <=
      (norm z ^ 2 * Real.exp (norm z) + kineticRemainderC q +
        norm z * (kineticRemainderC q + qAbs q)) * eps ^ 2 := by
  unfold massiveWend massiveGenerator;
  -- Apply the product identity from the previous prompt.
  have h_prod : massiveHNU z eps (fun i => eps * q i) = massCoin4 z eps * diracHNU (fun i => eps * q i) := by
    rfl;
  -- Apply the norm_add_le and norm_mul_le lemmas to bound the expression.
  have h_bound : ‖massiveHNU z eps (fun i => eps * q i) - (1 + (-(eps : Complex)) • (I • kinetic4 q + I • mass4 z))‖ ≤ ‖massCoin4 z eps - (1 + (-(eps : Complex)) • (I • mass4 z))‖ + ‖(-(eps : Complex)) • (I • mass4 z)‖ * ‖diracHNU (fun i => eps * q i) - 1‖ + ‖diracHNU (fun i => eps * q i) - (1 + (-(eps : Complex)) • (I • kinetic4 q))‖ := by
    rw [ h_prod ];
    convert norm_add_le ( ( massCoin4 z eps - ( 1 + -↑eps • I • mass4 z ) ) * diracHNU ( fun i => eps * q i ) ) ( ( -↑eps • I • mass4 z ) * ( diracHNU ( fun i => eps * q i ) - 1 ) + ( diracHNU ( fun i => eps * q i ) - ( 1 + -↑eps • I • kinetic4 q ) ) ) |> le_trans <| ?_ using 1;
    · congr 1 ; ext i j ; norm_num ; ring;
      simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_assoc, mul_sub, sub_mul, Finset.sum_ite, Finset.filter_eq', Finset.filter_ne' ] ; ring;
    · refine' le_trans ( add_le_add ( norm_mul_le _ _ ) ( norm_add_le _ _ ) ) _;
      rw [ show ‖diracHNU ( fun i => eps * q i )‖ = 1 from ?_ ];
      · norm_num [ add_assoc ];
        convert norm_mul_le _ _ using 2 ; norm_num [ norm_smul ];
      · convert CStarRing.norm_of_mem_unitary ( HNUPlueckerMassiveStay.diracHNU_unitary ( fun i => eps * q i ) ) using 1;
  convert h_bound.trans _ using 1;
  · norm_num [ smul_add ];
  · refine' le_trans ( add_le_add_three ( massCoin4_sub_linear_bound z hz eps heps ) ( mul_le_mul_of_nonneg_right ( _ ) ( norm_nonneg _ ) ) ( diracHNU_sub_linear_bound q eps heps ) ) _;
    exact |eps| * ‖z‖;
    · convert norm_smul_le ( - ( eps : ℂ ) ) ( I • mass4 z ) using 1 ; norm_num [ norm_smul ];
      exact Or.inl ( norm_mass4 z ▸ rfl );
    · have h_dirac_bound : ‖diracHNU (fun i => eps * q i) - 1‖ ≤ |eps| * qAbs q + kineticRemainderC q * eps ^ 2 := by
        have := diracHNU_sub_linear_bound q eps heps;
        have h_dirac_bound : ‖(diracHNU (fun i => eps * q i) - 1)‖ ≤ ‖(diracHNU (fun i => eps * q i) - (1 + (-(eps : Complex)) • (I • kinetic4 q)))‖ + ‖(-(eps : Complex)) • (I • kinetic4 q)‖ := by
          convert norm_add_le ( diracHNU ( fun i => eps * q i ) - ( 1 + -↑eps • I • kinetic4 q ) ) ( -↑eps • I • kinetic4 q ) using 2 ; abel_nf;
          · norm_cast;
          · norm_num [ Norm.norm ];
        refine le_trans h_dirac_bound <| le_trans ( add_le_add this le_rfl ) ?_;
        rw [ add_comm ];
        norm_num [ norm_smul ];
        exact mul_le_mul_of_nonneg_left ( norm_kinetic4_le_qAbs q ) ( abs_nonneg eps );
      refine' le_trans ( add_le_add_three le_rfl ( mul_le_mul_of_nonneg_left h_dirac_bound ( by positivity ) ) le_rfl ) _ ; ring_nf;
      norm_num [ abs_mul, abs_pow ];
      nlinarith only [ show 0 ≤ ‖z‖ * eps ^ 2 * kineticRemainderC q by exact mul_nonneg ( mul_nonneg ( norm_nonneg _ ) ( sq_nonneg _ ) ) ( show 0 ≤ kineticRemainderC q by exact mul_nonneg zero_le_two ( add_nonneg ( show 0 ≤ Cbound q by exact le_trans ( by positivity ) ( Cbound_nonneg q ) ) ( mul_nonneg ( sq_nonneg _ ) ( Real.exp_nonneg _ ) ) ) ), show |eps| ≤ 1 by assumption ]

/-
**Massive HNU one-step theorem.**  The exact local unitary walk is
second-order close to the exact massive Dirac flow.
-/
theorem massive_one_step_bound (z : Complex) (hz : z ≠ 0)
    (q : Fin 3 -> Real) (eps : Real) (heps : abs eps <= 1) :
    norm (massiveWend z q eps - massiveEflow z q eps) <=
      massiveRemainderC z q * eps ^ 2 := by
  convert le_trans _ ( add_le_add ( massiveWend_sub_linear_bound z hz q eps heps ) ( massiveEflow_sub_linear_bound z q eps heps ) ) using 1;
  · unfold massiveRemainderC; ring;
  · convert norm_add_le ( massiveWend z q eps - ( 1 + -↑eps • I • massiveGenerator z q ) ) ( 1 + -↑eps • I • massiveGenerator z q - massiveEflow z q eps ) using 2 ; abel_nf;
    · convert rfl;
      ext; norm_num;
    · norm_num [ Algebra.smul_def ];
      congr!

/-
Exact short-time massive flows compose to the time-`t` flow.
-/
theorem massiveEflow_div_pow (z : Complex) (q : Fin 3 -> Real)
    (t : Real) (n : Nat) (hn : 0 < n) :
    (massiveEflow z q (t / (n : Real))) ^ n = massiveEflow z q t := by
  unfold massiveEflow; simp +decide [ ← smul_assoc ] ;
  have h_exp_smul : ∀ (x : Mat4) (n : ℕ), NormedSpace.exp (n • x) = (NormedSpace.exp x) ^ n := by
    intros x n; exact (by
    rw [ ← Matrix.exp_nsmul ]);
  convert h_exp_smul _ n |> Eq.symm using 2 ; ring;
  ext i j ; norm_num [ hn.ne', mul_assoc, mul_left_comm, mul_comm ]

/-
Fixed-time `O(1/n)` convergence of the massive HNU endpoint at each
continuum momentum.
-/
theorem massive_many_step_bound (z : Complex) (hz : z ≠ 0)
    (q : Fin 3 -> Real) (t : Real) (n : Nat) (hn : 0 < n)
    (hsmall : abs (t / (n : Real)) <= 1) :
    norm ((massiveWend z q (t / (n : Real))) ^ n - massiveEflow z q t) <=
      massiveRemainderC z q * t ^ 2 / n := by
  -- Apply the unitary power difference bound to massiveWend and massiveEflow.
  have h_unitary_pow_diff : ‖(massiveWend z q (t / n)) ^ n - (massiveEflow z q (t / n)) ^ n‖ ≤ n * ‖massiveWend z q (t / n) - massiveEflow z q (t / n)‖ := by
    have h_unitary_pow_diff : ∀ (U V : Mat4), U ∈ Matrix.unitaryGroup (Fin 4) ℂ → V ∈ Matrix.unitaryGroup (Fin 4) ℂ → ∀ n : ℕ, 0 < n → ‖U ^ n - V ^ n‖ ≤ n * ‖U - V‖ := by
      exact fun U V hU hV n _ => Compact3Plus1DiracRate.unitary_pow_telescope hU hV n;
    exact h_unitary_pow_diff _ _ ( massiveWend_mem_unitary z hz q ( t / n ) ) ( massiveEflow_mem_unitary z q ( t / n ) ) n hn;
  convert h_unitary_pow_diff.trans _ using 1;
  · rw [ massiveEflow_div_pow z q t n hn ];
  · convert mul_le_mul_of_nonneg_left ( massive_one_step_bound z hz q ( t / n ) hsmall ) ( Nat.cast_nonneg n ) using 1 ; ring;
    simp +decide [ sq, mul_assoc, hn.ne' ]

/-
The coefficient is nonnegative, preventing a vacuous negative error
envelope.
-/
theorem massiveRemainderC_nonneg (z : Complex) (q : Fin 3 -> Real) :
    0 <= massiveRemainderC z q := by
  refine add_nonneg ?_ ?_;
  · refine add_nonneg ?_ ?_;
    · refine add_nonneg ?_ ?_ <;> norm_num [ kineticRemainderC ];
      · positivity;
      · exact add_nonneg ( HNUManyStepContinuum.Cbound_nonneg q ) ( mul_nonneg ( sq_nonneg _ ) ( Real.exp_nonneg _ ) );
    · refine mul_nonneg ( norm_nonneg _ ) ?_;
      refine add_nonneg ?_ ( qAbs_nonneg q );
      refine mul_nonneg ?_ ?_ <;> norm_num [ Cbound_nonneg, qAbs_nonneg ];
      exact add_nonneg ( Cbound_nonneg q ) ( mul_nonneg ( sq_nonneg _ ) ( Real.exp_nonneg _ ) );
  · positivity

/-
Nondegenerate control: both the HNU kinetic and Pluecker mass generators
are active.
-/
theorem massive_control_nonzero :
    kinetic4 ![1, 0, 0] ≠ 0 ∧ mass4 (3 + 4 * I) ≠ 0 := by
  constructor;
  · unfold kinetic4;
    simp +decide [ alpha1, alpha2, alpha3 ];
    exact ne_of_apply_ne ( fun m => m 0 3 ) one_ne_zero;
  · unfold mass4;
    intro h; have := congr_fun ( congr_fun h 0 ) 0; norm_num at this;
    unfold beta beta5 at this;
    unfold beta gamma5 at this ; norm_num [ Complex.ext_iff, Matrix.mul_apply ] at this

end PhysicsSM.Draft.NullEdge.HNUMassiveContinuumReduction
