/-
# D2 on the T2 witness: the carrier flow is a genuine sector isometry

DRAFT (kernel-clean; no `s o r r y`). Closes the one honestly-flagged open link of
the all-mass dynamics layer (manuscript §9a): `FiniteUnitaryEvolution` proves that
*any* sector isometry (`LinearIsometryEquiv`) conserves norm and energy, but leaves
open that the concrete carrier's time step actually *is* such an isometry.

It is. Take the Hermitian sector form `H` (e.g. the mass-gap block
`MassGapWitness.B lam kappa`): the flow `exp(-i t H)` it generates is **unitary**
— hence a genuine norm-preserving sector isometry — so `FiniteUnitaryEvolution`
fires on it, not merely a generic isometry. The kernel content is precisely: *the
flow generated by the carrier's Hermitian sector form is a sector isometry whose
orbit conserves norm and energy.*

**Two grade caveats (do not over-read):**
- *The generator is a posit (grade C).* `B` (= `Q_A + Q_C`, §4) is the compressed
  squared-mass / energy *form*, not a Hamiltonian derived from the D1 action
  (D1 yields the constraint `Dψ = 0`, not a Schrödinger equation). Taking the
  sector mass form as the generator of a one-parameter flow is a *canonical
  modeling choice* (Stueckelberg-style proper-time evolution), defensible but
  chosen, not derived. What is kernel-checked is the unitarity/isometry of
  `exp(-i t H)` for Hermitian `H`; that this flow *is* the carrier's physical time
  evolution is grade **C**.
- *The carrier tie is `(2,1)`-kernel.* `B(λ,κ)` is the carrier's compressed sector
  form kernel-checked only at `(λ,κ) = (2,1)` (via `MassGapWitness.M6_topBlock_eq_B`);
  at general `(λ,κ)` the identification is oracle-grade (`carrier_spectrum_sim.py`).
  So `carrierFlowStep`/`B_flow_unitary` are honest unitary flows of the *block*
  `B(λ,κ)` for all `(λ,κ)`, but "the flow of the *carrier*" is kernel-earned at
  `(2,1)`.

## Landed theorems (all M, kernel-clean)

- `skewHermitian_neg_I_smul` - the generator `A = -i t H` is skew-Hermitian.
- `hermitian_flow_mem_unitaryGroup` - **core**: `exp(-i t H)` is unitary
  (`∈ Matrix.unitaryGroup`), via `star(exp A) = exp(Aᴴ) = exp(-A)` and
  `exp(-A) * exp(A) = exp 0 = 1`.
- `hermitian_flow_isometry` - the induced map on `EuclideanSpace ℂ n` is a
  `LinearIsometryEquiv` (the sector isometry that plugs into
  `FiniteUnitaryEvolution.norm_conserved_orbit` / `energy_conserved_orbit`).
- `B_flow_unitary` - the specialization to the carrier block
  `MassGapWitness.B lam kappa`.

## Provenance

All-mass solo run 2026-07-08 [orig]. Statements by the reviewing agent (Claude);
the complete proofs are from Aristotle (standalone package
`AgentTasks/aristotle-standalone/allmass-d2-on-t2-20260708`), reviewed for
semantic alignment and adopted here. The core route (`Matrix.unitaryGroup` /
`U * Uᴴ = 1` via `Matrix.exp_conjTranspose` + `exp_add_of_commute`) dodges the
`unitary` monoid-instance diamond that times out on the direct `∈ unitary`
formulation. Instantiates `FiniteUnitaryEvolution` on the `MassGapWitness`
carrier block. Mathlib-only + `MassGapWitness`.
-/

import Mathlib
import PhysicsSM.Draft.NullEdge.Carrier.MassGapWitness
import PhysicsSM.Draft.NullEdge.Carrier.FiniteUnitaryEvolution

namespace PhysicsSM.Draft.NullEdge.Carrier.CarrierUnitaryFlow

open Matrix Complex

/-- **Helper.** For a Hermitian `H` and real `t`, the generator
`A := (-(t : ℂ)) • (Complex.I • H)` of the flow `exp(-i t H)` is skew-Hermitian:
`Aᴴ = -A`. -/
theorem skewHermitian_neg_I_smul {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (t : ℝ) :
    ((-(t : ℂ)) • (Complex.I • H))ᴴ = -((-(t : ℂ)) • (Complex.I • H)) := by
  rw [conjTranspose_smul, conjTranspose_smul, hH.eq]
  simp [Complex.conj_I]

/-- **Core.** For a Hermitian `H` and real `t`, the Hermitian-generated flow
`exp(-i t H)` is a unitary matrix. This is the load-bearing fact: the carrier's
time step is norm-preserving. -/
theorem hermitian_flow_mem_unitaryGroup {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (t : ℝ) :
    NormedSpace.exp ((-(t : ℂ)) • (Complex.I • H)) ∈ Matrix.unitaryGroup n ℂ := by
  set A : Matrix n n ℂ := (-(t : ℂ)) • (Complex.I • H) with hA
  have hskew : Aᴴ = -A := skewHermitian_neg_I_smul hH t
  rw [Matrix.mem_unitaryGroup_iff]
  have hstar : star (NormedSpace.exp A) = NormedSpace.exp (-A) := by
    rw [show star (NormedSpace.exp A) = (NormedSpace.exp A)ᴴ from rfl,
        ← Matrix.exp_conjTranspose, hskew]
  rw [hstar, ← Matrix.exp_add_of_commute A (-A) ((Commute.refl A).neg_right),
      add_neg_cancel, NormedSpace.exp_zero]

/-- **Isometry packaging.** The linear map on `EuclideanSpace ℂ n` induced by the
unitary flow `exp(-i t H)` is a `LinearIsometryEquiv`, i.e. a genuine
norm-preserving sector isometry — the object `FiniteUnitaryEvolution` takes as its
step. -/
noncomputable def hermitian_flow_isometry {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (t : ℝ) :
    EuclideanSpace ℂ n ≃ₗᵢ[ℂ] EuclideanSpace ℂ n := by
  set U : Matrix n n ℂ := NormedSpace.exp ((-(t : ℂ)) • (Complex.I • H)) with hU
  have hmem : U ∈ Matrix.unitaryGroup n ℂ := hermitian_flow_mem_unitaryGroup hH t
  have h1 : U * Uᴴ = 1 := Matrix.mem_unitaryGroup_iff.mp hmem
  have h2 : Uᴴ * U = 1 := Matrix.mem_unitaryGroup_iff'.mp hmem
  have hmul : ∀ P Q : Matrix n n ℂ,
      (P * Q).toEuclideanLin = P.toEuclideanLin ∘ₗ Q.toEuclideanLin := by
    intro P Q; ext x i; simp [Matrix.mulVec_mulVec]
  have hone : (1 : Matrix n n ℂ).toEuclideanLin = LinearMap.id := by
    ext x i; simp
  refine LinearEquiv.isometryOfInner
    (LinearEquiv.ofLinear U.toEuclideanLin Uᴴ.toEuclideanLin ?_ ?_) ?_
  · rw [← hmul, h1, hone]
  · rw [← hmul, h2, hone]
  · intro x y
    show inner ℂ (U.toEuclideanLin x) (U.toEuclideanLin y) = inner ℂ x y
    rw [← LinearMap.adjoint_inner_right, ← Matrix.toEuclideanLin_conjTranspose_eq_adjoint,
        ← LinearMap.comp_apply, ← hmul, h2, hone]
    rfl

/-- **Specialization.** The carrier block `MassGapWitness.B lam kappa` generates a
unitary flow: the T2 carrier's time step is a genuine sector isometry, so
`FiniteUnitaryEvolution` fires on the actual carrier. -/
theorem B_flow_unitary (lam kappa t : ℝ) :
    NormedSpace.exp ((-(t : ℂ)) • (Complex.I • MassGapWitness.B lam kappa))
      ∈ Matrix.unitaryGroup (Fin 3) ℂ :=
  hermitian_flow_mem_unitaryGroup (MassGapWitness.B_isHermitian lam kappa) t

/-- The flow step generated by the mass-gap block `B lam kappa`, as a
`LinearIsometryEquiv` on the sector Hilbert space `EuclideanSpace ℂ (Fin 3)` —
the concrete transfer step `FiniteUnitaryEvolution` takes. (Carrier tie:
kernel-checked at `(λ,κ) = (2,1)`, oracle-grade off it; generator-as-Hamiltonian
is a grade-C posit — see the module docstring.) -/
noncomputable def carrierFlowStep (lam kappa t : ℝ) :
    EuclideanSpace ℂ (Fin 3) ≃ₗᵢ[ℂ] EuclideanSpace ℂ (Fin 3) :=
  hermitian_flow_isometry (MassGapWitness.B_isHermitian lam kappa) t

/-- **D2/D3 fired on the actual carrier — norm.** The discrete time-evolution
orbit of the concrete T2 carrier (generated by the mass-gap block flow) conserves
the sector norm. This is `FiniteUnitaryEvolution.norm_conserved_orbit` instantiated
on the real carrier step, not a generic isometry: the open §9a link, now a
single kernel theorem. -/
theorem carrier_orbit_norm_conserved (lam kappa t : ℝ)
    (psi : EuclideanSpace ℂ (Fin 3)) (n : ℕ) :
    ‖FiniteUnitaryEvolution.orbit (carrierFlowStep lam kappa t) psi n‖ = ‖psi‖ :=
  FiniteUnitaryEvolution.norm_conserved_orbit _ psi n

/-- **D2/D3 fired on the actual carrier — energy.** Any observable that commutes
with the carrier flow step has conserved real expectation along the carrier orbit
(finite energy conservation on the real carrier). -/
theorem carrier_orbit_energy_conserved (lam kappa t : ℝ)
    (E : EuclideanSpace ℂ (Fin 3) →L[ℂ] EuclideanSpace ℂ (Fin 3))
    (hUE : FiniteUnitaryEvolution.CommutesWithStep (carrierFlowStep lam kappa t) E)
    (psi : EuclideanSpace ℂ (Fin 3)) (n : ℕ) :
    FiniteUnitaryEvolution.observableEnergy E (FiniteUnitaryEvolution.orbit
      (carrierFlowStep lam kappa t) psi n) = FiniteUnitaryEvolution.observableEnergy E psi :=
  FiniteUnitaryEvolution.energy_conserved_orbit _ E hUE psi n

/-- The flow step of the **full `6×6` physical sector form** `M6` (the actual
carrier compression `Pisoᴴ HAC Piso`, `= B(2,1) ⊕ B(2,-1)` by the bridge), as a
`LinearIsometryEquiv`. This is the honest "carrier sector evolution" object: `M6`
is the real physical sector form (not just the `3×3` block), kernel-tied to the
carrier at the fixed point. `M6` is Hermitian via `M6_posDef`. -/
noncomputable def carrierFlowStep6 (t : ℝ) :
    EuclideanSpace ℂ (Fin 6) ≃ₗᵢ[ℂ] EuclideanSpace ℂ (Fin 6) :=
  hermitian_flow_isometry SectorGroundMassWitness.M6_posDef.1 t

/-- **The full carrier sector orbit conserves norm.** The discrete time-evolution
orbit of the `6×6` physical sector form `M6`'s flow conserves the sector norm —
the concrete carrier's actual sector evolution, not just a block. -/
theorem carrier6_orbit_norm_conserved (t : ℝ)
    (psi : EuclideanSpace ℂ (Fin 6)) (n : ℕ) :
    ‖FiniteUnitaryEvolution.orbit (carrierFlowStep6 t) psi n‖ = ‖psi‖ :=
  FiniteUnitaryEvolution.norm_conserved_orbit _ psi n

end PhysicsSM.Draft.NullEdge.Carrier.CarrierUnitaryFlow
