import PhysicsSM.Draft.NullEdge.Carrier.PositiveHodgeDecoder

/-!
# Chain-homotopy gauge freedom for finite decoders

This module formalizes a finite core of the proposed moduli theory of null
information decoders.  On a fixed carrier with nilpotent constraint
differential `Q`, two decoder presentations are chain-homotopic when

`D' = D + Q R + R Q`

for some linear homotopy `R`.  The correction is `Q`-exact on every closed
representative, so `D` and `D'` induce the same action on
`ker Q / range Q`.  If `D` commutes with `Q`, then so does `D'`.

This turns one part of carrier non-rigidity into controlled gauge freedom:
individual matrices can differ while the physical cohomology action remains
fixed.  It does not prove that every observed four-channel non-uniqueness is of
this form, nor that spectra on the full prephysical carrier are invariant.

The final section instantiates the theorem on the positive Hodge witness.  The
shifted decoder `D + 2Q` is genuinely a different linear map, remains a chain
map, and acts identically on the surviving positive harmonic class `e2`.

Provenance: clean-room finite homological algebra inspired by the Pro moduli
analysis supplied 2026-07-09.  The representative-level formulation avoids
assuming an unformalized physical quotient API.
-/

namespace PhysicsSM.Draft.NullEdge.Carrier.DecoderChainHomotopy

section Generic

variable {𝕜 V : Type*} [Field 𝕜] [AddCommGroup V] [Module 𝕜 V]

/-- A vector is closed when it is killed by the constraint differential. -/
def IsClosed (Q : V →ₗ[𝕜] V) (x : V) : Prop := x ∈ LinearMap.ker Q

/-- A vector is exact when it lies in the range of the constraint differential. -/
def IsExact (Q : V →ₗ[𝕜] V) (x : V) : Prop := x ∈ LinearMap.range Q

/-- Two representatives are cohomologous when their difference is exact. -/
def Cohomologous (Q : V →ₗ[𝕜] V) (x y : V) : Prop :=
  x - y ∈ LinearMap.range Q

/-- A decoder descends to cohomology when it commutes with the differential. -/
def IsChainMap (Q D : V →ₗ[𝕜] V) : Prop := D ∘ₗ Q = Q ∘ₗ D

/-- The anticommutator-shaped exact deformation generated by `R`. -/
def exactDeformation (Q R : V →ₗ[𝕜] V) : V →ₗ[𝕜] V :=
  Q ∘ₗ R + R ∘ₗ Q

/-- Decoder presentations differ by a finite chain homotopy. -/
def ChainHomotopic (Q D D' : V →ₗ[𝕜] V) : Prop :=
  ∃ R : V →ₗ[𝕜] V, D' = D + exactDeformation Q R

theorem cohomologous_refl (Q : V →ₗ[𝕜] V) (x : V) :
    Cohomologous Q x x := by
  simp [Cohomologous]

theorem cohomologous_symm (Q : V →ₗ[𝕜] V) {x y : V}
    (hxy : Cohomologous Q x y) : Cohomologous Q y x := by
  change x - y ∈ LinearMap.range Q at hxy
  change y - x ∈ LinearMap.range Q
  have hneg := (LinearMap.range Q).neg_mem hxy
  simpa using hneg

theorem cohomologous_trans (Q : V →ₗ[𝕜] V) {x y z : V}
    (hxy : Cohomologous Q x y) (hyz : Cohomologous Q y z) :
    Cohomologous Q x z := by
  change x - y ∈ LinearMap.range Q at hxy
  change y - z ∈ LinearMap.range Q at hyz
  change x - z ∈ LinearMap.range Q
  convert (LinearMap.range Q).add_mem hxy hyz using 1
  abel

theorem chainHomotopic_refl (Q D : V →ₗ[𝕜] V) :
    ChainHomotopic Q D D := by
  refine ⟨0, ?_⟩
  simp [exactDeformation]

theorem chainHomotopic_symm (Q : V →ₗ[𝕜] V) {D D' : V →ₗ[𝕜] V}
    (h : ChainHomotopic Q D D') : ChainHomotopic Q D' D := by
  obtain ⟨R, rfl⟩ := h
  refine ⟨-R, ?_⟩
  ext x
  simp [exactDeformation]
  abel

theorem chainHomotopic_trans (Q : V →ₗ[𝕜] V) {D₁ D₂ D₃ : V →ₗ[𝕜] V}
    (h₁₂ : ChainHomotopic Q D₁ D₂) (h₂₃ : ChainHomotopic Q D₂ D₃) :
    ChainHomotopic Q D₁ D₃ := by
  obtain ⟨R, rfl⟩ := h₁₂
  obtain ⟨S, rfl⟩ := h₂₃
  refine ⟨R + S, ?_⟩
  ext x
  simp [exactDeformation]
  abel

/-- A commuting decoder preserves closed representatives. -/
theorem chainMap_preserves_closed (Q D : V →ₗ[𝕜] V) (hD : IsChainMap Q D)
    {x : V} (hx : IsClosed Q x) : IsClosed Q (D x) := by
  rw [IsClosed, LinearMap.mem_ker] at hx ⊢
  have hDx := LinearMap.congr_fun hD x
  simpa [LinearMap.comp_apply, hx] using hDx.symm

/-- A commuting decoder preserves exact representatives. -/
theorem chainMap_preserves_exact (Q D : V →ₗ[𝕜] V) (hD : IsChainMap Q D)
    {x : V} (hx : IsExact Q x) : IsExact Q (D x) := by
  rw [IsExact] at hx ⊢
  obtain ⟨y, rfl⟩ := hx
  refine ⟨D y, ?_⟩
  exact (LinearMap.congr_fun hD y).symm

/-- **Channel-equivalence theorem.** Chain-homotopic decoders act
cohomologously on every closed representative. -/
theorem chainHomotopic_same_on_closed (Q : V →ₗ[𝕜] V) {D D' : V →ₗ[𝕜] V}
    (h : ChainHomotopic Q D D') {x : V} (hx : IsClosed Q x) :
    Cohomologous Q (D' x) (D x) := by
  obtain ⟨R, rfl⟩ := h
  rw [IsClosed, LinearMap.mem_ker] at hx
  rw [Cohomologous]
  refine ⟨R x, ?_⟩
  simp [exactDeformation, hx]

/-- Under nilpotence, an exact deformation of a chain map is again a chain
map. -/
theorem chainHomotopic_isChainMap (Q : V →ₗ[𝕜] V) {D D' : V →ₗ[𝕜] V}
    (hQ2 : Q ∘ₗ Q = 0) (hD : IsChainMap Q D)
    (h : ChainHomotopic Q D D') : IsChainMap Q D' := by
  obtain ⟨R, rfl⟩ := h
  apply LinearMap.ext
  intro x
  have hQ2x : ∀ y : V, Q (Q y) = 0 := fun y => LinearMap.congr_fun hQ2 y
  have hDx : D (Q x) = Q (D x) := LinearMap.congr_fun hD x
  simp [IsChainMap, exactDeformation, LinearMap.comp_apply, hQ2x, hDx]

/-- The complete representative-level descent packet. -/
theorem chainHomotopy_physical_action (Q : V →ₗ[𝕜] V) {D D' : V →ₗ[𝕜] V}
    (hQ2 : Q ∘ₗ Q = 0) (hD : IsChainMap Q D)
    (h : ChainHomotopic Q D D') :
    IsChainMap Q D' ∧
      (∀ x, IsClosed Q x →
        IsClosed Q (D x) ∧ IsClosed Q (D' x) ∧ Cohomologous Q (D' x) (D x)) ∧
      (∀ x, IsExact Q x → IsExact Q (D x) ∧ IsExact Q (D' x)) := by
  have hD' := chainHomotopic_isChainMap Q hQ2 hD h
  refine ⟨hD', ?_, ?_⟩
  · intro x hx
    exact ⟨chainMap_preserves_closed Q D hD hx,
      chainMap_preserves_closed Q D' hD' hx,
      chainHomotopic_same_on_closed Q h hx⟩
  · intro x hx
    exact ⟨chainMap_preserves_exact Q D hD hx,
      chainMap_preserves_exact Q D' hD' hx⟩

end Generic

/-! ## Chain intertwiners between different carriers -/

section BetweenCarriers

variable {𝕜 V W : Type*} [Field 𝕜]
  [AddCommGroup V] [Module 𝕜 V] [AddCommGroup W] [Module 𝕜 W]

/-- A map between carriers respects their constraint differentials. -/
def IsConstraintMap (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W) : Prop :=
  U ∘ₗ Q = Q' ∘ₗ U

/-- The two decoder actions intertwine up to a chain homotopy.  This is the
typed cross-carrier form of `D' U - U D = Q' R + R Q`. -/
def DecoderIntertwinesUpToHomotopy
    (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W)
    (D : V →ₗ[𝕜] V) (D' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W) : Prop :=
  ∃ R : V →ₗ[𝕜] W,
    D' ∘ₗ U - U ∘ₗ D = Q' ∘ₗ R + R ∘ₗ Q

/-- A constraint map sends closed representatives to closed representatives. -/
theorem constraintMap_preserves_closed
    (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W)
    (hU : IsConstraintMap Q Q' U) {x : V} (hx : IsClosed Q x) :
    IsClosed Q' (U x) := by
  rw [IsClosed, LinearMap.mem_ker] at hx ⊢
  have hUx := LinearMap.congr_fun hU x
  simpa [IsConstraintMap, LinearMap.comp_apply, hx] using hUx.symm

/-- A constraint map sends exact representatives to exact representatives. -/
theorem constraintMap_preserves_exact
    (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W)
    (hU : IsConstraintMap Q Q' U) {x : V} (hx : IsExact Q x) :
    IsExact Q' (U x) := by
  rw [IsExact] at hx ⊢
  obtain ⟨y, rfl⟩ := hx
  refine ⟨U y, ?_⟩
  exact (LinearMap.congr_fun hU y).symm

/-- **Cross-carrier channel-equivalence theorem.** If decoder actions
intertwine up to a constraint homotopy, then they induce the same action after
transport by `U` on every closed class. -/
theorem decoderIntertwines_same_on_closed
    (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W)
    (D : V →ₗ[𝕜] V) (D' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W)
    (h : DecoderIntertwinesUpToHomotopy Q Q' D D' U)
    {x : V} (hx : IsClosed Q x) :
    Cohomologous Q' (D' (U x)) (U (D x)) := by
  obtain ⟨R, hR⟩ := h
  rw [IsClosed, LinearMap.mem_ker] at hx
  rw [Cohomologous]
  refine ⟨R x, ?_⟩
  have hRx := LinearMap.congr_fun hR x
  simpa [DecoderIntertwinesUpToHomotopy, LinearMap.comp_apply, hx] using hRx.symm

/-- The full representative-level physical-equivalence packet between two
carriers. -/
theorem decoder_chain_intertwining_packet
    (Q : V →ₗ[𝕜] V) (Q' : W →ₗ[𝕜] W)
    (D : V →ₗ[𝕜] V) (D' : W →ₗ[𝕜] W) (U : V →ₗ[𝕜] W)
    (hU : IsConstraintMap Q Q' U)
    (hD : DecoderIntertwinesUpToHomotopy Q Q' D D' U) :
    (∀ x, IsClosed Q x →
      IsClosed Q' (U x) ∧ Cohomologous Q' (D' (U x)) (U (D x))) ∧
      (∀ x, IsExact Q x → IsExact Q' (U x)) := by
  constructor
  · intro x hx
    exact ⟨constraintMap_preserves_closed Q Q' U hU hx,
      decoderIntertwines_same_on_closed Q Q' D D' U hD hx⟩
  · intro x hx
    exact constraintMap_preserves_exact Q Q' U hU hx

end BetweenCarriers

/-! ## Nontrivial positive-decoder witness -/

open KugoOjima PositiveHodgeDecoder

/-- A distinct presentation obtained by the identity homotopy:
`D'_mu = D_mu + Q + Q = D_mu + 2Q`. -/
noncomputable def shiftedMassDecoder (mu : ℝ) : W →ₗ[ℂ] W :=
  massDecoder mu + exactDeformation Qop LinearMap.id

theorem shifted_chainHomotopic (mu : ℝ) :
    ChainHomotopic Qop (massDecoder mu) (shiftedMassDecoder mu) := by
  exact ⟨LinearMap.id, rfl⟩

theorem massDecoder_isChainMap (mu : ℝ) : IsChainMap Qop (massDecoder mu) :=
  massDecoder_commutes_Q mu

/-- The shifted decoder is genuinely a different prephysical matrix. -/
theorem shifted_ne_original (mu : ℝ) : shiftedMassDecoder mu ≠ massDecoder mu := by
  intro h
  have h1 := LinearMap.congr_fun h (EuclideanSpace.single 1 1)
  have hcoord := congr_arg (fun x : W => x.ofLp 0) h1
  norm_num [shiftedMassDecoder, exactDeformation, Qop, Qmat, massDecoder,
    massDecoderMat, Matrix.toEuclideanLin, Matrix.mulVec, dotProduct,
    Fin.sum_univ_three] at hcoord
  simp +decide at hcoord

/-- The exact presentation shift vanishes on the surviving harmonic class. -/
theorem shifted_e2 (mu : ℝ) : shiftedMassDecoder mu e2 = massDecoder mu e2 := by
  ext i
  fin_cases i <;>
    simp [shiftedMassDecoder, exactDeformation, Qop, Qmat, e2,
      Matrix.toEuclideanLin, Matrix.mulVec, dotProduct, Fin.sum_univ_three]

/-- **Nonvacuous channel-gauge witness.** Two distinct decoder matrices are
chain-homotopic, both descend through the constraint quotient, and they act
identically on the positive non-exact harmonic class. -/
theorem positive_decoder_moduli_witness :
    shiftedMassDecoder 2 ≠ massDecoder 2 ∧
      ChainHomotopic Qop (massDecoder 2) (shiftedMassDecoder 2) ∧
      IsChainMap Qop (shiftedMassDecoder 2) ∧
      e2 ∈ LinearMap.ker Qop ∧
      e2 ∉ LinearMap.range Qop ∧
      constraintLaplacian e2 = 0 ∧
      0 < (kreinForm Jpos e2 e2).re ∧
      shiftedMassDecoder 2 e2 = massDecoder 2 e2 := by
  refine ⟨shifted_ne_original 2, shifted_chainHomotopic 2,
    chainHomotopic_isChainMap Qop Qop_sq (massDecoder_isChainMap 2)
      (shifted_chainHomotopic 2),
    e2_mem_ker, e2_not_mem_range, e2_is_harmonic,
    positive_of_closed_not_exact e2 e2_mem_ker e2_not_mem_range, shifted_e2 2⟩

/-! ## Axiom audit -/

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.DecoderChainHomotopy.chainHomotopy_physical_action' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms chainHomotopy_physical_action

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.DecoderChainHomotopy.decoder_chain_intertwining_packet' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms decoder_chain_intertwining_packet

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.DecoderChainHomotopy.positive_decoder_moduli_witness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms positive_decoder_moduli_witness

end PhysicsSM.Draft.NullEdge.Carrier.DecoderChainHomotopy
