/-
# Finite unitary evolution and conservation laws

DRAFT (kernel-clean). This module is the D2/D3 conservation seed for the
null-edge carrier dynamics lane. It is clean-room, but follows the API idea of
PhysLean's classical-mechanics examples: specify the step/evolution map, specify
the conserved observable, and prove the invariant rather than just checking it
numerically.

Here the finite time step is represented by a `LinearIsometryEquiv`, the Lean
form of a unitary transfer map. This is intentionally abstract: it applies to a
Hamiltonian time step, a checkerboard transfer step, or any future carrier
transfer operator once its unitarity/Krein-isometry hypotheses are formalized.

Theorems:

* `norm_conserved_step` and `norm_conserved_orbit`: unitary/transfer evolution
  preserves norm at one step and along all iterates.
* `energy_conserved_step` and `energy_conserved_orbit`: if an observable
  `E : H ->L[Complex] H` commutes with the transfer step, then the real
  expectation `Re <psi, E psi>` is conserved at one step and along all iterates.

This is not yet a derivation of a particular carrier transfer map from the
action, nor a proof of a continuum limit. It is the kernel-backed invariant
layer that numerical dynamics simulations can cite when they validate norm and
energy conservation.

Provenance: clean-room D2/D3 formalization from the 2026-07-08 dynamics
guidance, after consulting PhysLean's `ClassicalMechanics` conservation-law API
as an organizational model. No PhysLean source is imported.
-/

import Mathlib

namespace PhysicsSM.Draft.NullEdge.Carrier.FiniteUnitaryEvolution

open scoped ComplexConjugate

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- Real expectation of an observable/operator `E`. For self-adjoint `E` this is
the usual finite quantum-mechanical energy expectation. -/
noncomputable def observableEnergy (E : H →L[ℂ] H) (psi : H) : ℝ :=
  (inner ℂ psi (E psi)).re

/-- The observable `E` is covariant/constant under the transfer step `U`. -/
def CommutesWithStep (U : H ≃ₗᵢ[ℂ] H) (E : H →L[ℂ] H) : Prop :=
  ∀ psi : H, E (U psi) = U (E psi)

/-- Orbit generated by iterating the finite transfer step. -/
def orbit (U : H ≃ₗᵢ[ℂ] H) (psi : H) : ℕ → H
  | 0 => psi
  | n + 1 => U (orbit U psi n)

@[simp] theorem orbit_zero (U : H ≃ₗᵢ[ℂ] H) (psi : H) :
    orbit U psi 0 = psi := rfl

@[simp] theorem orbit_succ (U : H ≃ₗᵢ[ℂ] H) (psi : H) (n : ℕ) :
    orbit U psi (n + 1) = U (orbit U psi n) := rfl

/-- **D2 norm conservation, one step.** A finite unitary/transfer step preserves
the carrier norm. -/
theorem norm_conserved_step (U : H ≃ₗᵢ[ℂ] H) (psi : H) :
    ‖U psi‖ = ‖psi‖ := by
  simp

/-- **D2 inner-product conservation, one step.** A finite unitary/transfer step
preserves all inner products. -/
theorem inner_conserved_step (U : H ≃ₗᵢ[ℂ] H) (psi phi : H) :
    inner ℂ (U psi) (U phi) = inner ℂ psi phi :=
  LinearIsometry.inner_map_map U.toLinearIsometry psi phi

/-- **D2 energy conservation, one step.** If an observable commutes with the
transfer step, its real expectation is conserved. -/
theorem energy_conserved_step (U : H ≃ₗᵢ[ℂ] H) (E : H →L[ℂ] H)
    (hUE : CommutesWithStep U E) (psi : H) :
    observableEnergy E (U psi) = observableEnergy E psi := by
  unfold observableEnergy
  rw [hUE psi]
  have hinner : inner ℂ (U psi) (U (E psi)) = inner ℂ psi (E psi) :=
    inner_conserved_step U psi (E psi)
  rw [hinner]

/-- **D3 norm conservation along the discrete orbit.** -/
theorem norm_conserved_orbit (U : H ≃ₗᵢ[ℂ] H) (psi : H) (n : ℕ) :
    ‖orbit U psi n‖ = ‖psi‖ := by
  induction n with
  | zero => simp
  | succ n ih => simp [orbit_succ, ih]

/-- **D3 energy conservation along the discrete orbit.** -/
theorem energy_conserved_orbit (U : H ≃ₗᵢ[ℂ] H) (E : H →L[ℂ] H)
    (hUE : CommutesWithStep U E) (psi : H) (n : ℕ) :
    observableEnergy E (orbit U psi n) = observableEnergy E psi := by
  induction n with
  | zero => simp [orbit]
  | succ n ih =>
      rw [orbit_succ]
      rw [energy_conserved_step U E hUE (orbit U psi n)]
      exact ih

/-! ## Local axiom guard (self-contained) -/

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.FiniteUnitaryEvolution.norm_conserved_orbit' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms norm_conserved_orbit

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.FiniteUnitaryEvolution.energy_conserved_orbit' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms energy_conserved_orbit

end PhysicsSM.Draft.NullEdge.Carrier.FiniteUnitaryEvolution
