/-
# RG-Schur mass-generation witness: blocking a null chain generates
# non-null effective terms

DRAFT (kernel-clean; no `s o r r y`). The registered "dynamics" witness of
the two-day carrier run (2026-07-07): per-edge null nilpotency is NOT
stable under one decimation (Schur-complement) step, and the obstruction
coefficient is exactly the pairwise null-direction pairing.

## The statement family

* `null_pair_prod_sq_eq_pairing_smul` (abstract, any associative algebra):
  if `a * a = 0`, `b * b = 0`, and `a * b + b * a = k • 1`, then
  `(a * b) * (a * b) = k • (a * b)`. So the product of two null Clifford
  edge terms fails to be nilpotent exactly when their pairing `k` is
  nonzero - and for null covectors, nonzero pairing means non-collinear.
* Concrete light-cone pair `nullL = !![0,1;0,0]`, `nullN = !![0,0;1,0]`
  (each square-zero, anticommutator `1`): the effective edge term
  `nullL * nullN` is a nonzero idempotent, hence NOT nilpotent
  (`nullL_mul_nullN_not_nilpotent`).
* Schur wiring (`chain_schurComplement_eq`): on the 3-site chain
  `v1 - h - v2` with hidden middle block `1` and null couplings, the
  Schur complement (the `schurComplement` of
  `PhysicsSM.NullStrand.DualSolder.SpectralSchur`) equals
  `-(fromBlocks 0 (nullL*nullN) (nullN*nullL) 0)`: decimation induces a
  direct `v1 - v2` edge whose block is non-nilpotent
  (`effective_edge_not_nilpotent`), although no such edge existed before
  blocking and every original edge term was null.
* Negative control (`collinear_schurComplement_eq_zero`): if the two
  couplings are COLLINEAR (`t • nullL` against `nullL`, any `t`), the
  entire effective coupling vanishes - nullity survives blocking exactly
  on collinear (massless) configurations. This is what makes the witness
  a statement about mass, not an artifact.
* Bonus (`effective_total_sq_eq_zero`): the TOTAL effective operator is
  still square-zero on this chain; the failure of nullity is precisely a
  per-edge statement, which is why the program's per-edge nilpotency
  convention is the right level for the RG question.

## Reading and claim boundary

Kinematically (trusted layer) mass is pairwise null disagreement
(`det P = sum |psi_i wedge psi_j|^2`). This file shows the dynamical
counterpart at finite level: one decimation step converts the SAME
pairwise pairing into a non-null effective edge coefficient. It is ONE
finite Schur step - no RG flow, no fixed points, no continuum claim.
"Mass-like" is used only in the docstrings, never in a statement.

## Provenance

The Schur-complement effective-operator identity is classical (Loewdin
partitioning 1951; Feshbach projection 1958; Kron reduction for graph
Laplacians) - [import]. The instability of per-edge null nilpotency
under blocking was predicted by the Q08 memo ("null nilpotency is NOT
RG-stable") and the coefficient prediction `T^2 = (2<a,b>) T` appears in
`AgentTasks/twoday-carrier-run-2026-07-07/FABLE_HANDOFF_HARDEST_PIECES.md`
(piece 11) - [orig]. Wired into the run's landed Schur frame
(`PhysicsSM/NullStrand/DualSolder/SpectralSchur.lean`).
-/

import PhysicsSM.NullStrand.DualSolder.SpectralSchur

namespace PhysicsSM.Draft.NullEdge.Carrier.RGSchurMass

open Matrix

/-! ## The abstract pairing lemma -/

/-- **Null-pair product square.** In any associative algebra, if `a` and
`b` are square-zero and anticommute up to the scalar `k`
(`a * b + b * a = k • 1`), then `(a * b)^2 = k • (a * b)`. The effective
term generated by eliminating a site between two null edges is
non-nilpotent exactly when the pairing `k` is nonzero. -/
theorem null_pair_prod_sq_eq_pairing_smul {S R : Type*} [CommSemiring S]
    [Ring R] [Algebra S R] (a b : R) (k : S)
    (ha : a * a = 0) (hpair : a * b + b * a = k • (1 : R)) :
    (a * b) * (a * b) = k • (a * b) := by
  have hba : b * a = k • (1 : R) - a * b := eq_sub_of_add_eq' hpair
  have hassoc : (a * b) * (a * b) = a * (b * a) * b := by
    rw [mul_assoc, ← mul_assoc b a b, ← mul_assoc]
  rw [hassoc, hba, mul_sub, sub_mul, mul_smul_comm, mul_one, smul_mul_assoc,
    ← mul_assoc, ha, zero_mul, zero_mul, sub_zero]

/-! ## The concrete light-cone pair -/

/-- Clifford edge term for the null direction `l` (light-cone raising). -/
def nullL : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 0, 0]

/-- Clifford edge term for the null direction `n` (light-cone lowering). -/
def nullN : Matrix (Fin 2) (Fin 2) ℂ := !![0, 0; 1, 0]

/-- `nullL` is a null (square-zero) edge term. -/
theorem nullL_sq : nullL * nullL = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [nullL, Matrix.mul_apply, Fin.sum_univ_two]

/-- `nullN` is a null (square-zero) edge term. -/
theorem nullN_sq : nullN * nullN = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [nullN, Matrix.mul_apply, Fin.sum_univ_two]

/-- The light-cone pairing: `c(l) c(n) + c(n) c(l) = 1`, i.e. the two null
directions have unit Clifford pairing (they disagree maximally). -/
theorem lightcone_pairing : nullL * nullN + nullN * nullL = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [nullL, nullN]

/-- The effective edge term produced by decimation is the projector
`diag(1, 0)`. -/
theorem nullL_mul_nullN_eq : nullL * nullN = !![1, 0; 0, 0] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [nullL, nullN, Matrix.mul_apply, Fin.sum_univ_two]

/-- The effective edge term is idempotent (instance of the abstract
pairing lemma at `k = 1`). -/
theorem nullL_mul_nullN_idem :
    (nullL * nullN) * (nullL * nullN) = nullL * nullN := by
  have h := null_pair_prod_sq_eq_pairing_smul (S := ℂ) nullL nullN 1
    nullL_sq (by rw [lightcone_pairing, one_smul])
  rwa [one_smul] at h

/-- The effective edge term is nonzero. -/
theorem nullL_mul_nullN_ne_zero : nullL * nullN ≠ 0 := by
  rw [nullL_mul_nullN_eq]
  intro h
  have h00 := congrFun (congrFun h 0) 0
  simp at h00

/-- **Per-edge null nilpotency fails under blocking**: the effective edge
term is NOT nilpotent (it is a nonzero idempotent), although both original
edge terms were square-zero. -/
theorem nullL_mul_nullN_not_nilpotent : ¬ IsNilpotent (nullL * nullN) := by
  rintro ⟨n, hn⟩
  have hpow : ∀ m : ℕ, (nullL * nullN) ^ (m + 1) = nullL * nullN := by
    intro m
    induction m with
    | zero => simp
    | succ m ih => rw [pow_succ, ih, nullL_mul_nullN_idem]
  match n with
  | 0 =>
    rw [pow_zero] at hn
    have h00 := congrFun (congrFun hn 0) 0
    simp at h00
  | m + 1 => exact nullL_mul_nullN_ne_zero (by rw [← hpow m]; exact hn)

/-! ## The Schur wiring: the 3-site chain -/

open PhysicsSM.NullStrand.DualSolder

attribute [local instance] invertibleOne

/-- Decimating the hidden middle site of the null chain `v1 - h - v2`
(hidden on-site block `1`, couplings `nullL` into and `nullL, nullN` out
of the hidden site) produces the effective visible operator
`-(fromBlocks 0 (nullL*nullN) (nullN*nullL) 0)`: a direct `v1 - v2` edge
appears where none existed. -/
theorem chain_schurComplement_eq :
    schurComplement (0 : Matrix (Fin 2 ⊕ Fin 2) (Fin 2 ⊕ Fin 2) ℂ)
      (fromRows nullL nullN) (fromCols nullL nullN)
      (1 : Matrix (Fin 2) (Fin 2) ℂ)
      = -(fromBlocks 0 (nullL * nullN) (nullN * nullL) 0) := by
  unfold schurComplement
  rw [invOf_one, Matrix.mul_one, fromRows_mul_fromCols, nullL_sq, nullN_sq,
    zero_sub]

/-- The induced `v1 -> v2` block of the effective operator is
`-(nullL * nullN)`. -/
theorem effective_offdiag_eq_neg_edgeProd :
    (schurComplement (0 : Matrix (Fin 2 ⊕ Fin 2) (Fin 2 ⊕ Fin 2) ℂ)
      (fromRows nullL nullN) (fromCols nullL nullN)
      (1 : Matrix (Fin 2) (Fin 2) ℂ)).toBlocks₁₂
      = -(nullL * nullN) := by
  rw [chain_schurComplement_eq]
  ext i j
  simp [toBlocks₁₂, fromBlocks]

/-- **The witness**: the induced effective edge block is not nilpotent -
null microstructure Schur-complements to a non-null effective term. -/
theorem effective_edge_not_nilpotent :
    ¬ IsNilpotent (-(nullL * nullN)) := fun h =>
  nullL_mul_nullN_not_nilpotent (by simpa using h.neg)

/-- Bonus honesty lemma: the TOTAL effective operator is still
square-zero on this chain - nullity failure is a per-edge statement, not
a total-operator one. -/
theorem effective_total_sq_eq_zero :
    (fromBlocks 0 (nullL * nullN) (nullN * nullL) 0
        : Matrix (Fin 2 ⊕ Fin 2) (Fin 2 ⊕ Fin 2) ℂ)
      * fromBlocks 0 (nullL * nullN) (nullN * nullL) 0 = 0 := by
  rw [fromBlocks_multiply]
  have h₁ : (nullL * nullN) * (nullN * nullL) = 0 := by
    rw [mul_assoc, ← mul_assoc nullN nullN, nullN_sq, zero_mul, mul_zero]
  have h₂ : (nullN * nullL) * (nullL * nullN) = 0 := by
    rw [mul_assoc, ← mul_assoc nullL nullL, nullL_sq, zero_mul, mul_zero]
  simp [h₁, h₂]

/-! ## The collinear negative control -/

/-- **Negative control**: if the two couplings are collinear (`t • nullL`
against `nullL`, any scalar `t`), the entire effective coupling vanishes.
Blocking preserves nullity exactly on collinear (massless)
configurations; the non-null effective term of the witness is generated
by disagreement, not by decimation as such. -/
theorem collinear_schurComplement_eq_zero (t : ℂ) :
    schurComplement (0 : Matrix (Fin 2 ⊕ Fin 2) (Fin 2 ⊕ Fin 2) ℂ)
      (fromRows nullL (t • nullL)) (fromCols nullL (t • nullL))
      (1 : Matrix (Fin 2) (Fin 2) ℂ) = 0 := by
  unfold schurComplement
  rw [invOf_one, Matrix.mul_one, fromRows_mul_fromCols]
  simp [nullL_sq]

end PhysicsSM.Draft.NullEdge.Carrier.RGSchurMass
