import PhysicsSM.Draft.NullEdge.ChannelPhysicalCohomology
import PhysicsSM.Draft.NullEdge.Carrier.CarrierWardDescentWitness

/-!
# Physical endomorphism cohomology on the finite Ward witness

`ChannelPhysicalCohomology` proves the abstract finite contraction theorem:
a chain map has zero physical compression exactly when it is null-homotopic.
This module instantiates that theorem on the existing positive Ward/descent
witness of `KreinPositiveSectorWitness` and `CarrierWardDescentWitness`.

The live witness charge is

`Qmat = [[0,1,0],[0,0,0],[0,0,0]]`.

Its physical line is the third coordinate.  The matrix `wardContractS` reverses
the contractible arrow between the first two coordinates, while `wardPhysI`
and `wardPhysP` include and project the third coordinate.  The resulting
contraction identities are exact, and therefore the abstract quotient theorem
applies to every `Qmat`-chain map.

Scope: this is a concrete realization on the repository's finite `(2,1)` Ward
model.  It does not derive the charge or contraction from the full null-edge
carrier, impose graph locality on homotopies, or classify all automorphisms
preserving the carrier, Krein form, grading, soldering, and gauge data.

Lean 4.28.0.
-/

noncomputable section

namespace PhysicsSM.Draft.NullEdge.Carrier.WardPhysicalCohomology

open PhysicsSM.Draft.NullEdge.ChannelPhysicalCohomology
open PhysicsSM.Draft.NullEdge.Carrier.KugoOjima

/-- Reverse arrow for the contractible `e0 <- e1` pair. -/
def wardContractS : Matrix (Fin 3) (Fin 3) Complex :=
  !![0, 0, 0; 1, 0, 0; 0, 0, 0]

/-- Inclusion of the surviving physical line generated by `e2`. -/
def wardPhysI : Matrix (Fin 3) (Fin 1) Complex := !![0; 0; 1]

/-- Projection onto the surviving physical line generated by `e2`. -/
def wardPhysP : Matrix (Fin 1) (Fin 3) Complex := !![0, 0, 1]

/-- The existing Ward charge and the displayed maps form exact finite
contraction data. -/
theorem ward_contraction_data :
    Qmat * Qmat = 0 /\
      wardPhysP * wardPhysI = 1 /\
      Qmat * wardPhysI = 0 /\
      wardPhysP * Qmat = 0 /\
      Qmat * wardContractS + wardContractS * Qmat =
        1 - wardPhysI * wardPhysP := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;>
    ext i j <;> fin_cases i <;> fin_cases j <;>
      simp [Qmat, wardContractS, wardPhysI, wardPhysP,
        Matrix.mul_apply, Fin.sum_univ_three]

/-- On the concrete Ward model, a chain map acts trivially on the physical
line exactly when it is a `Qmat`-exact endomorphism. -/
theorem ward_zero_physical_iff_nullHomotopic
    (X : Matrix (Fin 3) (Fin 3) Complex)
    (hX : X * Qmat = Qmat * X) :
    wardPhysP * X * wardPhysI = 0 <->
      Exists fun H : Matrix (Fin 3) (Fin 3) Complex =>
        X = Qmat * H + H * Qmat := by
  rcases ward_contraction_data with ⟨hQ2, hpi, hQi, hpQ, hcontract⟩
  exact induced_eq_zero_iff_nullHomotopic Qmat X wardContractS wardPhysI
    wardPhysP hQ2 hpi hQi hpQ hcontract hX

/-- Every endomorphism of the one-dimensional Ward physical line has an
explicit chain-map lift to the prephysical three-dimensional space. -/
theorem ward_physical_lift
    (f : Matrix (Fin 1) (Fin 1) Complex) :
    wardPhysP * (wardPhysI * f * wardPhysP) * wardPhysI = f /\
      (wardPhysI * f * wardPhysP) * Qmat =
        Qmat * (wardPhysI * f * wardPhysP) := by
  rcases ward_contraction_data with ⟨_, hpi, hQi, hpQ, _⟩
  exact physical_lift_induces Qmat wardPhysI wardPhysP f hpi hQi hpQ

/-- A nonzero chain map with zero physical action, inherited from the
contractible two-coordinate sector. -/
theorem ward_nonzero_exact_witness :
    let X := Qmat * wardContractS + wardContractS * Qmat
    Ne X 0 /\
      X * Qmat = Qmat * X /\
      wardPhysP * X * wardPhysI = 0 /\
      (Exists fun H : Matrix (Fin 3) (Fin 3) Complex =>
        X = Qmat * H + H * Qmat) := by
  refine ⟨?_, ?_, ?_, ⟨wardContractS, rfl⟩⟩
  · intro hX
    have hentry := congrArg (fun M => M 0 0) hX
    simp [Qmat, wardContractS, Matrix.mul_apply, Fin.sum_univ_three] at hentry
  · ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Qmat, wardContractS, Matrix.mul_apply, Fin.sum_univ_three]
  · ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Qmat, wardContractS, wardPhysI, wardPhysP,
        Matrix.mul_apply, Fin.sum_univ_three]

/-! ## Build-enforced axiom pins -/

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.WardPhysicalCohomology.ward_zero_physical_iff_nullHomotopic' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms ward_zero_physical_iff_nullHomotopic

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.WardPhysicalCohomology.ward_physical_lift' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms ward_physical_lift

/-- info: 'PhysicsSM.Draft.NullEdge.Carrier.WardPhysicalCohomology.ward_nonzero_exact_witness' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms ward_nonzero_exact_witness

end PhysicsSM.Draft.NullEdge.Carrier.WardPhysicalCohomology
