import Mathlib

/-!
# Exact Lorentz plaquette tangent target

This focused target isolates the nonlinear link-holonomy step of the null-edge
Palatini program. Links are invertible real `4 x 4` matrices. A six-component
right-trivialized variation is inserted through the fixed mostly-minus Lorentz
Lie-algebra generator map.

The main identity states that the formal product/inverse variation of the exact
plaquette holonomy, right-trivialized at that holonomy, is the sum of four
adjoint-transported link generators. Under eta-Lorentz link hypotheses this
matrix is again in the Lorentz Lie algebra. At identity transport it reduces
to the oriented additive plaquette curl.
-/

namespace LorentzPlaquetteTangent

open Matrix

abbrev Fiber (n : Nat) := Fin n -> Real
abbrev GL4 := GL (Fin 4) Real
abbrev LinkConnection (Site : Type*) := Site -> Fin 4 -> GL4
abbrev LinkVariation (Site : Type*) := Site -> Fin 4 -> Fiber 6

def eta : Matrix (Fin 4) (Fin 4) Real :=
  !![1, 0, 0, 0; 0, -1, 0, 0; 0, 0, -1, 0; 0, 0, 0, -1]

def bivectorMatrix (bivector : Fiber 6) : Matrix (Fin 4) (Fin 4) Real :=
  !![0, bivector 3, bivector 4, bivector 5;
     -bivector 3, 0, bivector 0, bivector 1;
     -bivector 4, -bivector 0, 0, bivector 2;
     -bivector 5, -bivector 1, -bivector 2, 0]

def lorentzGenerator (bivector : Fiber 6) : Matrix (Fin 4) (Fin 4) Real :=
  bivectorMatrix bivector * eta

def IsEtaLorentz (matrix : Matrix (Fin 4) (Fin 4) Real) : Prop :=
  matrix.transpose * eta * matrix = eta

def IsLorentzLieAlgebra (generator : Matrix (Fin 4) (Fin 4) Real) : Prop :=
  generator.transpose * eta + eta * generator = 0

theorem lorentzGenerator_mem (bivector : Fiber 6) :
    IsLorentzLieAlgebra (lorentzGenerator bivector) := by
  unfold IsLorentzLieAlgebra
  ext mu nu
  fin_cases mu <;> fin_cases nu <;>
    simp [lorentzGenerator, bivectorMatrix, eta, Matrix.mul_apply,
      Matrix.transpose_apply, Fin.sum_univ_four]

def unitMatrix (unit : GL4) : Matrix (Fin 4) (Fin 4) Real := unit

@[simp]
theorem unitMatrix_one : unitMatrix (1 : GL4) = 1 := rfl

@[simp]
theorem unitMatrix_mul (left right : GL4) :
    unitMatrix (left * right) = unitMatrix left * unitMatrix right := rfl

def twoStepUnit {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (site : Site) (a b : Fin 4) : GL4 :=
  connection site a * connection (shift a site) b

def plaquetteUnit {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (site : Site) (a b : Fin 4) : GL4 :=
  twoStepUnit shift connection site a b *
    (twoStepUnit shift connection site b a)⁻¹

/-- Ambient matrix tangent generated by a right-trivialized six-component
link variation `delta U = U hat(X)`. -/
def linkMatrixVariation {Site : Type*}
    (connection : LinkConnection Site) (variation : LinkVariation Site)
    (site : Site) (direction : Fin 4) : Matrix (Fin 4) (Fin 4) Real :=
  unitMatrix (connection site direction) *
    lorentzGenerator (variation site direction)

/-- Product-rule tangent of one ordered two-link path. -/
def twoStepMatrixVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  linkMatrixVariation connection variation site a *
      unitMatrix (connection (shift a site) b) +
    unitMatrix (connection site a) *
      linkMatrixVariation connection variation (shift a site) b

/-- Product/inverse-rule tangent of the exact group plaquette holonomy. -/
def plaquetteMatrixVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  let pathAB := twoStepUnit shift connection site a b
  let pathBA := twoStepUnit shift connection site b a
  let deltaAB := twoStepMatrixVariation shift connection variation site a b
  let deltaBA := twoStepMatrixVariation shift connection variation site b a
  deltaAB * unitMatrix pathBA⁻¹ -
    unitMatrix (pathAB * pathBA⁻¹) * deltaBA * unitMatrix pathBA⁻¹

/-- The plaquette tangent translated back to the Lie algebra at the identity. -/
def rightTrivializedPlaquetteVariation {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  plaquetteMatrixVariation shift connection variation site a b *
    unitMatrix (plaquetteUnit shift connection site a b)⁻¹

/-- Adjoint transport of one six-component Lorentz generator. -/
def lorentzAdjoint (transport : GL4) (bivector : Fiber 6) :
    Matrix (Fin 4) (Fin 4) Real :=
  unitMatrix transport * lorentzGenerator bivector * unitMatrix transport⁻¹

/-- Four-corner adjoint sum predicted by the right logarithmic derivative of
the plaquette. -/
def plaquetteAdjointSum {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (connection : LinkConnection Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    Matrix (Fin 4) (Fin 4) Real :=
  let pathAB := twoStepUnit shift connection site a b
  let holonomy := plaquetteUnit shift connection site a b
  lorentzAdjoint (connection site a) (variation site a) +
    lorentzAdjoint pathAB (variation (shift a site) b) -
    lorentzAdjoint (holonomy * connection site b) (variation site b) -
    lorentzAdjoint pathAB (variation (shift b site) a)

/-- Target 1: the exact product/inverse tangent equals the four transported
Lie-algebra insertions. -/
theorem rightTrivializedPlaquetteVariation_eq_adjointSum
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (connection : LinkConnection Site) (variation : LinkVariation Site)
    (site : Site) (a b : Fin 4) :
    rightTrivializedPlaquetteVariation shift connection variation site a b =
      plaquetteAdjointSum shift connection variation site a b := by
  sorry

/-- Target 2: conjugation by an eta-Lorentz unit preserves the Lorentz Lie
algebra image. -/
theorem lorentzAdjoint_mem
    (transport : GL4) (hTransport : IsEtaLorentz (unitMatrix transport))
    (bivector : Fiber 6) :
    IsLorentzLieAlgebra (lorentzAdjoint transport bivector) := by
  sorry

/-- Target 3: with eta-Lorentz links, the exact right-trivialized plaquette
tangent is a valid Lorentz Lie-algebra element. -/
theorem rightTrivializedPlaquetteVariation_mem
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (connection : LinkConnection Site)
    (hConnection : forall site direction,
      IsEtaLorentz (unitMatrix (connection site direction)))
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    IsLorentzLieAlgebra
      (rightTrivializedPlaquetteVariation shift connection variation site a b) := by
  sorry

def identityConnection (Site : Type*) : LinkConnection Site :=
  fun _ _ => 1

def additivePlaquetteCurl {Site : Type*}
    (shift : Fin 4 -> Equiv Site Site) (variation : LinkVariation Site)
    (site : Site) (a b : Fin 4) : Fiber 6 :=
  fun component =>
    variation site a component + variation (shift a site) b component -
      variation site b component - variation (shift b site) a component

/-- Target 4: at identity transport the nonlinear tangent reduces exactly to
the oriented additive plaquette curl used by the existing linearized theory. -/
theorem rightTrivializedPlaquetteVariation_identity
    {Site : Type*} (shift : Fin 4 -> Equiv Site Site)
    (variation : LinkVariation Site) (site : Site) (a b : Fin 4) :
    rightTrivializedPlaquetteVariation shift (identityConnection Site)
        variation site a b =
      lorentzGenerator (additivePlaquetteCurl shift variation site a b) := by
  sorry

end LorentzPlaquetteTangent
