import PhysicsSM.Draft.NullEdge.ChannelDecompositionModuliCapstone

/-!
# Target: a rational stabilizer orbit obstructs invariant selection

The exact six-coordinate even Krein-self-adjoint normal form has two negative
coordinates, `b` and `f`, with equal coefficient in the Gram form.  Swapping
those coordinates is therefore a rational involutive isometry.  It fixes the
three named even channels, whose two negative coordinates vanish, but exchanges
the positive complement rays at `(3/5,0)` and `(0,3/5)`.

Prove all six statements without weakening the hypotheses.  The capstone must
exhibit the two distinct positive represented sectors and show that every
selector invariant under this explicitly declared normal-form symmetry gives
their complement witnesses the same value.

Scope: this is a stabilizer inside the rational six-coordinate quadratic model.
It is not asserted to be a carrier-algebra automorphism, gauge transformation,
edge relabeling, dynamical symmetry, or physical equivalence.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace PhysicsSM.Draft.NullEdge.ChannelStabilizerSelectorSuccessor

open CarrierRigidity.Concrete
open ChannelKreinMetricNoGo
open ChannelKreinSectorSignature
open ChannelPositiveComplementDisk

/-- Swap the equally weighted negative coordinates after reading the exact
normal-form entries of a represented matrix.  Claims about this map below are
restricted to the even Krein-self-adjoint normal-form sector. -/
def swapNegativeNormal (X : N) : N :=
  normalForm (X 0 0) (X 1 1) (X 2 2) (X 3 3) (X 2 3) (X 0 1)

/-- Reflection of the rational positive-complement disk across its diagonal. -/
def swapDisk (p : ℚ × ℚ) : ℚ × ℚ := (p.2, p.1)

/-- Orbit relation for the genuine order-two action generated by `swapDisk`. -/
def SameSwapOrbit (p q : ℚ × ℚ) : Prop :=
  q = p ∨ q = swapDisk p

/-- On exact normal forms, the map exchanges only the two negative
coordinates. -/
theorem swapNegativeNormal_normalForm (a d e g b f : ℚ) :
    swapNegativeNormal (normalForm a d e g b f) =
      normalForm a d e g f b := by
  sorry

/-- The coordinate swap is an involution on the full even
Krein-self-adjoint normal-form sector. -/
theorem swapNegativeNormal_involutive
    (X : N) (hself : kadj X = X) (heven : Gam * X = X * Gam) :
    swapNegativeNormal (swapNegativeNormal X) = X := by
  sorry

/-- The coordinate swap preserves the exact Gram pairing on every pair of
normal-form vectors, not only their self-pairings. -/
theorem swapNegativeNormal_gram
    (a d e g b f a' d' e' g' b' f' : ℚ) :
    kreinGram (swapNegativeNormal (normalForm a d e g b f))
        (swapNegativeNormal (normalForm a' d' e' g' b' f')) =
      kreinGram (normalForm a d e g b f)
        (normalForm a' d' e' g' b' f') := by
  sorry

/-- The residual rational isometry fixes each of the three named even
channels pointwise. -/
theorem swapNegativeNormal_fixes_named_channels :
    swapNegativeNormal apertureC = apertureC ∧
      swapNegativeNormal closureC = closureC ∧
      swapNegativeNormal turnC = turnC := by
  sorry

/-- On classified positive-complement representatives, the residual isometry
acts by reflection across the diagonal of the rational open disk. -/
theorem swapNegativeNormal_diskVector (u v : ℚ) :
    swapNegativeNormal (diskVector u v) = diskVector v u := by
  sorry

/-- **Stabilizer-orbit selector obstruction.** The rational points `(3/5,0)`
and `(0,3/5)` give distinct, strictly positive represented sectors, while
their normalized complement witnesses lie in one orbit of a Gram isometry
fixing all three named channels.  Consequently a selector invariant under this
single declared residual symmetry cannot separate those witnesses.

This does not assert that the orbit is a physical equivalence class. -/
theorem rational_swap_orbit_obstructs_invariant_selector
    {A : Type*} (selector : N → A)
    (hinv : ∀ X : N, kadj X = X → Gam * X = X * Gam →
      selector (swapNegativeNormal X) = selector X) :
    let X := diskVector (3 / 5) 0
    let Y := diskVector 0 (3 / 5)
    X ≠ Y ∧
      SameSwapOrbit ((3 / 5, 0) : ℚ × ℚ) (0, 3 / 5) ∧
      swapNegativeNormal X = Y ∧
      InTiltedSector (3 / 5) 0 X ∧
      ¬ InTiltedSector 0 (3 / 5) X ∧
      InTiltedSector 0 (3 / 5) Y ∧
      ¬ InTiltedSector (3 / 5) 0 Y ∧
      kreinGram X X = 32 / 25 ∧
      kreinGram Y Y = 32 / 25 ∧
      selector X = selector Y := by
  sorry

end PhysicsSM.Draft.NullEdge.ChannelStabilizerSelectorSuccessor
