import PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylEliminationCapstone
import PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylTzZeroInteriorBranch
import PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylRootClassification

/-!
# Aristotle target: stationary-Weyl quintic fibre and finite-chart census

Do not weaken any statement or change any polynomial, phase, matrix, or factor
convention.  The first theorem is the hard exact algebraic core.  A SymPy 1.14
lexicographic Groebner calculation over `QQ[tx,ty,tz]` gives exactly

* `430976 * tx = 1061280*tz^4 - 462525*tz^3 - 644875*tz^2 - 2634243*tz + 1258155`,
* `820352 * ty = 574560*tz^4 - 959475*tz^3 - 575125*tz^2 - 958797*tz + 2176245`,
* `rootPoly tz = 0`,

for the ideal generated by the three live numerators and `rootPoly tz`.
These are exactly the imported `tangentX` and `tangentY` formulas.  Prove the
result in Lean from the displayed hypotheses, preferably with exact
`linear_combination` certificates and then field normalization.

The second theorem composes that uniqueness result with the already landed
live matrix bridge, the exact elimination capstone, the complete `tz = 0`
slice, the globally positive excluded sextic, and the imported reconstruction
theorem.  It should leave no finite-chart branch implicit.
-/

noncomputable section

open Matrix Complex

namespace PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylQuinticFiberCensus

open StationaryAmplitudeWeylTangent
open StationaryAmplitudeWeylAlgebraicOffAxisAlias
open StationaryAmplitudeWeylLiveMatrixNumeratorBridge
open StationaryAmplitudeWeylEliminationCapstone
open StationaryAmplitudeWeylTzZeroInteriorBranch

/-- The unique fibre over the real quintic branch: once the three exact live
numerators vanish, `tx` and `ty` are forced to be the imported quartic
reconstruction functions of `tz`. -/
theorem quintic_fiber_unique {tx ty tz : Real}
    (hFx : Fx tx ty tz = 0)
    (hFy : Fy tx ty tz = 0)
    (hFz : Fz tx ty tz = 0)
    (hRoot : rootPoly tz = 0) :
    tx = tangentX tz ∧ ty = tangentY tz := by
  sorry

/-- Complete identity-crossing census on the finite real tangent chart.  The
three branches are the origin, the exact `9-40-41` `tz = 0` alias, and the
unique fibre over the unique real quintic root. -/
theorem live_identity_finite_chart_census (tx ty tz : Real) :
    weylStep (unitPhase tx) (unitPhase ty) (unitPhase tz) = 1 ↔
      (tx = 0 ∧ ty = 0 ∧ tz = 0) ∨
      (tx = -5 / 4 ∧ ty = 5 / 4 ∧ tz = 0) ∨
      (rootPoly tz = 0 ∧ tx = tangentX tz ∧ ty = tangentY tz) := by
  constructor
  · intro hLive
    rcases live_eq_one_implies_numerators_zero hLive with ⟨hFx, hFy, hFz⟩
    rcases live_alias_forces_elimination_branch hLive with htz | hroot | hexcluded
    · rcases (numerators_zero_and_tz_zero_iff tx ty tz).mp
          ⟨htz, hFx, hFy, hFz⟩ with horigin | hoff
      · exact Or.inl horigin
      · exact Or.inr (Or.inl hoff)
    · exact Or.inr (Or.inr ⟨hroot, quintic_fiber_unique hFx hFy hFz hroot⟩)
    · have hpos : 0 < excludedPoly tz := by
        simpa [excludedPoly,
          PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylRootClassification.excludedPoly]
          using PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylRootClassification.excludedPoly_pos tz
      exact (ne_of_gt hpos hexcluded).elim
  · rintro (horigin | hoff | hroot)
    · rcases horigin with ⟨rfl, rfl, rfl⟩
      exact origin_reconstructs_positive_identity
    · rcases hoff with ⟨rfl, rfl, rfl⟩
      exact offCorner_reconstructs_positive_identity
    · rcases hroot with ⟨hroot, rfl, rfl⟩
      exact exact_alias_of_root hroot

/-- Nonvacuity control: the finite-chart census contains a fully off-axis
identity crossing in addition to its two explicit `tz = 0` points. -/
theorem finite_chart_census_has_fully_offaxis_witness :
    ∃ tx ty tz : Real,
      tx ≠ 0 ∧ ty ≠ 0 ∧ tz ≠ 0 ∧
      weylStep (unitPhase tx) (unitPhase ty) (unitPhase tz) = 1 := by
  rcases exists_exact_fully_offaxis_alias with
    ⟨tx, ty, tz, htx, hty, htz, _, _, _, _, _, _, hLive⟩
  exact ⟨tx, ty, tz, htx, hty, htz, hLive⟩

end PhysicsSM.Draft.NullEdge.StationaryAmplitudeWeylQuinticFiberCensus
