import Mathlib

/-!
# Electroweak orbit obstruction: kernel `u(1)_em` and rank three

This file proves the **stage-1 electroweak stabilizer theorem** (entry T9 of the
null-edge unified-mass proof chain).  It is a *structural* finite-dimensional
representation-theory statement: **given** the Standard-Model electroweak group
`SU(2)_L × U(1)_Y`, the Higgs doublet representation on `ℂ²`, and the chosen
vacuum section, the orbit-obstruction map has a one-dimensional kernel (the
electromagnetic `u(1)_em` direction generated by the charge `Q`) and rank three.

This is **not a prediction**: photon "masslessness" here is the statement that
`Q` stabilises the vacuum, which is forced by the group, the representation, and
the vacuum section.  We use stabilizer / orbit-obstruction language throughout
and avoid any "gauge symmetry breaking" wording (a local gauge symmetry is a
redundancy and is not an observable that breaks).

## Conventions

* **Hermitian generator convention.**  We use *Hermitian* generators
  `T₁, T₂, T₃` (the Pauli matrices divided by two) and the Hermitian
  hypercharge generator `Y/2`.  The physical (anti-Hermitian) Lie-algebra
  generators are `i T₁, i T₂, i T₃, i Y/2`; the factor of `i` is an overall
  scalar and changes neither the kernel nor the rank of the obstruction map, so
  the theorems below hold verbatim in the anti-Hermitian convention as well.
* **Hypercharge.**  `Y(H) = 1`, so the hypercharge generator acting on the
  doublet is `Y/2 = (1/2)·I`.
* **Charge generator.**  `Q = T₃ + Y/2 = diag(1, 0)`.
* **Vacuum section.**  `H₀ = (0, v/√2)` with `v ≠ 0`.
* **Scalar field of the Lie algebra.**  `su(2)_L ⊕ u(1)_Y` is a *real* Lie
  algebra of dimension `4`, with real coordinates `(x₀, x₁, x₂, x₃)` along
  `(T₁, T₂, T₃, Y/2)`.  The orbit map is therefore `ℝ`-linear from `ℝ⁴` to
  `ℂ²` (the latter viewed as a real vector space of dimension `4`).

## Main results

* `PhysicsSM.Draft.B_EW_eq_matrix` — the closed-form obstruction map agrees with
  the matrix definition `X ↦ ρ(X) H₀`.
* `PhysicsSM.Draft.ew_stabilizer_kernel` — `ker B_EW = span ℝ {Q}` (the `u(1)_em`
  direction).
* `PhysicsSM.Draft.ew_stabilizer_kernel_finrank` — `dim (ker B_EW) = 1`.
* `PhysicsSM.Draft.ew_stabilizer_rank` — `rank B_EW = 3`.
* `PhysicsSM.Draft.ew_quadratic_form_kernel` — the quadratic obstruction
  `q(X) = ‖B_EW X‖²` vanishes exactly on `span ℝ {Q}`.
-/

namespace PhysicsSM
namespace Draft

open Matrix Module

/-! ### Generators (Hermitian convention) and the Higgs vacuum -/

/-- Hermitian `SU(2)_L` generator `T₁ = σ₁/2`. -/
noncomputable def T1 : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1 / 2; 1 / 2, 0]

/-- Hermitian `SU(2)_L` generator `T₂ = σ₂/2`. -/
noncomputable def T2 : Matrix (Fin 2) (Fin 2) ℂ := !![0, -Complex.I / 2; Complex.I / 2, 0]

/-- Hermitian `SU(2)_L` generator `T₃ = σ₃/2`. -/
noncomputable def T3 : Matrix (Fin 2) (Fin 2) ℂ := !![1 / 2, 0; 0, -1 / 2]

/-- Hermitian hypercharge generator `Y/2 = (1/2)·I` (with `Y(H) = 1`). -/
noncomputable def Yhalf : Matrix (Fin 2) (Fin 2) ℂ := !![1 / 2, 0; 0, 1 / 2]

/-- Charge generator `Q = T₃ + Y/2 = diag(1, 0)`. -/
noncomputable def Qmat : Matrix (Fin 2) (Fin 2) ℂ := !![1, 0; 0, 0]

/-- Higgs vacuum section `H₀ = (0, v/√2)`. -/
noncomputable def H0 (v : ℝ) : Fin 2 → ℂ := ![0, (v : ℂ) / Real.sqrt 2]

/-- The Lie-algebra representation on the doublet: a real combination of the four
Hermitian generators along coordinates `(x₀, x₁, x₂, x₃) = (T₁, T₂, T₃, Y/2)`. -/
noncomputable def rho (x : Fin 4 → ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (x 0 : ℂ) • T1 + (x 1 : ℂ) • T2 + (x 2 : ℂ) • T3 + (x 3 : ℂ) • Yhalf

/-- The coordinate vector of the charge generator `Q = T₃ + Y/2` in the basis
`(T₁, T₂, T₃, Y/2)`. -/
def Qgen : Fin 4 → ℝ := ![0, 0, 1, 1]

/-- The overall scalar `κ = v/(2√2)` appearing in the obstruction map. -/
noncomputable def kappa (v : ℝ) : ℂ := (v : ℂ) / (2 * Real.sqrt 2)

/-! ### The orbit-obstruction map -/

/-- The electroweak orbit-obstruction map `B_EW(X) = ρ(X) H₀`, expressed in
closed form as an `ℝ`-linear map `ℝ⁴ → ℂ²`. -/
noncomputable def B_EW (v : ℝ) : (Fin 4 → ℝ) →ₗ[ℝ] (Fin 2 → ℂ) where
  toFun x := ![kappa v * ((x 0 : ℂ) - Complex.I * (x 1 : ℂ)),
               kappa v * ((x 3 : ℂ) - (x 2 : ℂ))]
  map_add' x y := by
    funext i
    fin_cases i <;> · simp [kappa]; ring
  map_smul' r x := by
    funext i
    fin_cases i <;> · simp [kappa, Complex.real_smul]; ring

@[simp] lemma B_EW_apply (v : ℝ) (x : Fin 4 → ℝ) :
    B_EW v x = ![kappa v * ((x 0 : ℂ) - Complex.I * (x 1 : ℂ)),
                 kappa v * ((x 3 : ℂ) - (x 2 : ℂ))] := rfl

/--
The charge generator stabilises the vacuum: `Q H₀ = 0`.
-/
lemma Qmat_mulVec_H0 (v : ℝ) : Qmat.mulVec (H0 v) = 0 := by
  ext i; fin_cases i <;> norm_num [ Qmat, H0 ] ;

/--
`ρ(Q) = Q` at the matrix level, i.e. the coordinate vector `Qgen` represents
the charge matrix `Q = T₃ + Y/2`.
-/
lemma rho_Qgen : rho Qgen = Qmat := by
  ext i j; fin_cases i <;> fin_cases j <;> norm_num [ rho, Qgen, T1, T2, T3, Yhalf, Qmat ] ;
  · erw [ Matrix.cons_val_succ' ] ; norm_num;
  · erw [ Matrix.cons_val_succ' ] ; norm_num

/--
Faithfulness: the closed-form obstruction map agrees with the matrix
definition `X ↦ ρ(X) H₀`.
-/
lemma B_EW_eq_matrix (v : ℝ) (x : Fin 4 → ℝ) :
    B_EW v x = (rho x).mulVec (H0 v) := by
  funext i
  fin_cases i <;>
    · simp [B_EW, rho, H0, T1, T2, T3, Yhalf, kappa, Matrix.mulVec, dotProduct,
        Fin.sum_univ_two]
      ring

/-! ### Non-vanishing of the scalar `κ` -/

lemma kappa_ne_zero {v : ℝ} (hv : v ≠ 0) : kappa v ≠ 0 := by
  exact div_ne_zero ( by simpa ) ( by norm_num )

/-! ### Stage 1: kernel and rank -/

lemma Qgen_ne_zero : Qgen ≠ 0 := by
  exact fun h => by have := congr_fun h 2; simp +decide [ Qgen ] at this;

/--
**Stage-1 stabilizer kernel.**  The kernel of the orbit-obstruction map is
the electromagnetic line `span ℝ {Q}` (the `u(1)_em` direction).
-/
theorem ew_stabilizer_kernel {v : ℝ} (hv : v ≠ 0) :
    LinearMap.ker (B_EW v) = Submodule.span ℝ {Qgen} := by
  ext x;
  constructor <;> intro hx <;> simp_all +decide [ Submodule.mem_span_singleton ];
  · simp_all +decide [ Complex.ext_iff, kappa_ne_zero hv ];
    exact ⟨ x 2, by ext i; fin_cases i <;> simp +decide [ Qgen ] <;> linarith! ⟩;
  · obtain ⟨ a, rfl ⟩ := hx; simp +decide [ Qgen ] ;

/--
The stabilizer kernel is one-dimensional.
-/
theorem ew_stabilizer_kernel_finrank {v : ℝ} (hv : v ≠ 0) :
    finrank ℝ (LinearMap.ker (B_EW v)) = 1 := by
  rw [ ew_stabilizer_kernel hv, finrank_span_singleton ] ; norm_num [ Qgen_ne_zero ]

/--
**Stage-1 rank.**  The orbit-obstruction map has rank three.
-/
theorem ew_stabilizer_rank {v : ℝ} (hv : v ≠ 0) :
    finrank ℝ (LinearMap.range (B_EW v)) = 3 := by
  have hrk := LinearMap.finrank_range_add_finrank_ker (B_EW v);
  simp_all +decide [ ew_stabilizer_kernel_finrank ]

/-! ### The quadratic obstruction form -/

/-- The quadratic obstruction form `q(X) = ‖B_EW X‖²`. -/
noncomputable def qform (v : ℝ) (x : Fin 4 → ℝ) : ℝ := ‖B_EW v x‖ ^ 2

/--
The quadratic form vanishes exactly where the linear obstruction does.
-/
lemma qform_eq_zero_iff (v : ℝ) (x : Fin 4 → ℝ) :
    qform v x = 0 ↔ B_EW v x = 0 := by
  unfold qform; aesop;

/--
**Quadratic-form kernel.**  The quadratic obstruction `q(X) = ‖B_EW X‖²`
vanishes exactly on `span ℝ {Q}`; hence its kernel matches that of the linear
obstruction map, and its rank is likewise three (`ew_stabilizer_rank`).
-/
theorem ew_quadratic_form_kernel {v : ℝ} (hv : v ≠ 0) :
    {x : Fin 4 → ℝ | qform v x = 0} = (Submodule.span ℝ {Qgen} : Set (Fin 4 → ℝ)) := by
  convert Set.ext _;
  convert fun x => Iff.trans ( qform_eq_zero_iff v x ) ( LinearMap.mem_ker.symm ) using 1;
  rw [ ew_stabilizer_kernel hv ] ; aesop;

end Draft
end PhysicsSM
