import Mathlib

/-!
# Finite reflected-time Kallen-Lehmann kernel

This focused target formalizes the smallest honest two-point analogue of
Osterwalder-Schrader reflection positivity.  A finite positive spectral measure
with transfer eigenvalues `lambda_a` produces the Hankel kernel

`K(t,s) = sum_a w_a * lambda_a^(t+s)`.

Its reflected quadratic form is exactly a sum of weighted squares.  The final
two-level witness has a nonzero `lambda = 1/2` channel with mass `log 2` and a
zero-overlap control.

Scope: this is two-point reflected-kernel positivity.  It is not full OS
positivity of a polynomial field algebra, Hilbert-space reconstruction of a
gauge action, or a continuum mass-gap theorem.

Provenance: clean-room theorem design from K. Usui, arXiv:1201.3415, Sections
2-4; M. Luscher, Commun. Math. Phys. 54 (1977) 283-292; and K. Osterwalder and
E. Seiler, Ann. Phys. 110 (1978) 440-471.  No external code is copied.
-/

open scoped BigOperators

set_option autoImplicit false
set_option maxHeartbeats 8000000

namespace FiniteReflectionPositiveKL

noncomputable section

/-- Finite Euclidean correlation generated by spectral weights and transfer
eigenvalues. -/
def correlation {m : Nat} (lambda weight : Fin m -> Real) (n : Nat) : Real :=
  ∑ a, weight a * lambda a ^ n

/-- Reflected positive-time Hankel kernel. -/
def reflectedKernel {m : Nat} (lambda weight : Fin m -> Real)
    (t s : Nat) : Real :=
  correlation lambda weight (t + s)

/-- Spectral-channel amplitude generated by a finite positive-time test
sequence. -/
def channelAmplitude {m n : Nat} (lambda : Fin m -> Real)
    (c : Fin n -> Real) (a : Fin m) : Real :=
  ∑ t, c t * lambda a ^ t.val

/-- Exact Gram/sum-of-squares expansion of the reflected quadratic form. -/
theorem reflected_quadratic_eq_sum_sq {m n : Nat}
    (lambda weight : Fin m -> Real) (c : Fin n -> Real) :
    (∑ t, ∑ s,
      c t * reflectedKernel lambda weight t.val s.val * c s) =
      ∑ a, weight a * channelAmplitude lambda c a ^ 2 := by
  simp +decide only [reflectedKernel, correlation, mul_comm, channelAmplitude, pow_two]
  simp +decide only [pow_add, Finset.mul_sum _ _ _, mul_left_comm, mul_comm, mul_assoc]
  exact Eq.symm (Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
    Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
      Finset.sum_congr rfl fun _ _ => by ring)))

/-- Nonnegative spectral weights make the reflected two-point kernel positive
semidefinite for every finite positive-time test sequence. -/
theorem reflectedKernel_nonneg {m n : Nat}
    (lambda weight : Fin m -> Real) (hweight : ∀ a, 0 <= weight a)
    (c : Fin n -> Real) :
    0 <= ∑ t, ∑ s,
      c t * reflectedKernel lambda weight t.val s.val * c s := by
  convert Finset.sum_nonneg fun a _ =>
    mul_nonneg (hweight a) (sq_nonneg (channelAmplitude (fun k => lambda k) c a)) using 1
  convert reflected_quadratic_eq_sum_sq _ _ _ using 1

/-- Transfer eigenvalues in `(0,1]` have nonnegative Euclidean energies. -/
theorem transferEnergy_nonneg {m : Nat} (lambda : Fin m -> Real)
    (hlambda : ∀ a, 0 < lambda a ∧ lambda a <= 1) (a : Fin m) :
    0 <= -Real.log (lambda a) := by
  exact neg_nonneg_of_nonpos (Real.log_nonpos (hlambda a |>.1.le) (hlambda a |>.2))

/-- The transfer power is exactly the exponential of the reconstructed
Euclidean energy. -/
theorem transferPower_eq_exp_energy {m : Nat} (lambda : Fin m -> Real)
    (hlambda : ∀ a, 0 < lambda a) (a : Fin m) (n : Nat) :
    lambda a ^ n = Real.exp (-(n : Real) * (-Real.log (lambda a))) := by
  simp +zetaDelta at *
  rw [Real.exp_nat_mul, Real.exp_log (hlambda a)]

/-- Nondegenerate two-level control: the positive spectral atom at `1/2`
produces exact mass `log 2` and a positive reflected form, while a zero-weight
observable sees no connected channel at all. -/
theorem two_level_reflection_positive_mass_control :
    let lambda : Fin 2 -> Real := ![1, (1 / 2 : Real)]
    let visibleWeight : Fin 2 -> Real := ![0, 1]
    let blindWeight : Fin 2 -> Real := ![0, 0]
    let c : Fin 1 -> Real := ![1]
    (∀ n, correlation lambda visibleWeight n = (1 / 2 : Real) ^ n) ∧
      (∀ n, correlation lambda blindWeight n = 0) ∧
      (0 < -Real.log (lambda 1)) ∧
      (-Real.log (lambda 1) = Real.log 2) ∧
      (∑ t, ∑ s,
        c t * reflectedKernel lambda visibleWeight t.val s.val * c s) = 1 := by
  norm_num [correlation, reflectedKernel]
  exact ⟨Real.log_neg one_half_pos one_half_lt_one, by simp⟩

end

end FiniteReflectionPositiveKL
